1 stub -noname ShellGetUserList   ; (long long long)
2 stub -noname ShellStatusHostEnd ; (long)
3 stub -noname ShellIsFriendlyUIActive ; ()
4 stub -noname ShellIsSuspendAllowed   ; ()
5 stub -noname ShellIsRemoteConnectionsEnabled ; ()
6 stub -noname ShellEnableFriendlyUI    ; (long)
7 stub -noname ShellEnableMultipleUsers ; (long)
8 stub -noname ShellEnableRemoteConnections ; (long)
9 stub -noname ShellTurnOffDialog ; (long)
10 stub -noname ShellIsMultipleUsersEnabled ; ()
11 stub -noname ShellACPIPowerButtonPressed ; (long long long)
12 stub -noname ShellIsSingleUserNoPassword ; (wstr wstr)
13 stub -noname ShellStatusHostShuttingDown ; ()
14 stub -noname ShellNotifyThemeUserChange  ; (long long)
15 stub -noname ShellSwitchWhenInteractiveReady ; (long long)
16 stub -noname ShellDimScreen ; (ptr ptr)
17 stub -noname ShellInstallAccountFilterData ; ()
18 stub -noname ShellStatusHostBegin ; (long)
19 stub -noname ShellIsUserInteractiveLogonAllowed ; (long)
20 stub -noname ShellSwitchUser ; (long)
21 stub -noname ShellReturnToWelcome ; (long)
22 stub -noname ShellStatusHostPowerEvent ; ()
23 stub -noname ShellStartCredentialServer ; (wstr long long long)
24 stub -noname ShellAcquireLogonMutex ; ()
25 stub -noname ShellReleaseLogonMutex ; (long)
26 stub -noname ShellSignalShutdown    ; ()
27 stub -noname ShellStatusHostHide    ; ()
28 stub -noname ShellStatusHostShow    ; ()
@ stdcall ShellShutdownDialog(ptr wstr long)
@ stdcall WlxActivateUserShell(ptr wstr wstr ptr)
@ stdcall WlxDisconnectNotify(ptr)
@ stdcall WlxDisplayLockedNotice(ptr)
@ stdcall WlxDisplaySASNotice(ptr)
@ stdcall WlxDisplayStatusMessage(ptr ptr long wstr wstr)
@ stdcall WlxGetConsoleSwitchCredentials(ptr ptr)
@ stdcall WlxGetStatusMessage(ptr ptr ptr long)
@ stdcall WlxInitialize(wstr ptr ptr ptr ptr)
@ stdcall WlxIsLockOk(ptr)
@ stdcall WlxIsLogoffOk(ptr)
@ stdcall WlxLoggedOnSAS(ptr long ptr)
@ stdcall WlxLoggedOutSAS(ptr long ptr ptr ptr ptr ptr ptr)
@ stdcall WlxLogoff(ptr)
@ stdcall WlxNegotiate(long ptr)
@ stdcall WlxNetworkProviderLoad(ptr ptr)
@ stub WlxReconnectNotify ; (long)
@ stdcall WlxRemoveStatusMessage(ptr)
@ stdcall WlxScreenSaverNotify(ptr ptr)
@ stdcall WlxShutdown(ptr long)
@ stdcall WlxStartApplication(ptr wstr ptr wstr)
@ stdcall WlxWkstaLockedSAS(ptr long)
