
#pragma once

#ifndef IMAGEHLP_EXTENDED_OPTIONS_DEFINED
typedef enum
{
    SYMOPT_EX_DISABLEACCESSTIMEUPDATE,
    SYMOPT_EX_MAX,
    SYMOPT_EX_WINE_NATIVE_MODULES = 1000,
} IMAGEHLP_EXTENDED_OPTIONS;
#define IMAGEHLP_EXTENDED_OPTIONS_DEFINED
#endif /* ndef IMAGEHLP_EXTENDED_OPTIONS_DEFINED */

#include <psdk/dbghelp.h>
