#****************************** File Header ******************************\
# File Name: makefile.inc
#
# Copyright (c) 1985-96, Microsoft Corporation
#
# Project specific MAKEFILE.INC
#
# History:
# 09-Dec-96 BradG           Created
#***************************************************************************/
!include ..\makefile.inc

