@ stdcall AcceptSecurityContext(ptr ptr ptr long long ptr ptr ptr ptr)
@ stdcall AcquireCredentialsHandleW(ptr ptr long ptr ptr long ptr ptr ptr)
@ stdcall AddCredentialsW(ptr ptr ptr long ptr long ptr ptr)
@ stdcall ApplyControlToken(ptr ptr)
@ stdcall CredMarshalTargetInfo()
@ stdcall DeleteSecurityContext(ptr)
@ stdcall EfsDecryptFek()
@ stdcall EfsGenerateKey()
@ stdcall EnumerateSecurityPackagesW(ptr ptr)
@ stdcall ExportSecurityContext(ptr long ptr ptr)
@ stdcall FreeContextBuffer(ptr)
@ stdcall FreeCredentialsHandle(ptr)
@ stdcall GenerateDirEfs()
@ stdcall GenerateSessionKey()
@ stdcall GetSecurityUserInfo(ptr long ptr)
@ stdcall ImpersonateSecurityContext(ptr)
@ stdcall ImportSecurityContextW(ptr ptr ptr ptr)
@ stdcall InitSecurityInterfaceW()
@ stdcall InitializeSecurityContextW(ptr ptr ptr long long long ptr long ptr ptr ptr ptr)
@ stdcall KSecRegisterSecurityProvider()
@ stdcall KSecValidateBuffer()
@ stdcall LsaEnumerateLogonSessions()
@ stdcall LsaGetLogonSessionData()
@ stdcall MakeSignature(ptr long ptr long)
@ stdcall MapSecurityError()
@ stdcall QueryContextAttributesW(ptr long ptr)
@ stdcall QueryCredentialsAttributesW(ptr long ptr)
@ stdcall QuerySecurityContextToken(ptr ptr)
@ stdcall QuerySecurityPackageInfoW(ptr ptr)
@ stdcall RevertSecurityContext(ptr)
@ stdcall SealMessage()
@ stdcall SecLookupAccountName(ptr ptr ptr ptr ptr ptr)
@ stdcall SecLookupAccountSid(ptr ptr ptr ptr ptr ptr)
@ stdcall SecLookupWellKnownSid(long ptr long ptr)
@ stdcall SecMakeSPN(ptr ptr ptr long ptr ptr ptr long)
@ stdcall SecMakeSPNEx(ptr ptr ptr long ptr ptr ptr ptr long)
@ stdcall SecSetPagingMode()
@ stdcall UnsealMessage()
@ stdcall VerifySignature(ptr ptr long ptr)
