@ stdcall CapabilitiesRequestAndCapabilitiesReply(ptr ptr long)
@ stdcall DXVA2CreateDirect3DDeviceManager9(ptr ptr)
@ stdcall DXVA2CreateVideoService(ptr ptr ptr)
@ stdcall DXVAHD_CreateDevice(ptr ptr long ptr ptr)
@ stdcall DegaussMonitor(ptr)
@ stdcall DestroyPhysicalMonitor(ptr)
@ stdcall DestroyPhysicalMonitors(long ptr)
@ stdcall GetCapabilitiesStringLength(ptr ptr)
@ stdcall GetMonitorBrightness(ptr ptr ptr ptr)
@ stdcall GetMonitorCapabilities(ptr ptr ptr)
@ stdcall GetMonitorColorTemperature(ptr ptr)
@ stdcall GetMonitorContrast(ptr ptr ptr ptr)
@ stdcall GetMonitorDisplayAreaPosition(ptr long ptr ptr ptr)
@ stdcall GetMonitorDisplayAreaSize(ptr long ptr ptr ptr)
@ stdcall GetMonitorRedGreenOrBlueDrive(ptr long ptr ptr ptr)
@ stdcall GetMonitorRedGreenOrBlueGain(ptr long ptr ptr ptr)
@ stdcall GetMonitorTechnologyType(ptr ptr)
@ stdcall GetNumberOfPhysicalMonitorsFromHMONITOR(ptr ptr)
@ stdcall GetNumberOfPhysicalMonitorsFromIDirect3DDevice9(ptr ptr)
@ stdcall GetPhysicalMonitorsFromHMONITOR(ptr long ptr)
@ stdcall GetPhysicalMonitorsFromIDirect3DDevice9(ptr long ptr)
@ stdcall GetTimingReport(ptr ptr)
@ stdcall GetVCPFeatureAndVCPFeatureReply(ptr long ptr ptr ptr)
@ stdcall OPMGetVideoOutputsFromHMONITOR(ptr long ptr ptr)
@ stdcall OPMGetVideoOutputsFromIDirect3DDevice9Object(ptr long ptr ptr)
@ stdcall RestoreMonitorFactoryColorDefaults(ptr)
@ stdcall RestoreMonitorFactoryDefaults(ptr)
@ stdcall SaveCurrentMonitorSettings(ptr)
@ stdcall SaveCurrentSettings(ptr)
@ stdcall SetMonitorBrightness(ptr long)
@ stdcall SetMonitorColorTemperature(ptr long)
@ stdcall SetMonitorContrast(ptr long)
@ stdcall SetMonitorDisplayAreaPosition(ptr long long)
@ stdcall SetMonitorDisplayAreaSize(ptr long long)
@ stdcall SetMonitorRedGreenOrBlueDrive(ptr long long)
@ stdcall SetMonitorRedGreenOrBlueGain(ptr long long)
@ stdcall SetVCPFeature(ptr long long)
@ stub UABGetCertificate
