# $Id: Makefile,v 1.1 2003/10/27 03:03:22 hyperion Exp $

PATH_TO_TOP = ../../../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = themedump

TARGET_SDKLIBS = kernel32.a uxtheme.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
