# $Id: makefile,v 1.2 2003/07/30 14:08:16 royce Exp $

PATH_TO_TOP = ../../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = tokentst

TARGET_SDKLIBS = ntdll.a kernel32.a

TARGET_OBJECTS = tokentest.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
