//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by eventrap.rc
//
#define ID_PROPERTIES                   3
#define ID_ADD                          4
#define ID_REMOVE                       5
#define ID_SETTINGS                     6
#define ID_BUTTON_EXPORT                7
#define IDC_APPLY                       8
#define IDS_NOT_TRAPPING                15
#define IDS_IS_TRAPPING                 16
#define IDS_MULTIPLE_SEL                17
#define IDS_MSG_TEXTNOTFOUND            20
#define IDS_MSG_SELECTEVENT             21
#define IDS_MSG_DELETEEVENT             22
#define IDS_COLHDR_TYPE                 23
#define IDS_CANTCONNECT                 24
#define IDS_ALREADYTRAPPING             28
#define IDS_SOMETRAPPING                29
#define IDS_EVENT_SEV_SUCCESS           33
#define IDS_EVENT_SEV_INFORMATIONAL     34
#define IDS_EVENT_SEV_WARNING           35
#define IDS_EVENT_SEV_ERROR             36
#define IDS_LcSource_TITLE_EVENT_ID     37
#define IDS_LcSource_TITLE_TRAPPING     38
#define IDS_LcSource_TITLE_DESCRIPTION  39
#define IDS_LcSource_TITLE_SEVERITY     40
#define IDS_LcEvents_TITLE_LOG          41
#define IDS_LcEvents_TITLE_SOURCE       42
#define IDS_LcEvents_TITLE_ID           43
#define IDS_LcEvents_TITLE_SEVERITY     44
#define IDS_LcEvents_TITLE_COUNT        45
#define IDS_LcEvents_TITLE_TIME         46
#define IDS_LcEvents_TITLE_DESCRIPTION  47
#define IDS_TITLE_EDIT_BUTTON           48
#define IDS_TITLE_VIEW_BUTTON           49
#define IDS_ERR_REGISTRY_CORRUPTED      50
#define IDS_ERR_NOT_INSTALLED           51
#define IDS_WARNING_CANT_READ_CONFIG    53
#define IDS_WARNING_NO_MESSAGE_SELECTED 54
#define IDS_ERR_INVALID_ARGUMENT        56
#define IDS_EXPORT_DIALOG_TITLE         57
#define IDS_EXPORT_DEFAULT_FILENAME     63
#define IDS_EXPORT_CNF_FILTER           67
#define IDS_ERR_CANT_CREATE_FILE        68
#define IDS_WARNING_CANT_WRITE_CONFIG   69
#define IDS_ERR_PROP_TIME1              71
#define IDS_ERR_PROP_TIME2              72
#define IDS_ERR_PROP_TIME_LESS_THAN_TWO 73
#define IDS_RANGE_MESSAGE_PREFIX        76
#define IDS_RANGE_VALUE_SEPARATOR       77
#define IDS_SENTENCE_TERMINATOR         78
#define IDS_ERR_SETTINGS_MESSAGELENGTH_NOT_INT 79
#define IDS_SETTINGS_MESSAGE_LENGTH_RANGE 80
#define IDS_ERR_SETTINGS_TRAPSECONDS_NOT_INT 81
#define IDS_SETTINGS_TRAPSECONDS_RANGE  82
#define IDS_ERR_SETTINGS_TRAPCOUNT_NOT_INT 83
#define IDS_ERR_SETTINGS_TRAPCOUNT_RANGE 84
#define IDS_ERR_REGISTRY_BUSY           85
#define IDS_CONFIGTYPE_DEFAULT          86
#define IDS_CONFIGTYPE_CUSTOM           87
#define IDS_CONFIGTYPE_DEFAULT_PENDING  88
#define IDS_ERR_REG_NO_ACCESS           89
#define IDS_ERR_REG_NO_READ_ACCESS      90
#define IDS_ERR_RANGE                   91
#define IDS_ERROR_NOT_RESPONDING        92
#define IDS_ERR_LOAD_MESSAGE_FILE_FAILED 93
#define IDS_ERR_MESSAGE_NOT_FOUND       94
#define IDR_MAINICON                    128
#define IDD_EVNTTRAPDLG                 129
#define IDD_SETTINGSDLG                 131
#define IDD_PROPERTIESDLG               133
#define IDD_EVENTFINDDLG                134
#define IDB_FOLDERCLOSE                 137
#define IDB_FOLDEROPEN                  138
#define IDC_CURSOR1                     139
#define IDD_ABOUTBOX                    142
#define IDD_SAVE_PROGRESS               144
#define IDD_LOAD_PROGRESS               145
#define IDR_CTXMENUS                    152
#define IDC_PROGRESS                    1000
#define IDC_LIMITMSGLNGTH               1012
#define IDC_EDIT_MESSAGELENGTH          1013
#define IDC_MSGLENGTHSPN                1015
#define ID_FIND                         1022
#define IDC_FIND_OK                     1023
#define IDC_FIND_CANCEL                 1024
#define IDC_EVENTCOUNT                  1025
#define IDC_EVENTCOUNTSPN               1026
#define IDC_WITHINTIME                  1027
#define IDC_TIMEINTRVLSPN               1030
#define IDC_DESCRIPTION                 1031
#define ID_STAT_SOURCE                  1033
#define ID_STAT_LOG                     1035
#define ID_STAT_EVENTID                 1036
#define IDC_EVENTLIST                   1046
#define IDC_TIMEINTERVAL                1048
#define IDC_RADIO1                      1054
#define IDC_RADIO2                      1055
#define ID_VIEW                         1069
#define IDC_TV_SOURCES                  1070
#define IDC_LV_SOURCES                  1071
#define IDC_STAT_LABEL1                 1073
#define IDC_STAT_LABEL2                 1074
#define IDC_EDIT_TRAP_COUNT             1075
#define IDC_STAT_LABEL0                 1075
#define IDC_EDIT_TRAP_SECONDS           1076
#define IDC_RADIO_ENABLE                1077
#define IDC_RADIO_DISABLE               1078
#define IDC_BUTTON_RESET                1079
#define IDC_EDIT_FIND_WHAT              1083
#define IDC_CHECK_MATCH_WHOLEWORD       1084
#define IDC_CHECK_MATCH_CASE            1085
#define IDC_RADIO_SEARCH_SOURCES        1086
#define IDC_RADIO_SEARCH_DESCRIPTIONS   1087
#define IDC_EDIT_ENTERPRISEOID          1097
#define IDC_STAT_GRP_CONFIG_TYPE        1098
#define IDC_RADIO_CUSTOM                1099
#define IDC_RADIO_DEFAULT               1100
#define IDC_STAT_TRAP_LENGTH            1101
#define IDC_EDIT_FULL_EVENT_ID          1103
#define IDC_STATIC_MSG                  1105
#define IDC_STATIC_NTRAPS               1106
#define IDC_STATIC_INTERVAL             1107
#define IDC_STATIC_BYTES                1108
#define IDC_DEFAULT                     1109
#define ID_SOURCE_LABEL                 1110
#define ID_LOG_LABEL                    1111
#define ID_EVENTID_LABEL                1112
#define ID_THRESHOLD_LABEL              1113
#define ID_OID_LABEL                    1115
#define ID_TRAPID_LABEL                 1116
#define IDD_NULL                        -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        168
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1121
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
