PATH_TO_TOP = ../..

TARGET_NORC = yes

TARGET_TYPE = dynlink

TARGET_NAME = regtests

TARGET_CFLAGS = -D__USE_W32API -Wall -Werror

TARGET_OBJECTS = \
  regtests.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
