# $Id$

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = beep

TARGET_OBJECTS = beep.o

TARGET_CFLAGS = -Wall -Werror -D__USE_W32API

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
