
unsigned long (*FrLdrDbgPrint)(const char *Format, ...);



#define STUB(x) void x() {FrLdrDbgPrint("Sorry, %s is only a stub!\n", __FUNCTION__);}

STUB(KeActiveProcessors)
STUB(KeConnectInterrupt)
STUB(KeContextToTrapFrame)
STUB(KeDisableInterrupts)
STUB(KeDisconnectInterrupt)
STUB(KeFeatureBits)
STUB(KeFlushEntireTb)
STUB(KeGetRecommendedSharedDataAlignment)
STUB(KeInitializeInterrupt)
STUB(KeInvalidateAllCaches)
STUB(KeProcessorArchitecture)
STUB(KeProcessorLevel)
STUB(KeProcessorRevision)
STUB(KeQueryActiveProcessors)
STUB(KeRaiseUserException)
STUB(KeRestoreFloatingPointState)
STUB(KeSaveFloatingPointState)
STUB(KeSaveStateForHibernate)
STUB(KeSetDmaIoCoherency)
STUB(KeSwitchKernelStack)
STUB(KeSynchronizeExecution)
STUB(KeUpdateRunTime)
STUB(KeUpdateSystemTime)
STUB(KeUserModeCallback)
STUB(KiComputeTimerTableIndex)
STUB(KiDispatchException)
STUB(KiIdleLoop)
STUB(KiInitializeUserApc)
STUB(KiSwapProcess)
STUB(KiSystemService)
STUB(KdbEnterDebuggerException)
STUB(KdbpCliModuleLoaded)
STUB(KdbpCliInit)
STUB(KdpGdbStubInit)
STUB(NtContinue)
STUB(NtCallbackReturn)
STUB(NtRaiseException)
STUB(NtSetLdtEntries)
STUB(NtVdmControl)
STUB(PspGetOrSetContextKernelRoutine)
