# $Id: makefile,v 1.2 2002/04/15 20:39:49 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = cdfs

TARGET_OBJECTS = $(TARGET_NAME).o close.o common.o create.o dirctl.o \
                 fcb.o finfo.o fsctl.o rw.o volinfo.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
