# $Id: Makefile,v 1.1 2003/08/24 12:11:13 dwelch Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = bootvid

TARGET_OBJECTS = bootvid.o pixelsup_i386.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
