#!/bin/bash

if [ X$2 == X ];then
	echo 'Usage: make-blobs <server> <db>'
	exit 1
fi

echo "CREATE DATABASE $2" | mysql -u wikiadmin -p`wikiadmin_pass` -h $1 && \
mysql -u wikiadmin -p`wikiadmin_pass` -h $1 $2 < blobs.sql
	
	
