
PATH_TO_TOP=../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = whois

TARGET_SDKLIBS = ws2_32.a

TARGET_OBJECTS = $(TARGET_NAME).o

TARGET_GCCLIBS = iberty

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
