/* Automatically generated by make depend; DO NOT EDIT!! */

#define STANDALONE
#include <wine/test.h>

extern void func_asm(void);
extern void func_blob(void);
extern void func_hlsl(void);
extern void func_reflection(void);

const struct test winetest_testlist[] =
{
    { "asm", func_asm },
    { "blob", func_blob },
    { "hlsl", func_hlsl },
    { "reflection", func_reflection },
    { 0, 0 }
};
