PATH_TO_TOP = ../../../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = load

TARGET_CFLAGS = -DUNICODE -D_UNICODE

TARGET_SDKLIBS = ntdll.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
