@ fastcall -i386 ??0CBaseUnknown@@QAE@ABU_GUID@@PAUIUnknown@@@Z(ptr ptr ptr ptr) CBaseUnknown_ConstructorWithGUID
@ fastcall -i386 ??0CBaseUnknown@@QAE@PAUIUnknown@@@Z(ptr ptr ptr) CBaseUnknown_Constructor
@ fastcall -i386 ??1CBaseUnknown@@UAE@XZ(ptr ptr) CBaseUnknown_DefaultDestructor
@ fastcall -i386 ??_FCBaseUnknown@@QAEXXZ(ptr ptr ptr) CBaseUnknown_Destructor
@ stdcall -i386 ?IndirectedAddRef@CBaseUnknown@@UAGKXZ(ptr) IIndirectedUnknown_fnAddRef
@ stdcall -i386 ?IndirectedQueryInterface@CBaseUnknown@@UAGJABU_GUID@@PAPAX@Z(ptr ptr ptr) IIndirectedUnknown_fnQueryInterface
@ stdcall -i386 ?IndirectedRelease@CBaseUnknown@@UAGKXZ(ptr) IIndirectedUnknown_fnRelease
@ stdcall -i386 ?NonDelegatedAddRef@CBaseUnknown@@UAGKXZ(ptr) INonDelegatedUnknown_fnAddRef
@ stdcall -i386 ?NonDelegatedQueryInterface@CBaseUnknown@@UAGJABU_GUID@@PAPAX@Z(ptr ptr ptr) INonDelegatedUnknown_fnQueryInterface
@ stdcall -i386 ?NonDelegatedRelease@CBaseUnknown@@UAGKXZ(ptr) IIndirectedUnknown_fnRelease

@ stdcall -private DllInitialize(ptr)
@ stdcall KoCreateInstance(ptr ptr long ptr ptr)
@ stdcall KoDeviceInitialize(ptr)
@ stdcall KoDriverInitialize(ptr ptr ptr)
@ stdcall KoRelease(ptr)
@ stdcall KsAcquireControl(ptr)
@ stdcall KsAcquireDevice(ptr)
@ stdcall KsAcquireDeviceSecurityLock(ptr long)
@ stdcall KsAcquireResetValue(ptr ptr)
@ stdcall KsAddDevice(ptr ptr)
@ stdcall KsAddEvent(ptr ptr)
@ stdcall KsAddIrpToCancelableQueue(ptr ptr ptr long ptr)
@ stdcall KsAddItemToObjectBag(ptr ptr ptr)
@ stdcall KsAddObjectCreateItemToDeviceHeader (ptr ptr ptr ptr ptr)
@ stdcall KsAddObjectCreateItemToObjectHeader(ptr ptr ptr ptr ptr)
@ stdcall KsAllocateDefaultClock(ptr)
@ stdcall KsAllocateDefaultClockEx(ptr ptr ptr ptr ptr ptr long)
@ stdcall KsAllocateDeviceHeader(ptr long ptr)
@ stdcall KsAllocateExtraData(ptr long ptr)
@ stdcall KsAllocateObjectBag(ptr ptr)
@ stdcall KsAllocateObjectCreateItem(ptr ptr long ptr)
@ stdcall KsAllocateObjectHeader(ptr long ptr ptr ptr)
@ stdcall KsCacheMedium(ptr ptr long)
@ stdcall KsCancelIo(ptr ptr)
@ stdcall KsCancelRoutine(ptr ptr)
@ stdcall KsCompletePendingRequest(ptr)
@ stdcall KsCopyObjectBagItems(ptr ptr)
@ stdcall KsCreateAllocator(ptr ptr ptr)
@ stdcall KsCreateBusEnumObject(ptr ptr ptr ptr ptr ptr)
@ stdcall KsCreateClock(ptr ptr ptr)
@ stdcall KsCreateDefaultAllocator(ptr)
@ stdcall KsCreateDefaultAllocatorEx(ptr ptr ptr ptr ptr ptr)
@ stdcall KsCreateDefaultClock(ptr ptr)
@ stdcall KsCreateDefaultSecurity(ptr ptr)
@ stdcall KsCreateDevice(ptr ptr ptr long ptr)
@ stdcall KsCreateFilterFactory(ptr ptr ptr ptr long ptr ptr ptr)
@ stdcall KsCreatePin(ptr ptr long ptr)
@ stdcall KsCreateTopologyNode(ptr ptr long ptr)
@ stdcall KsDecrementCountedWorker(ptr)
@ stdcall KsDefaultAddEventHandler(ptr ptr ptr)
@ stdcall KsDefaultDeviceIoCompletion(ptr ptr)
@ stdcall KsDefaultDispatchPnp(ptr ptr)
@ stdcall KsDefaultDispatchPower(ptr ptr)
@ stdcall KsDefaultForwardIrp(ptr ptr)
@ stdcall KsDereferenceBusObject(ptr)
@ stdcall KsDereferenceSoftwareBusObject(ptr)
@ stdcall KsDeviceGetBusData(ptr long ptr long long)
@ stdcall KsDeviceRegisterAdapterObject(ptr ptr long long)
@ stdcall KsDeviceSetBusData(ptr long ptr long long)
@ stdcall KsDisableEvent(ptr ptr long long)
@ stdcall KsDiscardEvent(ptr)
@ stdcall KsDispatchFastIoDeviceControlFailure(ptr long ptr long ptr long long ptr ptr)
@ stdcall KsDispatchFastReadFailure(ptr ptr long long long ptr ptr ptr)
@ stdcall KsDispatchInvalidDeviceRequest(ptr ptr)
@ stdcall KsDispatchIrp(ptr ptr)
@ stdcall KsDispatchQuerySecurity(ptr ptr)
@ stdcall KsDispatchSetSecurity(ptr ptr)
@ stdcall KsDispatchSpecificMethod(ptr ptr)
@ stdcall KsDispatchSpecificProperty(ptr ptr)
@ stdcall _KsEdit(ptr ptr long long long)
@ stdcall KsEnableEvent(ptr long ptr ptr long ptr)
@ stdcall KsEnableEventWithAllocator(ptr long ptr ptr long ptr ptr long)
@ stdcall KsFastMethodHandler(ptr ptr long ptr long ptr long ptr)
@ stdcall KsFastPropertyHandler(ptr ptr long ptr long ptr long ptr)
@ stdcall KsFilterAcquireProcessingMutex(ptr)
@ stdcall KsFilterAddTopologyConnections(ptr long ptr)
@ stdcall KsFilterAttemptProcessing(ptr long)
@ stdcall KsFilterCreateNode(ptr ptr ptr)
@ stdcall KsFilterCreatePinFactory(ptr ptr ptr)
@ stdcall KsFilterFactoryAddCreateItem(ptr ptr ptr long)
@ stdcall KsFilterFactoryGetSymbolicLink(ptr)
@ stdcall KsFilterFactorySetDeviceClassesState(ptr long)
@ stdcall KsFilterFactoryUpdateCacheData(ptr ptr)
@ stdcall KsFilterGetAndGate(ptr)
@ stdcall KsFilterGetChildPinCount(ptr long)
@ stdcall KsFilterGetFirstChildPin(ptr long)
@ stdcall KsFilterRegisterPowerCallbacks(ptr ptr ptr)
@ stdcall KsFilterReleaseProcessingMutex(ptr)
@ stdcall KsForwardAndCatchIrp(ptr ptr ptr long)
@ stdcall KsForwardIrp(ptr ptr long)
@ stdcall KsFreeDefaultClock(ptr)
@ stdcall KsFreeDeviceHeader(ptr)
@ stdcall KsFreeEventList(ptr ptr long ptr)
@ stdcall KsFreeObjectBag(ptr)
@ stdcall KsFreeObjectCreateItem(ptr ptr)
@ stdcall KsFreeObjectCreateItemsByContext(ptr ptr)
@ stdcall KsFreeObjectHeader(ptr)
@ stdcall KsGenerateDataEvent(ptr long ptr)
@ stdcall KsGenerateEvent(ptr)
@ stdcall KsGenerateEventList(ptr long ptr long ptr)
@ stdcall KsGenerateEvents(ptr ptr long long ptr ptr ptr)
@ stdcall KsGetBusEnumIdentifier(ptr)
@ stdcall KsGetBusEnumParentFDOFromChildPDO(ptr ptr)
@ stdcall KsGetBusEnumPnpDeviceObject(ptr ptr)
@ stdcall KsGetDefaultClockState(ptr)
@ stdcall KsGetDefaultClockTime(ptr)
@ stdcall KsGetDevice(ptr)
@ stdcall KsGetDeviceForDeviceObject(ptr)
@ stdcall KsGetFilterFromIrp(ptr)
@ stdcall KsGetFirstChild(ptr)
@ stdcall KsGetImageNameAndResourceId(ptr ptr ptr ptr)
@ stdcall KsGetNextSibling(ptr)
@ stdcall KsGetNodeIdFromIrp(ptr)
@ stdcall KsGetObjectFromFileObject(ptr)
@ stdcall KsGetObjectTypeFromFileObject(ptr)
@ stdcall KsGetObjectTypeFromIrp(ptr)
@ stdcall KsGetOuterUnknown(ptr)
@ stdcall KsGetParent(ptr)
@ stdcall KsGetPinFromIrp(ptr)
@ stdcall KsHandleSizedListQuery(ptr long long ptr)
;@ stdcall KsiDefaultClockAddMarkEvent
@ stdcall KsIncrementCountedWorker(ptr)
@ stdcall KsInitializeDevice(ptr ptr ptr ptr)
@ stdcall KsInitializeDriver(ptr ptr ptr)
@ stdcall KsInstallBusEnumInterface(ptr)
;KsiPropertyDefaultClockGetCorrelatedPhysicalTime
;KsiPropertyDefaultClockGetCorrelatedTime
;KsiPropertyDefaultClockGetFunctionTable
;KsiPropertyDefaultClockGetPhysicalTime
;KsiPropertyDefaultClockGetResolution
;KsiPropertyDefaultClockGetState
;KsiPropertyDefaultClockGetTime
;KsiQueryObjectCreateItemsPresent
@ stdcall KsIsBusEnumChildDevice(ptr ptr)
@ stdcall KsLoadResource(ptr long long long ptr ptr)
@ stdcall KsMapModuleName(ptr ptr ptr ptr ptr)
@ stdcall KsMergeAutomationTables(ptr ptr ptr ptr)
@ stdcall KsMethodHandler(ptr long ptr)
@ stdcall KsMethodHandlerWithAllocator(ptr long ptr ptr long)
@ stdcall KsMoveIrpsOnCancelableQueue(ptr ptr ptr ptr long ptr ptr)
@ stdcall KsNullDriverUnload(ptr)
@ stdcall KsPinAcquireProcessingMutex(ptr)
@ stdcall KsPinAttachAndGate(ptr ptr)
@ stdcall KsPinAttachOrGate(ptr ptr)
@ stdcall KsPinAttemptProcessing(ptr long)
@ stdcall KsPinDataIntersection(ptr ptr ptr long ptr ptr)
@ stdcall KsPinGetAndGate(ptr)
@ stdcall KsPinGetAvailableByteCount(ptr ptr ptr)
@ stdcall KsPinGetConnectedFilterInterface(ptr ptr ptr)
@ stdcall KsPinGetConnectedPinDeviceObject(ptr)
@ stdcall KsPinGetConnectedPinFileObject(ptr)
@ stdcall KsPinGetConnectedPinInterface(ptr ptr ptr)
@ stdcall KsPinGetCopyRelationships(ptr ptr ptr)
@ stdcall KsPinGetFirstCloneStreamPointer(ptr)
@ stdcall KsPinGetLeadingEdgeStreamPointer(ptr long)
@ stdcall KsPinGetNextSiblingPin(ptr)
@ stdcall KsPinGetParentFilter(ptr)
@ stdcall KsPinGetReferenceClockInterface(ptr ptr)
@ stdcall KsPinGetTrailingEdgeStreamPointer(ptr ptr)
@ stdcall KsPinPropertyHandler(ptr ptr ptr long ptr)
@ stdcall KsPinRegisterFrameReturnCallback(ptr ptr)
@ stdcall KsPinRegisterHandshakeCallback(ptr ptr)
@ stdcall KsPinRegisterIrpCompletionCallback(ptr ptr)
@ stdcall KsPinRegisterPowerCallbacks(ptr ptr ptr)
@ stdcall KsPinReleaseProcessingMutex(ptr)
@ stdcall KsPinSetPinClockTime(ptr double)
@ stdcall KsPinSubmitFrame(ptr ptr long ptr ptr)
@ stdcall KsPinSubmitFrameMdl(ptr ptr ptr ptr)
@ stdcall KsProbeStreamIrp(ptr long long)
@ stdcall KsProcessPinUpdate(ptr)
@ stdcall KsPropertyHandler(ptr long ptr)
@ stdcall KsPropertyHandlerWithAllocator(ptr long ptr ptr long)
@ stdcall KsQueryDevicePnpObject(ptr)
@ stdcall KsQueryInformationFile(ptr ptr long long)
@ stdcall KsQueryObjectAccessMask(ptr)
@ stdcall KsQueryObjectCreateItem(ptr)
@ stdcall KsQueueWorkItem(ptr ptr)
@ stdcall KsReadFile(ptr ptr ptr ptr ptr long long long)
@ stdcall KsRecalculateStackDepth(ptr long)
@ stdcall KsReferenceBusObject(ptr)
@ stdcall KsReferenceSoftwareBusObject(ptr)
@ stdcall KsRegisterAggregatedClientUnknown(ptr ptr)
@ stdcall KsRegisterCountedWorker(long ptr ptr)
@ stdcall KsRegisterFilterWithNoKSPins(ptr ptr long ptr ptr ptr)
@ stdcall KsRegisterWorker(long ptr)
@ stdcall KsReleaseControl(ptr)
@ stdcall KsReleaseDevice(ptr)
@ stdcall KsReleaseDeviceSecurityLock(ptr)
@ stdcall KsReleaseIrpOnCancelableQueue(ptr ptr)
@ stdcall KsRemoveBusEnumInterface(ptr)
@ stdcall KsRemoveIrpFromCancelableQueue(ptr ptr long long)
@ stdcall KsRemoveItemFromObjectBag(ptr ptr long)
@ stdcall KsRemoveSpecificIrpFromCancelableQueue(ptr)
@ stdcall KsServiceBusEnumCreateRequest(ptr ptr)
@ stdcall KsServiceBusEnumPnpRequest(ptr ptr)
@ stdcall KsSetDefaultClockState(ptr long)
@ stdcall KsSetDefaultClockTime(ptr double)
@ stdcall KsSetDevicePnpAndBaseObject(ptr ptr ptr)
@ stdcall KsSetInformationFile(ptr ptr long long)
@ stdcall KsSetMajorFunctionHandler(ptr long)
@ stdcall KsSetPowerDispatch(ptr ptr ptr)
@ stdcall KsSetTargetDeviceObject(ptr ptr)
@ stdcall KsSetTargetState(ptr long)
@ stdcall KsStreamIo(ptr ptr ptr ptr ptr long ptr ptr long long long)
@ stdcall KsStreamPointerAdvance(ptr)
@ stdcall KsStreamPointerAdvanceOffsets(ptr long long long)
@ stdcall KsStreamPointerAdvanceOffsetsAndUnlock(ptr long long long)
@ stdcall KsStreamPointerCancelTimeout(ptr)
@ stdcall KsStreamPointerClone(ptr ptr long ptr)
@ stdcall KsStreamPointerDelete(ptr)
@ stdcall KsStreamPointerGetIrp(ptr ptr ptr)
@ stdcall KsStreamPointerGetMdl(ptr)
@ stdcall KsStreamPointerGetNextClone(ptr)
@ stdcall KsStreamPointerLock(ptr)
@ stdcall KsStreamPointerScheduleTimeout(ptr ptr double)
@ stdcall KsStreamPointerSetStatusCode(ptr long)
@ stdcall KsStreamPointerUnlock(ptr long)
@ stdcall KsSynchronousIoControlDevice(ptr long long ptr long ptr long ptr)
@ stdcall KsTerminateDevice(ptr)
@ stdcall KsTopologyPropertyHandler(ptr ptr ptr ptr)
@ stdcall KsUnregisterWorker(ptr)
@ stdcall KsUnserializeObjectPropertiesFromRegistry(ptr ptr ptr)
@ stdcall KsValidateAllocatorCreateRequest(ptr ptr)
@ stdcall KsValidateAllocatorFramingEx(ptr long ptr)
@ stdcall KsValidateClockCreateRequest(ptr ptr)
@ stdcall KsValidateConnectRequest(ptr long ptr ptr)
@ stdcall KsValidateTopologyNodeCreateRequest(ptr ptr ptr)
@ stdcall KsWriteFile(ptr ptr ptr ptr ptr long long long)
