tasks:
  - before: > 
      brew install cmake ninja
    init: >
      mkdir -p /workspace/reactos/build &&
      cd /workspace/reactos/build &&
      cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DSEPARATE_DBG:BOOL=TRUE -D_WINKD_:BOOL=TRUE -DKDBG:BOOL=FALSE -DENABLE_ROSTESTS:BOOL=TRUE -DCMAKE_TOOLCHAIN_FILE=toolchain-gcc.cmake -G "Ninja" &&
      ninja xdk psdk 
    command: >
      cd /workspace/reactos/build &&
      ninja all

image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - ms-vscode.cpptools@0.27.0-insiders3:Djj3Csw0GXjmueWAPWvTsg==
