foreach(lang C CXX)
    set(CMAKE_${lang}_FLAGS_DEBUG_INIT "")
    set(CMAKE_${lang}_FLAGS_INIT "")
    set(CMAKE_${lang}_FLAGS_RELEASE_INIT "")
    set(CMAKE_${lang}_STANDARD_LIBRARIES_INIT "")
endforeach()

foreach(type EXE MODULE SHARED)
    set(CMAKE_${type}_LINKER_FLAGS_DEBUG_INIT "/debug")
    set(CMAKE_${type}_LINKER_FLAGS_RELWITHDEBINFO_INIT "/debug")
endforeach()
