# $Id$

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = msfs

TARGET_OBJECTS = \
  create.o \
  finfo.o \
  fsctrl.o \
  msfs.o \
  rw.o

TARGET_CFLAGS = -Werror -Wall

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
