# $Id: Makefile,v 1.7 2001/08/21 20:13:12 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = msfs

TARGET_OBJECTS = \
  create.o \
  finfo.o \
  fsctrl.o \
  msfs.o \
  rw.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
