//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by AccWiz.rc
//
#define IDR_MENU                        1
#define IDR_MENUWITHSELECTED            2
#define IDS_WIZNOOPTIONSSELECTEDTITLE   4
#define IDS_WIZNOOPTIONSSELECTEDSUBTITLE 5
#define IDS_GENERICPAGETITLE            6
#define IDS_GENERICPAGESUBTITLE         7
#define IDS_WIZFILTERKEYSTITLE          8
#define IDS_WIZFILTERKEYSSUBTITLE       9
#define IDS_WIZSTICKYKEYSTITLE          10
#define IDM_NORMAL                      10
#define IDS_WIZSTICKYKEYSSUBTITLE       11
#define IDM_DISABLED                    11
#define IDS_WIZTOGGLEKEYSTITLE          12
#define IDM_SELECTED                    12
#define IDS_WIZTOGGLEKEYSSUBTITLE       13
#define IDS_WIZSHOWEXTRAKEYBOARDHELPTITLE 14
#define IDS_WIZSHOWEXTRAKEYBOARDHELPSUBTITLE 15
#define IDS_WIZHOTKEYANDNOTIFICATIONTITLE 18
#define IDS_WIZHOTKEYANDNOTIFICATIONSUBTITLE 19
#define IDS_WIZSAVEASDEFAULTTITLE       20
#define IDS_WIZSAVEASDEFAULTSUBTITLE    21
#define IDS_WIZACCESSTIMEOUTTITLE       22
#define IDS_WIZACCESSTIMEOUTSUBTITLE    23
#define IDS_WIZSAVETOFILETITLE          24
#define IDS_WIZSAVETOFILESUBTITLE       25
#define IDS_WIZOPTTITLE                 26
#define IDS_WIZOPTSUBTITLE              27
#define IDS_MSEWIZMOUSEKEYSTITLE        90
#define IDS_MSEWIZMOUSEKEYSSUBTITLE     91
#define IDS_MSEWIZMOUSECURSORTITLE      92
#define IDS_MSEWIZMOUSECURSORSUBTITLE   93
#define IDS_MSEWIZBUTTONCONFIGTITLE     94
#define IDS_MSEWIZBUTTONCONFIGSUBTITLE  95
#define IDC_GROUPBOX_2                  96
#define IDS_MSEWIZMOUSESPEEDTITLE       96
#define IDC_GROUPBOX_3                  97
#define IDS_MSEWIZMOUSESPEEDSUBTITLE    97
#define IDS_MSEWIZMOUSETRAILSTITLE      98
#define IDS_MSEWIZMOUSETRAILSSUBTITLE   99
#define MOUSE_LEFTHAND                  100
#define IDB_MOUSE                       100
#define MOUSE_RIGHTHAND                 101
#define IDI_APP_ICON                    101
#define IDD_WIZFINISH                   109
#define IDC_SELECTDRAG                  109
#define IDI_CURSOR_SMALL_BLACK          109
#define IDS_SNDWIZSENTRYSHOWSOUNDSTITLE 110
#define IDC_OBJECTMENU                  110
#define IDS_SNDWIZSENTRYSHOWSOUNDSSUBTITLE 111
#define IDI_CURSOR_SMALL_INVERTING      111
#define IDI_CURSOR_MEDIUM_BLACK         112
#define IDS_SNDWIZSENTRYTITLE           112
#define IDI_CURSOR_MEDIUM_INVERTING     113
#define IDS_SNDWIZSENTRYSUBTITLE        113
#define IDS_SNDWIZSHOWSOUNDSTITLE       114
#define IDS_SNDWIZSHOWSOUNDSSUBTITLE    115
#define IDB_ACCWIZ                      128
#define IDB_ACCMARK                     129
#define IDD_WIZOPTIONS                  154
#define IDD_WIZWORKSTATIONDEFAULT       176
#define IDD_WIZNOOPTIONSSELECTED        177
#define IDD_MSEWIZMOUSECURSOR           181
#define IDD_SNDWIZSENTRYSHOWSOUNDS      182
#define IDD_MSEWIZMOUSEKEYS             183
#define IDD_KBDWIZSTICKYKEYS            184
#define IDD_KBDWIZTOGGLEKEYS            186
#define IDD_KBDWIZSHOWEXTRAKEYBOARDHELP 187
#define IDI_CURSOR_LARGE_INVERTING      242
#define IDI_CURSOR_SMALL_WHITE          243
#define IDI_CURSOR_MEDIUM_WHITE         244
#define IDI_CURSOR_LARGE_WHITE          245
#define IDI_CURSOR_LARGE_BLACK          246
#define IDS_SNDSEN_SSWF_NONE            300
#define IDS_SNDSEN_SSWF_TITLE           301
#define IDS_SNDSEN_SSWF_WINDOW          302
#define IDS_SNDSEN_SSWF_DISPLAY         303
#define IDS_SNDSEN_SSTF_NONE            304
#define IDS_SNDSEN_SSTF_CHARS           305
#define IDS_SNDSEN_SSTF_BORDER          306
#define IDS_SNDSEN_SSTF_DISPLAY         307
#define IDD_MSEWIZBUTTONCONFIG          400
#define IDS_WELCOMETITLE                400
#define IDD_WIZSAVETOFILE               402
#define IDD_WIZWELCOME2                 404
#define IDD_FNTWIZSCROLLBAR             405
#define IDD_PREV_COLOR                  410
#define IDD_WIZACCESSTIMEOUT            417
#define IDD_MSEWIZMOUSEKEYS1            419
#define IDD_SNDWIZSENTRYSHOWSOUNDS2     422
#define IDD_WIZWELCOME                  423
#define IDD_PREV_ICON2                  424
#define IDD_MSEWIZMOUSESPEED            425
#define IDD_KBDWIZFILTERKEYS1           426
#define IDD_KBDWIZFILTERKEYS2           427
#define IDD_WIZLAUNCHMAGNIFY            428
#define IDD_WIZLAUNCHSCREENREADER       429
#define IDD_WIZLAUNCHONSCREENKEYBOARD   430
#define IDD_MSEWIZMOUSETRAILS           431
#define IDD_WIZNEWWELCOME               432
#define IDC_MK_TOPSPEED                 603
#define IDC_MK_ACCEL                    604
#define IDC_CHECKSAVESETTINGTODEFAULT   1000
#define IDC_DOBLIND                     1006
#define IDC_DOKEYBOARDMOUSE             1007
#define IDC_DOSOUND                     1008
#define IDC_DOADMIN                     1009
#define IDC_PERMENU                     1010
#define IDC_TRANSPARENT1                1011
#define IDC_MK_NLOFF                    1018
#define IDC_MK_NLON                     1019
#define IDC_FK_LBL_TESTBOX              1024
#define IDC_BK_TIME_LBL_SHORT           1025
#define IDC_BK_TIME_LBL_LONG            1026
#define IDC_MK_LBL1                     1033
#define IDC_MK_LBL2                     1034
#define IDC_MK_LBL3                     1035
#define IDC_MK_LBL4                     1036
#define IDC_TO_ENABLE                   1037
#define IDC_MK_LBL5                     1037
#define IDC_TO_TIMEOUTVAL               1038
#define IDC_MK_LBL6                     1038
#define IDC_MK_LBL7                     1039
#define IDC_RADIO1                      1042
#define IDC_RADIO2                      1043
#define IDC_RADIO3                      1044
#define IDC_RADIO4                      1045
#define IDC_RADIO5                      1046
#define IDC_RADIO6                      1047
#define IDC_RADIO7                      1048
#define IDC_BTNBROWSE                   1048
#define IDC_FK_TESTBOX                  1049
#define IDC_RADIO8                      1049
#define IDC_RADIO9                      1050
#define IDC_RADIO10                     1051
#define IDC_SWITCHRESOLUTION            1053
#define IDC_CHANGEFONTS                 1054
#define IDC_USEMAGNIFY                  1055
#define IDC_BK_TIME                     1056
#define IDC_SZRESMESSAGE                1056
#define IDC_BK_BOUNCERATE               1057
#define IDC_BTNRESTORETODEFAULT         1057
#define IDC_PREVLIST                    1074
#define IDC_RADIOYES                    1077
#define IDC_BK_TIME_LBL2                1088
#define IDC_TO_DISABLE                  1089
#define IDC_MOUSEPIC2                   1097
#define IDC_MOUSEPIC1                   1098
#define IDC_SLIDER1                     1105
#define IDC_SELECTIONMINTEXT            1107
#define IDC_SELECTIONICONSIZE           1108
#define IDC_SELECTIONSCROLLBAR          1109
#define IDC_SZCHANGES                   1110
#define IDC_RADIONO                     1111
#define IDC_RADIOBEEPYES                1113
#define IDC_RADIOBEEPNO                 1114
#define IDC_TEXT1                       1116
#define IDC_TEXT2                       1117
#define IDC_TEXT3                       1118
#define IDC_CHECK1                      1119
#define IDC_ICON1                       1120
#define IDC_ICON2                       1121
#define IDC_ICON3                       1122
#define IDC_SCROLL1                     1123
#define IDC_SCROLL2                     1124
#define IDC_SCROLL3                     1125
#define IDC_SCROLL4                     1126
#define IDS_ACTIVE                      1450
#define IDS_INACTIVE                    1451
#define IDS_MINIMIZED                   1452
#define IDS_ICONTITLE                   1453
#define IDS_NORMAL                      1454
#define IDS_DISABLED                    1455
#define IDS_SELECTED                    1456
#define IDS_MSGBOX                      1457
#define IDS_BUTTONTEXT                  1458
#define IDS_SMCAPTION                   1459
#define IDS_WINDOWTEXT                  1460
#define IDS_MSGBOXTEXT                  1461
#define IDC_LOOKPREV                    1470
#define IDS_WIZSAVECHANGESMESSAGETITLE  1501
#define IDS_WIZSAVECHANGESMESSAGETEXT   1502
#define IDS_WIZERRORLOADINGFILETITLE    1503
#define IDS_WIZERRORLOADINGFILETEXT     1504
#define IDS_WIZERRORNEEDADMINTITLE      1505
#define IDS_WIZERRORNEEDADMINTEXT       1506
#define IDS_WIZERRORSAVINGFILETITLE     1507
#define IDS_WIZERRORSAVINGFILETEXT      1508
#define IDS_WIZCHANGESHAPPENINGTITLE    1509
#define IDS_WIZCHANGESHAPPENINGTEXT     1510
#define IDS_WIZCANCELCHANGESTITLE       1511
#define IDS_WIZCANCELCHANGESTEXT        1512
#define IDS_ICONSIZENAMENORMAL          1600
#define IDS_ICONSIZENAMELARGE           1601
#define IDS_ICONSIZENAMEEXTRALARGE      1602
#define IDS_DEFAULTSAVEFILENAME         1700
#define IDS_FILTERNAME                  1701
#define IDS_FILTER                      1702
#define IDS_FILTER2                     1703
#define IDS_DISPLAYRESOLUTIONINFO       1709
#define IDS_SCHEME_HIGHCONTRASTBLACK    2000
#define IDS_SCHEME_HIGHCONTRASTWHITE    2001
#define IDS_SCHEME_HIGHCONTRASTBLACKALTERNATE 2002
#define IDS_SCHEME_HIGHCONTRASTWHITEALTERNATE 2003
#define IDS_SCHEME_WINDOWSSTANDARD      2004
#define IDS_SCHEME_CURRENTCOLORSCHEME   2005
#define IDS_SCHEME_BLAHBLAHBLAH         2006
#define IDC_BIGBOLDTITLE                2090
#define IDC_BOLDTITLE                   2091
#define IDC_BIGTITLE                    2092
#define IDB_MOUSE2                      2570
#define IDS_LKPREV_SCROLLSIZES          3000
#define IDS_LKPREV_MINTEXTSIZES         3001
#define IDS_LKPREV_BORDERSIZES          3002
#define IDS_LKPREV_WELCOME_MINTEXTSIZES 3003
#define IDS_LKPREV_MINTEXTTITLE         3100
#define IDS_LKPREV_MINTEXTSUBTITLE      3101
#define IDS_LKPREV_COLORTITLE           3102
#define IDS_LKPREV_COLORSUBTITLE        3103
#define IDS_LKPREV_SCROLLBARTITLE       3104
#define IDS_LKPREV_SCROLLBARSUBTITLE    3105
#define IDS_LKPREV_BORDERTITLE          3106
#define IDS_LKPREV_BORDERSUBTITLE       3107
#define IDS_LKPREV_ICONTITLE            3108
#define IDS_LKPREV_ICONSUBTITLE         3109
#define IDS_WELCOME2TITLE               3110
#define IDS_WELCOME2SUBTITLE            3111
#define IDS_ICONPREV_ITEM1              3112
#define IDS_ICONPREV_ITEM2              3113
#define IDS_ICONPREV_ITEM3              3114
#define IDS_ICONPREV_ITEM4              3115
#define IDS_ICONPREV_ITEM5              3116
#define IDS_ICONPREV_ITEM6              3117
#define IDS_BIGBOLDFONTSIZE             4000
#define IDS_BIGBOLDFONTNAME             4001
#define IDS_BOLDFONTSIZE                4002
#define IDS_BOLDFONTNAME                4003
#define IDS_BIGFONTSIZE                 4004
#define IDS_BIGFONTNAME                 4005
#define IDS_SYSTEMFONTNAME              4006
#define IDS_FONTCHARSET                 4100
#define IDS_WINDOWSDEFAULTSIZES         4200
#define IDS_PREVIEWMENUTEXT             4501
#define IDS_CURSOR_SCHEME_WINDOWS_STANDARD_LARGE 5002
#define IDS_CURSOR_SCHEME_WINDOWS_STANDARD_EXTRALARGE 5003
#define IDS_CURSOR_SCHEME_WINDOWS_BLACK 5004
#define IDS_CURSOR_SCHEME_WINDOWS_BLACK_LARGE 5005
#define IDS_CURSOR_SCHEME_WINDOWS_BLACK_EXTRALARGE 5006
#define IDS_CURSOR_SCHEME_WINDOWS_INVERTED 5007
#define IDS_CURSOR_SCHEME_WINDOWS_INVERTED_LARGE 5008
#define IDS_CURSOR_SCHEME_WINDOWS_INVERTED_EXTRALARGE 5009
#define IDS_WELCOMETEXT1                6001
#define IDS_WELCOMETEXT2                6002
#define IDS_WELCOMETEXT3                6003
#define IDS_WELCOMETEXT4                6004
#define IDS_CHANGESFILTERKEYS           7000
#define IDS_CHANGESMOUSEKEYS            7001
#define IDS_CHANGESSERIALKEYS           7002
#define IDS_CHANGESSTICKYKEYS           7003
#define IDS_CHANGESTOGGLEKEYS           7004
#define IDS_CHANGESSOUNDSENTRY          7005
#define IDS_CHANGESACCESSTIMEOUT        7006
#define IDS_CHANGESHIGHCONTRAST         7007
#define IDS_CHANGESShowSounds           7008
#define IDS_CHANGESShowExtraKeyboardHelp 7009
#define IDS_CHANGESSwapMouseButtons     7010
#define IDS_CHANGESCOLOR                7011
#define IDS_CHANGESNONCLIENTMETRICS     7012
#define IDS_CHANGESMouseSpeed           7013
#define IDS_CHANGESMouseTrails          7014
#define IDS_CHANGESIconSize             7015
#define IDS_CHANGES16                   7016
#define IDS_CHANGESCursorScheme         7016
#define IDS_CHANGES17                   7017
#define IDS_CHANGESScrollWidth          7017
#define IDS_CHANGES18                   7018
#define IDS_CHANGESBorderWidth          7018
#define IDS_CHANGES19                   7019
#define IDS_CHANGES19a                  7019
#define IDS_CHANGES20                   7020
#define IDS_CHANGES21                   7021
#define IDS_CHANGES22                   7022
#define IDS_CHANGESNOCHANGES            7023
#define IDC_WEBLINK                     7050
#define IDS_NAMEOFMAGNIFIER             8001
#define IDS_WIZFILTERKEYSETTING         8002
#define IDS_MSEWIZMOUSEKEYSETTING       8003
#define IDS_MSEWIZMOUSEKEYSETSUB        8004
#define IDS_TEXTSIZESUBTITLE            8004
#define IDS_TEXTSIZETITLE               8005
#define IDS_ENABLEWEB                   8006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1125
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
