@ stub CreateIMAPTransport2
@ stub CreateIMAPTransport
@ stub CreateNNTPTransport
@ stub CreatePOP3Transport
@ stub CreateRASTransport
@ stub CreateRangeList
@ stub CreateSMTPTransport
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ stub EssContentHintDecodeEx
@ stub EssContentHintEncodeEx
@ stub EssKeyExchPreferenceDecodeEx
@ stub EssKeyExchPreferenceEncodeEx
@ stub EssMLHistoryDecodeEx
@ stub EssMLHistoryEncodeEx
@ stub EssReceiptDecodeEx
@ stub EssReceiptEncodeEx
@ stub EssReceiptRequestDecodeEx
@ stub EssReceiptRequestEncodeEx
@ stub EssSecurityLabelDecodeEx
@ stub EssSecurityLabelEncodeEx
@ stub EssSignCertificateDecodeEx
@ stub EssSignCertificateEncodeEx
@ stub GetDllMajorVersion
@ stub HrAthGetFileName
@ stub HrAthGetFileNameW
@ stub HrAttachDataFromBodyPart
@ stub HrAttachDataFromFile
@ stub HrDoAttachmentVerb
@ stub HrFreeAttachData
@ stub HrGetAttachIcon
@ stub HrGetAttachIconByFile
@ stub HrGetDisplayNameWithSizeForFile
@ stub HrGetLastOpenFileDirectory
@ stub HrGetLastOpenFileDirectoryW
@ stub HrSaveAttachToFile
@ stub HrSaveAttachmentAs
@ stub MimeEditCreateMimeDocument
@ stub MimeEditDocumentFromStream
@ stub MimeEditGetBackgroundImageUrl
@ stub MimeEditIsSafeToRun
@ stub MimeEditViewSource
@ stub MimeGetAddressFormatW
@ stub MimeOleAlgNameFromSMimeCap
@ stub MimeOleAlgStrengthFromSMimeCap
@ stub MimeOleClearDirtyTree
@ stub MimeOleConvertEnrichedToHTML
@ stub MimeOleCreateBody
@ stub MimeOleCreateByteStream
@ stub MimeOleCreateHashTable
@ stub MimeOleCreateHeaderTable
@ stdcall MimeOleCreateMessage(ptr ptr)
@ stub MimeOleCreateMessageParts
@ stub MimeOleCreatePropertySet
@ stdcall MimeOleCreateSecurity(ptr)
@ stdcall MimeOleCreateVirtualStream(ptr)
@ stub MimeOleDecodeHeader
@ stub MimeOleEncodeHeader
@ stub MimeOleFileTimeToInetDate
@ stub MimeOleFindCharset
@ stub MimeOleGenerateCID
@ stub MimeOleGenerateFileName
@ stub MimeOleGenerateMID
@ stdcall MimeOleGetAllocator(ptr)
@ stub MimeOleGetBodyPropA
@ stub MimeOleGetBodyPropW
@ stub MimeOleGetCertsFromThumbprints
@ stdcall MimeOleGetCharsetInfo(ptr ptr)
@ stub MimeOleGetCodePageCharset
@ stub MimeOleGetCodePageInfo
@ stub MimeOleGetContentTypeExt
@ stub MimeOleGetDefaultCharset
@ stub MimeOleGetExtContentType
@ stub MimeOleGetFileExtension
@ stub MimeOleGetFileInfo
@ stub MimeOleGetFileInfoW
@ stub MimeOleGetInternat
@ stub MimeOleGetPropA
@ stub MimeOleGetPropW
@ stub MimeOleGetPropertySchema
@ stub MimeOleGetRelatedSection
@ stub MimeOleInetDateToFileTime
@ stub MimeOleObjectFromMoniker
@ stub MimeOleOpenFileStream
@ stub MimeOleParseMhtmlUrl
@ stub MimeOleParseRfc822Address
@ stub MimeOleParseRfc822AddressW
@ stub MimeOleSMimeCapAddCert
@ stub MimeOleSMimeCapAddSMimeCap
@ stub MimeOleSMimeCapGetEncAlg
@ stub MimeOleSMimeCapGetHashAlg
@ stub MimeOleSMimeCapInit
@ stub MimeOleSMimeCapRelease
@ stub MimeOleSMimeCapsFromDlg
@ stub MimeOleSMimeCapsFull
@ stub MimeOleSMimeCapsToDlg
@ stub MimeOleSetBodyPropA
@ stub MimeOleSetBodyPropW
@ stdcall MimeOleSetCompatMode(long)
@ stub MimeOleSetDefaultCharset
@ stub MimeOleSetPropA
@ stub MimeOleSetPropW
@ stub MimeOleStripHeaders
@ stub MimeOleUnEscapeStringInPlace
