# $Id: makefile,v 1.8 2001/08/21 20:13:16 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = tditest

TARGET_CFLAGS = -I./include

TARGET_OBJECTS = \
  tditest/tditest.o

TARGET_CLEAN = \
  tditest/*.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
