#pragma once

#define IDS_USAGE       100
#define IDS_CONTINUE    101
#define IDS_CONTINUE_PROGRESS   102
#define IDS_FILE_ACCESS 103
#define IDS_BAD_FLAG 104
#define IDS_CONTINUE_OPTIONS 105
#define IDS_CONTINUE_LINES 106
#define IDS_CONTINUE_LINE_AT 107
