#pragma once

#define IDS_USAGE       100
#define IDS_BAD_FLAG    101
#define IDS_FILE_ACCESS 102

#define IDS_CONTINUE_PROMPT     110
#define IDS_CONTINUE_PERCENT    111
#define IDS_CONTINUE_LINE_AT    112
#define IDS_CONTINUE_OPTIONS    113
#define IDS_CONTINUE_LINES      114
