# $Id: makefile,v 1.9 2003/11/14 17:13:25 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_BOOTSTRAP = yes

TARGET_TYPE = driver

TARGET_NAME = keyboard

TARGET_CFLAGS = -Wall -Werror

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
