# $Id: Makefile 13504 2005-02-12 14:33:41Z ea $

PATH_TO_TOP = ../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = bootpsx

TARGET_SDKLIBS = ntdll.a smdll.a kernel32.a

TARGET_OBJECTS = $(TARGET_NAME).o 

TARGET_CFLAGS = -Wall -Werror

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
