#define IDD_CONNECT                 100
#define IDC_CONNECTNAME             101
#define IDD_KEEPASDLG               300
#define IDC_KEEPASEDIT              301
#define IDHELP                      303
#define IDC_SHARECHECKBOX           304
#define IDD_SHAREDLG                200
#define IDD_PROPERTYDLG             400
#define IDC_STATICSHRNAME           201
#define IDC_STARTAPP                203
#define IDC_APPINIT                 204
#define IDC_STATICSHARENAME         212
#define IDC_PERMISSIONS             202
#define IDC_MINIMIZED               215
#define IDC_ALLOWLINK               204
