PATH_TO_TOP = ../../..

TARGET_TYPE = driver
TARGET_NAME = csqtest
TARGET_DDKLIBS = csq.a
TARGET_CFLAGS = -Wall -Werror
TARGET_OBJECTS = csqtest.o

include $(PATH_TO_TOP)/rules.mak
include $(TOOLS_PATH)/helper.mk
