@ stdcall SnmpSvcAddrIsIpx(ptr ptr)
@ stdcall SnmpSvcAddrToSocket(ptr ptr)
@ stdcall SnmpSvcGetEnterpriseOID(ptr ptr)
@ stdcall SnmpSvcGetUptime()
@ stdcall SnmpSvcInitUptime()
@ stdcall SnmpSvcSetLogLevel(long)
@ stdcall SnmpSvcSetLogType(long)
@ stdcall SnmpTfxClose(ptr ptr)
@ stdcall SnmpTfxOpen(ptr ptr)
@ stdcall SnmpTfxQuery(ptr ptr)
@ stdcall SnmpUtilAnsiToUnicode(ptr ptr)
@ stdcall SnmpUtilAsnAnyCpy(ptr ptr)
@ stdcall SnmpUtilAsnAnyFree(ptr)
@ cdecl SnmpUtilDbgPrint(long str)
@ stdcall SnmpUtilIdsToA(ptr long)
@ stdcall SnmpUtilMemAlloc(long)
@ stdcall SnmpUtilMemFree(ptr)
@ stdcall SnmpUtilMemReAlloc(ptr long)
@ stdcall SnmpUtilOctetsCmp(ptr ptr)
@ stdcall SnmpUtilOctetsCpy(ptr ptr)
@ stdcall SnmpUtilOctetsFree(ptr)
@ stdcall SnmpUtilOctetsNCmp(ptr ptr long)
@ stdcall SnmpUtilOidAppend(ptr ptr)
@ stdcall SnmpUtilOidCmp(ptr ptr)
@ stdcall SnmpUtilOidCpy(ptr ptr)
@ stdcall SnmpUtilOidFree(ptr)
@ stdcall SnmpUtilOidNCmp(ptr ptr long)
@ stdcall SnmpUtilOidToA(ptr)
@ stdcall SnmpUtilPrintAsnAny(ptr)
@ stdcall SnmpUtilPrintOid(ptr)
@ stdcall SnmpUtilUTF8ToUnicode(ptr ptr)
@ stdcall SnmpUtilUnicodeToAnsi(ptr ptr)
@ stdcall SnmpUtilUnicodeToUTF8(ptr ptr)
@ stdcall SnmpUtilVarBindCpy(ptr ptr)
@ stdcall SnmpUtilVarBindFree(ptr)
@ stdcall SnmpUtilVarBindListCpy(ptr ptr)
@ stdcall SnmpUtilVarBindListFree(ptr)
