PATH_TO_TOP = ../../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = patchnv4

TARGET_SDKLIBS = 

TARGET_OBJECTS = patchnv4.o

TARGET_CFLAGS += -Wall -Werror

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
