# $Id$

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = pci

TARGET_CFLAGS = -Wall -Werror

TARGET_OBJECTS = fdo.o pci.o pdo.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
