#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H

#define IDC_CPLICON_1	1

#define IDD_PROPPAGE1	100
#define IDD_PROPPAGE2	101
#define IDD_PROPPAGE3	102

#define IDS_CPLNAME_1	1001
#define IDS_CPLDESCRIPTION_1	2001

#endif /* __CPL_RESOURCE_H */

/* EOF */
