
cpp_quote("#pragma once")

#ifndef DO_NO_IMPORTS
import "objidl.idl";
import "oaidl.idl";
import "ocidl.idl";
#endif

[object, 
    hidden, restricted,
    uuid(8A674B48-1F63-11d3-B64C-00C04F79498E),
    pointer_default(unique),
    local
]
interface ICreatePropBagOnRegKey : IUnknown
{
    HRESULT Create([in] HKEY hkey, [in] LPCOLESTR subkey, [in] DWORD ulOptions, [in] DWORD samDesired, REFIID iid, [out] LPVOID *ppBag);
};

