
# This file is autogenerated by update.py

@ stdcall LsaAddAccountRights() advapi32.LsaAddAccountRights
@ stdcall LsaClose() advapi32.LsaClose
@ stdcall LsaCreateSecret() advapi32.LsaCreateSecret
@ stdcall LsaEnumerateAccountRights() advapi32.LsaEnumerateAccountRights
@ stdcall LsaEnumerateAccountsWithUserRight() advapi32.LsaEnumerateAccountsWithUserRight
@ stdcall LsaFreeMemory() advapi32.LsaFreeMemory
@ stdcall LsaICLookupNames() advapi32.LsaICLookupNames
@ stdcall LsaICLookupNamesWithCreds() advapi32.LsaICLookupNamesWithCreds
@ stdcall LsaICLookupSids() advapi32.LsaICLookupSids
@ stdcall LsaICLookupSidsWithCreds() advapi32.LsaICLookupSidsWithCreds
@ stdcall LsaLookupNames2() advapi32.LsaLookupNames2
@ stdcall LsaLookupSids() advapi32.LsaLookupSids
@ stub LsaLookupSids2
@ stdcall LsaOpenPolicy() advapi32.LsaOpenPolicy
@ stdcall LsaOpenSecret() advapi32.LsaOpenSecret
@ stdcall LsaQueryInformationPolicy() advapi32.LsaQueryInformationPolicy
@ stdcall LsaQuerySecret() advapi32.LsaQuerySecret
@ stdcall LsaRemoveAccountRights() advapi32.LsaRemoveAccountRights
@ stdcall LsaRetrievePrivateData() advapi32.LsaRetrievePrivateData
@ stdcall LsaSetInformationPolicy() advapi32.LsaSetInformationPolicy
@ stdcall LsaSetSecret() advapi32.LsaSetSecret
@ stdcall LsaStorePrivateData() advapi32.LsaStorePrivateData
