
# This file is autogenerated by update.py

@ stub RtlCopyExtendedContext
@ stub RtlGetEnabledExtendedFeatures
@ stub RtlGetExtendedContextLength
@ stub RtlGetExtendedFeaturesMask
@ stub RtlInitializeExtendedContext
@ stub RtlLocateExtendedFeature
@ stub RtlLocateLegacyContext
@ stub RtlSetExtendedFeaturesMask
