
# This file is autogenerated by update.py

@ stdcall CredDeleteA() advapi32.CredDeleteA
@ stdcall CredDeleteW() advapi32.CredDeleteW
@ stdcall CredEnumerateA() advapi32.CredEnumerateA
@ stdcall CredEnumerateW() advapi32.CredEnumerateW
@ stub CredFindBestCredentialA
@ stub CredFindBestCredentialW
@ stdcall CredFree() advapi32.CredFree
@ stdcall CredGetSessionTypes() advapi32.CredGetSessionTypes
@ stdcall CredGetTargetInfoA() advapi32.CredGetTargetInfoA
@ stdcall CredGetTargetInfoW() advapi32.CredGetTargetInfoW
@ stdcall CredIsMarshaledCredentialW() advapi32.CredIsMarshaledCredentialW
@ stub CredIsProtectedA
@ stub CredIsProtectedW
@ stdcall CredMarshalCredentialA() advapi32.CredMarshalCredentialA
@ stdcall CredMarshalCredentialW() advapi32.CredMarshalCredentialW
@ stub CredProtectA
@ stub CredProtectW
@ stdcall CredReadA() advapi32.CredReadA
@ stdcall CredReadDomainCredentialsA() advapi32.CredReadDomainCredentialsA
@ stdcall CredReadDomainCredentialsW() advapi32.CredReadDomainCredentialsW
@ stdcall CredReadW() advapi32.CredReadW
@ stdcall CredUnmarshalCredentialA() advapi32.CredUnmarshalCredentialA
@ stdcall CredUnmarshalCredentialW() advapi32.CredUnmarshalCredentialW
@ stub CredUnprotectA
@ stub CredUnprotectW
@ stdcall CredWriteA() advapi32.CredWriteA
@ stub CredWriteDomainCredentialsA
@ stdcall CredWriteDomainCredentialsW() advapi32.CredWriteDomainCredentialsW
@ stdcall CredWriteW() advapi32.CredWriteW
