
# This file is autogenerated by update.py

@ stdcall -version=0x600+ GetStringScripts() kernel32.GetStringScripts
@ stdcall -version=0x600+ IdnToNameprepUnicode() kernel32.IdnToNameprepUnicode
@ stdcall -version=0x600+ IsNormalizedString() kernel32.IsNormalizedString
@ stdcall -version=0x600+ NormalizeString() kernel32.NormalizeString
@ stdcall -version=0x600+ VerifyScripts() kernel32.VerifyScripts
