
# This file is autogenerated by update.py

@ stdcall GetTraceEnableFlags() advapi32.GetTraceEnableFlags
@ stdcall GetTraceEnableLevel() advapi32.GetTraceEnableLevel
@ stdcall GetTraceLoggerHandle() advapi32.GetTraceLoggerHandle
@ stdcall RegisterTraceGuidsW() advapi32.RegisterTraceGuidsW
@ stdcall TraceEvent() advapi32.TraceEvent
@ stdcall TraceMessage() advapi32.TraceMessage
@ stdcall TraceMessageVa() advapi32.TraceMessageVa
@ stdcall UnregisterTraceGuids() advapi32.UnregisterTraceGuids
