
# This file is autogenerated by update.py

@ stdcall ConvertDefaultLocale() kernel32.ConvertDefaultLocale
@ stdcall EnumSystemGeoID() kernel32.EnumSystemGeoID
@ stdcall EnumSystemLocalesA() kernel32.EnumSystemLocalesA
@ stdcall EnumSystemLocalesW() kernel32.EnumSystemLocalesW
@ stub FindNLSString
@ stub FindNLSStringEx
@ stdcall FormatMessageA() kernel32.FormatMessageA
@ stdcall FormatMessageW() kernel32.FormatMessageW
@ stdcall GetACP() kernel32.GetACP
@ stdcall GetCPInfo() kernel32.GetCPInfo
@ stdcall GetCPInfoExW() kernel32.GetCPInfoExW
@ stub GetCalendarInfoEx
@ stdcall GetCalendarInfoW() kernel32.GetCalendarInfoW
@ stub GetFileMUIInfo
@ stub GetFileMUIPath
@ stdcall GetGeoInfoW() kernel32.GetGeoInfoW
@ stdcall GetLocaleInfoA() kernel32.GetLocaleInfoA
@ stub GetLocaleInfoEx
@ stdcall GetLocaleInfoW() kernel32.GetLocaleInfoW
@ stdcall GetNLSVersion() kernel32.GetNLSVersion
@ stub GetNLSVersionEx
@ stdcall GetOEMCP() kernel32.GetOEMCP
@ stub GetProcessPreferredUILanguages
@ stdcall GetSystemDefaultLCID() kernel32.GetSystemDefaultLCID
@ stdcall GetSystemDefaultLangID() kernel32.GetSystemDefaultLangID
@ stub GetSystemPreferredUILanguages
@ stdcall GetThreadLocale() kernel32.GetThreadLocale
@ stub GetThreadPreferredUILanguages
@ stub GetThreadUILanguage
@ stub GetUILanguageInfo
@ stdcall GetUserDefaultLCID() kernel32.GetUserDefaultLCID
@ stdcall GetUserDefaultLangID() kernel32.GetUserDefaultLangID
@ stub GetUserDefaultLocaleName
@ stdcall GetUserGeoID() kernel32.GetUserGeoID
@ stub GetUserPreferredUILanguages
@ stub IdnToAscii
@ stub IdnToUnicode
@ stdcall IsDBCSLeadByte() kernel32.IsDBCSLeadByte
@ stdcall IsDBCSLeadByteEx() kernel32.IsDBCSLeadByteEx
@ stdcall IsNLSDefinedString() kernel32.IsNLSDefinedString
@ stdcall IsValidCodePage() kernel32.IsValidCodePage
@ stdcall IsValidLanguageGroup() kernel32.IsValidLanguageGroup
@ stdcall IsValidLocale() kernel32.IsValidLocale
@ stub IsValidLocaleName
@ stub IsValidNLSVersion
@ stdcall LCMapStringA() kernel32.LCMapStringA
@ stub LCMapStringEx
@ stdcall LCMapStringW() kernel32.LCMapStringW
@ stub LocaleNameToLCID
@ stub ResolveLocaleName
@ stdcall SetCalendarInfoW() kernel32.SetCalendarInfoW
@ stdcall SetLocaleInfoW() kernel32.SetLocaleInfoW
@ stub SetProcessPreferredUILanguages
@ stdcall SetThreadLocale() kernel32.SetThreadLocale
@ stub SetThreadPreferredUILanguages
@ stdcall SetThreadUILanguage() kernel32.SetThreadUILanguage
@ stdcall SetUserGeoID() kernel32.SetUserGeoID
@ stdcall VerLanguageNameA() kernel32.VerLanguageNameA
@ stdcall VerLanguageNameW() kernel32.VerLanguageNameW
