
# This file is autogenerated by update.py

@ stdcall CloseDriver() winmm.CloseDriver
@ stdcall DefDriverProc() winmm.DefDriverProc
@ stdcall DriverCallback() winmm.DriverCallback
@ stdcall DrvGetModuleHandle() winmm.DrvGetModuleHandle
@ stdcall GetDriverModuleHandle() winmm.GetDriverModuleHandle
@ stdcall OpenDriver() winmm.OpenDriver
@ stdcall SendDriverMessage() winmm.SendDriverMessage
@ stub mmDrvInstall
@ stdcall mmioAdvance() winmm.mmioAdvance
@ stdcall mmioAscend() winmm.mmioAscend
@ stdcall mmioClose() winmm.mmioClose
@ stdcall mmioCreateChunk() winmm.mmioCreateChunk
@ stdcall mmioDescend() winmm.mmioDescend
@ stdcall mmioFlush() winmm.mmioFlush
@ stdcall mmioGetInfo() winmm.mmioGetInfo
@ stdcall mmioInstallIOProcA() winmm.mmioInstallIOProcA
@ stdcall mmioInstallIOProcW() winmm.mmioInstallIOProcW
@ stdcall mmioOpenA() winmm.mmioOpenA
@ stdcall mmioOpenW() winmm.mmioOpenW
@ stdcall mmioRead() winmm.mmioRead
@ stdcall mmioRenameA() winmm.mmioRenameA
@ stdcall mmioRenameW() winmm.mmioRenameW
@ stdcall mmioSeek() winmm.mmioSeek
@ stdcall mmioSendMessage() winmm.mmioSendMessage
@ stdcall mmioSetBuffer() winmm.mmioSetBuffer
@ stdcall mmioSetInfo() winmm.mmioSetInfo
@ stdcall mmioStringToFOURCCA() winmm.mmioStringToFOURCCA
@ stdcall mmioStringToFOURCCW() winmm.mmioStringToFOURCCW
@ stdcall mmioWrite() winmm.mmioWrite
@ stub sndOpenSound
