
# This file is autogenerated by update.py

@ stdcall FlsAlloc() kernel32.FlsAlloc
@ stdcall FlsFree() kernel32.FlsFree
@ stdcall FlsGetValue() kernel32.FlsGetValue
@ stdcall FlsSetValue() kernel32.FlsSetValue
