
# This file is autogenerated by update.py

@ stdcall CancelIo() kernel32.CancelIo
@ stdcall -version=0x600+ CancelIoEx() kernel32.CancelIoEx
@ stdcall -version=0x600+ CancelSynchronousIo() kernel32.CancelSynchronousIo
@ stdcall CreateIoCompletionPort() kernel32.CreateIoCompletionPort
@ stdcall DeviceIoControl() kernel32.DeviceIoControl
@ stdcall GetOverlappedResult() kernel32.GetOverlappedResult
@ stub GetOverlappedResultEx
@ stdcall GetQueuedCompletionStatus() kernel32.GetQueuedCompletionStatus
@ stdcall -version=0x600+ GetQueuedCompletionStatusEx() kernel32.GetQueuedCompletionStatusEx
@ stdcall PostQueuedCompletionStatus() kernel32.PostQueuedCompletionStatus
