
# This file is autogenerated by update.py

@ stdcall ChangeServiceConfig2W() advapi32.ChangeServiceConfig2W
@ stdcall ChangeServiceConfigW() advapi32.ChangeServiceConfigW
@ stub NotifyServiceStatusChangeW
@ stdcall QueryServiceConfig2W() advapi32.QueryServiceConfig2W
@ stdcall QueryServiceConfigW() advapi32.QueryServiceConfigW
@ stdcall QueryServiceObjectSecurity() advapi32.QueryServiceObjectSecurity
@ stdcall QueryServiceStatusEx() advapi32.QueryServiceStatusEx
@ stdcall SetServiceObjectSecurity() advapi32.SetServiceObjectSecurity
