
# This file is autogenerated by update.py

@ stub K32EmptyWorkingSet
@ stub K32EnumDeviceDrivers
@ stub K32EnumPageFilesW
@ stub K32EnumProcesses
@ stub K32GetDeviceDriverBaseNameW
@ stub K32GetDeviceDriverFileNameW
@ stub K32GetMappedFileNameW
@ stub K32GetPerformanceInfo
@ stub K32GetProcessImageFileNameW
@ stub K32GetProcessMemoryInfo
@ stub K32GetWsChanges
@ stub K32GetWsChangesEx
@ stub K32InitializeProcessForWsWatch
@ stub K32QueryWorkingSet
@ stub K32QueryWorkingSetEx
@ stdcall -version=0x600+ QueryFullProcessImageNameW() kernel32.QueryFullProcessImageNameW
