@echo Nuking urlmon ...
@delnode /q agent\daytona\obj 1>nul: 2>nul:
@delnode /q agent\daytona\objd 1>nul: 2>nul:
@delnode /q agent\daytona\objp 1>nul: 2>nul:
@delnode /q dll\daytona\obj 1>nul: 2>nul:
@delnode /q dll\daytona\objd 1>nul: 2>nul:
@delnode /q dll\daytona\objp 1>nul: 2>nul:
@delnode /q download\daytona\obj 1>nul: 2>nul:
@delnode /q download\daytona\objd 1>nul: 2>nul:
@delnode /q download\daytona\objp 1>nul: 2>nul:
@delnode /q eapp\daytona\obj 1>nul: 2>nul:
@delnode /q eapp\daytona\objd 1>nul: 2>nul:
@delnode /q eapp\daytona\objp 1>nul: 2>nul:
@delnode /q iapp\daytona\obj 1>nul: 2>nul:
@delnode /q iapp\daytona\objd 1>nul: 2>nul:
@delnode /q iapp\daytona\objp 1>nul: 2>nul:
@delnode /q idl\obj 1>nul: 2>nul:
@delnode /q idl\objd 1>nul: 2>nul:
@delnode /q idl\objp 1>nul: 2>nul:
@delnode /q mon\daytona\obj 1>nul: 2>nul:
@delnode /q mon\daytona\objd 1>nul: 2>nul:
@delnode /q mon\daytona\objp 1>nul: 2>nul:
@delnode /q proxy\daytona\obj 1>nul: 2>nul:
@delnode /q proxy\daytona\objd 1>nul: 2>nul:
@delnode /q proxy\daytona\objp 1>nul: 2>nul:
@delnode /q stg\daytona\obj 1>nul: 2>nul:
@delnode /q stg\daytona\objd 1>nul: 2>nul:
@delnode /q stg\daytona\objp 1>nul: 2>nul:
@delnode /q trans\daytona\obj 1>nul: 2>nul:
@delnode /q trans\daytona\objd 1>nul: 2>nul:
@delnode /q trans\daytona\objp 1>nul: 2>nul:
@delnode /q urlhlink\daytona\obj 1>nul: 2>nul:
@delnode /q urlhlink\daytona\objd 1>nul: 2>nul:
@delnode /q urlhlink\daytona\objp 1>nul: 2>nul:
@delnode /q utils\daytona\obj 1>nul: 2>nul:
@delnode /q utils\daytona\objd 1>nul: 2>nul:
@delnode /q utils\daytona\objp 1>nul: 2>nul:
@delnode /q wcheckcb\daytona\obj 1>nul: 2>nul:
@delnode /q wcheckcb\daytona\objd 1>nul: 2>nul:
@delnode /q wcheckcb\daytona\objp 1>nul: 2>nul:
@delnode /q notifctn\daytona\obj 1>nul: 2>nul:
@delnode /q notifctn\daytona\objd 1>nul: 2>nul:
@delnode /q notifctn\daytona\objp 1>nul: 2>nul:
@delnode /q zones\daytona\obj 1>nul: 2>nul:
@delnode /q zones\daytona\objd 1>nul: 2>nul:
@delnode /q zones\daytona\objp 1>nul: 2>nul:
@delnode /q compress\gzip\daytona\obj 1>nul: 2>nul:
@delnode /q compress\gzip\daytona\objd 1>nul: 2>nul:
@delnode /q compress\gzip\daytona\objp 1>nul: 2>nul:
@delnode /q urltrack\daytona\obj 1>nul: 2>nul:
@delnode /q urltrack\daytona\objd 1>nul: 2>nul:
@delnode /q urltrack\daytona\objp 1>nul: 2>nul:
@delnode /q jit\obj 1>nul: 2>nul:
@delnode /q jit\objd 1>nul: 2>nul:
@delnode /q jit\daytona\objp 1>nul: 2>nul:
@del /q/s build*.* 1>nul: 2>nul:
@del /q proxy\dlldata.c 1>nul: 2>nul:
@del /q proxy\*_p.c 1>nul: 2>nul:
@del /q uuid\*_i.c 1>nul: 2>nul:
@del /q dll\daytona\msg00001.bin 1>nul: 2>nul:
@del /q dll\daytona\urlerr.h 1>nul: 2>nul:
@del /q dll\daytona\urlerr.rc 1>nul: 2>nul:
@del /q dll\selfreg.inf 1>nul: 2>nul:
@echo Files remaining after nuke:
@dir *.* /a:-r-d/s/b
