/*
 * COPYRIGHT:         See COPYING in the top level directory
 * PROJECT:           ReactOS system libraries
 * PURPOSE:           Implementation of fabs
 * FILE:              lib/sdk/crt/math/amd64/fabs.S
 * PROGRAMMER:        Timo Kreuzer (timo.kreuzer@reactos.org)
 */

/* INCLUDES ******************************************************************/

#include <reactos/asm.h>
#include <ndk/amd64/asm.h>

/* FUNCTIONS ****************************************************************/

.code64

PUBLIC fabs
fabs:
    UNIMPLEMENTED fabs
    ret

