/*
 * COPYRIGHT:         See COPYING in the top level directory
 * PROJECT:           ReactOS system libraries
 * PURPOSE:           Implementation of fmodf
 * FILE:              lib/sdk/crt/math/amd64/fmodf.S
 * PROGRAMMER:        Timo Kreuzer (timo.kreuzer@reactos.org)
 */

/* INCLUDES ******************************************************************/

#include <asm.inc>

/* DATA *********************************************************************/

PUBLIC fmodf
fmodf:
    UNIMPLEMENTED fmodf
    ret

END
