/*
 * COPYRIGHT:         See COPYING in the top level directory
 * PROJECT:           ReactOS system libraries
 * PURPOSE:           Implementation of fmod
 * FILE:              lib/sdk/crt/math/amd64/fmod.S
 * PROGRAMMER:        Timo Kreuzer (timo.kreuzer@reactos.org)
 */

/* INCLUDES ******************************************************************/

#include <reactos/asm.h>
#include <ndk/amd64/asm.h>

/* DATA *********************************************************************/

PUBLIC fmod
fmod:
    UNIMPLEMENTED fmod
    ret
