/*
 * COPYRIGHT:         See COPYING in the top level directory
 * PROJECT:           ReactOS system libraries
 * PURPOSE:           Implementation of pow
 * FILE:              lib/sdk/crt/math/amd64/pow.S
 * PROGRAMMER:        Timo Kreuzer (timo.kreuzer@reactos.org)
 */

/* INCLUDES ******************************************************************/

#include <reactos/asm.h>
#include <ndk/amd64/asm.h>

/* DATA *********************************************************************/

PUBLIC pow
pow:
    UNIMPLEMENTED pow
    ret

