#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H

/* metrics */
#define PROPSHEETWIDTH  246
#define PROPSHEETHEIGHT 228
#define PROPSHEETPADDING        6
#define SYSTEM_COLUMN   (18 * PROPSHEETPADDING)
#define LABELLINE(x)    (((PROPSHEETPADDING + 2) * x) + (x + 2))
#define ICONSIZE        16

/* ids */
#define IDI_CPLACCESS		100

#define IDD_PROPPAGEKEYBOARD	100
#define IDD_PROPPAGESOUND	101
#define IDD_PROPPAGEDISPLAY	102
#define IDD_PROPPAGEMOUSE	103
#define IDD_PROPPAGEGENERAL	104

#define IDS_CPLSYSTEMNAME	1001
#define IDS_CPLSYSTEMDESCRIPTION	2001

/* controls */
#define IDC_STICKY_BOX		200
#define IDC_STICKY_BUTTON	201
#define IDC_FILTER_BOX		202
#define IDC_FILTER_BUTTON	203
#define IDC_TOGGLE_BOX		204
#define IDC_TOGGLE_BUTTON	205
#define IDC_SENTRY_BOX		206
#define IDC_SENTRY_BUTTON	207
#define IDC_SSHOW_BOX		208
#define IDC_CONTRAST_BOX	209
#define IDC_CONTRAST_BUTTON	210
#define IDC_MOUSE_BOX		211
#define IDC_MOUSE_BUTTON	212
#define IDC_RESET_BOX		213
#define IDC_RESET_POPUP		214
#define IDC_NOTIFICATION_MESSAGE	215
#define IDC_NOTIFICATION_SOUND	216
#define IDC_SERIAL_BOX		217
#define IDC_SERIAL_BUTTON	218
#define IDC_ADMIN_LOGON_BOX	219
#define IDC_ADMIN_USERS_BOX	220



#endif /* __CPL_RESOURCE_H */

/* EOF */
