
set(MODULE_HEADER ${CMAKE_CURRENT_LIST_DIR}/pc98.h) # For precomp.h
list(APPEND SOURCE
    ${MODULE_HEADER}
    ${CMAKE_CURRENT_LIST_DIR}/bootvid.c)

set(REACTOS_STR_FILE_DESCRIPTION "NEC PC-98 Boot Video Driver")
