obj\$(TARGET_DIRECTORY)\app.res: \
        $(BASEDIR)\public\sdk\inc\windows.h \
        $(BASEDIR)\public\sdk\inc\common.ver \
        $(BASEDIR)\public\sdk\inc\ntverp.h \
        resource.h \
        obj\messages.h \
        obj\messages.rc
