#
#  ReactOS tlist
#
#  Makefile
#

PATH_TO_TOP = ../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = tlist

TARGET_SDKLIBS = epsapi.a kernel32.a user32.a ntdll.a

TARGET_OBJECTS = $(TARGET_NAME).o

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

include $(TOOLS_PATH)/depend.mk

# EOF
