PATH_TO_TOP = ../../../..

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = traceroute

TARGET_INSTALLDIR = system32

TARGET_SDKLIBS = ws2_32.a iphlpapi.a ntdll.a

TARGET_OBJECTS = \
$(TARGET_NAME).o

TARGET_GCCLIBS = 

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
