1 stdcall FaxAbort(ptr long)
2 stdcall FaxAccessCheck(ptr long)
3 stdcall FaxClose(ptr)
4 stdcall FaxCompleteJobParamsA(ptr ptr)
5 stdcall FaxCompleteJobParamsW(ptr ptr)
6 stdcall FaxConnectFaxServerA(str ptr)
7 stdcall FaxConnectFaxServerW(wstr ptr)
8 stdcall FaxEnableRoutingMethodA(ptr str long)
9 stdcall FaxEnableRoutingMethodW(ptr wstr long)
10 stdcall FaxEnumGlobalRoutingInfoA(ptr ptr ptr)
11 stdcall FaxEnumGlobalRoutingInfoW(ptr ptr ptr)
12 stdcall FaxEnumJobsA(ptr ptr ptr)
13 stdcall FaxEnumJobsW(ptr ptr ptr)
14 stdcall FaxEnumPortsA(ptr ptr ptr)
15 stdcall FaxEnumPortsW(ptr ptr ptr)
16 stdcall FaxEnumRoutingMethodsA(ptr ptr ptr)
17 stdcall FaxEnumRoutingMethodsW(ptr ptr ptr)
18 stdcall FaxFreeBuffer(ptr)
19 stdcall FaxGetConfigurationA(ptr ptr)
20 stdcall FaxGetConfigurationW(ptr ptr)
21 stdcall FaxGetDeviceStatusA(ptr ptr)
22 stdcall FaxGetDeviceStatusW(ptr ptr)
23 stdcall FaxGetJobA(ptr long ptr)
24 stdcall FaxGetJobW(ptr long ptr)
25 stdcall FaxGetLoggingCategoriesA(ptr ptr ptr)
26 stdcall FaxGetLoggingCategoriesW(ptr ptr ptr)
27 stdcall FaxGetPageData(ptr long ptr ptr ptr ptr)
28 stdcall FaxGetPortA(ptr ptr)
29 stdcall FaxGetPortW(ptr ptr)
30 stdcall FaxGetRoutingInfoA(ptr str ptr ptr)
31 stdcall FaxGetRoutingInfoW(ptr wstr ptr ptr)
32 stdcall FaxInitializeEventQueue(ptr ptr ptr ptr long)
33 stdcall FaxOpenPort(ptr long long ptr)
34 stdcall FaxPrintCoverPageA(ptr ptr)
35 stdcall FaxPrintCoverPageW(ptr ptr)
36 stdcall FaxRegisterRoutingExtensionW(ptr wstr wstr wstr ptr ptr)
37 stdcall FaxRegisterServiceProviderW(wstr wstr wstr wstr)
38 stdcall FaxSendDocumentA(ptr str ptr ptr ptr)
39 stdcall FaxSendDocumentForBroadcastA(ptr str ptr ptr ptr)
40 stdcall FaxSendDocumentForBroadcastW(ptr wstr ptr ptr ptr)
41 stdcall FaxSendDocumentW(ptr wstr ptr ptr ptr)
42 stdcall FaxSetConfigurationA(ptr ptr)
43 stdcall FaxSetConfigurationW(ptr ptr)
44 stdcall FaxSetGlobalRoutingInfoA(ptr ptr)
45 stdcall FaxSetGlobalRoutingInfoW(ptr ptr)
46 stdcall FaxSetJobA(ptr long long ptr)
47 stdcall FaxSetJobW(ptr long long ptr)
48 stdcall FaxSetLoggingCategoriesA(ptr ptr long)
49 stdcall FaxSetLoggingCategoriesW(ptr ptr long)
50 stdcall FaxSetPortA(ptr ptr)
51 stdcall FaxSetPortW(ptr ptr)
52 stdcall FaxSetRoutingInfoA(ptr str ptr long)
53 stdcall FaxSetRoutingInfoW(ptr wstr ptr long)
54 stdcall FaxStartPrintJobA(str ptr ptr ptr)
55 stdcall FaxStartPrintJobW(wstr ptr ptr ptr)
