#define IDS_STRING_LICENSE              1
#define IDS_MATH_ERROR                  2
#define IDS_QUICKHELP                   3
#define IDD_DIALOG_SCIENTIFIC           101
#define IDD_DIALOG_STANDARD             102
#define IDD_DIALOG_ABOUT                103
#define IDD_DIALOG_STAT                 104
#define IDD_DIALOG_CONVERSION           105
#define IDR_MENU_SCIENTIFIC_1           106
#define IDR_MENU_SCIENTIFIC_2           107
#define IDR_MENU_STANDARD               108
#define IDB_BITMAP_ROS                  109
#define IDI_CALC_BIG                    110
#define IDI_CALC_SMALL                  111
#define IDC_RADIO_HEX                   1002
#define IDC_RADIO_DEC                   1003
#define IDC_RADIO_OCT                   1004
#define IDC_RADIO_BIN                   1005
#define IDC_CHECK_INV                   1006
#define IDC_CHECK_HYP                   1007
#define IDC_BUTTON_STA                  1009
#define IDC_BUTTON_AVE                  1010
#define IDC_BUTTON_SUM                  1011
#define IDC_BUTTON_S                    1012
#define IDC_BUTTON_DAT                  1013
#define IDC_BUTTON_FE                   1014
#define IDC_BUTTON_DMS                  1015
#define IDC_BUTTON_SIN                  1016
#define IDC_BUTTON_COS                  1017
#define IDC_BUTTON_TAN                  1018
#define IDC_BUTTON_LEFTPAR              1019
#define IDC_BUTTON_EXP                  1020
#define IDC_BUTTON_XeY                  1021
#define IDC_BUTTON_Xe2                  1022
#define IDC_BUTTON_Xe3                  1023
#define IDC_BUTTON_RIGHTPAR             1024
#define IDC_BUTTON_LN                   1025
#define IDC_BUTTON_LOG                  1026
#define IDC_BUTTON_NF                   1027
#define IDC_BUTTON_RX                   1028
#define IDC_BUTTON_MC                   1029
#define IDC_BUTTON_MR                   1030
#define IDC_BUTTON_MS                   1031
#define IDC_BUTTON_MP                   1032
#define IDC_BUTTON_PI                   1033
#define IDC_BUTTON_7                    1034
#define IDC_BUTTON_4                    1035
#define IDC_BUTTON_1                    1036
#define IDC_BUTTON_0                    1037
#define IDC_BUTTON_A                    1038
#define IDC_BUTTON_8                    1039
#define IDC_BUTTON_5                    1040
#define IDC_BUTTON_2                    1041
#define IDC_BUTTON_SIGN                 1042
#define IDC_BUTTON_B                    1043
#define IDC_BUTTON_9                    1044
#define IDC_BUTTON_6                    1045
#define IDC_BUTTON_3                    1046
#define IDC_BUTTON_DOT                  1047
#define IDC_BUTTON_C                    1048
#define IDC_BUTTON_DIV                  1049
#define IDC_BUTTON_MULT                 1050
#define IDC_BUTTON_SUB                  1051
#define IDC_BUTTON_ADD                  1052
#define IDC_BUTTON_D                    1053
#define IDC_BUTTON_MOD                  1054
#define IDC_BUTTON_OR                   1055
#define IDC_BUTTON_LSH                  1056
#define IDC_BUTTON_EQU                  1057
#define IDC_BUTTON_E                    1058
#define IDC_BUTTON_AND                  1059
#define IDC_BUTTON_XOR                  1060
#define IDC_BUTTON_NOT                  1061
#define IDC_BUTTON_INT                  1062
#define IDC_BUTTON_F                    1063
#define IDC_RADIO_QWORD                 1064
#define IDC_RADIO_DWORD                 1065
#define IDC_RADIO_WORD                  1066
#define IDC_RADIO_BYTE                  1067
#define IDC_RADIO_DEG                   1068
#define IDC_RADIO_RAD                   1069
#define IDC_RADIO_GRAD                  1070
#define IDC_BUTTON_CANC                 1071
#define IDC_BUTTON_CE                   1072
#define IDC_BUTTON_BACK                 1073
#define IDC_TEXT_OUTPUT                 1074
#define IDC_TEXT_PARENT                 1075
#define IDC_TEXT_MEMORY                 1076
#define IDC_EDIT_LICENSE                1078
#define IDC_LIST_STAT                   1079
#define IDC_BUTTON_RET                  1080
#define IDC_BUTTON_LOAD                 1081
#define IDC_BUTTON_CD                   1082
#define IDC_BUTTON_CAD                  1083
#define IDC_TEXT_NITEMS                 1084
#define IDC_BUTTON_SQRT                 1085
#define IDC_BUTTON_PERCENT              1086
#define IDC_BUTTON_CONVERT              1087
#define IDC_TEXT_VERSION                1088
#define IDC_BUTTON_FOCUS                1089
#define IDC_COMBO_CATEGORY              1090
#define IDC_COMBO_FROM                  1091
#define IDC_COMBO_TO                    1092
#define IDC_BUTTON_RSH                  1093

/* TYPES OF CONVERSIONS */
#define IDS_CONV_ANGLE                  2000
#define IDS_CONV_AREA                   2001
#define IDS_CONV_CONSUMPTION            2002
#define IDS_CONV_CURRENCY               2003
#define IDS_CONV_ENERGY                 2004
#define IDS_CONV_LENGTH                 2005
#define IDS_CONV_POWER                  2006
#define IDS_CONV_PRESSURE               2007
#define IDS_CONV_TEMPERATURE            2008
#define IDS_CONV_TIME                   2009
#define IDS_CONV_VELOCITY               2010
#define IDS_CONV_VOLUME                 2011
#define IDS_CONV_WEIGHT                 2012

/* TYPES OF ANGLES */
#define IDS_ANGLE_DEGREES               2100
#define IDS_ANGLE_GRADIANS              2101
#define IDS_ANGLE_RADIANS               2102

/* TYPES OF AREAS */
#define IDS_AREA_ACRES                  2200
#define IDS_AREA_ACRES_BRAZIL           2201
#define IDS_AREA_ACRES_FRANCE           2202
#define IDS_AREA_ACRES_SCOTS            2203
#define IDS_AREA_ACRES_US               2204
#define IDS_AREA_ARES                   2205
#define IDS_AREA_CHOU                   2206
#define IDS_AREA_DANBO                  2207
#define IDS_AREA_HECTARES               2208
#define IDS_AREA_JEONGBO                2209
#define IDS_AREA_MORGEN_HUNGARY         2210
#define IDS_AREA_MU                     2211
#define IDS_AREA_PING                   2212
#define IDS_AREA_PYEONG                 2213
#define IDS_AREA_PYEONGBANGJA           2214
#define IDS_AREA_RAI                    2215
#define IDS_AREA_SE                     2216
#define IDS_AREA_SQUARE_CENTIMETERS     2217
#define IDS_AREA_SQUARE_CHR             2218
#define IDS_AREA_SQUARE_FATHOMS         2219
#define IDS_AREA_SQUARE_FATHOMS_HUNGARY 2220
#define IDS_AREA_SQUARE_FEET            2221
#define IDS_AREA_SQUARE_INCHES          2222
#define IDS_AREA_SQUARE_KILOMETERS      2223
#define IDS_AREA_SQUARE_LAR             2224
#define IDS_AREA_SQUARE_METER           2225
#define IDS_AREA_SQUARE_MILES           2226
#define IDS_AREA_SQUARE_MILLIMETERS     2227
#define IDS_AREA_SQUARE_SHAKU           2228
#define IDS_AREA_SQUARE_TSUEN           2229
#define IDS_AREA_SQUARE_VA              2230
#define IDS_AREA_SQUARE_YARD            2231
#define IDS_AREA_TAN                    2232
#define IDS_AREA_TSUBO                  2233

/* TYPES OF COMSUMPTIONS */
#define IDS_CONSUMPTION_KM_PER_L        2300
#define IDS_CONSUMPTION_L_PER_100_KM    2301
#define IDS_CONSUMPTION_MILES_GALLON_UK 2302
#define IDS_CONSUMPTION_MILES_GALLON_US 2303

/* TYPES OF CURRENCIES */
#define IDS_CURRENCY_AUSTRIAN_SCHILLING 2400
#define IDS_CURRENCY_BELGIAN_FRANC      2401
#define IDS_CURRENCY_CYPRIOT_POUND      2402
#define IDS_CURRENCY_CZECH_KORUNA       2403
#define IDS_CURRENCY_DEUTSCHE_MARK      2404
#define IDS_CURRENCY_DUTCH_GUILDER      2405
#define IDS_CURRENCY_EURO               2406
#define IDS_CURRENCY_FINNISH_MARKKA     2407
#define IDS_CURRENCY_FRENCH_FRANC       2408
#define IDS_CURRENCY_GREEK_DRACHMA      2409
#define IDS_CURRENCY_IRISH_POUND        2410
#define IDS_CURRENCY_ITALIAN_LIRA       2411
#define IDS_CURRENCY_LUXEMBOURG_FRANC   2412
#define IDS_CURRENCY_MALTESE_LIRA       2413
#define IDS_CURRENCY_PORTOGUESE_ESCUDO  2414
#define IDS_CURRENCY_SLOVAK_KORUNA      2415
#define IDS_CURRENCY_SLOVENIAN_TOLAR    2416
#define IDS_CURRENCY_SPANISH_PESETA     2417

/* TYPES OF ENERGIES */
#define IDS_ENERGY_15_C_CALORIES        2500
#define IDS_ENERGY_BTUS                 2501
#define IDS_ENERGY_ERGS                 2502
#define IDS_ENERGY_EVS                  2503
#define IDS_ENERGY_FOOT_POUNDS          2504
#define IDS_ENERGY_IT_CALORIES          2505
#define IDS_ENERGY_IT_KILOCALORIES      2506
#define IDS_ENERGY_JOULES               2507
#define IDS_ENERGY_KILOJOULES           2508
#define IDS_ENERGY_KILOWATT_HOURS       2509
#define IDS_ENERGY_NUTRITION_CALORIES   2510
#define IDS_ENERGY_TH_CALORIES          2511

/* TYPES OF LENGTHS */
#define IDS_LENGTH_ANGSTROMS            2600
#define IDS_LENGTH_ASTRONOMICAL_UNITS   2601
#define IDS_LENGTH_BARLEYCORNS          2602
#define IDS_LENGTH_CENTIMETERS          2603
#define IDS_LENGTH_CHAINS_UK            2604
#define IDS_LENGTH_CHI                  2605
#define IDS_LENGTH_CHOU                 2606
#define IDS_LENGTH_CHR                  2607
#define IDS_LENGTH_CUN                  2608
#define IDS_LENGTH_FATHOMS              2609
#define IDS_LENGTH_FATHOMS_HUNGARY      2610
#define IDS_LENGTH_FEET                 2611
#define IDS_LENGTH_FURLONGS             2612
#define IDS_LENGTH_GAN                  2613
#define IDS_LENGTH_HANDS                2614
#define IDS_LENGTH_HUNH                 2615
#define IDS_LENGTH_INCHES               2616
#define IDS_LENGTH_JA                   2617
#define IDS_LENGTH_JEONG                2618
#define IDS_LENGTH_KABIET               2619
#define IDS_LENGTH_KEN                  2620
#define IDS_LENGTH_KEUB                 2621
#define IDS_LENGTH_KILOMETERS           2622
#define IDS_LENGTH_LAR                  2623
#define IDS_LENGTH_LIGHT_YEARS          2624
#define IDS_LENGTH_LINKS_UK             2625
#define IDS_LENGTH_METERS               2626
#define IDS_LENGTH_MICRONS              2627
#define IDS_LENGTH_MILES                2628
#define IDS_LENGTH_MILLIMETERS          2629
#define IDS_LENGTH_NAUTICAL_MILES       2630
#define IDS_LENGTH_NIEU                 2631
#define IDS_LENGTH_PARSECS              2632
#define IDS_LENGTH_PICAS                2633
#define IDS_LENGTH_RODS                 2634
#define IDS_LENGTH_RI_JAPAN             2635
#define IDS_LENGTH_RI_KOREA             2636
#define IDS_LENGTH_SAWK                 2637
#define IDS_LENGTH_SEN                  2638
#define IDS_LENGTH_SHAKU                2639
#define IDS_LENGTH_SPAN                 2640
#define IDS_LENGTH_SUN                  2641
#define IDS_LENGTH_TSUEN                2642
#define IDS_LENGTH_VA                   2643
#define IDS_LENGTH_YARDS                2644
#define IDS_LENGTH_YOTE                 2645
#define IDS_LENGTH_ZHANG                2646

/* TYPES OF POWERS */
#define IDS_POWER_BTUS_PER_MINUTE       2700
#define IDS_POWER_FPS_PER_MINUTE        2701
#define IDS_POWER_HORSEPOWER            2702
#define IDS_POWER_KILOWATTS             2703
#define IDS_POWER_MEGAWATTS             2704
#define IDS_POWER_WATTS                 2705

/* TYPE OF PRESSURES */
#define IDS_PRESSURE_ATMOSPHERES        2800
#define IDS_PRESSURE_BARS               2801
#define IDS_PRESSURE_HECTOPASCALS       2802
#define IDS_PRESSURE_KILOPASCALS        2803
#define IDS_PRESSURE_MM_OF_MERCURY      2804
#define IDS_PRESSURE_PASCALS            2805
#define IDS_PRESSURE_PSI                2806

/* TYPES OF TEMPERATURES */
#define IDS_TEMPERATURE_CELSIUS         2900
#define IDS_TEMPERATURE_FAHRENHEIT      2901
#define IDS_TEMPERATURE_KELVIN          2902
#define IDS_TEMPERATURE_RANKINE         2903

/* TYPE OF TIME */
#define IDS_TIME_DAYS                   3001
#define IDS_TIME_HOURS                  3002
#define IDS_TIME_MICROSECONDS           3003
#define IDS_TIME_MILISECONDS            3004
#define IDS_TIME_MINUTES                3005
#define IDS_TIME_SECONDS                3006
#define IDS_TIME_WEEKS                  3007
#define IDS_TIME_YEARS                  3008

/* TYPES OF VELOCITIES */
#define IDS_VELOCITY_CMS_SECOND         3100
#define IDS_VELOCITY_FEET_SECOND        3101
#define IDS_VELOCITY_FEET_HOUR          3102
#define IDS_VELOCITY_KILOMETERS_HOUR    3103
#define IDS_VELOCITY_KNOTS              3104
#define IDS_VELOCITY_MACH               3105
#define IDS_VELOCITY_METERS_SECOND      3106
#define IDS_VELOCITY_MILES_HOUR         3107

/* TYPES OF VOLUMES */
#define IDS_VOLUME_BARRELS_UK           3200
#define IDS_VOLUME_BARRELS_OIL          3201
#define IDS_VOLUME_BUN                  3202
#define IDS_VOLUME_BUSHELS_UK           3203
#define IDS_VOLUME_BUSHELS_US           3204
#define IDS_VOLUME_CUBIC_CENTIMETERS    3205
#define IDS_VOLUME_CUBIC_FEET           3206
#define IDS_VOLUME_CUBIC_INCHES         3207
#define IDS_VOLUME_CUBIC_METERS         3208
#define IDS_VOLUME_CUBIC_YARDS          3209
#define IDS_VOLUME_DOE                  3210
#define IDS_VOLUME_FLUID_OUNCES_UK      3211
#define IDS_VOLUME_FLUID_OUNCES_US      3212
#define IDS_VOLUME_GALLONS_UK           3213
#define IDS_VOLUME_GALLONS_DRY_US       3214
#define IDS_VOLUME_GALLONS_LIQUID_US    3215
#define IDS_VOLUME_GOU                  3216
#define IDS_VOLUME_HOP                  3217
#define IDS_VOLUME_ICCE                 3218
#define IDS_VOLUME_KWIAN                3219
#define IDS_VOLUME_LITERS               3220
#define IDS_VOLUME_MAL                  3221
#define IDS_VOLUME_MILLILITERS          3222
#define IDS_VOLUME_PINTS_UK             3223
#define IDS_VOLUME_PINTS_DRY_US         3224
#define IDS_VOLUME_PINTS_LIQUID_US      3225
#define IDS_VOLUME_QUARTS_UK            3226
#define IDS_VOLUME_QUARTS_DRY_US        3227
#define IDS_VOLUME_QUARTS_LIQUID_US     3228
#define IDS_VOLUME_SEKI                 3229
#define IDS_VOLUME_SYOU                 3230
#define IDS_VOLUME_TANANLOUNG           3231
#define IDS_VOLUME_TANG                 3232
#define IDS_VOLUME_TO                   3233

/* TYPES OF WEIGHTS */
#define IDS_WEIGHT_BAHT                 3300
#define IDS_WEIGHT_CARATS               3301
#define IDS_WEIGHT_CHUNG                3302
#define IDS_WEIGHT_DON                  3303
#define IDS_WEIGHT_GEUN                 3304
#define IDS_WEIGHT_GRAMS                3305
#define IDS_WEIGHT_GWAN                 3306
#define IDS_WEIGHT_HARB                 3307
#define IDS_WEIGHT_JIN_CHINA            3308
#define IDS_WEIGHT_JIN_TAIWAN           3309
#define IDS_WEIGHT_KAN                  3310
#define IDS_WEIGHT_KILOGRAMS            3311
#define IDS_WEIGHT_KIN                  3312
#define IDS_WEIGHT_LIANG_CHINA          3313
#define IDS_WEIGHT_LIANG_TAIWAN         3314
#define IDS_WEIGHT_MONME                3315
#define IDS_WEIGHT_OUNCES_AVOIRDUPOIS   3316
#define IDS_WEIGHT_OUNCES_TROY          3317
#define IDS_WEIGHT_POUNDS               3318
#define IDS_WEIGHT_QUINTAL_METRIC       3319
#define IDS_WEIGHT_SALOUNG              3320
#define IDS_WEIGHT_STONES               3321
#define IDS_WEIGHT_TAMLUNG              3322
#define IDS_WEIGHT_TONNES               3323
#define IDS_WEIGHT_TONS_UK              3324
#define IDS_WEIGHT_TONS_US              3325

/* MENU */
#define IDM_EDIT_COPY                   40002
#define IDM_EDIT_PASTE                  40003
#define IDM_VIEW_STANDARD               40004
#define IDM_VIEW_SCIENTIFIC             40005
#define IDM_VIEW_HEX                    40006
#define IDM_VIEW_DEC                    40007
#define IDM_VIEW_OCT                    40008
#define IDM_VIEW_BIN                    40009
#define IDM_VIEW_DEG                    40010
#define IDM_VIEW_RAD                    40011
#define IDM_VIEW_GRAD                   40012
#define IDM_VIEW_GROUP                  40013
#define IDM_HELP_HELP                   40014
#define IDM_HELP_ABOUT                  40015
#define IDM_VIEW_QWORD                  40016
#define IDM_VIEW_WORD                   40017
#define IDM_VIEW_BYTE                   40018
#define IDM_VIEW_DWORD                  40019
#define IDM_VIEW_CONVERSION             40020

