
PATH_TO_TOP=../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = touch

TARGET_SDKLIBS = ntdll.a

TARGET_OBJECTS = $(TARGET_NAME).o \
err.o 

TARGET_GCCLIBS = iberty

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
