###############################################################################
#
#  Microsoft Confidential
#  Copyright (C) Microsoft Corporation 1995
#  All Rights Reserved.
#
#  Internet SDK Include makefile
#
###############################################################################

!if "$(NTMAKEENV)" != "" 
#
# This section is for the NT build ONLY.
# For NT build, change the 'sources' or 'dirs' file, not this makefile
#
!INCLUDE $(NTMAKEENV)\makefile.def

!else

#do nothing

!endif
