<?php
@define('PLUGIN_EVENT_STATISTICS_NAME', 'Statistiky');
@define('PLUGIN_EVENT_STATISTICS_DESC', 'Zobrazení statistik záznamů');
@define('PLUGIN_EVENT_STATISTICS_OUT_STATISTICS', 'Statistiky');
@define('PLUGIN_EVENT_STATISTICS_OUT_FIRST_ENTRY', 'První záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_LAST_ENTRY', 'Poslední záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOTAL_ENTRIES', 'Celkem záznamů');
@define('PLUGIN_EVENT_STATISTICS_OUT_ENTRIES', 'záznamů');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOTAL_PUBLIC', ' ... publikovaných');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOTAL_DRAFTS', ' ... konceptů');
@define('PLUGIN_EVENT_STATISTICS_OUT_CATEGORIES', 'Kategorie');
@define('PLUGIN_EVENT_STATISTICS_OUT_CATEGORIES2', 'kategorií');
@define('PLUGIN_EVENT_STATISTICS_OUT_DISTRIBUTION_CATEGORIES', 'Rozdělení záznamů');
@define('PLUGIN_EVENT_STATISTICS_OUT_DISTRIBUTION_CATEGORIES2', 'záznamů');
@define('PLUGIN_EVENT_STATISTICS_OUT_UPLOADED_IMAGES', 'Nahraných obrázků');
@define('PLUGIN_EVENT_STATISTICS_OUT_UPLOADED_IMAGES2', 'obrázků');
@define('PLUGIN_EVENT_STATISTICS_OUT_DISTRIBUTION_IMAGES', 'Rozdělení obrázků podle typů');
@define('PLUGIN_EVENT_STATISTICS_OUT_DISTRIBUTION_IMAGES2', 'souborů');
@define('PLUGIN_EVENT_STATISTICS_OUT_COMMENTS', 'Přijaté komentáře');
@define('PLUGIN_EVENT_STATISTICS_OUT_COMMENTS2', 'komentářů');
@define('PLUGIN_EVENT_STATISTICS_OUT_COMMENTS3', 'Nejčastěji komentované záznamy');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPCOMMENTS', 'Nejčastěji komentující čtenáři');
@define('PLUGIN_EVENT_STATISTICS_OUT_LINK', 'linka');
@define('PLUGIN_EVENT_STATISTICS_OUT_SUBSCRIBERS', 'Odběratelé');
@define('PLUGIN_EVENT_STATISTICS_OUT_SUBSCRIBERS2', 'odběratelů');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPSUBSCRIBERS', 'Nejčastěji odebírané záznamy');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPSUBSCRIBERS2', 'odběratelů');
@define('PLUGIN_EVENT_STATISTICS_OUT_TRACKBACKS', 'Přijaté odezvy');
@define('PLUGIN_EVENT_STATISTICS_OUT_TRACKBACKS2', 'odezev');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPTRACKBACK', 'Nejčastěji sledované záznamy');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPTRACKBACK2', 'odezev)');
@define('PLUGIN_EVENT_STATISTICS_OUT_TOPTRACKBACKS3', 'Nejčastějí odezvy čtenářů');
@define('PLUGIN_EVENT_STATISTICS_OUT_COMMENTS_PER_ARTICLE', 'počet komentářů na záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_TRACKBACKS_PER_ARTICLE', 'počet odezev na záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_DAY', 'počet záznamů za den');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_WEEK', 'počet záznamů za týden');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_MONTH', 'počet záznamů za měsíc');
@define('PLUGIN_EVENT_STATISTICS_OUT_COMMENTS_PER_ARTICLE2', 'komentářů/záznamy');
@define('PLUGIN_EVENT_STATISTICS_OUT_TRACKBACKS_PER_ARTICLE2', 'odezev/záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_DAY2', 'záznamů/den');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_WEEK2', 'záznamů/týden');
@define('PLUGIN_EVENT_STATISTICS_OUT_ARTICLES_PER_MONTH2', 'záznamů/měsíc');
@define('PLUGIN_EVENT_STATISTICS_OUT_CHARS', 'Celkový počet znaků');
@define('PLUGIN_EVENT_STATISTICS_OUT_CHARS2', 'znaků');
@define('PLUGIN_EVENT_STATISTICS_OUT_CHARS_PER_ARTICLE', 'Znaků na záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_CHARS_PER_ARTICLE2', 'znaků/záznam');
@define('PLUGIN_EVENT_STATISTICS_OUT_LONGEST_ARTICLES', '%s nejdelích záznamů');
@define('PLUGIN_EVENT_STATISTICS_MAX_ITEMS', 'Počet prvků');
@define('PLUGIN_EVENT_STATISTICS_MAX_ITEMS_DESC', 'Kolik prvků vzít pro statistické vyhodnocení? (Default: 20)');
?>
