@ stdcall EmptyWorkingSet(ptr)
@ stdcall EnumDeviceDrivers(ptr long ptr)
@ stdcall EnumPageFilesA(ptr ptr)
@ stdcall EnumPageFilesW(ptr ptr)
@ stdcall EnumProcessModules(ptr ptr long ptr)
@ stdcall EnumProcesses(ptr long ptr)
@ stdcall GetDeviceDriverBaseNameA(ptr ptr long)
@ stdcall GetDeviceDriverBaseNameW(ptr ptr long)
@ stdcall GetDeviceDriverFileNameA(ptr ptr long)
@ stdcall GetDeviceDriverFileNameW(ptr ptr long)
@ stdcall GetMappedFileNameA(ptr ptr ptr long)
@ stdcall GetMappedFileNameW(ptr ptr ptr long)
@ stdcall GetModuleBaseNameA(ptr ptr ptr long)
@ stdcall GetModuleBaseNameW(ptr ptr ptr long)
@ stdcall GetModuleFileNameExA(ptr ptr ptr long)
@ stdcall GetModuleFileNameExW(ptr ptr ptr long)
@ stdcall GetModuleInformation(ptr ptr ptr long)
@ stdcall GetPerformanceInfo(ptr long)
@ stdcall GetProcessImageFileNameA(ptr ptr long)
@ stdcall GetProcessImageFileNameW(ptr ptr long)
@ stdcall GetProcessMemoryInfo(ptr ptr long)
@ stdcall GetWsChanges(ptr ptr long)
@ stdcall InitializeProcessForWsWatch(ptr)
@ stdcall QueryWorkingSet(ptr ptr long)
@ stdcall QueryWorkingSetEx(ptr ptr long)
