//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dskquoui.rc
//
#define IDM_LISTVIEW_MENU               105
#define IDD_PROPPAGE_USERQUOTA          106
#define IDD_PROPPAGE_VOLQUOTA           107
#define IDM_CONTEXT_MENU                114
#define IDI_QUOTA                       117
#define IDI_SINGLE_USER                 130
#define IDI_MULTI_USER                  131
#define IDI_OKBUBBLE                    132
#define IDI_WARNERR                     134
#define IDR_KBDACCEL                    140
#define IDD_FINDUSER                    146
#define IDD_PROGRESS                    147
#define IDD_YNTOALL                     149
#define IDI_QUOTA_OPEN                  150
#define IDD_PROPPAGE_POLICY             151
#define IDD_OWNERSANDFILES              152
#define IDD_ADDUSER                     154
#define IDC_TOOLBAR                     500
#define IDC_TOOLBAR_COMBO               502
#define IDC_TXT_QUOTA_STATUS            1001
#define IDC_CBX_ENABLE_QUOTA            1002
#define IDC_CBX_DENY_LIMIT              1005
#define IDC_RBN_DEF_NOLIMIT             1006
#define IDC_RBN_DEF_LIMIT               1007
#define IDC_EDIT_DEF_LIMIT              1008
#define IDC_EDIT_DEF_THRESHOLD          1009
#define IDC_BTN_DETAILS                 1012
#define IDC_BTN_EVENTLOG                1013
#define IDC_TXT_WARN_LEVEL              1017
#define IDC_GRP_ACTIONS                 1019
#define IDC_TXT_USERNAME                1020
#define IDC_GRP_DEFAULTS                1021
#define IDC_TXT_SPACEUSED               1023
#define IDC_TXT_SPACEREMAINING          1025
#define IDC_EDIT_USER_LIMIT             1026
#define IDC_EDIT_USER_THRESHOLD         1027
#define IDC_RBN_USER_LIMIT              1028
#define IDC_RBN_USER_NOLIMIT            1029
#define IDC_CMB_DEF_LIMIT               1037
#define IDC_CMB_DEF_THRESHOLD           1038
#define IDC_CMB_USER_LIMIT              1040
#define IDC_CMB_USER_THRESHOLD          1041
#define IDC_ICON_USER                   1043
#define IDC_ICON_USERSTATUS             1044
#define IDC_TRAFFIC_LIGHT               1045
#define IDR_AVI_TRAFFIC                 1046
#define IDC_CMB_FINDUSER                1047
#define IDC_TXT_FINDUSER                1048
#define IDC_PROGRESS_BAR                1049
#define IDC_CBX_YNTOALL                 1051
#define IDC_TXT_YNTOALL                 1052
#define IDC_TXT_PROGRESS_DESCRIPTION    1054
#define IDC_TXT_PROGRESS_FILENAME       1055
#define IDC_TXT_QUOTA_STATUS_LABEL      1064
#define IDC_LV_OWNERDLG                 1071
#define IDC_CMB_OWNERDLG_OWNERS         1073
#define IDC_RBN_POLICY_FIXED            1076
#define IDC_RBN_POLICY_REMOVABLE        1077
#define IDC_BTN_OWNERDLG_DELETE         1079
#define IDC_BTN_OWNERDLG_TAKE           1080
#define IDC_BTN_OWNERDLG_MOVETO         1081
#define IDC_BTN_OWNERDLG_BROWSE         1082
#define IDC_EDIT_OWNERDLG_MOVETO        1083
#define IDC_TXT_OWNERDLG_HEADER         1084
#define IDC_CBX_LOG_OVERLIMIT           1088
#define IDC_CBX_LOG_OVERWARNING         1089
#define IDC_TXT_DEFAULTS                1090
#define IDC_TXT_LOGGING                 1091
#define IDC_LBL_SPACEUSED               1092
#define IDC_LBL_SPACEREMAINING          1093
#define IDC_STATIC2                     1094
#define IDM_QUOTA_NEW                   40001
#define IDM_QUOTA_EDIT                  40002
#define IDM_VIEW_TOOLBAR                40003
#define IDM_VIEW_STATUSBAR              40004
#define IDM_VIEW_ARRANGE_BYNAME         40010
#define IDM_VIEW_ARRANGE_BYUSED         40011
#define IDM_VIEW_ARRANGE_BYLIMIT        40012
#define IDM_VIEW_ARRANGE_BYTHRESHOLD    40013
#define IDM_VIEW_ARRANGE_BYPERCENT      40014
#define IDM_VIEW_REFRESH                40015
#define IDM_QUOTA_PROPERTIES            40016
#define IDM_QUOTA_CLOSE                 40017
#define IDM_HELP_TOPICS                 40018
#define IDM_HELP_ABOUT                  40019
#define IDM_EDIT_SELECTALL              40020
#define IDM_EDIT_INVERTSELECTION        40021
#define IDM_VIEW_SHOWFOLDER             40025
#define IDM_QUOTA_DELETE                40026
#define IDM_HELP_ABOUTNT                40027
#define IDM_VIEW_ARRANGE_BYFOLDER       40035
#define IDM_VIEW_ARRANGE_BYSTATUS       40036
#define IDM_DEBUG_DUMP                  40038
#define IDM_CLEAR_CACHE                 40039
#define IDM_EDIT_UNDO                   40040
#define IDM_EDIT_COPY                   40041
#define IDM_EDIT_FIND                   40042
#define IDM_EDIT_FIND_LIST              40043
#define IDM_QUOTA_IMPORT                40044
#define IDM_QUOTA_EXPORT                40045
#define IDS_WINDOWS                     40500
#define IDS_TOOLBAR_COMBO               40517
#define IDS_PROGRESS_IMPORTING          40518
#define IDS_PROGRESS_DELETING           40519
#define IDS_STATUS_OK                   40523
#define IDS_STATUS_WARNING              40524
#define IDS_STATUS_OVERLIMIT            40525
#define IDS_STATUS_UNKNOWN              40526
#define IDS_STATUS_DISABLED             40527
#define IDS_STATUS_ACTIVE               40528
#define IDS_STATUS_REBUILDING           40530
#define IDS_TITLE_DISK_QUOTA            40531
#define IDS_TITLE_COL_FOLDER            40532
#define IDS_TITLE_COL_USERNAME          40533
#define IDS_TITLE_COL_STATUS            40534
#define IDS_TITLE_COL_AMTUSED           40535
#define IDS_TITLE_COL_PCTUSED           40536
#define IDS_TITLE_COL_LIMIT             40537
#define IDS_TITLE_COL_THRESHOLD         40538
#define IDS_REPORT_HEADER_FOLDER        40539
#define IDS_REPORT_HEADER_USERNAME      40540
#define IDS_REPORT_HEADER_STATUS        40541
#define IDS_REPORT_HEADER_AMTUSED       40542
#define IDS_REPORT_HEADER_LIMIT         40543
#define IDS_REPORT_HEADER_THRESHOLD     40544
#define IDS_REPORT_HEADER_PCTUSED       40545
#define IDS_QUOTA_USED_SINGLEUSER       40546
#define IDS_TITLE_MULTIUSER             40547
#define IDS_TITLE_EDIT_USER             40548
#define IDS_TITLE_ADD_USER              40549
#define IDS_NOADD_EXISTING_USER         40550
#define IDS_NOADD_UNKNOWN_USER          40551
#define IDS_STATUSBAR_ITEMCOUNT         40554
#define IDS_STATUSBAR_ITEMCOUNT_STALE   40555
#define IDS_TITLE_MAINWINDOW            40556
#define IDS_USER_ACCOUNT_UNAVAILABLE    40557
#define IDS_USER_ACCOUNT_UNRESOLVED     40558
#define IDS_USER_ACCOUNT_UNKNOWN        40559
#define IDS_USER_ACCOUNT_INVALID        40560
#define IDS_USER_ACCOUNT_DELETED        40561
#define IDS_NOT_APPLICABLE              40562
#define IDS_DISABLE_QUOTA_WARNING       40564
#define IDS_ENABLE_QUOTA_WARNING        40565
#define IDS_OUTOFMEMORY                 40566
#define IDS_UNKNOWN_EXCEPTION           40567
#define IDS_UNKNOWN_ERROR               40568
#define IDS_NO_WRITE_ACCESS             40569
#define IDS_WRITE_ERROR                 40570
#define IDS_CANNOT_DELETE_USER          40571
#define IDS_CANNOT_DELETE_USERS         40572
#define IDS_ERROR_DELETE_USER           40573
#define IDS_ERROR_FILE_NOT_FOUND        40574
#define IDS_ERROR_FILE_CORRUPT          40575
#define IDS_ERROR_DDE_EXECUTE           40576
#define IDS_CONFIRM_DELETE_USER         40577
#define IDS_APPLY_SETTINGS_ERROR        40578
#define IDS_CANT_SET_ADMIN_LIMIT        40582
#define IDS_CANT_DELETE_ADMIN_RECORD    40583
#define IDS_USER_NOT_FOUND_IN_LISTVIEW  40584
#define IDS_EXPORT_STREAM_FAILED        40585
#define IDS_EXPORT_STREAM_NOACCESS      40586
#define IDS_EXPORT_STREAM_OUTOFMEMORY   40587
#define IDS_EXPORT_STREAM_INVALIDNAME   40588
#define IDS_EXPORT_STREAM_TOOMANYFILES  40589
#define IDS_EXPORT_STREAM_FILENAME_TEMPLATE 40590
#define IDS_IMPORT_STREAM_INVALID_STREAM 40591
#define IDS_IMPORT_STREAM_READ_ERROR    40592
#define IDS_IMPORT_STREAM_NOACCESS      40593
#define IDS_IMPORT_STREAM_OUTOFMEMORY   40594
#define IDS_IMPORT_STREAM_INVALIDNAME   40595
#define IDS_IMPORT_STREAM_TOOMANYFILES  40596
#define IDS_IMPORT_STREAM_FILENOTFOUND  40597
#define IDS_IMPORT_REPLACE_RECORD       40598
#define IDS_TT_QUOTA_NEW                40599
#define IDS_TT_QUOTA_DELETE             40600
#define IDS_TT_QUOTA_PROPERTIES         40601
#define IDS_TT_EDIT_UNDO                40602
#define IDS_TT_EDIT_FIND                40603
#define IDS_TITLE_EDIT_MULTIUSER        40605
#define IDS_TITLE_GENERAL               40606
#define IDS_TITLE_GETUSER_DIALOG        40607
#define IDS_FMT_ERR_ADDUSER             40608
#define IDS_MULTIPLE                    40609
#define IDS_PROGRESS_ADDUSER            40610
#define IDS_SNAPIN_COLUMN               40611
#define IDS_SNAPIN_RESULTNAME           40613
#define IDS_SNAPIN_SCOPENAME            40614
#define IDS_SNAPIN_NAME                 40615
#define IDS_VERB_OPEN                   40616
#define IDS_SNAPIN_POLICYDLG_TITLE      40617
#define IDS_OWNERDLG_HDR_FILE           40618
#define IDS_OWNERDLG_HDR_FOLDER         40619
#define IDS_OWNERDLG_HDR_OWNER          40620
#define IDS_FMT_ALLOWNERS               40621
#define IDS_FMT_OWNER                   40622
#define IDS_FMT_OWNERDLG_HEADER         40623
#define IDS_BROWSEFORFOLDER             40624
#define IDS_ERROR_MOVETO_SAMEVOL        40625
#define IDS_FMT_DISPLAY_LOGON_CONTAINER 40626
#define IDS_FMT_LOGON_CONTAINER         40627
#define IDS_FMT_DISPLAY_LOGON           40629
#define IDS_TITLE_COL_LOGONNAME         40630
#define IDS_REPORT_HEADER_LOGONNAME     40631
#define IDM_VIEW_ARRANGE_BYLOGONNAME    40632
#define IDS_PROGRESS_SEARCHINGFORFILES  40633
#define IDS_FMT_ERR_WARNOVERLIMIT       40634
#define IDS_FMT_MOUNTEDVOL_DISPLAYNAME  40636
#define IDS_EXPORT_STREAM_FILENAME_TEMPLATE_VOLSN 40637
#define IDS_DLGTITLE_IMPORT             40638
#define IDS_DLGTITLE_EXPORT             40639

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         40047
#define _APS_NEXT_CONTROL_VALUE         1095
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
