#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H


#define IDC_CPLICON		1
#define IDC_FLAGS		2
#define IDC_ICON1		3

#define IDD_GENERALPAGE		100
#define IDD_NUMBERSPAGE		101
#define IDD_CURRENCYPAGE	102

#define IDD_TIMEPAGE		103
#define IDC_TIMESAMPLE		107
#define IDC_TIMEFORMAT		108
#define IDC_TIMESEPARATOR	109
#define IDC_TIMEAMSYMBOL	110
#define IDC_TIMEPMSYMBOL	111

#define IDD_DATEPAGE		104
#define IDD_LOCALEPAGE		105
#define IDC_LANGUAGELIST	106

#define IDS_CPLNAME		1000
#define IDS_CPLDESCRIPTION	1001


#endif /* __CPL_RESOURCE_H */

/* EOF */
