# This makefile was generated automatically by mwgenmakeC.

.NOTPARALLEL: world all clean install depend

world all clean install depend:
	@enterdir imgutil ${MAKE} ${MFLAGS} $@
	@enterdir pngfilt ${MAKE} ${MFLAGS} $@

NOTNEEDED:
	@enterdir jpegfilt ${MAKE} ${MFLAGS} $@
	@enterdir wmffilt ${MAKE} ${MFLAGS} $@
