tagsetNull                      
tagsetBodyHead                  ETAG_BODY ETAG_HEAD
tagsetOverlapBoundary           ETAG_BUTTON ETAG_CAPTION ETAG_HTML ETAG_MARQUEE ETAG_RICHTEXT ETAG_TD ETAG_TH
tagsetOverlapBoundaryCenter     ETAG_BUTTON ETAG_CAPTION ETAG_HTML ETAG_MARQUEE ETAG_RICHTEXT ETAG_TD ETAG_TH ETAG_TC ETAG_TABLE
tagsetNestBoundary              ETAG_BODY ETAG_BUTTON ETAG_CAPTION ETAG_HEAD ETAG_MARQUEE ETAG_RICHTEXT ETAG_TABLE ETAG_TBODY ETAG_TC ETAG_TD ETAG_TFOOT ETAG_TH ETAG_THEAD ETAG_TR
tagsetLiteral                   ETAG_COMMENT ETAG_EVENT ETAG_SCRIPT ETAG_STYLE ETAG_TEXTAREA ETAG_GENERIC_LITERAL ETAG_TITLE_TAG
tagsetPaste                     ETAG_SEL ETAG_FRAG
tagsetPBoundary                 ETAG_BLOCKQUOTE ETAG_BODY ETAG_BUTTON ETAG_CAPTION ETAG_DIR ETAG_DL ETAG_LISTING ETAG_MARQUEE ETAG_MENU ETAG_OL ETAG_PRE ETAG_RICHTEXT ETAG_TABLE ETAG_TBODY ETAG_TC ETAG_TD ETAG_TFOOT ETAG_TH ETAG_THEAD ETAG_TR ETAG_UL
tagsetLiP                       ETAG_LI ETAG_P
tagsetDdDtP                     ETAG_DD ETAG_DT ETAG_P
tagsetFormHead                  ETAG_FORM ETAG_HEAD
tagsetTableTr                   ETAG_TABLE ETAG_TR
tagsetTdCloses                  ETAG_TC ETAG_TD ETAG_TH ETAG_CAPTION ETAG_COLGROUP ETAG_SELECT ETAG_OPTION
tagsetTrCloses                  ETAG_TR ETAG_CAPTION ETAG_COLGROUP ETAG_TC ETAG_SELECT ETAG_OPTION
tagsetColCloses                 ETAG_THEAD ETAG_TBODY ETAG_TFOOT ETAG_CAPTION ETAG_TC ETAG_SELECT ETAG_OPTION
tagsetTbodyCloses               ETAG_THEAD ETAG_TBODY ETAG_TFOOT ETAG_COLGROUP ETAG_CAPTION ETAG_TC ETAG_SELECT ETAG_OPTION
tagsetTableCloses               ETAG_TABLE ETAG_TC ETAG_SELECT ETAG_OPTION
tagsetEndTr                     ETAG_THEAD ETAG_TBODY ETAG_TFOOT ETAG_TABLE ETAG_TD ETAG_TH ETAG_CAPTION
tagsetAppletObject              ETAG_APPLET ETAG_OBJECT
tagsetTbodyTfootThead           ETAG_TBODY ETAG_TFOOT ETAG_THEAD
tagsetColgroupTable             ETAG_COLGROUP ETAG_TABLE
tagsetTableCellCaption          ETAG_CAPTION ETAG_TABLE ETAG_TC ETAG_TD ETAG_TH
tagsetObjectApplet              ETAG_OBJECT ETAG_APPLET
tagsetOverlapBoundaryBodyHead   ETAG_BODY ETAG_HEAD ETAG_BUTTON ETAG_CAPTION ETAG_HTML ETAG_MARQUEE ETAG_RICHTEXT ETAG_TD ETAG_TH
tagsetHeaders                   ETAG_H1 ETAG_H2 ETAG_H3 ETAG_H4 ETAG_H5 ETAG_H6
tagsetHtmlHead                  ETAG_HTML ETAG_HEAD
tagsetHtmlHeadBody              ETAG_HTML ETAG_HEAD ETAG_BODY
tagsetTextReject                ETAG_HTML ETAG_HEAD ETAG_BODY ETAG_FRAMESET ETAG_FRAME ETAG_OPTION ETAG_PARAM ETAG_UNKNOWN
tagsetHtmlFrameset              ETAG_HTML ETAG_FRAMESET
tagsetFramesetAccept            ETAG_EMBED ETAG_FRAME ETAG_FRAMESET ETAG_NOFRAMES ETAG_UNKNOWN ETAG_FORM ETAG_INPUT
tagsetSelectAccept              ETAG_OPTION ETAG_SCRIPT ETAG_UNKNOWN ETAG_TC ETAG_TD ETAG_TH ETAG_TR ETAG_TBODY ETAG_THEAD ETAG_TFOOT ETAG_TABLE ETAG_INPUT ETAG_TEXTAREA
tagsetObjectAccept              ETAG_APPLET ETAG_FRAG ETAG_OBJECT ETAG_SEL
tagsetBodyHeadFrameSet          ETAG_BODY ETAG_HEAD ETAG_FRAMESET
