#!/bin/sh

thisdir=`dirname "$0"`
bugids=`$thisdir/bugids "$@"` || echo "$bugids" 1>&2 && exit 1

bugids=`echo "$bugids" | sed -e 's/ /\,/g'`
echo "https://bugzilla.mozilla.org/buglist.cgi?ctype=html&bug_id=$bugids"

