# $Id: Makefile.ros-template,v 1.3.2.3 2004/12/13 16:18:07 hyperion Exp $

TARGET_NAME = mpr

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ kernel32.a wine.a ntdll.a

TARGET_BASE = $(TARGET_BASE_LIB_MPR)

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
