# $Id: Makefile.ros-template,v 1.2 2004/05/29 21:24:44 hbirr Exp $

TARGET_NAME = mpr

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ kernel32.a libwine.a ntdll.a

TARGET_BASE = $(TARGET_BASE_LIB_MPR)

TARGET_NORC = yes

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
