# $Id: Makefile.ros-template,v 1.2.14.1 2004/10/25 14:48:39 ion Exp $

TARGET_NAME = mpr

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ kernel32.a libwine.a ntdll.a

TARGET_BASE = $(TARGET_BASE_LIB_MPR)

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
