# $Id: makefile,v 1.1 2001/08/25 17:02:21 ekohl Exp $

PATH_TO_TOP = ../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = partinfo

#TARGET_CFLAGS = -fnative_struct

TARGET_SDKLIBS = kernel32.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
