typedef struct _ASSIGN_INPUT
{
    WCHAR letter;
    USHORT offset;
    USHORT len;
} ASSIGN_INPUT, *PASSIGN_INPUT;

#define FSCTL_HACKSSIGN_ASSIGN CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 0x42, METHOD_BUFFERED, FILE_ANY_ACCESS)
#define FSCTL_HACKSSIGN_DELETE CTL_CODE(FILE_DEVICE_FILE_SYSTEM, 42,   METHOD_BUFFERED, FILE_ANY_ACCESS)
