# $Id: makefile,v 1.7 2001/08/21 20:13:12 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = test

TARGET_OBJECTS = test.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
