#ifndef _FBT_HCI_SIZES_H
#define _FBT_HCI_SIZES_H

// Sizes
#define FBT_HCI_CMD_MIN_SIZE		3
#define FBT_HCI_CMD_MAX_SIZE		258

#define FBT_HCI_EVENT_MAX_SIZE		257

#define FBT_HCI_DATA_MIN_SIZE		5
#define FBT_HCI_DATA_MAX_SIZE		343

#define FBT_HCI_BDADDR_SIZE			6
#define FBT_HCI_NAME_SIZE			248

#define FBT_HCI_DEVICE_CLASS_SIZE	3

#define FBT_HCI_LAP_SIZE			3
#define FBT_HCI_MAX_CONDITION_SIZE	7

#define FBT_HCI_LINK_KEY_SIZE		16
#define FBT_HCI_PIN_CODE_SIZE		16

#define FBT_HCI_VARIABLE_SIZE       1


#endif // _FBT_HCI_SIZES_H
