# $Id: makefile,v 1.1 2001/09/09 21:31:13 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = atapi

TARGET_DDKLIBS = scsiport.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
