# $Id: makefile,v 1.11 2004/06/06 15:55:03 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = sermouse

TARGET_OBJECTS = \
  sermouse.o

TARGET_CFLAGS = -Wall -Werror

#mouse.o - Old Serial mouse driver

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
