
#include <initguid.h>


//GenericTelephonyServiceClass_UUID
//GenericAudioServiceClass_UUID
//GenericFileTransferServiceClass_UUID
//GenericNetworkingServiceClass_UUID
//PnPInformationServiceClass_UUID
//AudioVideoServiceClass_UUID
//UDITAServiceClass_UUID
//UDIMTServiceClass_UUID
//VideoConferencingGWServiceClass_UUID
//CommonISDNAccessServiceClass_UUID
//HCRScanServiceClass_UUID
//HCRPrintServiceClass_UUID
//HardcopyCableReplacementServiceClass_UUID
//HumanInterfaceDeviceServiceClass_UUID
//PrintingStatusServiceClass_UUID
//BasicPringingServiceClass_UUID
//ReflectedUIServiceClass_UUID
//DirectPrintingReferenceObjectsServiceClass_UUID
//HandsfreeAudioGatewayServiceClass_UUID
//HandsfreeServiceClass_UUID
//ImagingReferenceObjectsServiceClass_UUID
//ImagingAutomaticArchiveServiceClass_UUID
//ImagingResponderServiceClass_UUID
//ImagingServiceClass_UUID
//ReferencePrintingServiceClass_UUID
//DirectPrintingServiceClass_UUID
//GNServiceClass_UUID
//NAPServiceClass_UUID
//PANUServiceClass_UUID
//WAPClientServiceClass_UUID
//WAPServiceClass_UUID
//HeadsetAudioGatewayServiceClass_UUID
//FaxServiceClass_UUID
//IntercomServiceClass_UUID
//VideoConferencingServiceClass_UUID
//AVRemoteControlServiceClass_UUID
//AdvancedAudioDistributionServiceClass_UUID
//AVRemoteControlTargetServiceClass_UUID
//AudioSinkServiceClass_UUID
//AudioSourceServiceClass_UUID
//CordlessTelephonyServiceClass_UUID
//HeadsetServiceClass_UUID
//IrMCSyncCommandServiceClass_UUID
//OBEXFileTransferServiceClass_UUID
//OBEXObjectPushServiceClass_UUID
//IrMCSyncServiceClass_UUID
//DialupNetworkingServiceClass_UUID
//LANAccessUsingPPPServiceClass_UUID
//SerialPortServiceClass_UUID
//PublicBrowseGroupServiceClass_UUID
//BrowseGroupDescriptorServiceClassID_UUID
//ServiceDiscoveryServerServiceClassID_UUID
//L2CAP_PROTOCOL_UUID
//UDI_C_PLANE_PROTOCOL_UUID
//CMPT_PROTOCOL_UUID
//AVDTP_PROTOCOL_UUID
//AVCTP_PROTOCOL_UUID
//HN_PROTOCOL_UUID
//HCDC_PROTOCOL_UUID
//HCCC_PROTOCOL_UUID
//HID_PROTOCOL_UUID
//UPNP_PROTOCOL_UUID
//BNEP_PROTOCOL_UUID
//WSP_PROTOCOL_UUID
//HTTP_PROTOCOL_UUID
//FTP_PROTOCOL_UUID
//IP_PROTOCOL_UUID
//OBEX_PROTOCOL_UUID
//TCSAT_PROTOCOL_UUID
//TCSBIN_PROTOCOL_UUID
//TCP_PROTOCOL_UUID
//RFCOMM_PROTOCOL_UUID
//UDP_PROTOCOL_UUID
//SDP_PROTOCOL_UUID
//Bluetooth_Base_UUID
//GUID_BLUETOOTH_HCI_EVENT
//GUID_BLUETOOTH_L2CAP_EVENT
//GUID_BLUETOOTH_PIN_REQUEST
//GUID_BLUETOOTH_RADIO_OUT_OF_RANGE
//GUID_BLUETOOTH_RADIO_IN_RANGE
//GUID_BTHPORT_DEVICE_INTERFACE
