
#include <initguid.h>

//GUID_QOS_ENABLE_WINDOW_ADJUSTMENT
//GUID_QOS_ENABLE_AVG_STATS
//GUID_QOS_FLOW_8021P_NONCONFORMING
//GUID_QOS_FLOW_8021P_CONFORMING
//GUID_QOS_FLOW_IP_NONCONFORMING
//GUID_QOS_FLOW_IP_CONFORMING
//GUID_QOS_TIMER_RESOLUTION
//GUID_QOS_ISSLOW_FLOW
//GUID_QOS_FLOW_MODE
//GUID_QOS_STATISTICS_BUFFER
//GUID_QOS_MAX_OUTSTANDING_SENDS
//GUID_QOS_NON_BESTEFFORT_LIMIT
//GUID_QOS_FLOW_COUNT
//GUID_QOS_LATENCY
//GUID_QOS_BESTEFFORT_BANDWIDTH
//GUID_QOS_REMAINING_BANDWIDTH
