#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H


#define IDI_CPLICON	4379
#define IDI_MUTED_ICON 4380
#define IDI_MICROPHONE_ICON 4381

#define IDD_HARDWARE	100
#define IDD_VOLUME	101
#define IDD_SOUNDS	102
#define IDD_AUDIO	103
#define IDD_VOICE	104
#define IDC_VOLUME_TRACKBAR 105
#define IDC_MUTE_CHECKBOX 106
#define IDC_ICON_IN_TASKBAR 107
#define IDC_SOUND_SCHEME 108
#define IDC_SCHEME_LIST 109
#define IDC_SOUND_LIST 110
#define IDC_DEFAULT_DEV_CHECKBOX 111
#define IDC_DEVICE_PLAY_LIST 112
#define IDC_DEVICE_REC_LIST 113
#define IDC_DEVICE_MIDI_LIST 114
#define IDC_DEVICE_VOICE_LIST 115
#define IDC_DEVICE_VOICE_REC_LIST 116

#define IDB_SPEAKIMG  4624
#define IDC_SPEAKIMG  4625

#define IDS_CPLNAME	1000
#define IDS_CPLDESCRIPTION	1001


#endif /* __CPL_RESOURCE_H */

/* EOF */
