
PATH_TO_TOP = ../..

TARGET_DEFONLY = yes

TARGET_TYPE = dynlink

TARGET_NAME = dflat32

TARGET_LFLAGS = 

TARGET_SDKLIBS = 

TARGET_GCCLIBS =

TARGET_BASE = 0x98000000

TARGET_CFLAGS = # -pipe -O2 -Wall -Wstrict-prototypes -fno-builtin  -DDBG

TARGET_OBJECTS = \
applicat.o \
box.o \
checkbox.o \
clipbord.o \
config.o \
console.o \
decomp.o \
dfalloc.o \
dialbox.o \
dialogs.o \
dllmain.o \
editbox.o \
lists.o \
helpbox.o \
listbox.o \
log.o \
message.o \
menu.o \
menubar.o \
menus.o \
msgbox.o \
normal.o \
pictbox.o \
popdown.o \
keys.o \
radio.o \
rect.o \
spinbutt.o \
statbar.o \
stubs.o\
sysmenu.o \
text.o \
textbox.o \
video.o \
watch.o \
window.o 

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
