# $Id: Makefile.ros-template,v 1.1 2004/02/01 21:20:05 gvg Exp $

TARGET_NAME = riched32

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = @EXTRADEFS@ -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ libwine.a ntdll.a

TARGET_BASE = 0x76340000

TARGET_NORC = yes

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
