# $Id: Makefile.ros-template,v 1.3 2004/12/03 23:37:43 blight Exp $

TARGET_NAME = urlmon

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = @EXTRADEFS@ -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ wine.a wine_uuid.a ntdll.a wininet.a

TARGET_BASE = $(TARGET_BASE_LIB_RICHEDIT)

TARGET_NORC = yes

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
