@ stub TcAddClassMap
@ stub TcAddFilter
@ stub TcAddFlow
@ stub TcCloseInterface
@ stub TcDeleteFilter
@ stub TcDeleteFlow
@ stub TcDeregisterClient
@ stub TcEnumerateFlows
@ stub TcEnumerateInterfaces
@ stub TcGetFlowNameA
@ stub TcGetFlowNameW
@ stub TcModifyFlow
@ stub TcOpenInterfaceA
@ stub TcOpenInterfaceW
@ stub TcQueryFlowA
@ stub TcQueryFlowW
@ stub TcQueryInterface
@ stub TcRegisterClient
@ stub TcSetFlowA
@ stub TcSetFlowW
@ stub TcSetInterface
