@ stdcall DllInitialize(long)
@ stdcall DllUnload()
@ stdcall StreamClassRegisterAdapter(ptr ptr ptr)
@ stdcall StreamClassReenumerateStreams(ptr long)
@ stdcall StreamClassDebugAssert(long long ptr long)
@ varargs StreamClassDebugPrint(long str)
@ cdecl StreamClassDeviceNotification(long ptr)
@ stdcall StreamClassGetDmaBuffer(ptr)
@ stdcall StreamClassReadWriteConfig(ptr long ptr long long)