# This makefile was generated automatically by mwgenmake.
COMPONENT = SHELL
PRODUCT = BROWSEUI_SRCC

#NO_UNICODE = 1

VOBS=/vobs
CUSTOM_RULES = ${VOBS}/ie4/shell.template

SOURCES_FILE    = sources
SOURCES_IMPORTS = TARGETTYPE TARGETNAME

DEFINES = \
	-DIN_SHDOCVW \
        -DUNICODE_SHDOCVW \
	-DFEATURE_FRAMES \
	-DMSOCT2=1 \
	-DFEATURE_URLHIST \
	-DFEATURE_PICS \
	-DVSTF \
	-D_DESK_MOVER \
	-D_HSFOLDER \
    -DNO_FILETYPES \
    -DNO_SPLASHSCREEN

# Removed from UNIX-RTW
#	-DBETA1_DIALMON_HACK \

WLIB	= browseuisrcc
LIB	= lib${WLIB}.a # target static library

LIBOBJS := ${SOURCES:%.c=%.o}
LIBOBJS := ${LIBOBJS:%.cpp=%.o}
SRCS=${SOURCES}

## COMPILE_OPTION can have the values: debug, optimized
COMPILE_OPTION = debug

## you may define the following variables
## RUN.dir     : the directory where you want the executables to go
## APP_CFLAGS  : additional compilation flags
## APP_LDFLAGS : additional link flags (maybe specifying DLLs)
## DLL         : name of the DLL to make
## DLLOBJS     : list of .o of the DLL
## DLL-EXPORTS : name of the .def file for the DLL
## MWINIT_DEFINES : list of -D<symbols> used to initialize
##        Mainwin in certain specific ways 
## MWLOCALES: list of country codes corresponding to the
##        resources you have prepared in the res subdirectory
## 
PROJECT_CFLAGS = ${INCLUDES} ${DEFINES} -I..

__cplusplus = true

include $(MWHOME)/make.rules.simple

