..\i386\emulator.asm: ..\i386\emfinit.asm \
		      ..\i386\emerror.asm \
		      ..\i386\emdisp.asm \
		      ..\i386\emf386.asm \
		      ..\i386\emdecode.asm \
		      ..\i386\emarith.asm \
		      ..\i386\emfadd.asm \
		      ..\i386\emfmul.asm \
		      ..\i386\emfdiv.asm \
		      ..\i386\emround.asm \
		      ..\i386\emload.asm \
		      ..\i386\emstore.asm \
		      ..\i386\emfmisc.asm \
		      ..\i386\emfcom.asm \
		      ..\i386\emfconst.asm \
		      ..\i386\emlsbcd.asm \
		      ..\i386\emxtract.asm \
		      ..\i386\emfprem.asm \
		      ..\i386\emtrig.asm \
		      ..\i386\emftran.asm \
		      ..\i386\emlsenv.asm \
		      ..\i386\emfsqrt.asm
