
// MBH - bugbug, of course this should be an enum

#define GOODINSTRUCTION  0
#define BADOPCODE        2
#define BADREG           3
#define OVERFLOW         4
#define OPERAND          5
#define EXTRACHARS       6
#define BADSIZE          7





ULONG ParseIntMemory(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseFltMemory(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseMemSpec(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseJump(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseIntBranch(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseFltBranch(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseIntOp(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParsePal(PUCHAR, POPTBLENTRY, PULONG, PULONG);
ULONG ParseUnknown(PUCHAR, POPTBLENTRY, PULONG, PULONG);

