# $Id: Makefile,v 1.4 2001/08/21 20:13:05 chorns Exp $

PATH_TO_TOP = ../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = vmtest

TARGET_SDKLIBS = ntdll.a kernel32.a crtdll.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
