# $Id: makefile,v 1.9 2000/08/11 12:43:33 ekohl Exp $
#
#
all:
	make -C display
	make -C miniport
	
clean:
	make -C display clean
	make -C miniport clean

dist:
	make -C display dist
	make -C miniport dist

install:
	make -C display install
	make -C miniport install
