# $Id: Makefile.ros-template,v 1.4 2004/02/26 16:19:17 navaraf Exp $

TARGET_NAME = shlwapi

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = -D__REACTOS__ @EXTRADEFS@

# FIXME: we don't do delayed imports yet so oleaut32.a is listed explicitly
TARGET_SDKLIBS = @IMPORTS@ msvcrt.a oleaut32.a libwine.a wine_uuid.a libwine_unicode.a ntdll.a

TARGET_NORC = yes

TARGET_BASE = 0x76120000

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
