# $Id: Makefile.ros-template,v 1.3 2004/02/19 21:19:27 gvg Exp $

TARGET_NAME = shlwapi

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = -D__REACTOS__ @EXTRADEFS@

# FIXME: we don't do delayed imports yet so oleaut32.a is listed explicitly
TARGET_SDKLIBS = @IMPORTS@ oleaut32.a libwine.a wine_uuid.a ntdll.a libwine_unicode.a

TARGET_NORC = yes

TARGET_BASE = 0x76120000

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
