#!/bin/sh
#
# Definitions for the JavaScript compiler testing environment.
#

jscsources="defs.js lexer.js parser.js gram.js namespace.js \
	streams.js asm.js entry.js"

js="../../src/js"

# Check that $srcdir is set correctly.
test -f $srcdir/defs || {
  echo "defs: installation error" 1>&2
  exit 1
}
