# $Id: Makefile.ros-template,v 1.1 2004/01/24 15:39:18 sedwards Exp $

TARGET_NAME = setupapi

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = @EXTRADEFS@ -D__REACTOS__

TARGET_SDKLIBS = @IMPORTS@ libwine.a ntdll.a libwine_unicode.a

TARGET_BASE = 0x76160000

TARGET_RC_SRCS = @RC_SRCS@
TARGET_RC_BINSRC = @RC_BINSRC@
TARGET_RC_BINARIES = @RC_BINARIES@

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
