# -*-makefile-*-  Makefile mode for Emacs


ifndef MAKE_VERBOSE
MAKE_VERBOSE=false      # for make.noise
endif
MAKE_VERBOSE=true

CUSTOM_RULES = ${MWROOT}/ie4/xml.template

THIS = GNUmakefile

# To add additional .idl file, just add the .c file here
SOURCES = \
    xmldocnf_i.c \



DEFINES += -DWIN32=300 -D_CAIRO_=300 -DREGISTER_PROXY_DLL -DSTRICT -D_WIN32_LEAN_AND_MEAN -DINC_OLE2 -DDllMain=msxml_DllMain

DEFINES += -DSTD_CALL -DCONDITION_HANDLING=1 -DNT_UP=1  -DNT_INST=0 -DWIN32=100 -D_NT1X_=100 -DWINNT=1 -D_WIN32_WINNT=0x0400 -DWINVER=0x0400 -D_WIN32_IE=0x0500 -DDEVL=1 -DFPO=0 -DSTRICT  -DUNICODE  -D_UNICODE  -DOLEDBVER=0x0200 -DNASHVILLE   

ifndef COMPILE_OPTION
  COMPILE_OPTION = debug
endif

ifeq (${COMPILE_OPTION}, debug)
DEFINES += -DDBG=1 -DACTIVEX_DEBUG -D_DEBUG=1 -DNDEBUG
endif

WLIB = idl
LIB  = lib${WLIB}.a

CPP_OBJS := ${SOURCES:%.C=%.o}
CPP_OBJS := ${CPP_OBJS:%.cpp=%.o}
CPP_OBJS := ${CPP_OBJS:%.cxx=%.o}
LIBOBJS = ${CPP_OBJS:%.c=%.o}
SRCS=${SOURCES}


## you may define the following variables
## RUN.dir      : the directory where you want the executables to go
## APP_CFLAGS   : additional compilation flags for C compiler
## APP_CCPPFLAGS: additional compilation flags for C++ compiler
## APP_DLLFLAGS : additional link flags
## MWINIT_DEFINES : list of -D<symbols> used to initialize
##        Mainwin in certain specific ways 
## MWLOCALES: list of country codes corresponding to the
##        resources you have prepared in the res subdirectory
## 

APP_CFLAGS += ${XML_CFLAGS} ${INCLUDES} ${DEFINES}

__cplusplus = true

# Disable clearmake dependenc generation
.NO_CMP_NON_MF_DEPS: all

# Disable clearcase parallele makefiles.
.NOTPARALLEL:


MIDL_FLAGS = \
	-wchar 4bytes \
	-env unix \
	-newtlb \
	-DMIDL_COMPILER \
	-D__MKTYPLIB__ \
        -DUNIX \
	-I${SDK_DIR} \
	${PUBLIC_INCLUDES}


include $(MWHOME)/make.rules.simple

$(O)/%_i.c $(O)/%.tlb $(O)/%.h : %.idl $(THIS)
	${ECHONOISE} "[ $(notdir $<) --> $*.tlb $*_i.c $*.h ]"
	midl \
        -tlb $(O)/$*.tlb \
        -h $(O)/$*.h \
        -iid $(O)/$*_i.c \
	${MIDL_FLAGS} \
	$*.idl








