# Shortcuts to building and running tests on unix platforms.
# Output files will be written to the directory listed below.

all:
	cd ../../contrib/ports/unix/check/ && $(MAKE)

check:
	cd ../../contrib/ports/unix/check/ && $(MAKE) check

clean:
	cd ../../contrib/ports/unix/check/ && $(MAKE) clean
