#pragma once

#define IDS_USAGE                1000

#define IDS_HOST_NAME            100
#define IDS_OS_NAME              101
#define IDS_OS_VERSION           102
#define IDS_BUILD                103
#define IDS_OS_BUILD_TYPE        104
#define IDS_REG_OWNER            105
#define IDS_REG_ORG              106
#define IDS_PRODUCT_ID           107
#define IDS_INST_DATE            108
#define IDS_UP_TIME              109
#define IDS_UP_TIME_FORMAT       110
#define IDS_SYS_MANUFACTURER     111
#define IDS_SYS_MODEL            112
#define IDS_SYS_TYPE             113
#define IDS_PROCESSORS           114
#define IDS_PROCESSORS_FORMAT    115
#define IDS_BIOS_DATE            116
#define IDS_BIOS_VERSION         117
#define IDS_ROS_DIR              118
#define IDS_SYS_DIR              119
#define IDS_BOOT_DEV             120
#define IDS_SYS_LOCALE           121
#define IDS_INPUT_LOCALE         122
#define IDS_TOTAL_PHYS_MEM       123
#define IDS_AVAIL_PHISICAL_MEM   124
#define IDS_VIRT_MEM_MAX         125
#define IDS_VIRT_MEM_AVAIL       126
#define IDS_VIRT_MEM_INUSE       127
#define IDS_PAGEFILE_LOC         128
#define IDS_TIME_ZONE            129
#define IDS_DOMAIN               130
#define IDS_NETWORK_CARDS        131
#define IDS_NETWORK_CARDS_FORMAT 132
#define IDS_CONNECTION_NAME      133
#define IDS_STATUS               134
#define IDS_MEDIA_DISCONNECTED   135
#define IDS_DHCP_ENABLED         136
#define IDS_NO                   137
#define IDS_IP_ADDRESSES         138
