
PATH_TO_TOP = ../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = ipconfig

TARGET_SDKLIBS = user32.a iphlpapi.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
