# $Id: makefile,v 1.17 2003/11/16 22:42:43 sedwards Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = null

TARGET_OBJECTS = null.o

TARGET_CFLAGS = -D__USE_W32API 

#TARGET_LFLAGS = -Wl,--file-alignment,0x20 -Wl,--section-alignment,0x20

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
