/*++ BUILD Version: 0001
 *
 *  WOW v1.0
 *
 *  Copyright (c) 1991, Microsoft Corporation
 *
 *  WKERNEL.H
 *  WOW32 16-bit Kernel API support
 *
 *  History:
 *  Created 07-Mar-1991 by Jeff Parsons (jeffpar)
--*/



ULONG FASTCALL WK32AccessResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32AddAtom(PVDMFRAME pFrame);
ULONG FASTCALL WK32AllocDStoCSAlias(PVDMFRAME pFrame);
ULONG FASTCALL WK32AllocResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32AllocSelector(PVDMFRAME pFrame);
ULONG FASTCALL WK32Catch(PVDMFRAME pFrame);
ULONG FASTCALL WK32DebugBreak(PVDMFRAME pFrame);
ULONG FASTCALL WK32DeleteAtom(PVDMFRAME pFrame);
ULONG FASTCALL WK32FatalExit(PVDMFRAME pFrame);
ULONG FASTCALL WK32FindAtom(PVDMFRAME pFrame);
ULONG FASTCALL WK32FindResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32FreeLibrary(PVDMFRAME pFrame);
ULONG FASTCALL WK32FreeModule(PVDMFRAME pFrame);
ULONG FASTCALL WK32FreeProcInstance(PVDMFRAME pFrame);
ULONG FASTCALL WK32WOWFreeResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32FreeSelector(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetAtomHandle(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetAtomName(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetCodeHandle(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetCodeInfo(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetCurrentPDB(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetCurrentTask(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetDOSEnvironment(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetDriveType(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetFreeSpace(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetInstanceData(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetModuleFileName(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetModuleHandle(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetModuleUsage(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetNumTasks(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetPrivateProfileInt(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetPrivateProfileString(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetProcAddress(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetProfileInt(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetProfileString(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetSystemDirectory(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetTempDrive(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetTempFileName(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetVersion(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetWinFlags(PVDMFRAME pFrame);
ULONG FASTCALL WK32GetWindowsDirectory(PVDMFRAME pFrame);
ULONG FASTCALL WK32InitAtomTable(PVDMFRAME pFrame);
ULONG FASTCALL WK32LimitEmsPages(PVDMFRAME pFrame);
ULONG FASTCALL WK32LoadLibrary(PVDMFRAME pFrame);
ULONG FASTCALL WK32WOWLoadModule(PVDMFRAME pFrame);
ULONG FASTCALL WK32LoadResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32LockResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32LockSegment(PVDMFRAME pFrame);
ULONG FASTCALL WK32MakeProcInstance(PVDMFRAME pFrame);
ULONG FASTCALL WK32OpenFile(PVDMFRAME pFrame);
ULONG FASTCALL WK32OutputDebugString(PVDMFRAME pFrame);
ULONG FASTCALL WK32SetErrorMode(PVDMFRAME pFrame);
ULONG FASTCALL WK32SetHandleCount(PVDMFRAME pFrame);
ULONG FASTCALL WK32SetResourceHandler(PVDMFRAME pFrame);
ULONG FASTCALL WK32SetSwapAreaSize(PVDMFRAME pFrame);
ULONG FASTCALL WK32SizeofResource(PVDMFRAME pFrame);
ULONG FASTCALL WK32SwapRecording(PVDMFRAME pFrame);
ULONG FASTCALL WK32SwitchStackBack(PVDMFRAME pFrame);
ULONG FASTCALL WK32SwitchStackTo(PVDMFRAME pFrame);
ULONG FASTCALL WK32Throw(PVDMFRAME pFrame);
ULONG FASTCALL WK32UnlockSegment(PVDMFRAME pFrame);
ULONG FASTCALL WK32ValidateCodeSegments(PVDMFRAME pFrame);
ULONG FASTCALL WK32ValidateFreeSpaces(PVDMFRAME pFrame);
ULONG FASTCALL WK32WinExec(PVDMFRAME pFrame);
ULONG FASTCALL WK32WritePrivateProfileString(PVDMFRAME pFrame);
ULONG FASTCALL WK32WriteProfileString(PVDMFRAME pFrame);
ULONG FASTCALL WK32lstrcat(PVDMFRAME pFrame);
ULONG FASTCALL WK32lstrcpy(PVDMFRAME pFrame);
ULONG FASTCALL WK32lstrlen(PVDMFRAME pFrame);
ULONG FASTCALL WK32TermsrvGetWindowsDir(PVDMFRAME pFrame);

