/*++
 *
 *  WOW v1.0
 *
 *  Copyright (c) 1991, Microsoft Corporation
 *
 *  WSTBL2.h
 *  WOW32 16-bit Sound API tables
 *
 *  History:
 *  Created 27-Jan-1991 by Jeff Parsons (jeffpar)
--*/

    {W32FUN(UNIMPLEMENTEDAPI,     "DUMMYENTRY",        MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "OPENSOUND",         MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "CLOSESOUND",        MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEQUEUESIZE", MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICENOTE",      MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEACCENT",    MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICEENVELOPE",  MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETSOUNDNOISE",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICESOUND",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "STARTSOUND",        MOD_SOUND, 0)},

  /*** 0010 ***/
    {W32FUN(UNIMPLEMENTEDAPI,     "STOPSOUND",         MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "WAITSOUNDSTATE",    MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SYNCALLVOICES",     MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "COUNTVOICENOTES",   MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "GETTHRESHOLDEVENT", MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "GETTHRESHOLDSTATUS",MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "SETVOICETHRESHOLD", MOD_SOUND, 0)},
    {W32FUN(WS32DoBeep,           "DOBEEP",            MOD_SOUND, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,     "MYOPENSOUND",       MOD_SOUND, 0)},
