/*++
 *
 *  WOW v1.0
 *
 *  Copyright (c) 1991, 1992, 1993 Microsoft Corporation
 *
 *  WKTBL2.h
 *  WOW32 wifeman API thunks
 *
 *  This file is included into the master thunk table.
 *
--*/
#ifdef FE_SB
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0010 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0020 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0030 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0040 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0050 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},

  /*** 0060 ***/
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(WWM32MiscGetEUDCLeadByteRange, "MISCGETEUDCLEADBYTERANGE", MOD_WIFEMAN, sizeof(MISCGETEUDCLEADBYTERANGE16))},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
    {W32FUN(UNIMPLEMENTEDAPI,		"UNDEFINED",                MOD_WIFEMAN, 0)},
#endif // FE_SB
