@ stub VB_D3DXVec2Dot
@ stub VB_D3DXVec2CCW
@ stub VB_D3DXVec2Add
@ stub VB_D3DXVec2Subtract
@ stub VB_D3DXVec2Minimize
@ stub VB_D3DXVec2Maximize
@ stub VB_D3DXVec2Scale
@ stub VB_D3DXVec2Lerp
@ stub VB_D3DXVec2Normalize
@ stub VB_D3DXVec2Hermite
@ stub VB_D3DXVec2BaryCentric
@ stub VB_D3DXVec2Transform
@ stub VB_D3DXVec2TransformCoord
@ stub VB_D3DXVec2TransformNormal
@ stub VB_D3DXVec3Length
@ stub VB_D3DXVec3LengthSq
@ stub VB_D3DXVec3Dot
@ stub VB_D3DXVec3Cross
@ stub VB_D3DXVec3Add
@ stub VB_D3DXVec3Subtract
@ stub VB_D3DXVec3Minimize
@ stub VB_D3DXVec3Maximize
@ stub VB_D3DXVec3Scale
@ stub VB_D3DXVec3Lerp
@ stub VB_D3DXVec3Normalize
@ stub VB_D3DXVec3Hermite
@ stub VB_D3DXVec3BaryCentric
@ stub VB_D3DXVec3Transform
@ stub VB_D3DXVec3TransformCoord
@ stub VB_D3DXVec3TransformNormal
@ stub VB_D3DXVec4Length
@ stub VB_D3DXVec4LengthSq
@ stub VB_D3DXVec4Dot
@ stub VB_D3DXVec4Add
@ stub VB_D3DXVec4Subtract
@ stub VB_D3DXVec4Minimize
@ stub VB_D3DXVec4Maximize
@ stub VB_D3DXVec4Scale
@ stub VB_D3DXVec4Lerp
@ stub VB_D3DXVec4Cross
@ stub VB_D3DXVec4Normalize
@ stub VB_D3DXVec4Hermite
@ stub VB_D3DXVec4BaryCentric
@ stub VB_D3DXVec4Transform
@ stub VB_D3DXMatrixIdentity
@ stub VB_D3DXMatrixIsIdentity
@ stub VB_D3DXMatrixfDeterminant
@ stub VB_D3DXMatrixMultiply
@ stub VB_D3DXMatrixTranspose
@ stub VB_D3DXMatrixInverse
@ stub VB_D3DXMatrixScaling
@ stub VB_D3DXMatrixTranslation
@ stub VB_D3DXMatrixRotationX
@ stub VB_D3DXMatrixRotationY
@ stub VB_D3DXMatrixRotationZ
@ stub VB_D3DXMatrixRotationAxis
@ stub VB_D3DXMatrixRotationQuaternion
@ stub VB_D3DXMatrixRotationYawPitchRoll
@ stub VB_D3DXMatrixTransformation
@ stub VB_D3DXMatrixAffineTransformation
@ stub VB_D3DXMatrixLookAtRH
@ stub VB_D3DXMatrixLookAtLH
@ stub VB_D3DXMatrixPerspectiveRH
@ stub VB_D3DXMatrixPerspectiveLH
@ stub VB_D3DXMatrixPerspectiveFovRH
@ stub VB_D3DXMatrixPerspectiveFovLH
@ stub VB_D3DXMatrixPerspectiveOffCenterRH
@ stub VB_D3DXMatrixPerspectiveOffCenterLH
@ stub VB_D3DXMatrixOrthoRH
@ stub VB_D3DXMatrixOrthoLH
@ stub VB_D3DXMatrixOrthoOffCenterRH
@ stub VB_D3DXMatrixOrthoOffCenterLH
@ stub VB_D3DXMatrixShadow
@ stub VB_D3DXMatrixReflect
@ stub VB_D3DXQuaternionLength
@ stub VB_D3DXQuaternionLengthSq
@ stub VB_D3DXQuaternionIdentity
@ stub VB_D3DXQuaternionIsIdentity
@ stub VB_D3DXQuaternionConjugate
@ stub VB_D3DXQuaternionToAxisAngle
@ stub VB_D3DXQuaternionRotationMatrix
@ stub VB_D3DXQuaternionRotationAxis
@ stub VB_D3DXQuaternionRotationYawPitchRoll
@ stub VB_D3DXQuaternionMultiply
@ stub VB_D3DXQuaternionNormalize
@ stub VB_D3DXQuaternionInverse
@ stub VB_D3DXQuaternionLn
@ stub VB_D3DXQuaternionExp
@ stub VB_D3DXQuaternionSlerp
@ stub VB_D3DXQuaternionSquad
@ stub VB_D3DXQuaternionBaryCentric
@ stub VB_D3DXPlaneDot
@ stub VB_D3DXPlaneDotCoord
@ stub VB_D3DXPlaneDotNormal
@ stub VB_D3DXPlaneNormalize
@ stub VB_D3DXPlaneIntersectLine
@ stub VB_D3DXPlaneFromPointNormal
@ stub VB_D3DXPlaneFromPoints
@ stub VB_D3DXPlaneTransform
@ stub VB_D3DXColorNegative
@ stub VB_D3DXColorAdd
@ stub VB_D3DXColorSubtract
@ stub VB_D3DXColorScale
@ stub VB_D3DXColorModulate
@ stub VB_D3DXColorLerp
@ stub VB_D3DXColorAdjustSaturation
@ stub VB_D3DXColorAdjustContrast
@ stub VB_D3DXVec2Length
@ stub VB_D3DXVec2LengthSq
@ stub D3DVertexBuffer8SetData
@ stub D3DVertexBuffer8GetData
@ stub D3DIndexBuffer8SetData
@ stub D3DIndexBuffer8GetData
@ stub DXLockArray8
@ stub DXUnlockArray8
@ stub VB_NewBuffer
@ stub VB_AddDataToBuffer
@ stub VB_AddStringToBuffer
@ stub VB_GetDataFromBuffer
@ stub VB_GetStringFromBuffer
@ stub VB_D3DXVec2CatmullRom
@ stub VB_D3DXVec3CatmullRom
@ stub VB_D3DXVec4CatmullRom
@ stub VB_D3DXVec3Project
@ stub VB_D3DXVec3Unproject
@ stub VB_D3DColorRGBA
@ stub VB_D3DColorARGB
@ stub VB_D3DColorXRGB
@ stub VB_D3DColorMake
@ stub VB_D3DXQuaternionDot
@ stub D3DXMeshVertexBuffer8SetData
@ stub D3DXMeshVertexBuffer8GetData
@ stub D3DXMeshIndexBuffer8SetData
@ stub D3DXMeshIndexBuffer8GetData
@ stub DXCopyMemory
@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
