/* Can't use precomp.h because these weren't stubbed properly */
#define WIN32_NO_STATUS
#define NTOS_MODE_USER
#include <windows.h>
#include <ndk/ntndk.h>

#include <debug.h>

typedef ULONG DNS_STATUS;

DNS_STATUS WINAPI DnsAddRecordSet_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAddRecordSet_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAddRecordSet_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAllocateRecord() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsApiHeapReset() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAsyncRegisterHostAddrs_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAsyncRegisterHostAddrs_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAsyncRegisterHostAddrs_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAsyncRegisterInit() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsAsyncRegisterTerm() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCheckNameCollision_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCheckNameCollision_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCheckNameCollision_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCopyStringEx() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCreateReverseNameStringForIpAddress() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCreateStandardDnsNameCopy() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsCreateStringCopy() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDhcpSrvRegisterHostName_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDhcpSrvRegisterInit() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDhcpSrvRegisterTerm() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDisableAdapterDomainNameRegistration() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDisableBNodeResolverThread() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDisableDynamicRegistration() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsDowncaseDnsNameLabel() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsEnableAdapterDomainNameRegistration() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsEnableBNodeResolverThread() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsEnableDynamicRegistration() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsExtractRecordsFromMessage_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsExtractRecordsFromMessage_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFindAuthoritativeZone() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFlushResolverCache() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFlushResolverCacheEntry_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFlushResolverCacheEntry_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFlushResolverCacheEntry_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFreeAdapterInformation() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFreeNetworkInformation() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsFreeSearchInformation() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetBufferLengthForStringCopy() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetCacheDataTable() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetDnsServerList() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetDomainName() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetHostName_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetHostName_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetHostName_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetIpAddressInfoList() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetIpAddressList() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetLastServerUpdateIP() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetMaxNumberOfAddressesToRegister() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetNetworkInformation() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetPrimaryDomainName_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetPrimaryDomainName_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetPrimaryDomainName_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsGetSearchInformation() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIpv6AddressToString() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIpv6StringToAddress() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIsAMailboxType() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIsAdapterDomainNameRegistrationEnabled() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIsDynamicRegistrationEnabled() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIsStatusRcode() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsIsStringCountValidForTextType() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsMapRcodeToStatus() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordSet_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordSet_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordSet_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordsInSet_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordsInSet_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsModifyRecordsInSet_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsNameCompareEx_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsNameCompareEx_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsNameCompareEx_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsNameCopy() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsNameCopyAllocate() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsQueryConfig() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsQueryEx() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordBuild_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordBuild_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordCompare() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordCopyEx() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordSetCompare() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordSetCopyEx() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordSetDetach() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordStringForType() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordStringForWritableType() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRecordTypeForName() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRelationalCompare_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRelationalCompare_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsRemoveRegistrations() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSetA() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSetUTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSetW() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSet_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSet_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsReplaceRecordSet_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationDeregister_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationDeregister_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationDeregister_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationRegister_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationRegister_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsServiceNotificationRegister_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsSetMaxNumberOfAddressesToRegister() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsStatusString() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsStringCopyAllocateEx() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUnicodeToUtf8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUpdate() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUpdateTest_A() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUpdateTest_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUpdateTest_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsUtf8ToUnicode() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsValidateUtf8Byte() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsWinsRecordFlagForString() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsWinsRecordFlagString() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsWriteQuestionToBuffer_UTF8() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsWriteQuestionToBuffer_W() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI DnsWriteReverseNameStringForIpAddress() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}

DNS_STATUS WINAPI GetCurrentTimeInSeconds() {
  UNIMPLEMENTED;
  return ERROR_OUTOFMEMORY;
}
