# $Id: makefile,v 1.2 2003/11/13 15:25:55 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = mup

TARGET_OBJECTS = $(TARGET_NAME).o create.o

TARGET_CFLAGS = -Werror -Wall

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
