add_subdirectory(biditext)
add_subdirectory(controls)
add_subdirectory(dialog_initvisible)
add_subdirectory(editalign)
add_subdirectory(menuaccels)
add_subdirectory(messagebox)
add_subdirectory(paintdesktop)
add_subdirectory(psmtest)
add_subdirectory(sysicon)
add_subdirectory(useridletime)
add_subdirectory(winstation)
