
 @ stub LsaIAuditNotifyPackageLoad
 @ stub LsaIAuditSamEvent
 @ stub LsaIEnumerateSecrets
 @ stub LsaIFree_LSAI_PRIVATE_DATA #DATA
 @ stub LsaIFree_LSAI_SECRET_ENUM_BUFFER
 @ stub LsaIFree_LSAPR_ACCOUNT_ENUM_BUFFER
 @ stub LsaIFree_LSAPR_CR_CIPHER_VALUE
 @ stub LsaIFree_LSAPR_POLICY_INFORMATION
 @ stub LsaIFree_LSAPR_PRIVILEGE_ENUM_BUFFER
 @ stub LsaIFree_LSAPR_PRIVILEGE_SET
 @ stub LsaIFree_LSAPR_REFERENCED_DOMAIN_LIST
 @ stub LsaIFree_LSAPR_SR_SECURITY_DESCRIPTOR
 @ stub LsaIFree_LSAPR_TRANSLATED_NAMES
 @ stub LsaIFree_LSAPR_TRANSLATED_SIDS
 @ stub LsaIFree_LSAPR_TRUSTED_DOMAIN_INFO
 @ stub LsaIFree_LSAPR_TRUSTED_ENUM_BUFFER
 @ stub LsaIFree_LSAPR_TRUST_INFORMATION
 @ stub LsaIFree_LSAPR_UNICODE_STRING
 @ stub LsaIGetPrivateData
 @ stub LsaIGetSerialNumberPolicy
 @ stub LsaIGetSerialNumberPolicy2
 @ stub LsaIHealthCheck
 @ stub LsaIInitializeWellKnownSids
 @ stub LsaIOpenPolicyTrusted
 @ stub LsaIQueryInformationPolicyTrusted
 @ stub LsaISetPrivateData
 @ stub LsaISetSerialNumberPolicy
 @ stub LsaISetTimesSecret
 @ stub LsaISetupWasRun
 @ stub LsapAuOpenSam
 @ stdcall LsapInitLsa()
 @ stub LsarAddPrivilegesToAccount
 @ stub LsarClose
 @ stub LsarCreateAccount
 @ stub LsarCreateSecret
 @ stub LsarCreateTrustedDomain
 @ stub LsarDelete
 @ stub LsarEnumerateAccounts
 @ stub LsarEnumeratePrivileges
 @ stub LsarEnumeratePrivilegesAccount
 @ stub LsarEnumerateTrustedDomains
 @ stub LsarGetQuotasForAccount
 @ stub LsarGetSystemAccessAccount
 @ stub LsarLookupNames
 @ stub LsarLookupPrivilegeDisplayName
 @ stub LsarLookupPrivilegeName
 @ stub LsarLookupPrivilegeValue
 @ stub LsarLookupSids
 @ stub LsarOpenAccount
 @ stub LsarOpenPolicy
 @ stub LsarOpenSecret
 @ stub LsarOpenTrustedDomain
 @ stub LsarQueryInfoTrustedDomain
 @ stub LsarQueryInformationPolicy
 @ stub LsarQuerySecret
 @ stub LsarQuerySecurityObject
 @ stub LsarRemovePrivilegesFromAccount
 @ stub LsarSetInformationPolicy
 @ stub LsarSetInformationTrustedDomain
 @ stub LsarSetQuotasForAccount
 @ stub LsarSetSecret
 @ stub LsarSetSecurityObject
 @ stub LsarSetSystemAccessAccount
 @ stub ServiceInit
