
#include <initguid.h>

//IID_IAccessor
//IID_IRowset
//IID_IRowsetInfo
//IID_IRowsetLocate
//IID_IRowsetResynch
//IID_IRowsetScroll
//IID_IChapteredRowset
//IID_IRowsetFind
//IID_IRowPosition
//IID_IRowPositionChange
//IID_IViewRowset
//IID_IViewChapter
//IID_IViewSort
//IID_IViewFilter
//IID_IRowsetView
//IID_IRowsetExactScroll
//IID_IRowsetChange
//IID_IRowsetUpdate
//IID_IRowsetIdentity
//IID_IRowsetNotify
//IID_IRowsetIndex
//IID_ICommand
//IID_IMultipleResults
//IID_IConvertType
//IID_ICommandPrepare
//IID_ICommandProperties
//IID_ICommandText
//IID_ICommandWithParameters
//IID_IColumnsRowset
//IID_IColumnsInfo
//IID_IDBCreateCommand
//IID_IDBCreateSession
//IID_ISourcesRowset
//IID_IDBProperties
//IID_IDBInitialize
//IID_IDBInfo
//IID_IDBDataSourceAdmin
//IID_IDBAsynchNotify
//IID_IDBAsynchStatus
//IID_ISessionProperties
//IID_IIndexDefinition
//IID_ITableDefinition
//IID_IOpenRowset
//IID_IDBSchemaRowset
//IID_IMDDataset
//IID_IMDFind
//IID_IMDRangeRowset
//IID_IAlterTable
//IID_IAlterIndex
//IID_IRowsetChapterMember
//IID_ICommandPersist
//IID_IRowsetRefresh
//IID_IParentRowset
//IID_IErrorRecords
//IID_IErrorLookup
//IID_ISQLErrorInfo
//IID_IGetDataSource
//IID_ITransactionLocal
//IID_ITransactionJoin
//IID_ITransactionObject
//IID_ITrusteeAdmin
//IID_ITrusteeGroupAdmin
//IID_IObjectAccessControl
//IID_ISecurityInfo
//IID_ITableCreation
//IID_ITableDefinitionWithConstraints
//IID_IRow
//IID_IRowChange
//IID_IRowSchemaChange
//IID_IGetRow
//IID_IBindResource
//IID_IScopedOperations
//IID_ICreateRow
//IID_IDBBinderProperties
//IID_IColumnsInfo2
//IID_IRegisterProvider
//IID_IGetSession
//IID_IGetSourceRow
//IID_IRowsetCurrentIndex
//IID_ICommandStream
//IID_IRowsetBookmark
