/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	20070613
#define KERNEL_VERSION_BUILD_STR	"20070613-rUNKNOWN"
#define KERNEL_VERSION_BUILD_RC	"20070613-rUNKNOWN\0"
#define KERNEL_RELEASE_RC	"0.4-SVN\0"
#define KERNEL_RELEASE_STR	"0.4-SVN"
#define KERNEL_VERSION_RC	"0.4-SVN\0"
#define KERNEL_VERSION_STR	"0.4-SVN"
#define REACTOS_DLL_VERSION_MAJOR	42
#define REACTOS_DLL_RELEASE_RC	"42.4-SVN\0"
#define REACTOS_DLL_RELEASE_STR	"42.4-SVN"
#define REACTOS_DLL_VERSION_RC	"42.4-SVN\0"
#define REACTOS_DLL_VERSION_STR	"42.4-SVN"
#endif
/* EOF */
