/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	20050507
#define KERNEL_VERSION_BUILD_STR	"20050507-r15066"
#define KERNEL_VERSION_BUILD_RC	"20050507-r15066\0"
#define KERNEL_RELEASE_RC	"0.3-SVN\0"
#define KERNEL_RELEASE_STR	"0.3-SVN"
#define KERNEL_VERSION_RC	"0.3-SVN\0"
#define KERNEL_VERSION_STR	"0.3-SVN"
#define REACTOS_DLL_VERSION_MAJOR	42
#define REACTOS_DLL_RELEASE_RC	"42.3-SVN\0"
#define REACTOS_DLL_RELEASE_STR	"42.3-SVN"
#define REACTOS_DLL_VERSION_RC	"42.3-SVN\0"
#define REACTOS_DLL_VERSION_STR	"42.3-SVN"
#endif
/* EOF */
