#
#   to be included in makefile
#

VERSION=WIN_RELEASE

##C_DEFINE00=-DCHAR_MIXED -DLANG=JAPANESE


NO_READONLY_STRINGS=1


C_DEFINE0=-DWIN32 -D_WIN32 -D_WINDOWS -DNT -D_NTSDK -DSDK_CODE
C_DEFINE1=-DNDEBUG -DNO_SMARTHEAP -DNT_EDITION -DJAPANESE
C_DEFINES=-DVERSION=WIN_RELEASE $(C_DEFINE0) $(C_DEFINE1)

MSC_OPTIMIZATION=/J

##MFC_FLAGS=/J /Gf
