# $Id: makefile,v 1.1 2004/10/21 04:48:46 sedwards Exp $

PATH_TO_TOP = ../../../reactos

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = tokentst

TARGET_SDKLIBS = ntdll.a kernel32.a

TARGET_OBJECTS = tokentest.o

TARGET_CFLAGS = -Wall -Werror -Wno-format

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
