// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.


//---------------------------------------------------------------------------

//
// This file is automatically generated.  Please do not edit it directly.
//
// File name: wgx_sdk_version.h
//---------------------------------------------------------------------------

#pragma once

// MIL protocol fingerprint
#define MIL_SDK_VERSION 0x200184C0

// DWM protocol fingerprint
#define DWM_SDK_VERSION 0xBDDCB2B



