#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H


#define IDC_CPLICON		200
#define IDC_FLAGS		2
#define IDC_ICON1		3

#define IDD_GENERALPAGE		100
#define IDD_NUMBERSPAGE		101

#define IDD_CURRENCYPAGE	140
#define IDC_CURRENCYPOSSAMPLE	141
#define IDC_CURRENCYNEGSAMPLE	142
#define IDC_CURRENCYSYMBOL	143
#define IDC_CURRENCYPOSVALUE	144
#define IDC_CURRENCYNEGVALUE	145
#define IDC_CURRENCYDECSEP	146
#define IDC_CURRENCYDECNUM	148
#define IDC_CURRENCYGRPSEP	149
#define IDC_CURRENCYGRPNUM	150

#define IDD_TIMEPAGE		103
#define IDC_TIMESAMPLE		107
#define IDC_TIMEFORMAT		108
#define IDC_TIMESEPARATOR	109
#define IDC_TIMEAMSYMBOL	110
#define IDC_TIMEPMSYMBOL	111

#define IDD_DATEPAGE		104
#define IDD_LOCALEPAGE		105
#define IDC_LANGUAGELIST	106

#define IDS_CPLNAME		1000
#define IDS_CPLDESCRIPTION	1001


#endif /* __CPL_RESOURCE_H */

/* EOF */
