#ifndef __CPL_RESOURCE_H
#define __CPL_RESOURCE_H


#define IDC_CPLICON		200
#define IDC_FLAGS		2

#define IDD_GENERALPAGE		100
#define IDD_NUMBERSPAGE		101

#define IDC_NUMSAMPLE_EDIT       300
#define IDC_MONEYSAMPLE_EDIT     301
#define IDC_TIMESAMPLE_EDIT      302
#define IDC_SHORTTIMESAMPLE_EDIT 303
#define IDC_FULLTIMESAMPLE_EDIT  304
#define IDC_SETUP_BUTTON 305

#define IDD_CURRENCYPAGE	140
#define IDC_CURRENCYPOSSAMPLE	141
#define IDC_CURRENCYNEGSAMPLE	142
#define IDC_CURRENCYSYMBOL	    143
#define IDC_CURRENCYPOSVALUE	144
#define IDC_CURRENCYNEGVALUE	145
#define IDC_CURRENCYDECSEP	146
#define IDC_CURRENCYDECNUM	148
#define IDC_CURRENCYGRPSEP	149
#define IDC_CURRENCYGRPNUM	150

#define IDC_NUMBERSPOSSAMPLE    250
#define IDC_NUMBERSNEGSAMPLE    251
#define IDC_NUMBERDSYMBOL       252
#define IDC_NUMBERSNDIGDEC      253
#define IDC_NUMBERSDIGITGRSYM   254
#define IDC_NUMBERSDGROUPING    255
#define IDC_NUMBERSNSIGNSYM     256
#define IDC_NUMBERSNNUMFORMAT   257
#define IDC_NUMBERSDISPLEADZER  258
#define IDC_NUMBERSLSEP         259
#define IDC_NUMBERSMEASSYS      260

#define IDD_TIMEPAGE		103
#define IDC_TIMESAMPLE		107
#define IDC_TIMEFORMAT		108
#define IDC_TIMESEPARATOR	109
#define IDC_TIMEAMSYMBOL	110
#define IDC_TIMEPMSYMBOL	111

#define IDD_DATEPAGE		104
#define IDC_LANGUAGELIST	106
#define IDD_LANGUAGESPAGE   112
#define IDD_ADVANCEDPAGE    113
#define IDC_LOCATION_COMBO  114
#define IDC_DETAIL_BUTTON   115
#define IDC_LANGUAGE_COMBO  116

#define IDC_GROUPBOX 350
#define IDC_FIRSTYEAR_EDIT 351
#define IDC_SECONDYEAR_EDIT 352
#define IDC_SCR_MAX_YEAR 353
#define IDC_CALTYPE_COMBO 354
#define IDC_HIJCHRON_COMBO 355
#define IDC_SHRTDATESAMPLE_EDIT 356
#define IDC_SHRTDATERTOL_EDIT 357
#define IDC_SHRTDATEFMT_COMBO 358
#define IDC_SHRTDATESEP_COMBO 359
#define IDC_LONGDATESAMPLE_EDIT 361
#define IDC_LONGDATERTOL_EDIT 362
#define IDC_LONGDATEFMT_COMBO 363
#define IDC_INST_FILES_FOR_RTOL_LANG 364
#define IDC_INST_FILES_FOR_ASIAN 365
#define IDC_APPLY_CUR_USER_DEF_PROFILE 366
#define IDC_CONV_TABLES 367

#define IDD_SORTPAGE		400
#define IDC_SORTLIST_COMBO	401

#define IDS_CPLNAME		    1000
#define IDS_CPLDESCRIPTION	1001
#define IDS_CUSTOMIZE_TITLE 1002
#define IDS_SPAIN 1003

#endif /* __CPL_RESOURCE_H */

/* EOF */
