PRODUCT = SITE
VOBS=/vobs
CUSTOM_RULES = ${VOBS}/ie4/trident.template

SOURCES =  \
    empty.cxx

WLIB	= sitepch
LIB	= lib${WLIB}.a # target static library

LIBOBJS := ${SOURCES:%.C=%.o}
LIBOBJS := ${LIBOBJS:%.cpp=%.o}
LIBOBJS := ${LIBOBJS:%.cxx=%.o}
LIBOBJS := ${LIBOBJS:%.c=%.o}
SRCS=${SOURCES}

## COMPILE_OPTION can have the values: debug, optimized
COMPILE_OPTION = debug

## you may define the following variables
## RUN.dir      : the directory where you want the executables to go
## PROJECT_CFLAGS   : additional compilation flags for C compiler
## PROJECT_CCPPFLAGS: additional compilation flags for C++ compiler
## PROJECT_LDFLAGS  : additional link flags (maybe specifying DLLs)
## MWINIT_DEFINES : list of -D<symbols> used to initialize
##        Mainwin in certain specific ways 
## MWLOCALES: list of country codes corresponding to the
##        resources you have prepared in the res subdirectory
## 

INCLUDES= \
    $(SITEINCLUDES)

PROJECT_CFLAGS = ${TYPE_CFLAGS} ${INCLUDES:%=-I%}

__cplusplus = true


include $(MWHOME)/make.rules.simple

