#ifndef RESOURCE_H
#define RESOURCE_H

#ifndef IDC_STATIC
    #define IDC_STATIC (-1)
#endif

/* Dialogs */
#define IDD_THEMES 1000
#define IDD_SCREENSAVER 1015
#define IDD_APPEARANCE 1001
#define IDD_SETTINGS 1007
#define IDD_ADVAPPEARANCE 1002
#define IDD_EFFAPPEARANCE 1006
#define IDD_ADVANCED_GENERAL 1010
#define IDD_CONFIRMSETTINGS 1011

/* IDD_THEMES Dialog */
#define IDC_THEMES_COMBOBOX 1000
#define IDC_THEMES_SAVE_AS 1001
#define IDC_THEMES_DELETE 1002
#define IDC_THEMES_PREVIEW 1003

/* IDD_SCREENSAVER Dialog */
#define IDC_SCREENS_PREVIEW 1010
#define IDC_SCREENS_LIST 1011
#define IDC_SCREENS_POWER_BUTTON 1012
#define IDC_SCREENS_SETTINGS 1013
#define IDC_SCREENS_TESTSC 1014
#define IDC_SCREENS_USEPASSCHK 1015
#define IDC_SCREENS_TIMEDELAY 1016
#define IDC_SCREENS_TIME 1017
#define IDC_WAITTEXT 1018
#define IDC_MINTEXT 1019
#define IDC_SCREENS_DUMMY 5000
#define IDC_SCREENS_DUMMY2 5001

/* IDD_SETTINGS Dialog */
#define IDC_SETTINGS_DEVICE 201
#define IDC_SETTINGS_BPP 202
#define IDC_SETTINGS_RESOLUTION 203
#define IDC_SETTINGS_RESOLUTION_TEXT 204
#define IDC_SETTINGS_ADVANCED 205
#define IDC_SETTINGS_MONSEL 206
#define IDC_SETTINGS_SPECTRUM 207

/* IDD_APPEARANCE Page */
#define IDC_APPEARANCE_PREVIEW 1500
#define IDC_APPEARANCE_COLORSCHEME 1501
#define IDC_APPEARANCE_FONTSIZE 1502
#define IDC_APPEARANCE_EFFECTS 1503
#define IDC_APPEARANCE_ADVANCED 1504
#define IDC_APPEARANCE_VISUAL_STYLE 1505
#define IDC_APPEARANCE_SIZE 1506

/* IDD_ADVAPPEARANCE Dialog */
#define IDC_ADVAPPEARANCE_PREVIEW 3101
#define IDC_ADVAPPEARANCE_ELEMENT 3102
#define IDC_ADVAPPEARANCE_SIZE_T 3103
#define IDC_ADVAPPEARANCE_SIZE_E 3104
#define IDC_ADVAPPEARANCE_SIZE_UD 3105
#define IDC_ADVAPPEARANCE_COLOR1_T 3106
#define IDC_ADVAPPEARANCE_COLOR1_B 3107
#define IDC_ADVAPPEARANCE_COLOR2_T 3108
#define IDC_ADVAPPEARANCE_COLOR2_B 3109
#define IDC_ADVAPPEARANCE_FONT_T 3110
#define IDC_ADVAPPEARANCE_FONT_C 3111
#define IDC_ADVAPPEARANCE_FONTSIZE_T 3112
#define IDC_ADVAPPEARANCE_FONTSIZE_E 3113
#define IDC_ADVAPPEARANCE_FONTCOLOR_T 3114
#define IDC_ADVAPPEARANCE_FONTCOLOR_B 3115
#define IDC_ADVAPPEARANCE_FONTBOLD 3116
#define IDC_ADVAPPEARANCE_FONTITALIC 3117

/* IDD_EFFAPPEARANCE Dialog */
#define IDC_EFFAPPEARANCE_KEYBOARDCUES 3601
#define IDC_EFFAPPEARANCE_ANIMATION 3602
#define IDC_EFFAPPEARANCE_ANIMATIONTYPE 3603
#define IDC_EFFAPPEARANCE_SMOOTHING 3604
#define IDC_EFFAPPEARANCE_SMOOTHINGTYPE 3605
#define IDC_EFFAPPEARANCE_LARGEICONS 3606
#define IDC_EFFAPPEARANCE_SETDROPSHADOW 3607
#define IDC_EFFAPPEARANCE_DRAGFULLWINDOWS 3608
#define IDC_EFFAPPEARANCE_FLATMENUS 3609

/* IDD_ADVANCED_GENERAL Dialog */
#define IDC_FONTSIZE_COMBO   5000
#define IDC_FONTSIZE_CUSTOM  5001
#define IDC_RESTART_RB       5002
#define IDC_WITHOUTREBOOT_RB 5003
#define IDC_ASKME_RB         5004

/* IDD_CONFIRMSETTINGS Dialog */
#define IDC_TIMEOUTTEXT      5100

#define IDS_BRICK           850
#define IDS_SAND            851
#define IDS_EGGPLANT        852
#define IDS_HCONTRAST_1     853
#define IDS_HCONTRAST_2     856
#define IDS_HCONTRAST_BLACK 859
#define IDS_HCONTRAST_WHITE 862
#define IDS_LILAC           865
#define IDS_MAPLE           867
#define IDS_MARINE          868
#define IDS_PLUM            869
#define IDS_PUMPKIN         870
#define IDS_WHEAT           871
#define IDS_RAIN            872
#define IDS_RWB             873
#define IDS_ROSE            874
#define IDS_SLATE           876
#define IDS_GOLIVE          877
#define IDS_STORM           878
#define IDS_TEAL            879
#define IDS_CLASSIC         880
#define IDS_STANDARD        883
#define IDS_SKY             884

#define IDS_SIZE_NORMAL     2019
#define IDS_SIZE_LARGE      2020
#define IDS_SIZE_XLARGE     2021

#endif /* RESOURCE_H */
