//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by dbgwiz.rc
//
#define IDS_ADV_OR_STD_SYMCPY_HDR                               1
#define IDS_ADV_OR_STD_SYMCPY_HDR_SUB                           2
#define IDS_OPT_01_ADV_OR_STD_SYMCPY                            3
#define IDS_OPT_02_ADV_OR_STD_SYMCPY                            4
#define IDS_OS_SYM_LOC_SYMCPY_HDR                               5
#define IDS_OS_SYM_LOC_SYMCPY_HDR_SUB                           6
#define IDS_OS_SYM_LOC_SYMCPY                                   7
#define IDS_SP_SYM_LOC_SYMCPY_HDR                               8
#define IDS_SP_SYM_LOC_SYMCPY_HDR_SUB                           9
#define IDS_SP_SYM_LOC_SYMCPY                                   10
#define IDS_HOTFIX_SYM_LOC_SYMCPY_HDR                           11
#define IDS_HOTFIX_SYM_LOC_SYMCPY_HDR_SUB                       12
#define IDS_HOTFIX_SYM_LOC_SYMCPY                               13
#define IDS_STD_SYMCPY_HDR                                      14
#define IDS_STD_SYMCPY_HDR_SUB                                  15
#define IDS_STD_SYMCPY                                          16
#define IDS_GEN_ERROR_HDR                                       17
#define IDS_GEN_WARNING_HDR                                     18
#define IDS_SYMBOL_FILE_COPY_HDR                                19
#define IDS_SYMBOL_FILE_COPY_HDR_SUB                            20
#define IDS_SYMBOL_FILE_COPY                                    21
#define IDS_ASK_ADDITIONAL_SYM_LOC_SYMCPY_HDR                   22
#define IDS_ASK_ADDITIONAL_SYM_LOC_SYMCPY_HDR_SUB               23
#define IDS_ASK_ADDITIONAL_SYM_LOC_SYMCPY                       24
#define IDS_ADV_OR_STD_SYMCPY                                   25
#define IDS_OPT_1_ASK_ADDITIONAL_SYM_LOC_SYMCPY                 26
#define IDS_OPT_2_ASK_ADDITIONAL_SYM_LOC_SYMCPY                 27
#define IDS_ADDITIONAL_SYM_LOC_SYMCPY_HDR                       28
#define IDS_ADDITIONAL_SYM_LOC_SYMCPY_HDR_SUB                   29
#define IDS_ADDITIONAL_SYM_LOC_SYMCPY                           30
#define IDS_LARGEFONTNAME                                       32
#define IDS_LARGEFONTSIZE                                       33
#define IDS_YES                                                 34
#define IDS_NO                                                  35
#define IDS_SAVE_INI_FILE_HDR                                   47
#define IDS_SAVE_INI_FILE_HDR_SUB                               48
#define IDS_SAVE_INI_FILE                                       49
#define IDS_MI_01_SYMBOL_FILE_COPY                              50
#define IDS_MI_01_SYMBOL_FILE_COPY_HDR                          51
#define IDS_MI_01_SYMBOL_FILE_COPY_HDR_SUB                      52
#define IDS_RUN_WIZARD_ON_TARGET_HDR                            53
#define IDS_RUN_WIZARD_ON_TARGET_HDR_SUB                        54
#define IDS_RUN_WIZARD_ON_TARGET                                55
#define IDS_SPECIFY_INI_FILE_HDR                                56
#define IDS_SPECIFY_INI_FILE_HDR_SUB                            57
#define IDS_SPECIFY_INI_FILE                                    58
#define IDS_CONNECTION_SELECTION_HDR                            59
#define IDS_CONNECTION_SELECTION_HDR_SUB                        60
#define IDS_CONNECTION_SELECTION                                61
#define IDS_TARGET_CONFIG_FILE_LOCATION_HDR                     62
#define IDS_TARGET_CONFIG_FILE_LOCATION_HDR_SUB                 63
#define IDS_TARGET_CONFIG_FILE_LOCATION                         64
#define IDS_SELECT_COM_PORT_HDR                                 65
#define IDS_SELECT_COM_PORT_HDR_SUB                             66
#define IDS_SELECT_COM_PORT                                     67
#define IDS_SHORTCUT_NAME_HDR                                   68
#define IDS_SHORTCUT_NAME_HDR_SUB                               69
#define IDS_SHORTCUT_NAME                                       70
#define IDS_IS_THIS_KERNEL_MODE_HDR                             71
#define IDS_IS_THIS_KERNEL_MODE_HDR_SUB                         72
#define IDS_IS_THIS_KERNEL_MODE                                 73
#define IDS_KERNEL_MACHINE_ROLE_HDR                             74
#define IDS_KERNEL_MACHINE_ROLE_HDR_SUB                         75
#define IDS_KERNEL_MACHINE_ROLE                                 76
#define IDS_IS_TARGET_RESPONSIVE_HDR                            77
#define IDS_IS_TARGET_RESPONSIVE_HDR_SUB                        78
#define IDS_IS_TARGET_RESPONSIVE                                79
#define IDS_TOAST_MESSAGE_HDR                                   80
#define IDS_TOAST_MESSAGE_HDR_SUB                               81
#define IDS_TOAST_MESSAGE                                       82
#define IDS_IS_THIS_AN_APPLICATION_HDR                          83
#define IDS_IS_THIS_AN_APPLICATION_HDR_SUB                      84
#define IDS_IS_THIS_AN_APPLICATION                              85
#define IDS_IS_THIS_A_DUMP_HDR                                  86
#define IDS_IS_THIS_A_DUMP_HDR_SUB                              87
#define IDS_IS_THIS_A_DUMP                                      88
#define IDS_UNKNOWN_DEBUGGEE_HDR                                89
#define IDS_UNKNOWN_DEBUGGEE_HDR_SUB                            90
#define IDS_UNKNOWN_DEBUGGEE                                    91
#define IDS_DEBUG_APP_HDR                                       92
#define IDS_DEBUG_APP_HDR_SUB                                   93
#define IDS_DEBUG_APP                                           94
#define IDS_OPT_01_DEBUG_APP                                    95
#define IDS_OPT_02_DEBUG_APP                                    96
#define IDS_HOST_OR_TARGET_HDR                                  97
#define IDS_HOST_OR_TARGET_HDR_SUB                              98
#define IDS_HOST_OR_TARGET                                      99
#define IDS_CRASHDUMP_HDR                                       100
#define IDS_CRASHDUMP_HDR_SUB                                   101
#define IDS_CRASHDUMP                                           102
#define IDS_REMOTE_TARGET_APP_HDR                               103
#define IDS_REMOTE_TARGET_APP_HDR_SUB                           104
#define IDS_REMOTE_TARGET_APP                                   105
#define IDS_OPT_01_SPECIFY_INI_FILE                             106
#define IDS_OPT_02_SPECIFY_INI_FILE                             107
#define IDS_REMOTE_CONNECTION_TYPE_HDR                          108
#define IDS_REMOTE_CONNECTION_TYPE_HDR_SUB                      109
#define IDS_REMOTE_CONNECTION_TYPE                              110
#define IDS_WELCOME_HDR                                         111
#define IDS_WELCOME_HDR_SUB                                     112
#define IDS_WELCOME                                             113
#define IDS_OPT_01_SELECT_HANDDOLD_INI                          114
#define IDS_OPT_02_SELECT_HANDDOLD_INI                          115
#define IDS_OPT_03_SELECT_HANDDOLD_INI                          116
#define IDS_SELECT_HANDDOLD_INI_HDR_SUB                         117
#define IDS_SELECT_HANDDOLD_INI_HDR                             118
#define IDS_SELECT_HANDDOLD_INI                                 119
#define IDS_EXPERT_DEBUGGING_CHOICE_HDR_SUB                     120
#define IDS_EXPERT_DEBUGGING_CHOICE_HDR                         121
#define IDS_EXPERT_DEBUGGING_CHOICE                             122
#define IDS_HOST                                                123
#define IDS_TARGET                                              124
#define IDS_KERNEL_HOST_TARGET_CHOICE_HDR_SUB                   125
#define IDS_KERNEL_HOST_TARGET_CHOICE_HDR                       126
#define IDS_KERNEL_HOST_TARGET_CHOICE                           127
#define IDS_KERNEL_SELECT_PORT_BAUD_HDR_SUB                     129
#define IDS_KERNEL_SELECT_PORT_BAUD_HDR                         130
#define IDS_KERNEL_SELECT_PORT_BAUD                             131
#define IDS_OPT_01_SAVE_INI_FILE                                132
#define IDS_OPT_02_SAVE_INI_FILE                                133
#define IDS_DISPLAY_SUMMARY_INFO_HDR_SUB                        134
#define IDS_DISPLAY_SUMMARY_INFO_HDR                            135
#define IDS_DISPLAY_SUMMARY_INFO                                136
#define IDS_FINISH_HDR_SUB                                      137
#define IDS_FINISH_HDR                                          138
#define IDS_FINISH                                              139
#define IDS_OPT_01_EXPERT_DEBUGGING_CHOICE                      140
#define IDS_OPT_02_EXPERT_DEBUGGING_CHOICE                      141
#define IDS_OPT_03_EXPERT_DEBUGGING_CHOICE                      142
#define IDS_OPT_04_EXPERT_DEBUGGING_CHOICE                      143
#define IDS_SELECT_PORT_BAUD_HDR                                144
#define IDS_SELECT_PORT_BAUD_HDR_SUB                            145
#define IDS_SELECT_PORT_BAUD                                    146
#define IDS_RM_USER_HOST_TARGET_CHOICE_HDR                      147
#define IDS_RM_USER_HOST_TARGET_CHOICE_HDR_SUB                  148
#define IDS_RM_USER_HOST_TARGET_CHOICE                          149
#define IDS_OPT_01_USER_EXE_PROCESS_CHOICE                      150
#define IDS_OPT_02_USER_EXE_PROCESS_CHOICE                      151
#define IDS_USER_EXE_PROCESS_CHOICE_HDR                         152
#define IDS_USER_EXE_PROCESS_CHOICE_HDR_SUB                     153
#define IDS_USER_EXE_PROCESS_CHOICE                             154
#define IDS_ADV_SYMBOL_FILE_COPY_HDR                            155
#define IDS_ADV_SYMBOL_FILE_COPY_HDR_SUB                        156
#define IDS_ADV_SYMBOL_FILE_COPY                                157
#define IDS_OPT_01_HOST_OR_TARGET                               158
#define IDS_OPT_02_HOST_OR_TARGET                               159
#define IDS_FILE_MASK_EXE                                       160
#define IDS_FILE_MASK_DMP                                       161
#define IDS_ERROR_NEED_PATH                                     162
#define IDS_ERROR_NEED_PIPE_NAME                                163
#define IDS_ERROR_NEED_SRC_PATH                                 164
#define IDS_ERROR_NEED_COMP_NAME                                165
#define IDS_ERROR_NEED_DEST_PATH                                166
#define IDS_WARN_NOT_A_SYMBOL                                   167
#define IDS_WARNING                                             168
#define IDS_ERR_COPYING_SYMBOL                                  169
#define IDS_ERROR_CANT_CREATE_DIR                               170
#define IDS_ERROR_NO_FILES_FOUND                                171
#define IDS_ERROR_RETRYCANCEL_CANT_CREATE_DIR                   172
#define IDS_KERNEL_SUMMARY                                      173
#define IDS_REMOTE_USER_SUMMARY                                 174
#define IDS_OS_SUMMARY                                          175
#define IDS_SERIAL_CONNECTION                                   176
#define IDS_NETWORK_CONNECTION                                  177
#define IDS_USER_DEFINED_BAUD_RATE                              178
#define IDS_OS_DESC_INTEL                                       179
#define IDS_OS_DESC_ALPHA                                       180
#define IDS_OS_DESC_MIPS                                        181
#define IDS_OS_DESC_PPC                                         182
#define IDS_OS_DESC_FREE                                        183
#define IDS_OS_DESC_CHECKED                                     184
#define IDS_OS_DESC_WORKSTATION                                 185
#define IDS_OS_DESC_SERVER                                      186
#define IDS_OS_DESC_ENTERPRISE                                  187
#define IDS_UNKNOWN                                             188
#define IDS_WINDBG_NEEDS_TO_BE_LOCATED                          189
#define IDS_ERROR_COULDNT_EXEC_MUNGER                           190
#define IDS_ERROR_COULD_NOT_OPEN_CFG_FILE                       191
#define IDS_ERROR_COULD_NOT_CREATE_CFG_FILE                     192
#define IDS_FILE_MASK_INF                                       193
#define IDS_OPT_1_SYMBOL_FILE_COPY                              194
#define IDS_OPT_2_SYMBOL_FILE_COPY                              195
#define IDS_OPT_01_SP_SYM_LOC_SYMCPY                            196
#define IDS_OPT_02_SP_SYM_LOC_SYMCPY                            197
#define IDS_OPT_01_HOTFIX_SYM_LOC_SYMCPY                        198
#define IDS_OPT_02_HOTFIX_SYM_LOC_SYMCPY                        199
#define IDS_RETRY_CREATING_SHORTCUT                             200
#define IDS_NONE                                                201
#define IDS_FINISH_LAUNCH_DEBUGGER                              202
#define IDS_FINISH_DO_NOT_LAUNCH_DEBUGGER                       203
#define IDS_CONFIRM_CANCEL                                      204
#define IDS_ERROR_LAUNCHING_DEBUGGER                            205
#define IDS_ERROR_DELETE_SHORTCUT                               206
#define IDS_GET_DEST_DIR_SYMCPY_HDR                             207
#define IDS_GET_DEST_DIR_SYMCPY_HDR_SUB                         208
#define IDS_GET_DEST_DIR_SYMCPY                                 209
#define IDS_ERROR_GETTING_DRIVE_INFO                            210
#define IDS_COPYING_OS                                          211
#define IDS_COPYING_SP                                          212
#define IDS_COPYING_HOTFIXES                                    213
#define IDS_COPYING_ADDITIONAL_SYMBOLS                          214
#define IDS_ERROR_INCORRECT_PATH                                215
#define IDS_INFORMATIONAL                                       216
#define IDS_WARN_FILES_LINKED_INSTEAD_OF_COPIED                 217
#define IDS_WARN_NON_REMOVABLE_MEDIA_ADD_PATH                   218
#define IDS_WARN_WILL_NETWORK_CONNECTION_BE_AVAILABLE           219
#define IDS_OPT_01_OS_SYM_LOC_SYMCPY                            220
#define IDS_OPT_02_OS_SYM_LOC_SYMCPY                            221
#define IDS_WARN_THAT_COPYING_IS_ABOUT_TO_BEGIN_HDR             222
#define IDS_WARN_THAT_COPYING_IS_ABOUT_TO_BEGIN_HDR_SUB         223
#define IDS_WARN_THAT_COPYING_IS_ABOUT_TO_BEGIN                 224
#define IDS_ERROR_YOU_MUST_COPY_SOME_SYMBOLS_HDR_SUB            225
#define IDS_ERROR_YOU_MUST_COPY_SOME_SYMBOLS                    226
#define IDS_WARN_CHECK_IF_DECOMPRESSION_OF_SYMBOLS_REQUIRED     227
#define IDS_ERROR_SYM_COPY_IS_RECURSIVE                         228
#define IDS_WARN_ADV_NO_SYMBOLS_SPECIFIED                       229
#define IDS_OPT_1_IS_TARGET_RESPONSIVE                          230
#define IDS_OPT_2_IS_TARGET_RESPONSIVE                          231
#define IDS_OPT_1_KERNEL_MACHINE_ROLE                           232
#define IDS_OPT_2_KERNEL_MACHINE_ROLE                           233
#define IDS_ERROR_UNSUPPORTED_OS                                234
#define IDS_STOPPING                                            235
#define IDS_MORE_INFO_HDR                                       236
#define IDS_MI_01_IS_TARGET_RESPONSIVE                          237
#define IDS_MI_01_BLUE_SCREEN                                   238
#define IDS_MI_01_HOST_TARGET                                   239
#define IDS_MI_01_SAVE_LOAD_INI                                 240
#define IDS_MI_01_WHY_RUN_ON_TARGET_FIRST                       241
#define IDS_MI_01_SYMBOLS                                       242
#define IDS_MI_01_SYMBOL_COPY_METHOD                            243
#define IDS_MI_01_NULL_MODEM_CABLE                              244
#define IDS_MI_01_SERVICE_PACK                                  245
#define IDS_MI_01_ADDITIONAL_SYMBOLS                            246
#define IDS_MI_01_OEM                                           247
#define IDS_MI_01_LAUNCH_ATTACH                                 248
#define IDS_MI_01_DUMP_FILE                                     249
#define IDS_MI_01_APPLICATION                                   250



#define IDD_DIALOG1                                             501
#define IDD_INTRO                                               502
#define IDI_DBGWIZ                                              503
#define IDD_WELCOME                                             504
#define IDD_YESNO                                               505
#define IDD_TWO_OPT                                             506
#define IDD_BROWSE_PATH                                         507
#define IDB_WATERMARK                                           508
#define IDD_TEXT_ONLY                                           509
#define IDD_STD_COPY_SYMS                                       510
#define IDB_BANNER                                              511
#define IDD_BLANK                                               512
#define IDD_THREE_OPT                                           513
#define IDD_SAVE_INI_FILE                                       515
#define IDD_TWO_OPT_BROWSE_PATH                                 516
#define IDD_SELECT_PORT_BAUD_PIPE_COMPNAME                      517
#define IDD_SELECT_PORT_BAUD_PIPE                               518
#define IDD_SELECT_PORT_BAUD                                    519
#define IDD_SELECT_PORT                                         520
#define IDD_FOUR_OPT                                            521
#define IDD_ADV_COPY_SYMS                                       522
#define IDD_COPYING                                             523
#define IDD_SUMMARY                                             524

#define IDD_H_ADV_COPY_SYMS                                     525 
#define IDD_H_BROWSE_PATH                                       526
#define IDD_H_FOUR_OPT                                          527
#define IDD_H_SELECT_PORT                                       528
#define IDD_H_SELECT_PORT_BAUD                                  529
#define IDD_H_SELECT_PORT_BAUD_PIPE                             530
#define IDD_H_SELECT_PORT_BAUD_PIPE_COMPNAME                    531
#define IDD_H_STD_COPY_SYMS                                     532
#define IDD_H_SUMMARY                                           533
#define IDD_H_TEXT_ONLY                                         534
#define IDD_H_THREE_OPT                                         535
#define IDD_H_TWO_OPT                                           536
#define IDD_H_TWO_OPT_BROWSE_PATH                               537
#define IDD_H_WELCOME                                           538



#define IDC_BUT_MORE_INFO                                       1000
#define IDC_RADIO_NO                                            1001
#define IDC_RADIO_OPT_2                                         1002
#define IDC_BUT_MORE_INFO2                                      1003
#define IDC_RADIO_YES                                           1004
#define IDC_RADIO_OPT_1                                         1005
#define IDC_RADIO_OPT_3                                         1006
#define IDC_WELCOME2                                            1007
#define IDC_EDIT_PATH                                           1008
#define IDC_BUTTON1                                             1009
#define IDC_BUT_COPY                                            1009
#define IDC_BUT_BROWSE                                          1010
#define IDC_EDIT_TARG_PATH                                      1011
#define IDC_STXT_MAIN                                           1012
#define IDC_RADIO_OP_1                                          1013
#define IDC_EDIT_DEST                                           1013
#define IDC_WELCOME                                             1014
#define IDC_EDIT_PIPE_NAME                                      1015
#define IDC_COMBO_COMM_PORT                                     1016
#define IDC_COMBO_BAUD_RATE                                     1017
#define IDC_RADIO_SERIAL                                        1018
#define IDC_RADIO_NETWORK                                       1019
#define IDC_STXT_MACHINE_NAME                                   1020
#define IDC_EDIT_MACHINE_NAME                                   1021
#define IDC_STXT_PIPE_NAME                                      1022
#define IDC_STXT_COMM_PORT                                      1023
#define IDC_STXT_BAUD_RATE                                      1024
#define IDC_RADIO_OPT_4                                         1025
#define IDC_RADIO_LINK_SYMBOLS                                  1026
#define IDC_RADIO_COPY_SYMBOLS                                  1027
#define IDC_BUT_BROWSE_SOURCE                                   1028
#define IDC_BUT_BROWSE_SRC                                      1028
#define IDC_STXT_SOURCE                                         1029
#define IDC_BUT_BROWSE_TARGET                                   1030
#define IDC_BUT_BROWSE_DEST                                     1030
#define IDC_STXT_DEST                                           1031
#define IDC_EDIT_SRC                                            1032
#define IDC_PROGRESS                                            1033
#define IDC_STATIC_CURRENT_FILE                                 1034
#define IDC_EDIT_MAIN                                           1035
#define IDC_STATIC_COPY_STATUS                                  1036
#define IDC_WELCOME3                                            1037
#define IDC_STXT_HDR                                            1038
#define IDC_STXT_SUB_HDR                                        1039
#define IDC_STATIC                                              -1

                                                                
// Next default values for new objects                          
//                                                              
#ifdef APSTUDIO_INVOKED                                         
#ifndef APSTUDIO_READONLY_SYMBOLS                               
#define _APS_NEXT_RESOURCE_VALUE                                186
#define _APS_NEXT_COMMAND_VALUE                                 40001
#define _APS_NEXT_CONTROL_VALUE                                 1038
#define _APS_NEXT_SYMED_VALUE                                   225
#endif
#endif
