/*
 * COM Classes for hnetcfg
 *
 * Copyright 2010 Alexandre Julliard
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    helpstring("HNetCfg.FwMgr"),
    progid("HNetCfg.FwMgr"),
    threading(both),
    uuid(304ce942-6e39-40d8-943a-b913c40c9cd4)
]
coclass NetFwMgr { interface INetFwMgr; }

[
    helpstring("HNetCfg.FwAuthorizedApplication"),
    progid("HNetCfg.FwAuthorizedApplication"),
    threading(both),
    uuid(ec9846b3-2762-4a6b-a214-6acb603462d2)
]
coclass NetFwAuthorizedApplication { interface INetFwAuthorizedApplications; }

[
    helpstring("HNetCfg.FwOpenPort"),
    progid("HNetCfg.FwOpenPort"),
    threading(both),
    uuid(0ca545c6-37ad-4a6c-bf92-9f7610067ef5)
]
coclass NetFwOpenPort { interface INetFwOpenPort; }
