#!/bin/sh

export PATH=$PATH:/usr/local/pkg/reactos-powerpc/bin
make \
	ARCH=powerpc \
	HOST=mingw32-linux \
	PREFIX=reactos-powerpc \
	ROS_INTERMEDIATE=obj-ppc \
	ROS_OUTPUT=output-ppc \
	ROS_PREFIX=reactos-powerpc \
	ROS_INSTALL=rosppc \
	ROS_AUTOMAKE=makefile.ppc \
	ROS_RBUILDFLAGS=-rReactOS-ppc.rbuild \
	$*
