# $Id: Makefile.ros,v 1.1 2004/02/25 20:00:41 sedwards Exp $

TARGET_NAME = winmm

TARGET_OBJECTS = driver.o joystick.o lolvldrv.o mci.o mmio.o playsound.o time.o winmm.o

TARGET_CFLAGS = -D_WINMM_ -D__REACTOS__

TARGET_SDKLIBS = user32.a advapi32.a kernel32.a ntdll.a libwine.a wine_uuid.a ntdll.a

TARGET_BASE = 0x76160000

TARGET_RC_SRCS = winmm_res.rc
TARGET_RC_BINSRC = 
TARGET_RC_BINARIES = 

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
