@ stdcall BatteryClassInitializeDevice(ptr ptr)
@ stdcall BatteryClassIoctl(ptr ptr)
@ stdcall BatteryClassQueryWmiDataBlock(ptr ptr ptr long ptr long ptr)
@ stdcall BatteryClassStatusNotify(ptr)
@ stdcall BatteryClassSystemControl(ptr ptr ptr ptr ptr)
@ stdcall BatteryClassUnload(ptr)
