# $Id: makefile,v 1.27 2003/11/14 17:13:25 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = ide

TARGET_CFLAGS = -Wall -Werror

TARGET_OBJECTS = ide.o

TARGET_HEADERS = *.h

TARGET_GCCLIBS = gcc

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
