# $Id: makefile,v 1.3 2003/11/14 17:13:20 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_NORC = yes

TARGET_TYPE = program

TARGET_APPTYPE = windows

TARGET_NAME = shaptest

TARGET_CFLAGS = -Wall -Werror

TARGET_SDKLIBS = kernel32.a gdi32.a

TARGET_OBJECTS = $(TARGET_NAME).o

TARGET_CFLAGS = -Wall -Werror

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
