Import('*')

env = env.Clone()

softpipe = env.ConvenienceLibrary(
	target = 'softpipe',
	source = [
		'sp_fs_exec.c',
		'sp_clear.c',
		'sp_context.c',
		'sp_draw_arrays.c',
		'sp_fence.c',
		'sp_flush.c',
		'sp_prim_vbuf.c',
		'sp_setup.c',
		'sp_quad_blend.c',
		'sp_quad_pipe.c',
		'sp_quad_depth_test.c',
		'sp_quad_fs.c',
		'sp_quad_stipple.c',
		'sp_query.c',
		'sp_screen.c',
		'sp_state_blend.c',
		'sp_state_clip.c',
		'sp_state_derived.c',
		'sp_state_rasterizer.c',
		'sp_state_sampler.c',
		'sp_state_shader.c',
		'sp_state_so.c',
		'sp_state_surface.c',
		'sp_state_vertex.c',
		'sp_surface.c',
		'sp_tex_sample.c',
		'sp_tex_tile_cache.c',
		'sp_texture.c',
		'sp_tile_cache.c',
	])

env.Alias('softpipe', softpipe)

Export('softpipe')
