/*
 * nls/lcDEA.c
 * Copyright (C) 1996, Onno Hovers
 * 
 * This file has been generated by genlc.exe
 */

#include <windows.h>
#include <kernel32/nls.h>

CONST WCHAR *__LC_DEA0[]=
{
   NULL, 
   (CONST WCHAR[]) { '0', 'c', '0', '7', 0 }, 
   (CONST WCHAR[]) { 'G', 'e', 'r', 'm', 'a', 'n', ' ', '(', 'A', 'u', 's', 't', 'r', 'i', 'a', 'n', ')', 0 }, 
   (CONST WCHAR[]) { 'D', 'E', 'A', 0 }, 
   (CONST WCHAR[]) { 'D', 'e', 'u', 't', 's', 'c', 'h', 0 }, 
   (CONST WCHAR[]) { '4', '3', 0 }, 
   (CONST WCHAR[]) { 'A', 'u', 's', 't', 'r', 'i', 'a', 0 }, 
   (CONST WCHAR[]) { 'A', 'U', 'T', 0 }, 
   (CONST WCHAR[]) { 0xD6, 's', 't', 'e', 'r', 'r', 'e', 'i', 'c', 'h', 0 }, 
   (CONST WCHAR[]) { '0', 'c', '0', '7', 0 }, 
   (CONST WCHAR[]) { '4', '3', 0 }, 
   (CONST WCHAR[]) { '8', '5', '0', 0 }, 
   (CONST WCHAR[]) { ';', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { '.', 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 0 }, 
   (CONST WCHAR[]) { 0xF6, 'S', 0 }, 
   (CONST WCHAR[]) { 'A', 'T', 'S', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { '.', 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '9', 0 }, 
   (CONST WCHAR[]) { '.', 0 }, 
   (CONST WCHAR[]) { ':', 0 }, 
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0 }, 
   (CONST WCHAR[]) { 'd', 'd', 'd', 'd', ',', ' ', 'd', 'd', '.', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 'M', 'o', 'n', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'D', 'i', 'e', 'n', 's', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'M', 'i', 't', 't', 'w', 'o', 'c', 'h', 0 }, 
   (CONST WCHAR[]) { 'D', 'o', 'n', 'n', 'e', 'r', 's', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'F', 'r', 'e', 'i', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'S', 'a', 'm', 's', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'S', 'o', 'n', 'n', 't', 'a', 'g', 0 }, 
   (CONST WCHAR[]) { 'M', 'o', 0 }, 
   (CONST WCHAR[]) { 'D', 'i', 0 }, 
   (CONST WCHAR[]) { 'M', 'i', 0 }, 
   (CONST WCHAR[]) { 'D', 'o', 0 }, 
   (CONST WCHAR[]) { 'F', 'r', 0 }, 
   (CONST WCHAR[]) { 'S', 'a', 0 }, 
   (CONST WCHAR[]) { 'S', 'o', 0 }, 
   (CONST WCHAR[]) { 'J', 0xE4, 'n', 'n', 'e', 'r', 0 }, 
   (CONST WCHAR[]) { 'F', 'e', 'b', 'r', 'u', 'a', 'r', 0 }, 
   (CONST WCHAR[]) { 'M', 0xE4, 'r', 'z', 0 }, 
   (CONST WCHAR[]) { 'A', 'p', 'r', 'i', 'l', 0 }, 
   (CONST WCHAR[]) { 'M', 'a', 'i', 0 }, 
   (CONST WCHAR[]) { 'J', 'u', 'n', 'i', 0 }, 
   (CONST WCHAR[]) { 'J', 'u', 'l', 'i', 0 }, 
   (CONST WCHAR[]) { 'A', 'u', 'g', 'u', 's', 't', 0 }, 
   (CONST WCHAR[]) { 'S', 'e', 'p', 't', 'e', 'm', 'b', 'e', 'r', 0 }, 
   (CONST WCHAR[]) { 'O', 'k', 't', 'o', 'b', 'e', 'r', 0 }, 
   (CONST WCHAR[]) { 'N', 'o', 'v', 'e', 'm', 'b', 'e', 'r', 0 }, 
   (CONST WCHAR[]) { 'D', 'e', 'z', 'e', 'm', 'b', 'e', 'r', 0 }, 
   (CONST WCHAR[]) { 'J', 0xE4, 'n', 0 }, 
   (CONST WCHAR[]) { 'F', 'e', 'b', 0 }, 
   (CONST WCHAR[]) { 'M', 0xE4, 'r', 0 }, 
   (CONST WCHAR[]) { 'A', 'p', 'r', 0 }, 
   (CONST WCHAR[]) { 'M', 'a', 'i', 0 }, 
   (CONST WCHAR[]) { 'J', 'u', 'n', 0 }, 
   (CONST WCHAR[]) { 'J', 'u', 'l', 0 }, 
   (CONST WCHAR[]) { 'A', 'u', 'g', 0 }, 
   (CONST WCHAR[]) { 'S', 'e', 'p', 0 }, 
   (CONST WCHAR[]) { 'O', 'k', 't', 0 }, 
   (CONST WCHAR[]) { 'N', 'o', 'v', 0 }, 
   (CONST WCHAR[]) { 'D', 'e', 'z', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '-', 0 }, 
   (CONST WCHAR[]) { '3', 0 }, 
   (CONST WCHAR[]) { '3', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '/', 0x8000, 0x3808, 0, 0, 0, 0, 0, 0x1, 0, 0, 0x4000, 0x93, 0, 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_DEA1[]=
{
   NULL, 
   (CONST WCHAR[]) { 'G', 'e', 'r', 'm', 'a', 'n', 0 }, 
   (CONST WCHAR[]) { 'A', 'u', 's', 't', 'r', 'i', 'a', 0 }, 
   (CONST WCHAR[]) { 'H', 'H', ':', 'm', 'm', ':', 's', 's', 0 }, 
   (CONST WCHAR[]) { '1', '2', '5', '2', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   NULL, 
   NULL, 
   NULL, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL
};

CONST WCHAR *__LC_DEAds[]=
{
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', '.', 'y', 'y', 'y', 'y', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_DEAdl[]=
{
   (CONST WCHAR[]) { 'd', 'd', 'd', 'd', ',', ' ', 'd', 'd', '.', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', '.', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', '.', 'M', 'M', 'M', 'y', 'y', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', ' ', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_DEAt[]=
{
   (CONST WCHAR[]) { 'H', 'H', ':', 'm', 'm', ':', 's', 's', 0, 0 }, 
   (CONST WCHAR[]) { 'H', ':', 'm', 'm', ':', 's', 's', 0, 0 }, 
   (CONST WCHAR[]) { 'H', 'H', ':', 'm', 'm', 0, 0 }, 
   (CONST WCHAR[]) { 'H', 'H', ':', 'm', 'm', '\'', ' ', 'U', 'h', 'r', '\'', 0, 0 }, 
   NULL
};

