/*
 * nls/lcRUS.c
 * Copyright (C) 1996, Onno Hovers
 * 
 * This file has been generated by genlc.exe
 */

#include <windows.h>
#include <kernel32/nls.h>

CONST WCHAR *__LC_RUS0[]=
{
   NULL, 
   (CONST WCHAR[]) { '0', '4', '1', '9', 0 }, 
   (CONST WCHAR[]) { 'R', 'u', 's', 's', 'i', 'a', 'n', 0 }, 
   (CONST WCHAR[]) { 'R', 'U', 'S', 0 }, 
   (CONST WCHAR[]) { 0x440, 0x443, 0x441, 0x441, 0x43A, 0x438, 0x439, 0 }, 
   (CONST WCHAR[]) { '7', 0 }, 
   (CONST WCHAR[]) { 'R', 'u', 's', 's', 'i', 'a', 0 }, 
   (CONST WCHAR[]) { 'R', 'U', 'S', 0 }, 
   (CONST WCHAR[]) { 0x420, 0x43E, 0x441, 0x441, 0x438, 0x44F, 0 }, 
   (CONST WCHAR[]) { '0', '4', '1', '9', 0 }, 
   (CONST WCHAR[]) { '7', 0 }, 
   (CONST WCHAR[]) { '8', '6', '6', 0 }, 
   (CONST WCHAR[]) { ';', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { 0xA0, 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 0 }, 
   (CONST WCHAR[]) { 0x440, '.', 0 }, 
   (CONST WCHAR[]) { 'R', 'U', 'R', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { 0xA0, 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '5', 0 }, 
   (CONST WCHAR[]) { '.', 0 }, 
   (CONST WCHAR[]) { ':', 0 }, 
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0 }, 
   (CONST WCHAR[]) { 'd', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', ' ', '\'', 0x433, '.', '\'', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0x43F, 0x43E, 0x43D, 0x435, 0x434, 0x435, 0x43B, 0x44C, 0x43D, 0x438, 0x43A, 0 }, 
   (CONST WCHAR[]) { 0x432, 0x442, 0x43E, 0x440, 0x43D, 0x438, 0x43A, 0 }, 
   (CONST WCHAR[]) { 0x441, 0x440, 0x435, 0x434, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x447, 0x435, 0x442, 0x432, 0x435, 0x440, 0x433, 0 }, 
   (CONST WCHAR[]) { 0x43F, 0x44F, 0x442, 0x43D, 0x438, 0x446, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x441, 0x443, 0x431, 0x431, 0x43E, 0x442, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x432, 0x43E, 0x441, 0x43A, 0x440, 0x435, 0x441, 0x435, 0x43D, 0x44C, 0x435, 0 }, 
   (CONST WCHAR[]) { 0x41F, 0x43D, 0 }, 
   (CONST WCHAR[]) { 0x412, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x427, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x41F, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x431, 0 }, 
   (CONST WCHAR[]) { 0x412, 0x441, 0 }, 
   (CONST WCHAR[]) { 0x42F, 0x43D, 0x432, 0x430, 0x440, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x424, 0x435, 0x432, 0x440, 0x430, 0x43B, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41C, 0x430, 0x440, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x410, 0x43F, 0x440, 0x435, 0x43B, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41C, 0x430, 0x439, 0 }, 
   (CONST WCHAR[]) { 0x418, 0x44E, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x418, 0x44E, 0x43B, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x410, 0x432, 0x433, 0x443, 0x441, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x435, 0x43D, 0x442, 0x44F, 0x431, 0x440, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41E, 0x43A, 0x442, 0x44F, 0x431, 0x440, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41D, 0x43E, 0x44F, 0x431, 0x440, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x414, 0x435, 0x43A, 0x430, 0x431, 0x440, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x44F, 0x43D, 0x432, 0 }, 
   (CONST WCHAR[]) { 0x444, 0x435, 0x432, 0 }, 
   (CONST WCHAR[]) { 0x43C, 0x430, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x430, 0x43F, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x43C, 0x430, 0x439, 0 }, 
   (CONST WCHAR[]) { 0x438, 0x44E, 0x43D, 0 }, 
   (CONST WCHAR[]) { 0x438, 0x44E, 0x43B, 0 }, 
   (CONST WCHAR[]) { 0x430, 0x432, 0x433, 0 }, 
   (CONST WCHAR[]) { 0x441, 0x435, 0x43D, 0 }, 
   (CONST WCHAR[]) { 0x43E, 0x43A, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x43D, 0x43E, 0x44F, 0 }, 
   (CONST WCHAR[]) { 0x434, 0x435, 0x43A, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '-', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { 0x203, 0x8000, 0x3848, 0, 0, 0, 0, 0, 0x4, 0, 0, 0x2, 0x4, 0, 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_RUS1[]=
{
   NULL, 
   (CONST WCHAR[]) { 'R', 'u', 's', 's', 'i', 'a', 'n', 0 }, 
   (CONST WCHAR[]) { 'R', 'u', 's', 's', 'i', 'a', 0 }, 
   (CONST WCHAR[]) { 'H', ':', 'm', 'm', ':', 's', 's', 0 }, 
   (CONST WCHAR[]) { '1', '2', '5', '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   NULL, 
   NULL, 
   NULL, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL
};

CONST WCHAR *__LC_RUSds[]=
{
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', '.', 'M', '.', 'y', 'y', 0, 0 }, 
   (CONST WCHAR[]) { 'd', 'd', '/', 'M', 'M', '/', 'y', 'y', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_RUSdl[]=
{
   (CONST WCHAR[]) { 'd', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', ' ', '\'', 0x433, '.', '\'', 0, 0 }, 
   (CONST WCHAR[]) { 'd', 'd', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', ' ', '\'', 0x433, '.', '\'', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_RUSt[]=
{
   (CONST WCHAR[]) { 'H', ':', 'm', 'm', ':', 's', 's', 0, 0 }, 
   (CONST WCHAR[]) { 'H', 'H', ':', 'm', 'm', ':', 's', 's', 0, 0 }, 
   NULL
};

