/*
 * nls/lcUKR.c
 * Copyright (C) 1996, Onno Hovers
 * 
 * This file has been generated by genlc.exe
 */

#include <windows.h>
#include <kernel32/nls.h>

CONST WCHAR *__LC_UKR0[]=
{
   NULL, 
   (CONST WCHAR[]) { '0', '4', '2', '2', 0 }, 
   (CONST WCHAR[]) { 'U', 'k', 'r', 'a', 'i', 'n', 'i', 'a', 'n', 0 }, 
   (CONST WCHAR[]) { 'U', 'K', 'R', 0 }, 
   (CONST WCHAR[]) { 0x443, 0x43A, 0x440, 0x430, 0x457, 0x43D, 0x44C, 0x441, 0x43A, 0x430, 0 }, 
   (CONST WCHAR[]) { '3', '8', '0', 0 }, 
   (CONST WCHAR[]) { 'U', 'k', 'r', 'a', 'i', 'n', 'e', 0 }, 
   (CONST WCHAR[]) { 'U', 'K', 'R', 0 }, 
   (CONST WCHAR[]) { 0x423, 0x43A, 0x440, 0x430, 0x457, 0x43D, 0x430, 0 }, 
   (CONST WCHAR[]) { '0', '4', '2', '2', 0 }, 
   (CONST WCHAR[]) { '7', 0 }, 
   (CONST WCHAR[]) { '8', '6', '6', 0 }, 
   (CONST WCHAR[]) { ';', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { 0xA0, 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 0 }, 
   (CONST WCHAR[]) { 0x43A, '.', 0 }, 
   (CONST WCHAR[]) { 'U', 'A', 'K', 0 }, 
   (CONST WCHAR[]) { ',', 0 }, 
   (CONST WCHAR[]) { 0xA0, 0 }, 
   (CONST WCHAR[]) { '3', ';', '0', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '2', 0 }, 
   (CONST WCHAR[]) { '3', 0 }, 
   (CONST WCHAR[]) { '8', 0 }, 
   (CONST WCHAR[]) { '.', 0 }, 
   (CONST WCHAR[]) { ':', 0 }, 
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0 }, 
   (CONST WCHAR[]) { 'd', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', '\'', ' ', 0x440, '.', '\'', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0x43F, 0x43E, 0x43D, 0x435, 0x434, 0x456, 0x43B, 0x43E, 0x43A, 0 }, 
   (CONST WCHAR[]) { 0x432, 0x456, 0x432, 0x442, 0x43E, 0x440, 0x43E, 0x43A, 0 }, 
   (CONST WCHAR[]) { 0x441, 0x435, 0x440, 0x435, 0x434, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x447, 0x435, 0x442, 0x432, 0x435, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x43F, '\'', 0x44F, 0x442, 0x43D, 0x438, 0x446, 0x44F, 0 }, 
   (CONST WCHAR[]) { 0x441, 0x443, 0x431, 0x43E, 0x442, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x43D, 0x435, 0x434, 0x456, 0x43B, 0x44F, 0 }, 
   (CONST WCHAR[]) { 0x41F, 0x43D, 0 }, 
   (CONST WCHAR[]) { 0x412, 0x432, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x427, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x41F, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x431, 0 }, 
   (CONST WCHAR[]) { 0x41D, 0x434, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x456, 0x447, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41B, 0x44E, 0x442, 0x438, 0x439, 0 }, 
   (CONST WCHAR[]) { 0x411, 0x435, 0x440, 0x435, 0x437, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41A, 0x432, 0x456, 0x442, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x422, 0x440, 0x430, 0x432, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x427, 0x435, 0x440, 0x432, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41B, 0x438, 0x43F, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x435, 0x440, 0x43F, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x412, 0x435, 0x440, 0x435, 0x441, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x416, 0x43E, 0x432, 0x442, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x41B, 0x438, 0x441, 0x442, 0x43E, 0x43F, 0x430, 0x434, 0 }, 
   (CONST WCHAR[]) { 0x413, 0x440, 0x443, 0x434, 0x435, 0x43D, 0x44C, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x456, 0x447, 0 }, 
   (CONST WCHAR[]) { 0x41B, 0x44E, 0x442, 0 }, 
   (CONST WCHAR[]) { 0x411, 0x435, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x41A, 0x432, 0x456, 0 }, 
   (CONST WCHAR[]) { 0x422, 0x440, 0x430, 0 }, 
   (CONST WCHAR[]) { 0x427, 0x435, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x416, 0x438, 0x43F, 0 }, 
   (CONST WCHAR[]) { 0x421, 0x435, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x412, 0x435, 0x440, 0 }, 
   (CONST WCHAR[]) { 0x416, 0x43E, 0x432, 0 }, 
   (CONST WCHAR[]) { 0x41B, 0x438, 0x441, 0 }, 
   (CONST WCHAR[]) { 0x413, 0x440, 0x433, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '-', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   (CONST WCHAR[]) { 0x203, 0x8000, 0x3848, 0, 0, 0, 0, 0, 0x4, 0, 0, 0x2, 0x4, 0, 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_UKR1[]=
{
   NULL, 
   (CONST WCHAR[]) { 'U', 'k', 'r', 'a', 'i', 'n', 'i', 'a', 'n', 0 }, 
   (CONST WCHAR[]) { 'U', 'k', 'r', 'a', 'i', 'n', 'e', 0 }, 
   (CONST WCHAR[]) { 'H', ':', 'm', 'm', ':', 's', 's', 0 }, 
   (CONST WCHAR[]) { '1', '2', '5', '1', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   NULL, 
   NULL, 
   NULL, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { '0', 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { 0, 0 }, 
   (CONST WCHAR[]) { '1', 0 }, 
   NULL
};

CONST WCHAR *__LC_UKRds[]=
{
   (CONST WCHAR[]) { 'd', 'd', '.', 'M', 'M', '.', 'y', 'y', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_UKRdl[]=
{
   (CONST WCHAR[]) { 'd', ' ', 'M', 'M', 'M', 'M', ' ', 'y', 'y', 'y', 'y', '\'', ' ', 0x440, '.', '\'', 0, 0 }, 
   NULL
};

CONST WCHAR *__LC_UKRt[]=
{
   (CONST WCHAR[]) { 'H', ':', 'm', 'm', ':', 's', 's', 0, 0 }, 
   NULL
};

