#ifndef __RESOURCE__H
#define __RESOURCE__H

#define IDD_MONITOR  100

#define IDC_MONITORNAME 201
#define IDC_MONITORLIST 202
#define IDC_MONITORPROPERTIES 203
#define IDS_MONITORSETTINGSGROUP 204
#define IDS_REFRESHRATELABEL 205
#define IDC_REFRESHRATE 206

#define IDS_USEDEFFRQUENCY 101
#define IDS_FREQFMT 102

#endif /* __RESOURCE__H */
