@ stdcall gluBeginCurve(ptr)
@ stdcall gluBeginPolygon(ptr)
@ stdcall gluBeginSurface(ptr)
@ stdcall gluBeginTrim(ptr)
@ stdcall gluBuild1DMipmapLevels(long long long long long long long long ptr)
@ stdcall gluBuild1DMipmaps(long long long long long ptr)
@ stdcall gluBuild2DMipmapLevels(long long long long long long long long long ptr)
@ stdcall gluBuild2DMipmaps(long long long long long long ptr)
@ stdcall gluBuild3DMipmapLevels(long long long long long long long long long long ptr)
@ stdcall gluBuild3DMipmaps(long long long long long long long ptr)
@ stdcall gluCheckExtension(str ptr)
@ stdcall gluCylinder(ptr double double double long long)
@ stdcall gluDeleteNurbsRenderer(ptr)
@ stdcall gluDeleteQuadric(ptr)
@ stdcall gluDeleteTess(ptr)
@ stdcall gluDisk(ptr double double long long)
@ stdcall gluEndCurve(ptr)
@ stdcall gluEndPolygon(ptr)
@ stdcall gluEndSurface(ptr)
@ stdcall gluEndTrim(ptr)
@ stdcall gluErrorString(long)
@ stdcall gluGetNurbsProperty(ptr long ptr)
@ stdcall gluGetString(long)
@ stdcall gluGetTessProperty(ptr long ptr)
@ stdcall gluLoadSamplingMatrices(ptr ptr ptr ptr)
@ stdcall gluLookAt(double double double double double double double double double)
@ stdcall gluNewNurbsRenderer()
@ stdcall gluNewQuadric()
@ stdcall gluNewTess()
@ stdcall gluNextContour(ptr long)
@ stdcall gluNurbsCallback(ptr long ptr)
@ stdcall gluNurbsCallbackData(ptr ptr)
@ stdcall gluNurbsCallbackDataEXT(ptr ptr)
@ stdcall gluNurbsCurve(ptr long ptr long ptr long long)
@ stdcall gluNurbsProperty(ptr long long)
@ stdcall gluNurbsSurface(ptr long ptr long ptr long long ptr long long long)
@ stdcall gluOrtho2D(double double double double)
@ stdcall gluPartialDisk(ptr double double long long double double)
@ stdcall gluPerspective(double double double double)
@ stdcall gluPickMatrix(double double double double ptr)
@ stdcall gluProject(double double double ptr ptr ptr ptr ptr ptr)
@ stdcall gluPwlCurve(ptr long ptr long long)
@ stdcall gluQuadricCallback(ptr long ptr)
@ stdcall gluQuadricDrawStyle(ptr long)
@ stdcall gluQuadricNormals(ptr long)
@ stdcall gluQuadricOrientation(ptr long)
@ stdcall gluQuadricTexture(ptr long)
@ stdcall gluScaleImage(long long long long ptr long long long ptr)
@ stdcall gluSphere(ptr double long long)
@ stdcall gluTessBeginContour(ptr)
@ stdcall gluTessBeginPolygon(ptr ptr)
@ stdcall gluTessCallback(ptr long ptr)
@ stdcall gluTessEndContour(ptr)
@ stdcall gluTessEndPolygon(ptr)
@ stdcall gluTessNormal(ptr double double double)
@ stdcall gluTessProperty(ptr long double)
@ stdcall gluTessVertex(ptr ptr ptr)
@ stdcall gluUnProject(double double double ptr ptr ptr ptr ptr ptr)
@ stdcall gluUnProject4(double double double double ptr ptr ptr double double ptr ptr ptr ptr)
