@ stub ClassInstall32
@ stub PSetupAssociateICMProfiles
@ stub PSetupBuildDriversFromPath
@ stub PSetupCreateDrvSetupPage
@ stdcall PSetupCreateMonitorInfo(long wstr)
@ stub PSetupCreatePrinterDeviceInfoList
@ stub PSetupDestroyDriverInfo3
@ stdcall PSetupDestroyMonitorInfo(long)
@ stub PSetupDestroyPrinterDeviceInfoList
@ stub PSetupDestroySelectedDriverInfo
@ stub PSetupDriverInfoFromName
@ stdcall PSetupEnumMonitor(long long ptr ptr)
@ stub PSetupFreeDrvField
@ stub PSetupGetDriverInfForPrinter
@ stub PSetupGetDriverInfo3
@ stub PSetupGetLocalDataField
@ stub PSetupGetPathToSearch
@ stub PSetupGetSelectedDriverInfo
@ stub PSetupInstallICMProfiles
@ stub PSetupInstallMonitor
@ stub PSetupInstallPrinterDriver
@ stub PSetupInstallPrinterDriverFromTheWeb
@ stub PSetupIsCompatibleDriver
@ stub PSetupIsDriverInstalled
@ stub PSetupIsMonitorInstalled
@ stub PSetupIsOemDriver
@ stub PSetupIsTheDriverFoundInInfInstalled
@ stub PSetupKillBadUserConnections
@ stub PSetupPreSelectDriver
@ stub PSetupProcessPrinterAdded
@ stub PSetupRefreshDriverList
@ stub PSetupSelectDeviceButtons
@ stub PSetupSelectDriver
@ stub PSetupSetSelectDevTitleAndInstructions
@ stub PSetupThisPlatform
