@ stub DllRegisterServer
@ stub DllUnregisterServer
@ stub FreeCryptProvFromCert
@ stub GetCryptProvFromCert
@ stub PvkFreeCryptProv
@ stub PvkGetCryptProv
@ stub PvkPrivateKeyAcquireContext
@ stub PvkPrivateKeyAcquireContextA
@ stub PvkPrivateKeyAcquireContextFromMemory
@ stub PvkPrivateKeyAcquireContextFromMemoryA
@ stub PvkPrivateKeyLoad
@ stub PvkPrivateKeyLoadA
@ stub PvkPrivateKeyLoadFromMemory
@ stub PvkPrivateKeyLoadFromMemoryA
@ stub PvkPrivateKeyReleaseContext
@ stub PvkPrivateKeyReleaseContextA
@ stub PvkPrivateKeySave
@ stub PvkPrivateKeySaveA
@ stub PvkPrivateKeySaveToMemory
@ stub PvkPrivateKeySaveToMemoryA
@ stub SignError
@ stub SignerAddTimeStampResponse
@ stub SignerAddTimeStampResponseEx
@ stub SignerCreateTimeStampRequest
@ stub SignerFreeSignerContext
@ stub SignerSign
@ stub SignerSignEx
@ stub SignerTimeStamp
@ stub SignerTimeStampEx
@ stub SpcGetCertFromKey
