------------ Testing for1 ------------
--- plain FOR with multiple lines
A
B
C
------------ Testing for2 ------------
--- plain FOR with lines and spaces
D
E
F
------------ Testing for3 ------------
--- plain FOR with multiple lines and commas
G
H
I
------------ Testing for4 ------------
--- plain FOR with multiple lines and %I
%I
%I
%I
------------ Testing for5 ------------
--- plain FOR with multiple lines and %j
%j
%j
%j
------------ Testing Amp-Amp ---------
--- test for something that is TRUE
TRUE Amp-Amp
------------ Testing Amp-Amp ---------
--- test for something that is FALSE
------------ Testing Pipe-Pipe -------
--- test for something that is TRUE
------------ Testing Pipe-Pipe -------
--- test for something that is FALSE
FALSE Pipe-Pipe
------------ End of Testing ------------
--- Testing ends here
