------------ Testing FOR loop ------------
--- Multiple lines
A
B
C
--- Lines and spaces
D
E
F
--- Multiple lines and commas
G
H
I
--- Multiple lines and %I
%I
%I
%I
--- Multiple lines and %j
%j
%j
%j
---------- Testing AND operator ----------
TRUE AND condition
---------- Testing OR operator -----------
FALSE OR condition
---------- Testing CMD exit codes and errorlevels ----------
--- CMD /C Direct EXIT call
OK
OK
--- CMD /C Direct EXIT /B call
OK
OK
--- CMD /C Non-existing command
OK
OK
OK
OK
--- CMD /C RMDIR (no ERRORLEVEL set)
OK
OK
OK
OK
--- CMD /C DIR (sets ERRORLEVEL) - With failure
OK
OK
OK
OK
OK
OK
OK
OK
--- CMD /C DIR (sets ERRORLEVEL) - With success
OK
OK
OK
OK
OK
OK
--- CALL Batch Non-existing command
OK
OK
--- CALL Batch RMDIR (no ERRORLEVEL set)
OK
OK
--- CALL Batch RMDIR with || (sets ERRORLEVEL)
OK
OK
OK
OK
--- CALL Batch DIR (sets ERRORLEVEL) - With failure
OK
OK
OK
OK
OK
OK
OK
OK
--- CALL Batch DIR (sets ERRORLEVEL) - With success
OK
OK
OK
OK
OK
OK
OK
OK
--------- Finished  --------------
