/*
 * DHCP Client service interface definition
 */

#include <ms-dtyp.idl>

typedef [handle] wchar_t *PDHCP_SERVER_NAME;

cpp_quote("#ifndef _DHCPCSDK_")
typedef struct _DHCPCAPI_CLASSID
{
    ULONG  Flags;
#if defined(__midl) || defined(__WIDL__)
    [size_is(nBytesData), unique] LPBYTE Data;
#else
    LPBYTE Data;
#endif
    ULONG  nBytesData;
} DHCPCAPI_CLASSID, *PDHCPCAPI_CLASSID, *LPDHCPCAPI_CLASSID;
cpp_quote("#endif")

[
    uuid(4D5839D6-01BC-559C-B2EC-7DF12EC1B7E6),
    version(0.0),
    pointer_default(unique),
#ifdef __midl
    ms_union,
#endif
    endpoint("ncacn_np:[\\pipe\\dhcpcsvc]")
#ifndef __midl
    ,explicit_handle
#endif
]
interface dhcpcsvc
{
    /* Function 0 */
    DWORD
    __stdcall
    EnableDhcp(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName,
        [in] BOOL Enable);

    /* Function 1 */
    DWORD
    __stdcall
    AcquireParameters(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName);

    /* Function 2 */
    DWORD
    __stdcall
    AcquireParametersByBroadcast(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName);

    /* Function 3 */
    DWORD
    __stdcall
    ReleaseParameters(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName);

    /* Function 4 */
    DWORD
    __stdcall
    FallbackRefreshParams(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName);

    /* Function 5 */
    DWORD
    __stdcall
    StaticRefreshParams(
        [in, string, unique] PDHCP_SERVER_NAME ServerName,
        [in] DWORD AdapterIndex,
        [in] DWORD Address,
        [in] DWORD Netmask);

    /* Function 6 */
    DWORD
    __stdcall
    RemoveDNSRegistrations(
        [in, string, unique] PDHCP_SERVER_NAME ServerName);

    /* Function 7 */
    DWORD
    __stdcall
    RequestParams(
        [in, unique, string] PDHCP_SERVER_NAME ServerName,
        [in, string] LPWSTR AdapterName,
        [in, unique] DHCPCAPI_CLASSID *ClassId,
        [in] DWORD Unknown4,
        [in] DWORD Unknown5,
        [in] DWORD Unknown6);
}
