/*
 * WLAN Service interface definition
 */

#include <ms-dtyp.idl>
#include <wlanapi.h>

typedef [context_handle] PVOID WLANSVC_RPC_HANDLE;
typedef WLANSVC_RPC_HANDLE *LPWLANSVC_RPC_HANDLE;
typedef [handle, string] LPWSTR WLANSVC_HANDLE;

/* FIXME */
typedef struct struct_C {
    ULONGLONG elem_1;
    ULONGLONG elem_2;
    GUID elem_3;
    GUID elem_4;
    DWORD elem_5;
    GUID elem_6;
    DWORD elem_7;
    DWORD elem_8;
    ULONGLONG elem_9;
    [size_is(elem_7)] BYTE elem_10[];
} struct_C ;

typedef struct struct_D {
    GUID elem_1;
    GUID elem_2;
    DWORD elem_3;
    ULONGLONG elem_4;
    [size_is(elem_3)] BYTE elem_5[];
} struct_D ;

typedef struct struct_E {
    /* enum16 */ short elem_1;
    DWORD elem_2;
    WCHAR elem_3[256];
    WCHAR elem_4[1024];
} struct_E ;

[
    uuid(266f33b4-c7c1-4bd1-8f52-ddb8f2214ea9),
    version(1.0),
    pointer_default(unique)
#ifndef __midl
    ,explicit_handle
#endif    
]
 
interface wlansvc_interface
{
    /* Function: 0x00 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcOpenHandle(
#else
    DWORD  _RpcOpenHandle(
#endif
        [in] WLANSVC_HANDLE szMachineName,
        [in] DWORD dwClientVersion,
        [out] DWORD* pdwNegotiatedVersion,
        [out] WLANSVC_RPC_HANDLE *phClientHandle);

    /* Function: 0x01 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcCloseHandle(
#else
    DWORD _RpcCloseHandle(
#endif
        [in, out] WLANSVC_RPC_HANDLE *phClientHandle);

    /* Function: 0x02 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcEnumInterfaces(
#else
    DWORD _RpcEnumInterfaces(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [out, ref] PWLAN_INTERFACE_INFO_LIST *ppInterfaceList);

    /* Function: 0x03 */ 
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetAutoConfigParameter(
#else
    DWORD _RpcSetAutoConfigParameter(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] /* enum32 */ long OpCode,
        [in] DWORD dwDataSize,
        [in][size_is(dwDataSize)] LPBYTE pData);

    /* Function: 0x04 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcQueryAutoConfigParameter(
#else
    DWORD _RpcQueryAutoConfigParameter(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] /* enum32 */ DWORD OpCode,
        [in, out] LPDWORD pdwDataSize,
        [out][ref][size_is(*pdwDataSize)] char ** ppData,
        [out] /* enum32 */ DWORD * pWlanOpcodeValueType);

    /* Function: 0x05 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetInterfaceCapability(
#else
    DWORD _RpcGetInterfaceCapability(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [out, ref] PWLAN_INTERFACE_CAPABILITY *ppCapability);

    /* Function: 0x06 */
#ifdef __REACTOS__
     DWORD RPC_ENTRY _RpcSetInterface(
#else
     DWORD _RpcSetInterface(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] /* enum32 */ DWORD OpCode,
        [in] DWORD dwDataSize,
        [in, size_is(dwDataSize)] LPBYTE pData);

     /* Function: 0x07 */
#ifdef __REACTOS__
     DWORD RPC_ENTRY _RpcQueryInterface(
#else
     DWORD _RpcQueryInterface(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] /* enum32 */ long OpCode,
        [in, out] LPDWORD pdwDataSize,
        [out][ref][size_is(*pdwDataSize)] LPBYTE* ppData,
        [out] /* enum32 */ LPDWORD pWlanOpcodeValueType);

    /* Function: 0x08 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcIhvControl(
#else
    DWORD _RpcIhvControl(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] /* enum32 */ DWORD Type,
        [in] DWORD dwInBufferSize,
        [in][size_is(dwInBufferSize)] LPBYTE pInBuffer,
        [in] DWORD dwOutBufferSize,
        [out][size_is(dwOutBufferSize), length_is(*pdwBytesReturned)] LPBYTE pOutBuffer,
        [out] LPDWORD pdwBytesReturned);

    /* Function: 0x09 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcScan(
#else
    DWORD _RpcScan(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][unique] PDOT11_SSID pDot11Ssid,
        [in][unique] PWLAN_RAW_DATA pIeData);

    /* Function: 0x0A */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetAvailableNetworkList(
#else
    DWORD _RpcGetAvailableNetworkList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] DWORD dwFlags,
        [out][ref] WLAN_AVAILABLE_NETWORK_LIST **ppAvailableNetworkList);

    /* Function: 0x0B */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetNetworkBssList(
#else
    DWORD _RpcGetNetworkBssList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][unique] PDOT11_SSID pDot11Ssid,
        [in] /* enum16 */ short dot11BssType,
        [in] DWORD bSecurityEnabled,
        [in, out] LPDWORD dwBssListSize,
        [out][ref][size_is(*dwBssListSize)] LPBYTE *ppWlanBssList);

    /* Function: 0x0C */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcConnect(
#else
    DWORD _RpcConnect(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] const PWLAN_CONNECTION_PARAMETERS* pConnectionParameters);

    /* Function: 0x0D */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcDisconnect(
#else
    DWORD _RpcDisconnect(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGUID);

    /* Function: 0x0E */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcRegisterNotification(
#else
    DWORD _RpcRegisterNotification(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] DWORD arg_2,
        [out] LPDWORD pdwPrevNotifSource);

    /* Function: 0x0F */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcAsyncGetNotification(
#else
    DWORD _RpcAsyncGetNotification(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [out][ref] PWLAN_NOTIFICATION_DATA *NotificationData);

    /* Function: 0x10 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetProfileEapUserData(
#else
    DWORD _RpcSetProfileEapUserData(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [in] EAP_METHOD_TYPE MethodType,
        [in] DWORD dwFlags,
        [in] DWORD dwEapUserDataSize,
        [in][size_is(dwEapUserDataSize)] LPBYTE pbEapUserData);

    /* Function: 0x11 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetProfile(
#else
    DWORD _RpcSetProfile(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] DWORD dwFlags,
        [in][string] wchar_t * strProfileXml,
        [in][unique][string] wchar_t * strAllUserProfileSecurity,
        [in] BOOL bOverwrite,
        [out] LPDWORD pdwReasonCode);

    /* Function: 0x12 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetProfile(
#else
    DWORD _RpcGetProfile(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [out][ref][string] wchar_t ** pstrProfileXml,
        [out] LPDWORD pdwFlags,
        [in, out][unique] LPDWORD pdwGrantedAccess);

    /* Function: 0x13 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcDeleteProfile(
#else
    DWORD _RpcDeleteProfile(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] const wchar_t * strProfileName);

    /* Function: 0x14 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcRenameProfile(
#else
    DWORD _RpcRenameProfile(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] const wchar_t * strOldProfileName,
        [in][string] const wchar_t * strNewProfileName);

    /* Function: 0x15 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetProfileList(
#else
    DWORD _RpcSetProfileList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in] DWORD dwItems,
        [in] /* [string] */ [size_is(dwItems)] /* wchar_t */ BYTE ** strProfileNames); /* FIXME */

    /* Function: 0x16 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetProfileList(
#else
    DWORD _RpcGetProfileList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [out][ref] PWLAN_PROFILE_INFO_LIST *ppProfileList);

    /* Function: 0x17 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetProfilePosition(
#else
    DWORD _RpcSetProfilePosition(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [in] DWORD dwPosition);

    /* Function: 0x18 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetProfileCustomUserData(
#else
    DWORD _RpcSetProfileCustomUserData(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [in] DWORD dwDataSize,
        [in][unique][size_is(dwDataSize)] LPBYTE pData);

    /* Function: 0x19 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetProfileCustomUserData(
#else
    DWORD _RpcGetProfileCustomUserData(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [in, out] LPDWORD dwDataSize,
        [out][ref][size_is(*dwDataSize)] LPBYTE *pData);

    /* Function: 0x1A */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetFilterList(
#else
    DWORD _RpcSetFilterList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] /* enum16 */ short wlanFilterListType,
        [in][unique] PDOT11_NETWORK_LIST pNetworkList);

    /* Function: 0x1B */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetFilterList(
#else
    DWORD _RpcGetFilterList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] /* enum16 */ short wlanFilterListType,
        [out][ref] PDOT11_NETWORK_LIST *pNetworkList);

    /* Function: 0x1C */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetPsdIEDataList(
#else
    DWORD _RpcSetPsdIEDataList(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in][unique][string] wchar_t * strFormat,
        [in] DWORD dwDataListSize,
        [in][unique][size_is(dwDataListSize)] LPBYTE pPsdIEDataList);

    /* Function: 0x1D */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSaveTemporaryProfile(
#else
    DWORD _RpcSaveTemporaryProfile(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * strProfileName,
        [in][unique][string] wchar_t * strAllUserProfileSecurity,
        [in] DWORD dwFlags,
        [in] BOOL bOverWrite);

    /* Function: 0x1E */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcIsUIRequestPending(
#else
    DWORD _RpcIsUIRequestPending(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] const GUID* pInterfaceGuid,
        [in] struct_C * arg_3,
        [out] LPDWORD arg_4);

    /* Function: 0x1F */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetUIForwardingNetworkList(
#else
    DWORD _RpcSetUIForwardingNetworkList(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in][size_is(dwSize)] GUID* arg_2,
        [in] DWORD dwSize,
        [out] GUID* arg_4);

    /* Function: 0x20 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcIsNetworkSuppressed(
#else
    DWORD _RpcIsNetworkSuppressed(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] DWORD arg_2,
        [in] const GUID* pInterfaceGuid,
        [out] LPDWORD arg_4);

    /* Function: 0x21 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcRemoveUIForwardingNetworkList(
#else
    DWORD _RpcRemoveUIForwardingNetworkList(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] const GUID* pInterfaceGuid);

    /* Function: 0x22 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcQueryExtUIRequest(
#else
    DWORD _RpcQueryExtUIRequest(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] GUID* arg_2,
        [in] GUID* arg_3,
        [in] /* enum16 */ short arg_4,
        [out] GUID* pInterfaceGuid,
        [out][ref] struct_C ** arg_6);

    /* Function: 0x23 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcUIResponse(
#else
    DWORD _RpcUIResponse(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] struct_C * arg_2,
        [in] struct_D * arg_3);

    /* Function: 0x24 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetProfileKeyInfo(
#else
    DWORD _RpcGetProfileKeyInfo(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] DWORD arg_2,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * arg_4,
        [in] DWORD arg_5,
        [out] LPDWORD arg_6,
        [in, out][unique][size_is(arg_5)] char * arg_7,
        [out] LPDWORD arg_8);

    /* Function: 0x25 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcAsyncDoPlap(
#else
    DWORD _RpcAsyncDoPlap(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] const GUID* pInterfaceGuid,
        [in][string] wchar_t * arg_3,
        [in] DWORD dwSize,
        [in][size_is(dwSize)] struct_E arg_5[]);

    /* Function: 0x26 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcQueryPlapCredentials(
#else
    DWORD _RpcQueryPlapCredentials(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in, out] LPDWORD dwSize,
        [out][ref][size_is(*dwSize)] struct_E ** arg_3,
        [out][ref][string] wchar_t ** arg_4,
        [out] GUID* pInterfaceGuid,
        [out] LPDWORD arg_6,
        [out] LPDWORD arg_7,
        [out] LPDWORD arg_8,
        [out] LPDWORD arg_9);

    /* Function: 0x27 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcCancelPlap(
#else
    DWORD _RpcCancelPlap(
#endif
        [in] WLANSVC_HANDLE arg_1,
        [in] const GUID* pInterfaceGuid);

    /* Function: 0x28 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcSetSecuritySettings(
#else
    DWORD _RpcSetSecuritySettings(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] WLAN_SECURABLE_OBJECT SecurableObject,
        [in][string] const wchar_t * strModifiedSDDL);

    /* Function: 0x29 */
#ifdef __REACTOS__
    DWORD RPC_ENTRY _RpcGetSecuritySettings(
#else
    DWORD _RpcGetSecuritySettings(
#endif
        [in] WLANSVC_RPC_HANDLE hClientHandle,
        [in] WLAN_SECURABLE_OBJECT SecurableObject,
        [out] WLAN_OPCODE_VALUE_TYPE *pValueType,
        [out][ref][string] wchar_t ** pstrCurrentSDDL,
        [out] LPDWORD pdwGrantedAccess);

}
