@ stdcall DrvCopyContext(ptr ptr long)
@ stdcall DrvCreateContext(ptr)
@ stdcall DrvCreateLayerContext(ptr long)
@ stdcall DrvDeleteContext(ptr)
@ stdcall DrvDescribeLayerPlane(ptr long long long ptr)
@ stdcall DrvDescribePixelFormat(ptr long long ptr)
@ stdcall DrvGetLayerPaletteEntries(ptr long long long ptr)
@ stdcall DrvGetProcAddress(str)
@ stdcall DrvRealizeLayerPalette(ptr long long)
@ stdcall DrvReleaseContext(ptr)
@ stdcall DrvSetCallbackProcs(long ptr)
@ stdcall DrvSetContext(ptr ptr ptr)
@ stdcall DrvSetLayerPaletteEntries(ptr long long long ptr)
@ stdcall DrvSetPixelFormat(ptr long)
@ stdcall DrvShareLists(ptr ptr)
@ stdcall DrvSwapBuffers(ptr)
@ stdcall DrvSwapLayerBuffers(ptr long)
@ stdcall DrvValidateVersion(long)
