; Old KD
@ stdcall KdPortGetByte(ptr)
@ stdcall KdPortGetByteEx(ptr ptr)
@ stdcall KdPortInitialize(ptr long long)
@ stdcall KdPortInitializeEx(ptr long long)
@ stdcall KdPortPollByte(ptr)
@ stdcall KdPortPollByteEx(ptr ptr)
@ stdcall KdPortPutByte(long)
@ stdcall KdPortPutByteEx(ptr long)
@ stdcall KdPortRestore()
@ stdcall KdPortSave()
@ stdcall KdPortDisableInterrupts()
@ stdcall KdPortEnableInterrupts()

; New KD
@ stdcall KdDebuggerInitialize0(ptr)
@ stdcall KdDebuggerInitialize1(ptr)
@ stdcall KdSave(long)
@ stdcall KdRestore(long)
@ stdcall KdReceivePacket(long ptr ptr ptr ptr)
@ stdcall KdSendPacket(long ptr ptr ptr)
