# $Id:  $

PATH_TO_TOP = ../../..

TARGET_TYPE = export_driver

TARGET_NAME = usbd

TARGET_OBJECTS = usbd.o

TARGET_GCCLIBS = gcc

TARGET_CFLAGS = -D__USE_W32API -O3 -s

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
