//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by inetui.rc
//
#define IDS_SECERT_SUBJECT              1
#define ISNO                            2
#define IDS_SECERT_ISSUER               2
#define IDS_SECERT_EFFECTIVE            3
#define IDCANCEL2                       3
#define IDS_SECERT_EXPIRATION           4
#define IDCANCEL3                       4
#define IDS_SECERT_PROTOCOL             5
#define IDS_SECERT_SIGALG               6
#define IDS_SECERT_ENCRALG              7
#define IDS_SECERT_ENCRSTRENGTH         8
#define IDS_LW95_ENTERAUTHINFO          9
#define IDS_SECERT_CERTINFO             10
#define IDS_SECERT_STRENGTH_HIGH        11
#define IDS_SECERT_STRENGTH_MEDIUM      12
#define IDS_SECERT_STRENGTH_LOW         13
#define IDS_CERT_SUBJECT                14
#define IDS_CERT_ISSUER                 15
#define IDS_CERT_EFFECTIVE_DATE         16
#define IDS_CERT_EXPIRATION_DATE        17
#define IDS_CERT_PROTOCOL               18
#define IDS_CERT_SIG_ALG                19
#define IDS_CERT_ENCRYPT_ALG            20
#define IDS_CERT_PRIV_STRENTH           21
#define IDS_CERT_USAGE                  21
#define IDS_COMMENT_EXPIRES             22
#define IDS_COMMENT_NOT_VALID           23
#define IDS_COMMENT_BAD_CN              24
#define IDS_COMMENT_BAD_CA              25
#define IDS_CERT_COMMENT                26
#define IDS_COMMENT_BAD_SIGNATURE       27
#define IDS_FTP_ROOT                    28
#define IDS_FTP_DIR                     29
#define IDS_FTP_UPLEVEL                 30
#define IDS_GOPHER_ROOT                 31
#define IDS_GOPHER_DIR                  32
#define IDS_GOPHER_INDEX                33
#define IDS_GOPHER_CSO                  34
#define IDS_TAG_DIRECTORY               35
#define IDS_TAG_SEARCH                  36
#define IDS_CACHE_DEFAULT_SUBDIR        37
#define IDS_COOKIES_DEFAULT_SUBDIR      38
#define IDS_HISTORY_DEFAULT_SUBDIR      39
#define IDS_COMMENT_REVOKED             40
#define IDS_CERT_FINGERPRINT            41
#define IDD_CERTPICKER                  101
#define IDD_INVALID_CERT                102
#define IDD_INVALID_CA                  102
#define IDD_VIEW_CERT                   103
#define IDD_CONFIRM_COOKIE              104
#define IDI_COOKIE_ICON                 105
#define IDD_FAILED_DOWNLOAD             106
#define IDD_SCRIPT_ERROR                107
#define IDD_AUTODIAL_SELECT             108
#define IDD_CONNECT_TO                  109
#define IDD_GOONLINE                    110
#define IDC_GOONLINE_TOPMESSAGE         111
#define IDS_GOONLINE_REFRESH_CAPTION    112
#define IDS_GOONLINE_REFRESH_TOPMESSAGE 113
#define IDI_DIAL                        114
#define IDD_PROGRESS                    115
#define IDI_SECURITY1                   116
#define IDD_HTTP_POST_REDIRECT          117
#define IDI_SECURITY2                   118
#define IDI_SECURITY3                   119
#define IDC_LINKFROMDLG                 120
#define IDD_CERT_EXPIRED                121
#define IDB_DIAL                        122
#define IDD_AUTHENTICATION              124
#define IDD_NTLM_AUTH                   124
#define IDD_SEC_CERT_ERRORS             125
#define IDB_CHECK                       126
#define IDD_REALM_AUTH                  126
#define IDB_X                           127
#define IDC_CERT_TRUST_TEXT             128
#define IDI_SECURITY4                   128
#define IDC_CERT_DATE_TEXT              129
#define IDC_CERT_NAME_TEXT              130
#define IDC_CERT_TRUST_ICON             131
#define IDC_CERT_DATE_ICON              132
#define IDC_CERT_NAME_ICON              133
#define IDS_CERT_TRUST                  134
#define IDS_CERT_DATE                   135
#define IDS_CERT_NAME                   136
#define IDI_WARN                        137
#define IDI_SUCCESS                     138
#define IDS_SECURITY_CAPTION            139
#define IDS_CERT_REVOKED                140
#define IDD_REVOCATION_PROBLEM          141
#define IDI_OFFLINE                     142
#define IDI_CONNECT                     143
#define IDC_DONT_WANT_WARNING           1001
#define IDC_CERTPICKLIST                1002
#define IDC_FIELDLIST                   1005
#define IDC_CERT_SUBJECT                1006
#define IDC_CERT_ISSUER                 1007
#define IDC_CERT_EXPIRES                1008
#define IDC_CERT_STATUS                 1009
#define IDC_DELETE_CERT                 1010
#define IDC_EDIT1                       1010
#define IDC_COOKIE_DATA                 1010
#define IDC_USER_NAME                   1010
#define IDC_DOMAIN_FIELD                1010
#define IDC_DETAILSLIST                 1011
#define IDC_COOKIE_DETAILS              1011
#define IDC_EDIT2                       1012
#define IDC_COOKIE_HELP                 1012
#define IDC_DETAILS_LIST                1012
#define IDC_COOKIE_ALLOW_ALL            1013
#define IDC_COOKIE_NAME                 1014
#define IDC_COOKIE_DOMAIN               1016
#define IDC_COOKIE_PATH                 1017
#define IDC_COOKIE_EXPIRES              1018
#define IDC_COOKIE_SECURE               1019
#define IDC_COOKIE_SERVER               1021
#define IDC_COOKIE_ICON                 1022
#define IDC_COOKIE_INFO                 1023
#define IDC_SAVE_PASSWORD               1024
#define IDC_CONNECT_TO                  1025
#define IDC_CONN_TXT                    1025
#define ID_CONNECT                      1026
#define IDC_URL                         1027
#define ID_STAYOFFLINE                  1028
#define IDC_UNATTENDED                  1029
#define IDC_PROGRESS                    1030
#define IDC_STATUS                      1031
#define IDC_ZONEALERTTEXT               1032
#define IDC_BUTTON_EXPORT               1034
#define IDC_BUTTON_IMPORT               1035
#define IDC_AUTOCONNECT                 1036
#define IDC_BMP                         1039
#define IDC_AVI                         1040
#define IDC_SETTINGS                    1041
#define IDC_PROXY_OR_SERVER             1041
#define IDC_SERVER_OR_PROXY             1041
#define IDC_SITE_OR_FIREWALL            1042
#define IDC_DOMAIN_OR_REALM             1043
#define IDC_DOMAIN                      1043
#define IDC_DOMAIN_TAG                  1043
#define IDC_REALM_FIELD                 1044
#define IDC_REALM                       1045
#define IDC_REALM_TAG                   1045
#define IDC_USERNAME_TAG                1046
#define IDC_PASSWORD_TAG                1047
#define IDC_PERM_OR_SESS_COOKIE         1048
#define IDC_COOKIE_TYPE                 1048
#define IDC_CONN_LIST                   1048
#define IDC_NAME_TXT                    1050
#define IDC_PASSWORD_TXT                1051
#define IDS_TRY_AGAIN                   1053
#define IDD_WARN_ON_POST                1175
#define IDD_HTTP_TO_HTTPS_ZONE_CROSSING 1177
#define IDD_HTTPS_TO_HTTP_ZONE_CROSSING 1178
#define IDD_MIXED_SECURITY              1179
#define ID_TELL_ME_ABOUT_SECURITY       1181
#define ID_TELL_ME_ABOUT_SECURITY2      1182
#define IDD_BAD_CN                      1188
#define IDD_BASIC_AUTHENTICATION        1216
#define IDC_REALM_NAME                  1217
#define IDC_USERNAME                    1218
#define IDC_PASSWORD                    1219
#define IDD_SHOW_CERT                   1301
#define IDD_CERTPICKER1                 1302
#define IDD_CERTVIEWER                  1302
#define IDD_HTTPS_POST_REDIRECT         1303
#define IDD_HTTPS_TO_HTTP_SUBMIT_REDIRECT 1303
#define ID_CERT_EDIT                    1318
#define ID_SHOW_CERTIFICATE             1630
#define ID_SHOW_CERTIFICATE2            1631
#define ID_CERT_MORE_INFO               1632
#define IDS_SETTING_COOKIE              1800
#define IDS_SETTING_COOKIE_TITLE        1801
#define IDS_YES                         1802
#define IDS_NO                          1803
#define IDS_COOKIE_EXPIRES_ENDSESSION   1804
#define IDS_PROTOCOL_UNKNOWN            1806
#define IDS_PROTOCOL_SSL2               1807
#define IDS_PROTOCOL_SSL3               1808
#define IDS_PROTOCOL_PCT1               1809
#define IDS_PROTOCOL_TLS1               1810
#define IDS_CIPHER_UNKNOWN              1811
#define IDS_ALG_MD2                     1812
#define IDS_ALG_MD4                     1813
#define IDS_ALG_MD5                     1814
#define IDS_ALG_SHA                     1815
#define IDS_ALG_MAC                     1816
#define IDS_ALG_HMAC                    1817
#define IDS_ALG_RSA_SIGN                1818
#define IDS_ALG_DSS_SIGN                1819
#define IDS_ALG_RSA_KEYX                1820
#define IDS_ALG_DES                     1821
#define IDS_ALG_3DES_112                1822
#define IDS_ALG_3DES                    1823
#define IDS_ALG_RC2                     1824
#define IDS_ALG_RC4                     1825
#define IDS_ALG_RC5                     1826
#define IDS_ALG_SEAL                    1827
#define IDS_ALG_DH_SF                   1828
#define IDS_ALG_DH_EPHEM                1829
#define IDS_ALG_KEA_KEYX                1830
#define IDS_ALG_SKIPJACK                1831
#define IDS_ALG_TEK                     1832
#define IDS_STRING_CIPHMSG              1833
#define IDS_STRING_HASHMSG              1834
#define IDS_STRING_EXCHMSG              1835
#define IDS_HASH_UNKNOWN                1836
#define IDS_EXCH_UNKNOWN                1837
#define IDS_CERT_HASH_ALG               1838
#define IDS_CERT_EXCH_ALG               1839
#define IDS_EXPORTCERT_ERRORTEXT        1900
#define IDS_EXPORTCERT_ERRORTITLE       1901
#define IDS_IMPORTCERT_ERRORTEXT        1902
#define IDS_IMPORTCERT_ERRORTITLE       1903
#define IDS_RNADLL_FILENAME             2000
#define IDS_CONNECTED_TO                2001
#define IDS_INETCFG_FILENAME            2002
#define IDS_REDIAL_WAIT                 2003
#define IDS_REDIAL_ATTEMPT              2004
#define IDS_DIALING                     2005
#define IDS_AUTHENTICATE                2006
#define IDS_CANCEL                      2007
#define IDS_WORK_OFFLINE                2008
#define IDS_CONNECTED                   2009
#define IDS_DISCONNECTED                2010
#define IDS_NOCERT_TITLE                2011
#define IDS_NOCERT                      2012
#define IDS_CONNECT_TO                  2013
#define IDS_PPPRANDOMFAILURE            2014
#define IDS_MEDIAINIERROR               2015
#define IDS_PHONEBUSY                   2016
#define IDS_NOANSWER                    2017
#define IDS_NODIALTONE                  2019
#define IDS_NODEVICE                    2020
#define IDS_TCPINSTALLERROR             2021
#define IDS_AUTHFAILURE                 2022
#define IDS_DOMAIN                      2023
#define IDS_REALM                       2024
#define IDS_SITE                        2025
#define IDS_FIREWALL                    2026
#define IDD_CHOOSE_CONNECTION           4001
#define IDD_NEW                         4002
#define IDD_DISABLEAUTODIAL             4003
#define IDD_TX_CHOOSE_CONNECTION        4004
#define IDD_EDIT                        4005
#define IDD_ZONE_ALERT                  4006
#define IDD_INVALID_CERT_CONTENTS       4007
#define IDD_INSERT_CDROM                4008
#define IDC_CD_NAME                     4009
#define IDC_USE_CDROM                   4011
#define IDC_CONNECT_TO_INTERNET         4012
#define IDS_LAN_CONNECTION              4013
#define IDD_GOOFFLINE                   4014
#define IDS_RASPHONEBOOK                4015
#define IDS_CONFIRM_PERM_COOKIE         4016
#define IDS_PERM_COOKIE                 4016
#define IDS_CONFIRM_SESS_COOKIE         4017
#define IDS_SESS_COOKIE                 4017
#define IDS_PROXY_TITLE                 4018
#define IDS_PROXY_MSG                   4019
#define IDS_CACHE_DEFAULT_SUBDIR_UNIX   4020

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
