[
uuid(?),
version(1.0),
pointer_default(?)
]
interface SCM
{
  handle_t SvcOpenSCManagerW([in, string] wchar_t* lpMachineName,
			     [in, string] wchar_t* lpDatabaseName,
			     [in] unsigned int dwDesiredAccess);
  handle_t SvcOpenSCManagerA([in, string] char* lpMachineName,
			     [in, string] char* lpDatabaseName,
			     [in] unsigned int dwDesiredAccess);
  bool SvcClose([in] handle_t hSCObject);
}
  
