# $Id: Makefile,v 1.2 2003/11/14 17:13:24 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = bootvid

TARGET_OBJECTS = bootvid.o pixelsup_i386.o

TARGET_CFLAGS = -Wall -Werror

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
