/* Do not edit - Machine generated */
#ifndef _INC_REACTOS_BUILDNO
#define _INC_REACTOS_BUILDNO
#define KERNEL_VERSION_BUILD	@KERNEL_VERSION_BUILD@
#define KERNEL_VERSION_BUILD_HEX	0x@KERNEL_VERSION_BUILD_HEX@
#define KERNEL_VERSION_BUILD_STR	"@KERNEL_VERSION_BUILD@-@REVISION@"
#define KERNEL_VERSION_BUILD_RC	"@KERNEL_VERSION_BUILD@-@REVISION@\0"
#define KERNEL_RELEASE_RC	"@KERNEL_VERSION@\0"
#define KERNEL_RELEASE_STR	"@KERNEL_VERSION@"
#define KERNEL_VERSION_RC	"@KERNEL_VERSION@\0"
#define KERNEL_VERSION_STR	"@KERNEL_VERSION@"
#define REACTOS_DLL_VERSION_MAJOR	@REACTOS_DLL_VERSION_MAJOR@
#define REACTOS_DLL_RELEASE_RC	"@DLL_VERSION_STR@\0"
#define REACTOS_DLL_RELEASE_STR	"@DLL_VERSION_STR@"
#define REACTOS_DLL_VERSION_RC	"@DLL_VERSION_STR@\0"
#define REACTOS_DLL_VERSION_STR	"@DLL_VERSION_STR@"
#endif
/* EOF */
