@ stub TcAddClassMap
@ stub TcAddFilter
@ stub TcAddFlow
@ stub TcCloseInterface
@ stub TcDeleteFilter
@ stub TcDeleteFlow
@ stdcall TcDeregisterClient(ptr)
@ stub TcEnumerateFlows
@ stub TcEnumerateInterfaces
@ stub TcGetFlowNameA
@ stub TcGetFlowNameW
@ stub TcModifyFlow
@ stub TcOpenInterfaceA
@ stub TcOpenInterfaceW
@ stub TcQueryFlowA
@ stub TcQueryFlowW
@ stub TcQueryInterface
@ stdcall TcRegisterClient(long ptr ptr ptr)
@ stub TcSetFlowA
@ stub TcSetFlowW
@ stub TcSetInterface
