# This makefile has been generated automatically by mwgenmakeC for
# compiling MFC application.

CUSTOM_RULES = /vobs/ie4/wininet.template

SOURCES =  \
	cachapia.cxx \
	cachapiw.cxx \
	cacheapi.cxx \
	cachecfg.cxx \
	urlcache.cxx \
	contain.cxx \
	instcon.cxx \
	downsize.cxx \
	filemap.cxx \
	hashutil.cxx \
	hndlmgr.cxx \
	initglob.cxx \
	cookies.cxx \
	conlist.cxx \
	conmgr.cxx \
    filemgr.cxx \
	reg.cxx \
	util.cxx\
    group.cxx \
        401imprt.cxx \
	debug.c \
    flock.cxx \
    unxcache.cxx \


INCLUDES += \
          -I.\
          -I${WININET_DIR}/inc\
          -I${WININET_DIR}/inc/private\
          -I${WININET_DIR}inetui

DEFINES += -D_URLCACHEAPI_ -D_WINX32_

WLIB = urlcache
LIB  = lib${WLIB}.a

CPP_OBJS := ${SOURCES:%.C=%.o}
CPP_OBJS := ${CPP_OBJS:%.cpp=%.o}
CPP_OBJS := ${CPP_OBJS:%.cxx=%.o}
LIBOBJS = ${CPP_OBJS:%.c=%.o}
SRCS=${SOURCES}

## you may define the following variables
## RUN.dir      : the directory where you want the executables to go
## APP_CFLAGS   : additional compilation flags for C compiler
## APP_CCPPFLAGS: additional compilation flags for C++ compiler
## APP_DLLFLAGS : additional link flags
## MWINIT_DEFINES : list of -D<symbols> used to initialize
##        Mainwin in certain specific ways 
## MWLOCALES: list of country codes corresponding to the
##        resources you have prepared in the res subdirectory
## 

NO_UNICODE = 1
APP_CFLAGS += ${WININET_CFLAGS} ${INCLUDES} ${DEFINES}
__cplusplus = true


include $(MWHOME)/make.rules.simple
