
/***** Internal Error codes *****/

#define SWCHERROR_SUCCESS					ERROR_SUCCESS
#define SWCHERROR_INVALID_HWND			ERROR_INVALID_WINDOW_HANDLE
#define SWCHERROR_INVALID_HSWITCHPORT	ERROR_INVALID_HANDLE
#define SWCHERROR_INVALID_HSD				ERROR_INVALID_HANDLE
#define SWCHERROR_MAXIMUM_PORTS			ERROR_ACCESS_DENIED
#define SWCHERROR_HWND_ALREADY_USED		ERROR_ACCESS_DENIED
#define SWCHERROR_INVALID_PARAMETER		ERROR_INVALID_PARAMETER
#define SWCHERROR_INVALID_DEVICETYPE	ERROR_INVALID_PARAMETER
#define SWCHERROR_INVALID_DEVICENUMBER	ERROR_INVALID_PARAMETER
#define SWCHERROR_INSUFFICIENT_BUFFER	ERROR_INSUFFICIENT_BUFFER
