//+-------------------------------------------------------------------------
//
//  Microsoft Windows
//
//  Copyright (C) Microsoft Corporation, 1997 - 1999
//
//  File:       resource.h
//
//--------------------------------------------------------------------------
//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cscui.rc
//
#define IDS_UNKNOWN_USER                33
#define IDS_DISKCLEAN_DISPLAY           35
#define IDS_DISKCLEAN_DESCRIPTION       36
#define IDS_ERROR                       37
#define IDS_MENU_PIN                    38
#define IDS_MENU_SYNCHRONIZE            39
#define IDS_HELP_PIN                    40
#define IDS_HELP_UPDATE_SEL             41
#define IDS_PIN_ENCRYPT_WARNING         43
#define IDS_DISKCLEAN_BTN_TEXT          44
#define IDS_APPLICATION                 45
#define IDS_DISKCLEAN_PIN_DESCRIPTION   46
#define IDS_VERSION_FORMAT              47
#define IDS_SHARE_STATUS_ONLINE         51
#define IDS_SHARE_STATUS_OFFLINE        52
#define IDS_TITLE_COL_SERVER            54
#define IDS_PIN_FILE_ERROR              96
#define IDS_FILL_SPARSE_FILES_ERROR     97
#define IDS_MERGE_SHARE_ERROR           98
#define IDS_COPY_WARNING                99
#define IDS_UNDO_SCAN                   100
#define IDS_NEW_SCAN                    101
#define IDS_DELETE_WARNING              102
#define IDS_FILE_OPEN_ERROR             103
#define IDS_SERVER_FULL_ERROR           104
#define IDS_LOCAL_DISK_FULL_ERROR       105
#define IDS_NET_ERROR                   106
#define IDS_NAME_CONFLICT_ERROR         107
#define IDS_ACCESS_ERROR                108
#define IDS_SHARE_CONNECT_ERROR         109
#define IDS_UNKNOWN_SYNC_ERROR          110
#define IDS_OPENFILE_MERGE_WARNING      111
#define IDS_STALEREASON_FIRST           112
#define IDS_STALEREASON_NOTSTALE        112
#define IDS_STALEREASON_ORPHAN          113
#define IDS_STALEREASON_SUSPECT         114
#define IDS_STALEREASON_STALE           115
#define IDS_STALEREASON_LOCALLY_MODATTR 116
#define IDS_STALEREASON_LOCALLY_MODTIME 117
#define IDS_STALEREASON_LOCALLY_MODDATA 118
#define IDS_STALEREASON_LOCALLY_CREATED 119
#define IDS_STALEREASON_SPARSE          120
#define IDS_STALEREASON_LAST            127
#define IDS_CONFIRM_UNPIN_OFFLINE       129
#define IDS_FMT_PIN_EFS_MSG             130
#define IDS_FMT_DELETE_APPLY_ALL        140
#define IDS_ERR_POLICY_NOVIEWCACHE      160
#define IDS_FMT_ERR_DELFROMCACHE        162
#define IDS_FMT_ERR_DELFROMCACHE_BUSY   163
#define IDS_FMT_CACHESIZE_DISPLAY       167
#define IDS_ORDER_BYTES                 168
#define IDS_ORDER_KB                    169
#define IDS_ORDER_MB                    170
#define IDS_ORDER_GB                    171
#define IDS_ORDER_TB                    172
#define IDS_ORDER_PB                    173
#define IDS_ORDER_EB                    174
#define IDS_CSC_CM_SHOWVIEWER           180
#define IDS_BROWSEFORSERVER             188
#define IDS_ERR_NOTSERVERNAME           189
#define IDS_OPENDETAILS                 195
#define IDS_NOTHING_TO_SYNC             196
#define IDS_CSCOPT_PROPSHEET_TITLE      202
#define IDS_TITLE_COL_ACTION            203
#define IDS_GOOFFLINE_ACTION_FIRST      204
#define IDS_GOOFFLINE_ACTION_SILENT     204
#define IDS_GOOFFLINE_ACTION_FAIL       205
#define IDS_ERR_INVALIDSERVER           207
#define IDS_ERR_GOOFFLINE_DUPACTION     209
#define IDS_ERR_GOOFFLINE_DUPACTION_NOCHG 210
#define IDS_FMT_GOOFFLINE_SERVER_POLICY 212
#define IDS_GOOFFLINE_MULTISERVER       213
#define IDS_CACHE_CORRUPT               214
#define IDS_REBOOTSYSTEM                219
#define IDS_CLOSEDETAILS                223
#define IDS_SCANNING_DOTDOTDOT          225
#define IDS_DELETING_DOTDOTDOT          226
#define IDS_FILE_PINNED                 227
#define IDS_FILE_NOTPINNED              228
#define IDS_COL_NAME                    229
#define IDS_COL_TYPE                    230
#define IDS_COL_SYNCSTATUS              231
#define IDS_COL_PINSTATUS               232
#define IDS_COL_LOCATION                233
#define IDS_COL_SIZE                    234
#define IDS_COL_DATE                    235
#define IDR_ADVOPTIONS_CONTEXTMENU      1103
#define IDI_CSCUI_ICON                  1200
#define IDI_PIN_OVERLAY                 1201
#define IDI_SHARE                       1205
#define IDI_DOCUMENT                    1208
#define IDI_NUKE                        1209
#define IDI_CSCNORMAL                   1213
#define IDI_CSCINFORMATION              1214
#define IDI_CSCWARNING                  1215
#define IDA_FILEDEL                     1218
#define IDD_CSC_OPTIONS                 1315
#define IDD_CSC_ADVOPTIONS              1323
#define IDD_CSC_ADVOPTIONS_ADD          1324
#define IDD_CSC_ADVOPTIONS_EDIT         1325
#define IDD_CONFIRM_PIN                 1328
#define IDD_OPEN_FILES_WARNING          1329
#define IDD_CONFIRM_PURGE               1330
#define IDD_FILE_CONFLICT_DELETE        1331
#define IDD_FIRSTPIN_WELCOME            1332
#define IDD_FIRSTPIN_PIN                1333
#define IDD_FIRSTPIN_OFFLINE            1334
#define IDB_FIRSTPIN_COVER              1340
#define IDD_CONFIRM_UNPIN               1341
#define IDD_CSCUI_STATUS                1342
#define IDB_FIRSTPIN_PIN                1343
#define IDB_FIRSTPIN_SYNC               1344
#define IDB_FIRSTPIN_TRAY               1346
#define IDI_SERVER                      1347
#define IDI_SERVER_OFFLINE              1348
#define IDD_CONFIRM_DELETE              1349
#define IDB_FIRSTPIN_OVERLAY            1350
#define IDD_CONFIRM_DELETEMOD           1351
#define IDD_CONFIRM_PIN_EFS             1352
#define IDD_FOLDER_CONFLICT_DELETE      1353
#define IDC_CBX_ENABLE_CSC              2033
#define IDC_RBN_FULLSYNC_AT_LOGOFF      2068
#define IDC_RBN_PARTSYNC_AT_LOGOFF      2069
#define IDC_SLIDER_CACHESIZE_PCT        2096
#define IDC_TXT_CACHESIZE_PCT           2097
#define IDC_LBL_CACHESIZE_PCT           2098
#define IDC_BTN_DELETE_CACHE            2101
#define IDC_BTN_VIEW_CACHE              2102
#define IDC_BTN_EDIT_CUSTGOOFFLINE      2103
#define IDC_BTN_ADD_CUSTGOOFFLINE       2104
#define IDC_BTN_DELETE_CUSTGOOFFLINE    2105
#define IDC_GRP_GOOFFLINE_DEFAULTS      2106
#define IDC_RBN_GOOFFLINE_SILENT        2108
#define IDC_RBN_GOOFFLINE_FAIL          2109
#define IDC_LV_CUSTGOOFFLINE            2110
#define IDC_EDIT_GOOFFLINE_SERVER       2111
#define IDC_TXT_GOOFFLINE_SERVER        2112
#define IDC_CBX_ENCRYPT_CSC             2113
#define IDC_GRP_CUSTGOOFFLINE           2114
#define IDC_BTN_ADVANCED                2121
#define IDC_ERROR_TABS                  2124
#define IDC_SHARELB                     2126
#define IDC_OPENFILESLB                 2127
#define IDC_DETAILS                     2129
#define IDC_SINGLESHARENAME             2130
#define IDC_SEP                         2131
#define IDC_BTN_BROWSEFORSERVER         2132
#define IDC_DLGTYPEICON                 2133
#define IDC_RASCONNECT                  2135
#define IDC_WORKOFFLINE                 2136
#define IDC_CBRASENTRIES                2137
#define IDC_NETDOWNTEXT                 2138
#define IDC_STATIC2                     2141
#define IDC_STATIC3                     2142
#define IDC_STATIC4                     2143
#define IDC_PIN_NO_RECURSE              2144
#define IDC_PIN_RECURSE                 2145
#define IDC_FILENAME                    2147
#define IDC_KEEP_LOCAL                  2148
#define IDC_DELETE_LOCAL                2149
#define IDC_RBN_CONFIRMPURGE_UNPINNED   2150
#define IDC_RBN_CONFIRMPURGE_ALL        2151
#define IDC_TXT_CONFIRMPURGE            2152
#define IDC_CBX_FULLSYNC_AT_LOGOFF      2153
#define IDC_CBX_REMINDERS               2155
#define IDC_EDIT_REMINDERS              2157
#define IDC_SPIN_REMINDERS              2159
#define IDC_TXT_REMINDERS1              2160
#define IDC_TXT_REMINDERS2              2161
#define IDC_CBX_FIRSTPIN_AUTOSYNC       2165
#define IDC_CBX_FIRSTPIN_FLDRLNK        2166
#define IDC_TXT_FIRSTPIN_WELCOME_TITLE  2168
#define IDC_TXT_FIRSTPIN_FINISH_TITLE   2169
#define IDC_CBX_FIRSTPIN_NOSHOW         2170
#define IDC_BTN_DETAILS                 2171
#define IDC_BTN_SYNCHRONIZE             2172
#define IDC_LV_STATUSDLG                2174
#define IDC_BTN_VIEWFILES               2175
#define IDC_BTN_SETTINGS                2176
#define IDC_TXT_STATUSDLG               2178
#define IDC_SEP_STATUSDLG               2179
#define IDC_CBX_STATUSDLG               2183
#define IDC_CBX_CONFIRMDEL_NOSHOW       2186
#define IDC_TXT_CONFIRM_DELETEMOD       2187
#define IDC_CBX_LINK_ON_DESKTOP         2188
#define IDC_DEBUG_LIST                  2189
#define IDC_SKIP_EFS                    2190
#define IDC_EFS_MSG                     2191
#define IDC_APPLY_TO_ALL                2193
#define IDC_LIST_PURGE                  2195
#define IDS_COL_SERVERSTATUS            4101
#define IDS_BTHDR_INITIAL               4103
#define IDS_BTHDR_REMIND                4104
#define IDS_BTSTA_OFFLINE               4106
#define IDS_BTBOD_OFFLINE               4107
#define IDS_BTBOD_OFFLINE_M             4108
#define IDS_BTBOD_STILLOFFLINE          4109
#define IDS_BTBOD_STILLOFFLINE_M        4110
#define IDS_BTDIR_VIEWSTATUS            4111
#define IDS_BTDIR_RECONNECT             4112
#define IDS_BTSTA_DIRTY                 4114
#define IDS_BTSTA_SERVERBACK            4115
#define IDS_BTBOD_SERVERBACK            4116
#define IDS_BTBOD_SERVERBACK_M          4117
#define IDS_BTBOD_DIRTY                 4118
#define IDS_BTBOD_DIRTY_M               4119
#define IDS_BTBOD_STILLBACK             4120
#define IDS_BTBOD_STILLBACK_M           4121
#define IDS_BTBOD_STILLDIRTY            4122
#define IDS_BTBOD_STILLDIRTY_M          4123
#define IDS_BTDIR_SYNC                  4124
#define IDS_CSC_CM_SETTINGS             4125
#define IDS_FIRSTPIN_PIN_TITLE          4131
#define IDS_FIRSTPIN_PIN_SUBTITLE       4132
#define IDS_FIRSTPIN_OFFLINE_TITLE      4133
#define IDS_FIRSTPIN_OFFLINE_SUBTITLE   4134
#define IDS_FIRSTPIN_CONTROLS_TITLE     4135
#define IDS_FIRSTPIN_CONTROLS_SUBTITLE  4136
#define IDS_FIRSTPIN_SYNC_TITLE         4137
#define IDS_FIRSTPIN_SYNC_SUBTITLE      4138
#define IDS_FIRSTPIN_FONTHT_PTS         4139
#define IDS_ERR_REGSYNCATLOGONLOGOFF    4140
#define IDS_BTSTA_NONET                 4141
#define IDS_BTBOD_NONET                 4142
#define IDS_BTBOD_STILLNONET            4143
#define IDS_CSC_CM_STATUS               4144
#define IDS_STATUSDLG_HDR_SERVER        4145
#define IDS_STATUSDLG_HDR_STATUS        4146
#define IDS_STATUSDLG_HDR_INFO          4147
#define IDS_TT_HEADER                   4148
#define IDS_TT_OFFLINE                  4149
#define IDS_TT_OFFLINE_M                4150
#define IDS_TT_SERVERBACK               4151
#define IDS_TT_SERVERBACK_M             4152
#define IDS_TT_DIRTY                    4153
#define IDS_TT_DIRTY_M                  4154
#define IDS_TT_NONET                    4155
#define IDS_STATUSDLG_TITLE             4156
#define IDS_STATUSDLG_OFFLINE           4157
#define IDS_STATUSDLG_SERVERBACK        4158
#define IDS_STATUSDLG_DIRTY             4159
#define IDS_STATUSDLG_BTN_SYNC          4160
#define IDS_STATUSDLG_BTN_RECONN        4161
#define IDS_CSC_CM_SYNCHRONIZE          4162
#define IDS_STATUSDLG_OFFLINE_M         4163
#define IDS_STATUSDLG_SERVERBACK_M      4164
#define IDS_STATUSDLG_DIRTY_M           4165
#define IDS_SHARE_INFO_DIRTY            4166
#define IDS_SHARE_INFO_AVAIL_MOD        4167
#define IDS_SHARE_INFO_UNAVAIL_MOD      4168
#define IDS_SHARE_INFO_AVAIL            4169
#define IDS_SHARE_INFO_UNAVAIL          4170
#define IDS_SHARE_INFO_BLANK            4171
#define IDS_REFORMAT_CACHE              4172
#define IDS_STATUSDLG_NONET             4173
#define IDS_BALLOONHDR_FORMAT           4174
#define IDS_BALLOONBODY_FORMAT          4175
#define IDS_FMT_DELCACHE_FILESDELETED   4176
#define IDS_FMT_DELCACHE_FILEDELETED    4177
#define IDS_DELFILEPROG_LINE1           4178
#define IDS_FMT_DELFILES_ERROR          4179
#define IDS_FOLDER_LINK_NAME            4180
#define IDS_OPENFILESONDISABLE          4181
#define IDS_ERR_DISABLECSC              4182
#define IDS_ERR_ENABLECSC               4183
#define IDS_COL_ACCESS                  4184
#define IDS_ACCESS_NONE                 4185
#define IDS_ACCESS_READ                 4186
#define IDS_ACCESS_WRITE                4187
#define IDS_ACCESS_READWRITE            4188
#define IDS_NULLMERGE_ITEMNAME          4189
#define IDS_NULLSYNC_ITEMNAME           4190
#define IDS_CONFIRM_DELETEMOD           4191
#define IDS_CANTPIN_SYNCINPROGRESS      4192
#define IDS_CANTSYNC_SYNCINPROGRESS     4193
#define IDS_CANTRECONN_SYNCINPROGRESS   4194
#define IDS_CACHING_DISALLOWED          4195
#define IDM_MORE_SHARES                 4199
#define IDM_SHARES_LAST                 4199
#define IDM_SHOW_DEBUGINFO              4200
#define IDM_ACTION_DELETE               4292
#define IDM_ACTION_WORKOFFLINE          4293
#define IDM_ACTION_FAIL                 4295
#define IDS_DELCACHE_NOFILESDELETED     4296
#define IDS_CMD_DELETE                  4297
#define IDS_CMD_DELETE_HELPTEXT         4298
#define IDC_TXT_STATUSDLG_CHECKTOSYNC   4299
#define IDS_BTN_TITLE_CLOSE             4300
#define IDC_TXT_CONFIRMPURGE2           4301
#define IDC_TXT_CONFIRMPURGE3           4302
#define IDS_TXT_NO_FILES_TO_DELETE      4303
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        1354
#define _APS_NEXT_COMMAND_VALUE         4304
#define _APS_NEXT_CONTROL_VALUE         2199
#define _APS_NEXT_SYMED_VALUE           2000
#endif
#endif
