# $Id: Makefile,v 1.2 2003/11/14 17:13:32 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = gstart

TARGET_INSTALLDIR = system32

TARGET_SDKLIBS = user32.a gdi32.a ntdll.a kernel32.a

TARGET_OBJECTS = $(TARGET_NAME).o

TARGET_CFLAGS = -Wall -Werror

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
