
list(APPEND UCRT_STRING_SOURCES
    string/memcpy_s.cpp
    string/memicmp.cpp
    string/strcat_s.cpp
    string/strcoll.cpp
    string/strcpy_s.cpp
    string/strdup.cpp
    string/stricmp.cpp
    string/stricoll.cpp
    string/strlwr.cpp
    string/strncat_s.cpp
    string/strncnt.cpp
    string/strncoll.cpp
    string/strncpy_s.cpp
    string/strnicmp.cpp
    string/strnicol.cpp
    string/strnlen.cpp
    string/strnset_s.cpp
    string/strset_s.cpp
    string/strtok.cpp
    string/strtok_s.cpp
    string/strupr.cpp
    string/strxfrm.cpp
    string/wcscat.cpp
    string/wcscat_s.cpp
    string/wcscmp.cpp
    string/wcscoll.cpp
    string/wcscpy.cpp
    string/wcscpy_s.cpp
    string/wcscspn.cpp
    string/wcsdup.cpp
    string/wcsicmp.cpp
    string/wcsicoll.cpp
    string/wcslwr.cpp
    string/wcsncat.cpp
    string/wcsncat_s.cpp
    string/wcsncmp.cpp
    string/wcsncnt.cpp
    string/wcsncoll.cpp
    string/wcsncpy.cpp
    string/wcsncpy_s.cpp
    string/wcsnicmp.cpp
    string/wcsnicol.cpp
    string/wcsnset.cpp
    string/wcsnset_s.cpp
    string/wcspbrk.cpp
    string/wcsrev.cpp
    string/wcsset.cpp
    string/wcsset_s.cpp
    string/wcsspn.cpp
    string/wcstok.cpp
    string/wcstok_s.cpp
    string/wcsupr.cpp
    string/wcsxfrm.cpp
    string/wmemcpy_s.cpp
    string/wmemmove_s.cpp
)
