# $Id: makefile,v 1.8 2003/09/28 00:30:34 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = psaux

TARGET_OBJECTS = $(TARGET_NAME).o controller.o mouse.o logips2pp.o synaptics.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
