#ifndef __REPORTERROR_H
#define __REPORTERROR_H

#ifndef PSCB_BUTTONPRESSED
#define PSCB_BUTTONPRESSED	(3)
#endif

#ifndef PBS_MARQUEE
#define PBS_MARQUEE	(8)
#endif

/* metrics */
#define PROPSHEETWIDTH 250
#define PROPSHEETHEIGHT 120
#define PROPSHEETPADDING 6
#define SYSTEM_COLUMN (18 * PROPSHEETPADDING)
#define LABELLINE(x) (((PROPSHEETPADDING + 2) * x) + (x + 2))
#define ICONSIZE 16

/* Resource IDs */

#define IDS_WIZARD_NAME 100
#define IDS_FAILED_TO_CONTACT_SERVER 101

#define IDS_CONTACTING_SERVER	201
#define IDS_FAILED_TO_INITIALIZE_WINSOCK 202
#define IDS_FAILED_TO_LOCATE_SERVER	203
#define IDS_FAILED_TO_DELIVER_ERROR_REPORT 204

#define IDD_FIRSTPAGE 100
#define IDD_SUBMIT_REPORT 101
#define IDD_SUBMITTING_REPORT 102
#define IDD_SUBMITTED_REPORT 103

#define IDC_SUBMISSION_STATUS 200
#define IDC_SUBMITTING_IN_PROGRESS 201

#define IDE_SUBMIT_REPORT_YOUR_EMAIL 300
#define IDE_SUBMIT_REPORT_PROBLEM_DESCRIPTION 301

#define IDB_WATERMARK 100
#define IDB_HEADER 101

typedef struct _ERROR_REPORT
{
  LPSTR YourEmail;
  LPSTR ProblemDescription;
} ERROR_REPORT, *LPERROR_REPORT;

#endif /* __REPORTERROR_H */
