# $Id: makefile,v 1.1 2002/06/25 22:21:41 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = mup

TARGET_OBJECTS = $(TARGET_NAME).o create.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
