fc icc.h d:\win\drivers\printers\adobe43\pscript\inc\icc.h > m
fc icm.h d:\win\drivers\printers\adobe43\pscript\inc\icm.h >> m
fc icc_i386.h d:\win\drivers\printers\adobe43\pscript\inc\icc_i386.h >> m
fc getcsa.h d:\win\drivers\printers\adobe43\pscript\inc\getcsa.h >> m
fc getcrd.h d:\win\drivers\printers\adobe43\pscript\inc\getcrd.h >> m
fc csprof.h d:\win\drivers\printers\adobe43\pscript\inc\csprof.h >> m
fc icmstr.h d:\win\drivers\printers\adobe43\pscript\inc\icmstr.h >> m
fc profcrd.h d:\win\drivers\printers\adobe43\pscript\inc\profcrd.h >> m
fc getcsa.c d:\win\drivers\printers\adobe43\pscript\dmg\getcsa.c >> m
fc getcrd.c d:\win\drivers\printers\adobe43\pscript\dmg\getcrd.c >> m
fc csprof.c d:\win\drivers\printers\adobe43\pscript\dmg\csprof.c >> m
fc profcrd.c d:\win\drivers\printers\adobe43\pscript\dmg\profcrd.c >> m
