/* $Id: svctabm.c,v 1.3 2002/09/08 10:23:51 chorns Exp $
 * 
 *  Entry Point for win32k.sys
 */

#undef WIN32_LEAN_AND_MEAN
#define WIN32_NO_STATUS
#include <windows.h>
#include <ddk/service.h>
#include <win32k/win32k.h>

/*
 * NOTE: the table is actually in the file ./svctab.c,
 * generated by iface/addsys/mktab.c + w32ksvc.db
 */
#include "svctab.c"

