#ifndef PCI_IDS__H
#define PCI_IDS__H

#define PCI_VENDOR_ID_NS		0x100b
#define PCI_DEVICE_ID_NS_87560_LIO	0x000e
#define	PCI_VENDOR_ID_AMD		0x1022
#define PCI_VENDOR_ID_OPTI		0x1045

#define PCI_CLASS_SERIAL_USB (PCI_CLASS_SERIAL_BUS_CTLR << 8 + PCI_SUBCLASS_SB_USB)

#endif