# $Id: Makefile.i386,v 1.3 2003/07/06 23:04:19 hyperion Exp $


EXCLUDE_FILTER = \
	memchr.o \
	memcpy.o \
	memmove.o \
	memset.o \
	strcat.o \
	strchr.o \
	strcmp.o \
	strcpy.o \
	strlen.o \
	strncat.o \
	strncmp.o \
	strncpy.o \
	strrchr.o \
        strnlen.o \
	wcscat.o \
	wcschr.o \
	wcscmp.o \
	wcscpy.o \
	wcslen.o \
	wcsncat.o \
	wcsncmp.o \
	wcsncpy.o \
	wcsnlen.o \
	wcsrchr.o
	

OBJECTS_ARCH = $(addprefix i386/, $(EXCLUDE_FILTER))


# EOF
