# $Id$

PATH_TO_TOP = ../..

TARGET_TYPE = dynlink

TARGET_NAME = winsta

TARGET_CFLAGS = -g -Werror -Wall

TARGET_OBJECTS = \
	main.o \
	misc.o \
	server.o \
	ws.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

include $(TOOLS_PATH)/depend.mk

# EOF
