1   stdcall  accept(long ptr ptr)
2   stdcall  bind(long ptr long)
3   stdcall  closesocket(long)
4   stdcall  connect(long ptr long)
5   stdcall  getpeername(long ptr ptr)
6   stdcall  getsockname(long ptr ptr)
7   stdcall  getsockopt(long long long ptr ptr)
8   stdcall  htonl(long)
9   stdcall  htons(long)
10  stdcall  ioctlsocket(long long ptr)
11  stdcall  inet_addr(str)
12  stdcall  inet_ntoa(ptr)
13  stdcall  listen(long long)
14  stdcall  ntohl(long)
15  stdcall  ntohs(long)
16  stdcall  recv(long ptr long long)
17  stdcall  recvfrom(long ptr long long ptr ptr)
18  stdcall  select(long ptr ptr ptr ptr)
19  stdcall  send(long ptr long long)
20  stdcall  sendto(long ptr long long ptr long)
21  stdcall  setsockopt(long long long ptr long)
22  stdcall  shutdown(long long)
23  stdcall  socket(long long long)

51  stdcall  gethostbyaddr(ptr long long)
52  stdcall  gethostbyname(str)
53  stdcall  getprotobyname(str)
54  stdcall  getprotobynumber(long)
55  stdcall  getservbyname(str str)
56  stdcall  getservbyport(long str)
57  stdcall  gethostname(ptr long)

101 stdcall WSAAsyncSelect(long long long long)
102 stdcall WSAAsyncGetHostByAddr(long long ptr long long ptr long)
103 stdcall WSAAsyncGetHostByName(long long str ptr long)
104 stdcall WSAAsyncGetProtoByNumber(long long long ptr long)
105 stdcall WSAAsyncGetProtoByName(long long str ptr long)
106 stdcall WSAAsyncGetServByPort(long long long str ptr long)
107 stdcall WSAAsyncGetServByName(long long str str ptr long)
108 stdcall WSACancelAsyncRequest(long)
109 stdcall WSASetBlockingHook(ptr)
110 stdcall WSAUnhookBlockingHook()
111 stdcall WSAGetLastError()
112 stdcall WSASetLastError(long)
113 stdcall WSACancelBlockingCall()
114 stdcall WSAIsBlocking()
115 stdcall WSAStartup(long ptr)
116 stdcall WSACleanup()

151 stdcall  __WSAFDIsSet(long ptr)

500 stdcall WEP()

@ stdcall WSApSetPostRoutine(ptr)
@ stdcall -stub -version=0x600+ FreeAddrInfoEx(ptr)
@ stdcall -stub -version=0x600+ FreeAddrInfoExW(ptr)
@ stdcall FreeAddrInfoW(ptr) freeaddrinfo
@ stdcall -stub -version=0x600+ GetAddrInfoExA(str str long ptr ptr ptr ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ GetAddrInfoExW(wstr wstr long ptr ptr ptr ptr ptr ptr ptr)
@ stdcall GetAddrInfoW(wstr wstr ptr ptr)
@ stdcall GetNameInfoW(ptr long wstr long wstr long long)
@ stdcall -version=0x600+ InetNtopW(long ptr ptr long)
@ stdcall -version=0x600+ InetPtonW(long wstr ptr)
@ stdcall -stub -version=0x600+ SetAddrInfoExA(str str ptr long ptr long long ptr ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ SetAddrInfoExW(wstr wstr ptr long ptr long long ptr ptr ptr ptr ptr)
@ stdcall WPUCompleteOverlappedRequest(long ptr long long ptr)
@ stdcall WSAAccept(long ptr ptr ptr long)
@ stdcall WSAAddressToStringA(ptr long ptr ptr ptr)
@ stdcall WSAAddressToStringW(ptr long ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSAAdvertiseProvider(ptr ptr)
@ stdcall WSACloseEvent(long)
@ stdcall WSAConnect(long ptr long ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSAConnectByList(long ptr ptr ptr ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSAConnectByNameA(long str str ptr ptr ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSAConnectByNameW(long str str ptr ptr ptr ptr ptr ptr)
@ stdcall WSACreateEvent()
@ stdcall WSADuplicateSocketA(long long ptr)
@ stdcall WSADuplicateSocketW(long long ptr)
@ stdcall WSAEnumNameSpaceProvidersA(ptr ptr)
@ stdcall -stub -version=0x600+ WSAEnumNameSpaceProvidersExA(ptr ptr)
@ stdcall -stub -version=0x600+ WSAEnumNameSpaceProvidersExW(ptr ptr)
@ stdcall WSAEnumNameSpaceProvidersW(ptr ptr)
@ stdcall WSAEnumNetworkEvents(long long ptr)
@ stdcall WSAEnumProtocolsA(ptr ptr ptr)
@ stdcall WSAEnumProtocolsW(ptr ptr ptr)
@ stdcall WSAEventSelect(long long long)
@ stdcall WSAGetOverlappedResult(long ptr ptr long ptr)
@ stdcall WSAGetQOSByName(long ptr ptr)
@ stdcall WSAGetServiceClassInfoA(ptr ptr ptr ptr)
@ stdcall WSAGetServiceClassInfoW(ptr ptr ptr ptr)
@ stdcall WSAGetServiceClassNameByClassIdA(ptr ptr ptr)
@ stdcall WSAGetServiceClassNameByClassIdW(ptr ptr ptr)
@ stdcall WSAHtonl(long long ptr)
@ stdcall WSAHtons(long long ptr)
@ stdcall WSAInstallServiceClassA(ptr)
@ stdcall WSAInstallServiceClassW(ptr)
@ stdcall WSAIoctl(long long ptr long ptr long ptr ptr ptr)
@ stdcall WSAJoinLeaf(long ptr long ptr ptr ptr ptr long)
@ stdcall WSALookupServiceBeginA(ptr long ptr)
@ stdcall WSALookupServiceBeginW(ptr long ptr)
@ stdcall WSALookupServiceEnd(long)
@ stdcall WSALookupServiceNextA(long long ptr ptr)
@ stdcall WSALookupServiceNextW(long long ptr ptr)
@ stdcall WSANSPIoctl(ptr long ptr long ptr long ptr ptr)
@ stdcall WSANtohl(long long ptr)
@ stdcall WSANtohs(long long ptr)
@ stdcall -stub -version=0x600+ WSAPoll(ptr long long)
@ stdcall -stub -version=0x600+ WSAProviderCompleteAsyncCall(ptr long)
@ stdcall WSAProviderConfigChange(ptr ptr ptr)
@ stdcall WSARecv(long ptr long ptr ptr ptr ptr)
@ stdcall WSARecvDisconnect(long ptr)
@ stdcall WSARecvFrom(long ptr long ptr ptr ptr ptr ptr ptr)
@ stdcall WSARemoveServiceClass(ptr)
@ stdcall WSAResetEvent(long)
@ stdcall WSASend(long ptr long ptr long ptr ptr)
@ stdcall WSASendDisconnect(long ptr)
@ stdcall -stub -version=0x600+ WSASendMsg(long ptr long ptr ptr ptr)
@ stdcall WSASendTo(long ptr long ptr long ptr long ptr ptr)
@ stdcall WSASetEvent(long)
@ stdcall WSASetServiceA(ptr long long)
@ stdcall WSASetServiceW(ptr long long)
@ stdcall WSASocketA(long long long ptr long long)
@ stdcall WSASocketW(long long long ptr long long)
@ stdcall WSAStringToAddressA(str long ptr ptr ptr)
@ stdcall WSAStringToAddressW(wstr long ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSAUnadvertiseProvider(ptr)
@ stdcall WSAWaitForMultipleEvents(long ptr long long long)
@ stdcall WSCDeinstallProvider(ptr ptr)
@ stdcall -stub -arch=win64 WSCDeinstallProvider32(ptr ptr)
@ stdcall WSCEnableNSProvider(ptr long)
@ stdcall -stub -arch=win64 WSCEnableNSProvider32(ptr long)
@ stdcall -stub -arch=win64 WSCEnumNameSpaceProviders32(ptr ptr)
@ stdcall -stub -version=0x600+ -arch=win64 WSCEnumNameSpaceProvidersEx32(ptr ptr)
@ stdcall WSCEnumProtocols(ptr ptr ptr ptr)
@ stdcall -stub -arch=win64 WSCEnumProtocols32(ptr ptr ptr ptr)
@ stdcall -stub -version=0x600+ WSCGetApplicationCategory(wstr long wstr long ptr ptr)
@ stdcall -stub -version=0x600+ WSCGetProviderInfo(ptr long ptr ptr long ptr)
@ stdcall -stub -version=0x600+ -arch=win64 WSCGetProviderInfo32(ptr long ptr ptr long ptr)
@ stdcall WSCGetProviderPath(ptr ptr ptr ptr)
@ stdcall -stub -arch=win64 WSCGetProviderPath32(ptr ptr ptr ptr)
@ stdcall WSCInstallNameSpace(wstr wstr long long ptr)
@ stdcall -stub -arch=win64 WSCInstallNameSpace32(wstr wstr long long ptr)
@ stdcall -stub -version=0x600+ WSCInstallNameSpaceEx(wstr wstr long long ptr ptr)
@ stdcall -stub -version=0x600+ -arch=win64 WSCInstallNameSpaceEx32(wstr wstr long long ptr ptr)
@ stdcall WSCInstallProvider(ptr wstr ptr long ptr)
@ stdcall -stub -arch=win64 WSCInstallProvider64_32(ptr wstr ptr long ptr)
@ stdcall -stub -version=0x600+ -arch=win64 WSCInstallProviderAndChains64_32(ptr wstr wstr wstr long ptr long ptr ptr)
@ stdcall -stub -version=0x600+ WSCSetApplicationCategory(wstr long wstr long long ptr ptr)
@ stdcall -stub -version=0x600+ WSCSetProviderInfo(ptr long ptr long long ptr)
@ stdcall -stub -version=0x600+ -arch=win64 WSCSetProviderInfo32(ptr long ptr long long ptr)
@ stdcall WSCUnInstallNameSpace(ptr)
@ stdcall -stub -arch=win64 WSCUnInstallNameSpace32(ptr)
@ stdcall WSCUpdateProvider(ptr wstr ptr long ptr)
@ stdcall -stub -arch=win64 WSCUpdateProvider32(ptr wstr ptr long ptr)
@ stdcall WSCWriteNameSpaceOrder(ptr long)
@ stdcall -stub -arch=win64 WSCWriteNameSpaceOrder32(ptr long)
@ stdcall WSCWriteProviderOrder(ptr long)
@ stdcall -stub -arch=win64 WSCWriteProviderOrder32(ptr long)
@ stdcall -version=0x600+ WahCloseApcHelper(long)
@ stdcall -version=0x600+ WahCloseHandleHelper(long)
@ stdcall -version=0x600+ WahCloseNotificationHandleHelper(long)
@ stdcall -version=0x600+ WahCloseSocketHandle(long ptr)
@ stdcall -version=0x600+ WahCloseThread(long ptr)
@ stdcall -version=0x600+ WahCompleteRequest(long ptr ptr long long)
@ stdcall -version=0x600+ WahCreateHandleContextTable(ptr)
@ stdcall -version=0x600+ WahCreateNotificationHandle(long ptr)
@ stdcall -version=0x600+ WahCreateSocketHandle(long ptr)
@ stdcall -version=0x600+ WahDestroyHandleContextTable(ptr)
@ stdcall -version=0x600+ WahDisableNonIFSHandleSupport()
@ stdcall -version=0x600+ WahEnableNonIFSHandleSupport()
@ stdcall -version=0x600+ WahEnumerateHandleContexts(ptr ptr ptr)
@ stdcall -version=0x600+ WahInsertHandleContext(ptr ptr)
@ stdcall -version=0x600+ WahNotifyAllProcesses(long)
@ stdcall -version=0x600+ WahOpenApcHelper(ptr)
@ stdcall -version=0x600+ WahOpenCurrentThread(long ptr)
@ stdcall -version=0x600+ WahOpenHandleHelper(ptr)
@ stdcall -version=0x600+ WahOpenNotificationHandleHelper(ptr)
@ stdcall -version=0x600+ WahQueueUserApc(long ptr ptr ptr)
@ stdcall -version=0x600+ WahReferenceContextByHandle(ptr long)
@ stdcall -version=0x600+ WahRemoveHandleContext(ptr ptr)
@ stdcall -version=0x600+ WahWaitForNotification(long long ptr ptr)
@ stdcall -stub -version=0x600+ WahWriteLSPEvent(ptr ptr)
@ stdcall freeaddrinfo(ptr)
@ stdcall getaddrinfo(str str ptr ptr)
@ stdcall getnameinfo(ptr long ptr long ptr long long)
@ stdcall -version=0x600+ inet_ntop(long ptr ptr long)
@ stdcall -version=0x600+ inet_pton(long str ptr)
