
#include <stdarg.h>
#include "windef.h"
#include "winbase.h"
#include "wine/config.h"
#include "wine/exception.h"

void __wine_spec_unimplemented_stub( const char *module, const char *function )
{
    ULONG_PTR args[2];

    args[0] = (ULONG_PTR)module;
    args[1] = (ULONG_PTR)function;
    RaiseException( EXCEPTION_WINE_STUB, EH_NONCONTINUABLE, 2, args );
}

static const char __wine_spec_file_name[] = "advapi32.dll";

void __wine_stub_advapi32_dll_12(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "AccessCheckByTypeResultList"); }
void __wine_stub_advapi32_dll_53(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CancelOverlappedAccess"); }
void __wine_stub_advapi32_dll_61(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CloseCodeAuthzLevel"); }
void __wine_stub_advapi32_dll_62(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CloseEncryptedFileRaw"); }
void __wine_stub_advapi32_dll_65(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CloseTrace"); }
void __wine_stub_advapi32_dll_67(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ComputeAccessTokenFromCodeAuthzLevel"); }
void __wine_stub_advapi32_dll_72(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertAccessToSecurityDescriptorA"); }
void __wine_stub_advapi32_dll_73(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertAccessToSecurityDescriptorW"); }
void __wine_stub_advapi32_dll_74(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSDToStringSDRootDomainA"); }
void __wine_stub_advapi32_dll_75(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSDToStringSDRootDomainW"); }
void __wine_stub_advapi32_dll_76(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSecurityDescriptorToAccessA"); }
void __wine_stub_advapi32_dll_77(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSecurityDescriptorToAccessNamedA"); }
void __wine_stub_advapi32_dll_78(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSecurityDescriptorToAccessNamedW"); }
void __wine_stub_advapi32_dll_79(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertSecurityDescriptorToAccessW"); }
void __wine_stub_advapi32_dll_84(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertStringSDToSDDomainA"); }
void __wine_stub_advapi32_dll_85(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertStringSDToSDDomainW"); }
void __wine_stub_advapi32_dll_86(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertStringSDToSDRootDomainA"); }
void __wine_stub_advapi32_dll_87(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ConvertStringSDToSDRootDomainW"); }
void __wine_stub_advapi32_dll_94(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CreateCodeAuthzLevel"); }
void __wine_stub_advapi32_dll_105(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CreateTraceInstanceId"); }
void __wine_stub_advapi32_dll_113(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredGetTargetInfoA"); }
void __wine_stub_advapi32_dll_114(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredGetTargetInfoW"); }
void __wine_stub_advapi32_dll_115(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredIsMarshaledCredentialA"); }
void __wine_stub_advapi32_dll_116(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredIsMarshaledCredentialW"); }
void __wine_stub_advapi32_dll_117(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredMarshalCredentialA"); }
void __wine_stub_advapi32_dll_118(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredMarshalCredentialW"); }
void __wine_stub_advapi32_dll_119(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredProfileLoaded"); }
void __wine_stub_advapi32_dll_124(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredRenameA"); }
void __wine_stub_advapi32_dll_125(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredRenameW"); }
void __wine_stub_advapi32_dll_130(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredpConvertCredential"); }
void __wine_stub_advapi32_dll_131(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredpConvertTargetInfo"); }
void __wine_stub_advapi32_dll_132(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredpDecodeCredential"); }
void __wine_stub_advapi32_dll_133(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "CredpEncodeCredential"); }
void __wine_stub_advapi32_dll_179(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "DuplicateEncryptionInfoFile"); }
void __wine_stub_advapi32_dll_182(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfBackupEventLogFileA"); }
void __wine_stub_advapi32_dll_183(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfBackupEventLogFileW"); }
void __wine_stub_advapi32_dll_184(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfChangeNotify"); }
void __wine_stub_advapi32_dll_185(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfClearEventLogFileA"); }
void __wine_stub_advapi32_dll_186(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfClearEventLogFileW"); }
void __wine_stub_advapi32_dll_187(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfCloseEventLog"); }
void __wine_stub_advapi32_dll_188(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfDeregisterEventSource"); }
void __wine_stub_advapi32_dll_189(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfDeregisterEventSourceW"); }
void __wine_stub_advapi32_dll_190(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfFlushEventLog"); }
void __wine_stub_advapi32_dll_191(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfNumberOfRecords"); }
void __wine_stub_advapi32_dll_192(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfOldestRecord"); }
void __wine_stub_advapi32_dll_193(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfOpenBackupEventLogA"); }
void __wine_stub_advapi32_dll_194(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfOpenBackupEventLogW"); }
void __wine_stub_advapi32_dll_195(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfOpenEventLogA"); }
void __wine_stub_advapi32_dll_196(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfOpenEventLogW"); }
void __wine_stub_advapi32_dll_197(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfReadEventLogA"); }
void __wine_stub_advapi32_dll_198(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfReadEventLogW"); }
void __wine_stub_advapi32_dll_199(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfRegisterEventSourceA"); }
void __wine_stub_advapi32_dll_200(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfRegisterEventSourceW"); }
void __wine_stub_advapi32_dll_201(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfReportEventA"); }
void __wine_stub_advapi32_dll_202(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ElfReportEventW"); }
void __wine_stub_advapi32_dll_206(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "EncryptedFileKeyInfo"); }
void __wine_stub_advapi32_dll_210(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "EnumServiceGroupA"); }
void __wine_stub_advapi32_dll_216(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "EnumerateTraceGuids"); }
void __wine_stub_advapi32_dll_223(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "FlushTraceA"); }
void __wine_stub_advapi32_dll_224(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "FlushTraceW"); }
void __wine_stub_advapi32_dll_225(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "FreeEncryptedFileKeyInfo"); }
void __wine_stub_advapi32_dll_229(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetAccessPermissionsForObjectA"); }
void __wine_stub_advapi32_dll_230(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetAccessPermissionsForObjectW"); }
void __wine_stub_advapi32_dll_244(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetInformationCodeAuthzLevelW"); }
void __wine_stub_advapi32_dll_245(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetInformationCodeAuthzPolicyW"); }
void __wine_stub_advapi32_dll_250(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetLocalManagedApplicationData"); }
void __wine_stub_advapi32_dll_251(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetLocalManagedApplications"); }
void __wine_stub_advapi32_dll_252(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetManagedApplicationCategories"); }
void __wine_stub_advapi32_dll_253(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetManagedApplications"); }
void __wine_stub_advapi32_dll_254(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetMangledSiteSid"); }
void __wine_stub_advapi32_dll_260(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetNamedSecurityInfoExA"); }
void __wine_stub_advapi32_dll_261(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetNamedSecurityInfoExW"); }
void __wine_stub_advapi32_dll_265(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "GetOverlappedAccessResults"); }
void __wine_stub_advapi32_dll_299(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "I_ScGetCurrentGroupStateW"); }
void __wine_stub_advapi32_dll_300(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "I_ScIsSecurityProcess"); }
void __wine_stub_advapi32_dll_301(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "I_ScPnPGetServiceName"); }
void __wine_stub_advapi32_dll_302(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "I_ScSendTSMessage"); }
void __wine_stub_advapi32_dll_303(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "I_ScSetServiceBit"); }
void __wine_stub_advapi32_dll_306(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "IdentifyCodeAuthzLevelW"); }
void __wine_stub_advapi32_dll_318(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "InstallApplication"); }
void __wine_stub_advapi32_dll_319(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "IsProcessRestricted"); }
void __wine_stub_advapi32_dll_322(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "IsTokenUntrusted"); }
void __wine_stub_advapi32_dll_329(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LogonUserExA"); }
void __wine_stub_advapi32_dll_330(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LogonUserExW"); }
void __wine_stub_advapi32_dll_342(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LookupSecurityDescriptorPartsA"); }
void __wine_stub_advapi32_dll_343(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LookupSecurityDescriptorPartsW"); }
void __wine_stub_advapi32_dll_345(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaAddPrivilegesToAccount"); }
void __wine_stub_advapi32_dll_346(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaClearAuditLog"); }
void __wine_stub_advapi32_dll_348(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaCreateAccount"); }
void __wine_stub_advapi32_dll_349(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaCreateSecret"); }
void __wine_stub_advapi32_dll_350(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaCreateTrustedDomain"); }
void __wine_stub_advapi32_dll_355(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaEnumerateAccounts"); }
void __wine_stub_advapi32_dll_357(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaEnumeratePrivileges"); }
void __wine_stub_advapi32_dll_358(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaEnumeratePrivilegesOfAccount"); }
void __wine_stub_advapi32_dll_362(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaGetQuotasForAccount"); }
void __wine_stub_advapi32_dll_363(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaGetRemoteUserName"); }
void __wine_stub_advapi32_dll_364(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaGetSystemAccessAccount"); }
void __wine_stub_advapi32_dll_366(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaICLookupNames"); }
void __wine_stub_advapi32_dll_367(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaICLookupNamesWithCreds"); }
void __wine_stub_advapi32_dll_368(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaICLookupSids"); }
void __wine_stub_advapi32_dll_369(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaICLookupSidsWithCreds"); }
void __wine_stub_advapi32_dll_372(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaLookupPrivilegeDisplayName"); }
void __wine_stub_advapi32_dll_377(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaOpenAccount"); }
void __wine_stub_advapi32_dll_379(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaOpenPolicySce"); }
void __wine_stub_advapi32_dll_380(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaOpenSecret"); }
void __wine_stub_advapi32_dll_381(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaOpenTrustedDomain"); }
void __wine_stub_advapi32_dll_383(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaQueryDomainInformationPolicy"); }
void __wine_stub_advapi32_dll_384(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaQueryForestTrustInformation"); }
void __wine_stub_advapi32_dll_387(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaQuerySecret"); }
void __wine_stub_advapi32_dll_388(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaQuerySecurityObject"); }
void __wine_stub_advapi32_dll_393(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaRemovePrivilegesFromAccount"); }
void __wine_stub_advapi32_dll_396(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaSetForestTrustInformation"); }
void __wine_stub_advapi32_dll_397(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaSetInformationTrustedDomain"); }
void __wine_stub_advapi32_dll_398(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaSetQuotasForAccount"); }
void __wine_stub_advapi32_dll_400(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaSetSecurityObject"); }
void __wine_stub_advapi32_dll_401(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "LsaSetSystemAccessAccount"); }
void __wine_stub_advapi32_dll_412(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "MSChapSrvChangePassword"); }
void __wine_stub_advapi32_dll_413(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "MSChapSrvChangePassword2"); }
void __wine_stub_advapi32_dll_430(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "OpenEncryptedFileRawA"); }
void __wine_stub_advapi32_dll_431(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "OpenEncryptedFileRawW"); }
void __wine_stub_advapi32_dll_440(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "OpenTraceA"); }
void __wine_stub_advapi32_dll_441(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "OpenTraceW"); }
void __wine_stub_advapi32_dll_445(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ProcessIdleTasks"); }
void __wine_stub_advapi32_dll_446(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ProcessTrace"); }
void __wine_stub_advapi32_dll_447(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ProvAccessRightsToNTAccessMask"); }
void __wine_stub_advapi32_dll_461(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "QueryTraceA"); }
void __wine_stub_advapi32_dll_462(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "QueryTraceW"); }
void __wine_stub_advapi32_dll_465(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "ReadEncryptedFileRaw"); }
void __wine_stub_advapi32_dll_522(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "RegRemapPreDefKey"); }
void __wine_stub_advapi32_dll_542(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "RegisterIdleTask"); }
void __wine_stub_advapi32_dll_549(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "RemoveTraceCallback"); }
void __wine_stub_advapi32_dll_554(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferCloseLevel"); }
void __wine_stub_advapi32_dll_555(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferComputeTokenFromLevel"); }
void __wine_stub_advapi32_dll_557(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferGetLevelInformation"); }
void __wine_stub_advapi32_dll_559(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferIdentifyLevel"); }
void __wine_stub_advapi32_dll_560(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferRecordEventLogEntry"); }
void __wine_stub_advapi32_dll_561(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferSetLevelInformation"); }
void __wine_stub_advapi32_dll_562(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferSetPolicyInformation"); }
void __wine_stub_advapi32_dll_563(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiChangeRegistryScope"); }
void __wine_stub_advapi32_dll_564(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiCompareTokenLevels"); }
void __wine_stub_advapi32_dll_565(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiIsExecutableFileType"); }
void __wine_stub_advapi32_dll_566(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiPopulateDefaultsInRegistry"); }
void __wine_stub_advapi32_dll_567(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiRecordEventLogEntry"); }
void __wine_stub_advapi32_dll_568(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiReplaceProcessThreadTokens"); }
void __wine_stub_advapi32_dll_569(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SaferiSearchMatchingHashRules"); }
void __wine_stub_advapi32_dll_571(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetEntriesInAccessListA"); }
void __wine_stub_advapi32_dll_572(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetEntriesInAccessListW"); }
void __wine_stub_advapi32_dll_575(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetEntriesInAuditListA"); }
void __wine_stub_advapi32_dll_576(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetEntriesInAuditListW"); }
void __wine_stub_advapi32_dll_579(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetInformationCodeAuthzLevelW"); }
void __wine_stub_advapi32_dll_580(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetInformationCodeAuthzPolicyW"); }
void __wine_stub_advapi32_dll_583(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetNamedSecurityInfoExA"); }
void __wine_stub_advapi32_dll_584(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetNamedSecurityInfoExW"); }
void __wine_stub_advapi32_dll_587(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetPrivateObjectSecurityEx"); }
void __wine_stub_advapi32_dll_596(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetSecurityInfoExA"); }
void __wine_stub_advapi32_dll_597(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetSecurityInfoExW"); }
void __wine_stub_advapi32_dll_603(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetTraceCallback"); }
void __wine_stub_advapi32_dll_604(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "SetUserFileEncryptionKey"); }
void __wine_stub_advapi32_dll_611(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "StopTraceA"); }
void __wine_stub_advapi32_dll_612(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "StopTraceW"); }
void __wine_stub_advapi32_dll_653(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "TraceEventInstance"); }
void __wine_stub_advapi32_dll_655(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "TraceMessageVa"); }
void __wine_stub_advapi32_dll_658(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "TrusteeAccessToObjectA"); }
void __wine_stub_advapi32_dll_659(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "TrusteeAccessToObjectW"); }
void __wine_stub_advapi32_dll_660(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "UninstallApplication"); }
void __wine_stub_advapi32_dll_662(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "UnregisterIdleTask"); }
void __wine_stub_advapi32_dll_664(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "UpdateTraceA"); }
void __wine_stub_advapi32_dll_665(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "UpdateTraceW"); }
void __wine_stub_advapi32_dll_666(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WdmWmiServiceMain"); }
void __wine_stub_advapi32_dll_667(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiCloseBlock"); }
void __wine_stub_advapi32_dll_668(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiCloseTraceWithCursor"); }
void __wine_stub_advapi32_dll_669(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiConvertTimestamp"); }
void __wine_stub_advapi32_dll_670(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiDevInstToInstanceNameA"); }
void __wine_stub_advapi32_dll_671(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiDevInstToInstanceNameW"); }
void __wine_stub_advapi32_dll_672(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiEnumerateGuids"); }
void __wine_stub_advapi32_dll_673(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiExecuteMethodA"); }
void __wine_stub_advapi32_dll_674(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiExecuteMethodW"); }
void __wine_stub_advapi32_dll_675(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiFileHandleToInstanceNameA"); }
void __wine_stub_advapi32_dll_676(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiFileHandleToInstanceNameW"); }
void __wine_stub_advapi32_dll_677(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiFreeBuffer"); }
void __wine_stub_advapi32_dll_678(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiGetFirstTraceOffset"); }
void __wine_stub_advapi32_dll_679(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiGetNextEvent"); }
void __wine_stub_advapi32_dll_680(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiGetTraceHeader"); }
void __wine_stub_advapi32_dll_681(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiMofEnumerateResourcesA"); }
void __wine_stub_advapi32_dll_682(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiMofEnumerateResourcesW"); }
void __wine_stub_advapi32_dll_683(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiNotificationRegistrationA"); }
void __wine_stub_advapi32_dll_684(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiNotificationRegistrationW"); }
void __wine_stub_advapi32_dll_685(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiOpenBlock"); }
void __wine_stub_advapi32_dll_686(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiOpenTraceWithCursor"); }
void __wine_stub_advapi32_dll_687(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiParseTraceEvent"); }
void __wine_stub_advapi32_dll_688(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQueryAllDataA"); }
void __wine_stub_advapi32_dll_689(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQueryAllDataMultipleA"); }
void __wine_stub_advapi32_dll_690(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQueryAllDataMultipleW"); }
void __wine_stub_advapi32_dll_691(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQueryAllDataW"); }
void __wine_stub_advapi32_dll_692(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQueryGuidInformation"); }
void __wine_stub_advapi32_dll_693(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQuerySingleInstanceA"); }
void __wine_stub_advapi32_dll_694(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQuerySingleInstanceMultipleA"); }
void __wine_stub_advapi32_dll_695(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQuerySingleInstanceMultipleW"); }
void __wine_stub_advapi32_dll_696(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiQuerySingleInstanceW"); }
void __wine_stub_advapi32_dll_697(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiReceiveNotificationsA"); }
void __wine_stub_advapi32_dll_698(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiReceiveNotificationsW"); }
void __wine_stub_advapi32_dll_699(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiSetSingleInstanceA"); }
void __wine_stub_advapi32_dll_700(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiSetSingleInstanceW"); }
void __wine_stub_advapi32_dll_701(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiSetSingleItemA"); }
void __wine_stub_advapi32_dll_702(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WmiSetSingleItemW"); }
void __wine_stub_advapi32_dll_703(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "Wow64Win32ApiEntry"); }
void __wine_stub_advapi32_dll_704(void) { __wine_spec_unimplemented_stub(__wine_spec_file_name, "WriteEncryptedFileRaw"); }
