# $Id: makefile,v 1.1 2003/10/15 18:28:54 weiden Exp $

PATH_TO_TOP = ../../..

TARGET_NORC = no

TARGET_TYPE = program

TARGET_APPTYPE = windows

TARGET_NAME = carets

TARGET_SDKLIBS = kernel32.a gdi32.a ntdll.a

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
