
list(APPEND UCRT_MBSTRING_SOURCES
    mbstring/ismbalnm.cpp
    mbstring/ismbalph.cpp
    mbstring/ismbbyte.cpp
    mbstring/ismbdgt.cpp
    mbstring/ismbgrph.cpp
    mbstring/ismbknj.cpp
    mbstring/ismblgl.cpp
    mbstring/ismblwr.cpp
    mbstring/ismbprn.cpp
    mbstring/ismbpunc.cpp
    mbstring/ismbsle.cpp
    mbstring/ismbspc.cpp
    mbstring/ismbupr.cpp
    mbstring/mbbtype.cpp
    mbstring/mbccpy.cpp
    mbstring/mbccpy_s.cpp
    mbstring/mbccpy_s_l.cpp
    mbstring/mbclen.cpp
    mbstring/mbclevel.cpp
    mbstring/mbctype.cpp
    mbstring/mbsbtype.cpp
    mbstring/mbscat_s.cpp
    mbstring/mbscat_s_l.cpp
    mbstring/mbschr.cpp
    mbstring/mbscmp.cpp
    mbstring/mbscoll.cpp
    mbstring/mbscpy_s.cpp
    mbstring/mbscpy_s_l.cpp
    mbstring/mbscspn.cpp
    mbstring/mbsdec.cpp
    mbstring/mbsicmp.cpp
    mbstring/mbsicoll.cpp
    mbstring/mbsinc.cpp
    mbstring/mbslen.cpp
    mbstring/mbslen_s.cpp
    mbstring/mbslwr.cpp
    mbstring/mbsnbcat.cpp
    mbstring/mbsnbcat_s.cpp
    mbstring/mbsnbcat_s_l.cpp
    mbstring/mbsnbcmp.cpp
    mbstring/mbsnbcnt.cpp
    mbstring/mbsnbcol.cpp
    mbstring/mbsnbcpy.cpp
    mbstring/mbsnbcpy_s.cpp
    mbstring/mbsnbcpy_s_l.cpp
    mbstring/mbsnbicm.cpp
    mbstring/mbsnbico.cpp
    mbstring/mbsnbset.cpp
    mbstring/mbsnbset_s.cpp
    mbstring/mbsnbset_s_l.cpp
    mbstring/mbsncat.cpp
    mbstring/mbsncat_s.cpp
    mbstring/mbsncat_s.inl
    mbstring/mbsncat_s_l.cpp
    mbstring/mbsnccnt.cpp
    mbstring/mbsncmp.cpp
    mbstring/mbsncoll.cpp
    mbstring/mbsncpy.cpp
    mbstring/mbsncpy_s.cpp
    mbstring/mbsncpy_s.inl
    mbstring/mbsncpy_s_l.cpp
    mbstring/mbsnextc.cpp
    mbstring/mbsnicmp.cpp
    mbstring/mbsnicol.cpp
    mbstring/mbsninc.cpp
    mbstring/mbsnset.cpp
    mbstring/mbsnset_s.cpp
    mbstring/mbsnset_s.inl
    mbstring/mbsnset_s_l.cpp
    mbstring/mbspbrk.cpp
    mbstring/mbsrchr.cpp
    mbstring/mbsrev.cpp
    mbstring/mbsset.cpp
    mbstring/mbsset_s.cpp
    mbstring/mbsset_s_l.cpp
    mbstring/mbsspn.cpp
    mbstring/mbsspnp.cpp
    mbstring/mbsstr.cpp
    mbstring/mbstok.cpp
    mbstring/mbstok_s.cpp
    mbstring/mbsupr.cpp
    mbstring/mbtohira.cpp
    mbstring/mbtokata.cpp
    mbstring/mbtolwr.cpp
    mbstring/mbtoupr.cpp
    mbstring/tojisjms.cpp
    mbstring/tombbmbc.cpp
)

# All multibyte string functions require the _MBCS macro to be defined
set_source_files_properties(${UCRT_MBSTRING_SOURCES} PROPERTIES COMPILE_DEFINITIONS _MBCS)
