hal.dll  _init_end__
hal.dll  _init_start__
hal.dll  _text_end__
hal.dll  @ExAcquireFastMutex@4
hal.dll  @ExReleaseFastMutex@4
hal.dll  @ExTryToAcquireFastMutex@4
hal.dll  HalAcquireDisplayOwnership@4
hal.dll  HalAllocateAdapterChannel@16
hal.dll  HalAllocateCommonBuffer@16
hal.dll  HalAllProcessorsStarted@0
hal.dll  HalBeginSystemInterrupt@12
hal.dll  HalDisableSystemInterrupt@8
hal.dll  HalDisplayString@
hal.dll  HalDisplayString@4
hal.dll  HalEnableSystemInterrupt@12
hal.dll  HalEndSystemInterrupt@8
hal.dll  HalFreeCommonBuffer@24
hal.dll  HalGetAdapter@8
hal.dll  HalGetEnvironmentVariable@12
hal.dll  HalInitializeProcessor@8
hal.dll  HalInitSystem@8
hal.dll  HalQueryRealTimeClock@4
hal.dll  HalReadDmaCounter@4
hal.dll  HalReleaseDisplayOwnership@0
hal.dll  HalReportResourceUsage@0
hal.dll  HalRequestIpi@4
hal.dll  @HalRequestSoftwareInterrupt@4
hal.dll  HalReturnToFirmware@4
hal.dll  HalSetEnvironmentVariable@8
hal.dll  HalSetRealTimeClock@4
hal.dll  IoAssignDriveLetters@16
hal.dll  IoFlushAdapterBuffers@24
hal.dll  IoFreeAdapterChannel@4
hal.dll  IoFreeMapRegisters@12
hal.dll  IoMapTransfer@24
hal.dll  KdPortGetByteEx@8
hal.dll  KdPortInitializeEx@12
hal.dll  KdPortPutByteEx@8
hal.dll  KeAcquireSpinLock@8
hal.dll  KeFlushWriteBuffer@0
hal.dll  KeGetCurrentIrql@0
hal.dll  KeLowerIrql@4
hal.dll  KeQueryPerformanceCounter@4
hal.dll  KeRaiseIrql@8
hal.dll  KeRaiseIrqlToDpcLevel@0
hal.dll  KeRaiseIrqlToSynchLevel@0
hal.dll  KeReleaseSpinLock@8
hal.dll  @KfAcquireSpinLock@4
hal.dll  @KfLowerIrql@4
hal.dll  @KfReleaseSpinLock@8
hal.dll  READ_PORT_UCHAR@4
hal.dll  READ_PORT_ULONG@4
hal.dll  READ_PORT_USHORT@4
hal.dll  WRITE_PORT_UCHAR@8
hal.dll  WRITE_PORT_ULONG@8
hal.dll  WRITE_PORT_USHORT@8