#line 2 "tools/wrc/lex.yy.c"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <unistd.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 92
#define YY_END_OF_BUFFER 93
static yyconst short int yy_accept[207] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   82,   82,
        0,    0,   13,   13,   18,   18,   20,   20,    3,    3,
        5,    5,    8,    8,   93,   90,   89,   88,   53,   75,
       29,   30,   26,   26,   86,   29,   30,   24,   25,   89,
        2,   70,   74,   55,   91,   51,   52,   33,   91,   80,
       78,   79,   76,   80,   82,   84,   83,   91,   13,   14,
       91,   11,    9,   10,   13,    2,   18,   19,   15,   16,
       91,   18,   23,   20,   22,   21,    3,    5,    5,    8,
        8,   89,   29,   30,   81,   30,   26,   26,   29,   29,
       86,   31,   89,    2,    2,    0,   70,   54,   71,   68,

       60,   68,   68,   56,   59,   61,   62,   63,   64,   65,
       66,   67,   68,   51,   32,   48,   46,   38,   46,   46,
       34,   37,   39,   40,   41,   42,   43,   44,   45,   46,
       78,   77,   82,   83,   83,   85,   13,   12,   13,   18,
       17,   18,   20,    3,    5,    5,    8,    8,    8,    8,
       87,   30,   28,   27,    0,   73,   60,   69,   72,   56,
       59,   58,   50,   38,   47,   49,   34,   37,   36,    5,
        8,    7,    8,   28,   27,    0,   56,   57,   34,   36,
        5,    7,    8,    0,   34,   36,    5,    8,    0,   34,
       35,    5,    8,    0,   34,    5,    8,    1,    5,    8,

        4,    8,    6,    4,    6,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    1,    1,    1,    7,    8,
        9,   10,    1,    1,    1,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,    1,   16,    1,
        1,    1,    1,    1,   17,   17,   17,   17,   17,   17,
       11,   11,   11,   11,   11,   18,   11,   11,   19,   11,
       11,   11,   11,   11,   11,   11,   11,   20,   11,   11,
        1,   21,    1,    1,   22,    1,   23,   24,   25,   26,

       27,   28,   29,   11,   11,   11,   11,   30,   31,   32,
       33,   34,   11,   35,   11,   36,   37,   38,   11,   39,
       11,   11,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[42] =
    {   0,
        1,    1,    2,    1,    3,    4,    1,    5,    5,    6,
        7,    8,    9,    9,    9,    4,    9,    7,    7,    7,
       10,    7,    9,    9,    9,    9,    9,    9,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,   11,
       11
    } ;

static yyconst short int yy_base[246] =
    {   0,
        0,   40,   40,   44,   45,   48,   68,   95,   49,   52,
        0,    0,   74,  122,  124,  162,   85,  101,  367,  366,
       51,   53,   55,   65,  358,  764,  109,  764,  764,  764,
       95,  119,  167,  122,    0,  132,  341,  764,  764,  141,
      150,    0,  764,  144,  204,    0,  764,  154,  241,  764,
      165,  764,  764,    0,    0,  764,  163,  764,    0,  764,
      340,  764,  764,  764,  187,  188,    0,  764,  764,  764,
      322,  192,  764,  197,  764,  764,    0,    0,  296,    0,
      200,  201,  139,  316,  764,  280,  191,  200,  236,  310,
        0,  764,  227,  233,  249,  284,    0,  256,  764,  764,

      221,  291,  273,  257,  278,  764,  764,  764,  764,  764,
      764,  764,    0,    0,  293,  764,  764,  264,  272,  269,
      286,  289,  764,  764,  764,  764,  764,  764,  764,    0,
      303,  764,    0,  296,  299,  764,    0,  764,  308,    0,
      764,  311,  314,    0,    0,  237,    0,  326,  340,  235,
        0,  355,  354,   49,  236,  764,  341,  764,  764,  333,
      363,    0,  764,  377,  764,  764,  372,  375,    0,  225,
      389,    0,  213,  226,  361,  205,  386,  764,  389,    0,
      198,    0,  193,  164,  392,    0,  149,  140,  153,  395,
      764,  149,  127,  390,  398,  121,  103,  412,  108,  413,

        0,  416,    0,    0,    0,  764,  425,  436,  447,  458,
      469,  480,  491,  502,  513,  524,  535,  540,  545,  555,
      566,  577,  588,  599,   97,  610,  621,  632,  642,  653,
      664,  675,  686,  697,  708,   91,   75,  719,   65,   55,
      730,   51,   48,  741,  752
    } ;

static yyconst short int yy_def[246] =
    {   0,
      206,    1,  207,  207,  208,  208,  209,  209,  210,  210,
      211,  211,  212,  212,  213,  213,  214,  214,  215,  215,
      216,  216,  217,  217,  206,  206,  206,  206,  206,  206,
      218,  219,  218,   33,  220,  218,  219,  206,  206,  206,
      206,  221,  206,  206,  222,  223,  206,  206,  224,  206,
      206,  206,  206,  225,  226,  206,  227,  206,  228,  206,
      229,  206,  206,  206,  228,  206,  230,  206,  206,  206,
      231,  230,  206,  206,  206,  206,  232,  233,  233,  234,
      234,  206,  218,  219,  206,  235,   33,  218,  218,  218,
      220,  206,  206,  206,  206,  206,  221,  206,  206,  206,

      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  236,  223,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  237,
      206,  206,  226,  227,  227,  206,  228,  206,  228,  230,
      206,  230,  206,  232,  233,  233,  234,  234,  234,  234,
      238,  235,  218,   90,  206,  206,  206,  206,  206,  206,
      206,  239,  206,  206,  206,  206,  206,  206,  240,  233,
      234,  241,  234,  218,  218,  206,  206,  206,  206,  242,
      233,  241,  234,  206,  206,  243,  233,  234,  206,  206,
      206,  233,  234,  206,  206,  233,  234,  206,  233,  234,

      244,  234,  245,  244,  245,    0,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206
    } ;

static yyconst short int yy_nxt[806] =
    {   0,
       26,   27,   28,   27,   29,   26,   30,   26,   26,   26,
       31,   32,   33,   34,   34,   35,   31,   36,   31,   31,
       37,   31,   31,   31,   31,   31,   31,   31,   31,   31,
       31,   31,   31,   31,   31,   31,   31,   31,   31,   38,
       39,   40,   43,   40,   44,   41,   43,   47,   44,   48,
       47,   56,   48,   58,   56,   58,  191,   58,   57,  186,
       45,   57,   81,  180,   45,   49,  175,   58,   49,   51,
       52,   51,   81,  178,   53,   79,   60,   79,  175,   58,
       54,   54,   54,  169,   54,   61,   74,   75,   74,   62,
       54,   54,   54,   54,   54,   54,   51,   52,   51,  162,

       76,   53,   74,   75,   74,  132,   84,   54,   54,   54,
       82,   54,   82,   63,   64,   84,   76,   54,   54,   54,
       54,   54,   54,   65,   60,   65,   68,   66,   85,   58,
       86,   69,   70,   61,  201,   71,   92,   62,  200,   58,
       83,   83,   93,   84,   93,   98,   94,   98,   99,  199,
       84,   95,   84,   95,   83,  115,  197,  115,  116,   84,
       83,   63,   64,   72,   68,   72,  131,   66,  131,   69,
       70,  196,  135,   71,  136,  194,  193,   58,   84,   87,
       87,   87,  192,   96,   88,   89,   90,   84,  139,   95,
      139,   95,   94,  142,  189,  142,   88,   94,  143,   89,

      143,  148,   82,  148,   82,   90,  101,  102,  103,   83,
       83,   84,  149,  149,  149,  188,  104,  104,  105,  187,
       84,   96,  157,   83,  157,  150,  106,  107,   93,   83,
       93,  108,   94,  184,   95,  109,   95,   84,  110,  111,
      183,  112,  113,  118,  119,  120,   84,   84,  153,  153,
       95,  181,   95,  121,  121,  122,   84,   98,  176,   98,
      156,  173,  170,  123,  124,  164,   96,  164,  125,  160,
      160,  161,  126,  166,  165,  127,  128,  159,  129,  130,
      151,  151,   96,  151,  151,  151,  151,  151,  151,  151,
      161,  161,  161,  158,  115,  151,  115,  163,  167,  167,

      168,  168,  168,  168,  131,  206,  131,  206,  135,  139,
      136,  139,  142,   94,  142,  143,   94,  143,  155,  151,
      151,   84,  154,  154,  154,  206,  154,  148,  146,  148,
       84,   85,  154,  154,  154,  154,  154,  154,  149,  149,
      149,  171,  157,  171,  157,  177,  177,  161,  172,   85,
      206,  150,  149,  149,  149,  151,  151,  206,  151,  151,
      151,  151,  151,  151,  151,   84,  153,  153,   58,   58,
      151,  174,   84,  206,   84,  161,  161,  161,  164,  206,
      164,   84,  206,  174,  179,  179,  168,  168,  168,  168,
      171,  198,  171,  198,  151,  151,  206,  172,  161,  161,

      161,  185,  185,  168,  190,  190,  168,  195,  195,  168,
      168,  168,  168,  198,  202,  198,  202,  202,  206,  202,
      206,  203,  206,  206,  203,   42,   42,   42,   42,   42,
       42,   42,   42,   42,   42,   42,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   50,   50,   50,
       50,   50,   50,   50,   50,   50,   50,   50,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   58,
       58,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       59,   59,   59,   59,   59,   59,   59,   59,   59,   59,
       59,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   73,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   78,   78,   78,   78,   78,   78,
       78,   78,   78,   78,   78,   80,   80,   80,   80,   80,
       80,   80,   80,   80,   80,   80,   83,   83,   83,   83,
       84,   84,   84,   84,   84,   91,  206,   91,   91,   91,
       91,   91,   91,   91,   91,   91,   97,  206,  206,   97,
       97,   97,   97,   97,   97,  206,   97,  100,  100,  100,
      100,  100,  100,  100,  100,  100,  100,  100,  114,  206,
      206,  114,  114,  114,  114,  114,  114,  206,  114,  117,

      117,  117,  117,  117,  117,  117,  117,  117,  117,  117,
      133,  206,  133,  133,  133,  206,  133,  133,  133,  133,
      133,  134,  206,  134,  134,  134,  134,  134,  134,  134,
      134,  134,  137,  206,  137,  206,  137,  137,  137,  206,
      137,  137,  138,  206,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  140,  206,  140,  206,  206,  140,  140,
      206,  140,  140,  140,  141,  206,  141,  141,  141,  141,
      141,  141,  141,  141,  141,  144,  206,  144,  144,  144,
      144,  144,  144,  144,  144,  144,  145,  206,  145,  145,
      145,  145,  145,  145,  145,  145,  145,  147,  206,  147,

      147,  147,  147,  147,  147,  147,  147,  147,  152,  206,
      152,  152,  152,  152,  152,  152,  152,  152,  152,  151,
      206,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      182,  206,  182,  182,  182,  182,  182,  182,  182,  182,
      182,  204,  206,  204,  204,  204,  204,  204,  204,  204,
      204,  204,  205,  206,  205,  205,  205,  205,  205,  205,
      205,  205,  205,   25,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206
    } ;

static yyconst short int yy_chk[806] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    2,    3,    2,    4,    5,    4,    5,
        6,    9,    6,   21,   10,   22,  243,   23,    9,  242,
        3,   10,   23,  240,    4,    5,  154,   24,    6,    7,
        7,    7,   24,  239,    7,   21,   13,   22,  154,   13,
        7,    7,    7,  237,    7,   13,   17,   17,   17,   13,
        7,    7,    7,    7,    7,    7,    8,    8,    8,  236,

       17,    8,   18,   18,   18,  225,   31,    8,    8,    8,
       27,    8,   27,   13,   13,   31,   18,    8,    8,    8,
        8,    8,    8,   14,   14,   14,   15,   14,   32,   15,
       32,   15,   15,   14,  199,   15,   36,   14,  197,   15,
       34,   34,   40,   36,   40,   44,   40,   44,   44,  196,
       83,   41,   36,   41,   34,   48,  193,   48,   48,   83,
       34,   14,   14,   16,   16,   16,   51,   16,   51,   16,
       16,  192,   57,   16,   57,  189,  188,   16,   33,   33,
       33,   33,  187,   41,   33,   33,   33,   33,   65,   66,
       65,   66,   65,   72,  184,   72,   33,   72,   74,   33,

       74,   81,   82,   81,   82,   33,   45,   45,   45,   87,
       87,   88,   81,   81,   81,  183,   45,   45,   45,  181,
       88,   66,  101,   87,  101,   81,   45,   45,   93,   87,
       93,   45,   93,  176,   94,   45,   94,  174,   45,   45,
      173,   45,   45,   49,   49,   49,  174,   89,   89,   89,
       95,  170,   95,   49,   49,   49,   89,   98,  155,   98,
       98,  150,  146,   49,   49,  118,   94,  118,   49,  104,
      104,  104,   49,  120,  119,   49,   49,  103,   49,   49,
       86,   86,   95,   86,   86,   86,   86,   86,   86,   86,
      105,  105,  105,  102,  115,   86,  115,  115,  121,  121,

      121,  122,  122,  122,  131,  134,  131,  134,  135,  139,
      135,  139,  142,  139,  142,  143,  142,  143,   96,   86,
       86,   90,   90,   90,   90,   84,   90,  148,   79,  148,
       90,   71,   90,   90,   90,   90,   90,   90,  148,  148,
      148,  149,  157,  149,  157,  160,  160,  160,  149,   61,
       37,  148,  149,  149,  149,  152,  152,   25,  152,  152,
      152,  152,  152,  152,  152,  153,  153,  153,   20,   19,
      152,  153,  175,    0,  153,  161,  161,  161,  164,    0,
      164,  175,    0,  153,  167,  167,  167,  168,  168,  168,
      171,  194,  171,  194,  152,  152,    0,  171,  177,  177,

      177,  179,  179,  179,  185,  185,  185,  190,  190,  190,
      195,  195,  195,  198,  200,  198,  200,  202,    0,  202,
        0,  200,    0,    0,  202,  207,  207,  207,  207,  207,
      207,  207,  207,  207,  207,  207,  208,  208,  208,  208,
      208,  208,  208,  208,  208,  208,  208,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  209,  210,  210,
      210,  210,  210,  210,  210,  210,  210,  210,  210,  211,
      211,  211,  211,  211,  211,  211,  211,  211,  211,  211,
      212,  212,  212,  212,  212,  212,  212,  212,  212,  212,
      212,  213,  213,  213,  213,  213,  213,  213,  213,  213,

      213,  213,  214,  214,  214,  214,  214,  214,  214,  214,
      214,  214,  214,  215,  215,  215,  215,  215,  215,  215,
      215,  215,  215,  215,  216,  216,  216,  216,  216,  216,
      216,  216,  216,  216,  216,  217,  217,  217,  217,  217,
      217,  217,  217,  217,  217,  217,  218,  218,  218,  218,
      219,  219,  219,  219,  219,  220,    0,  220,  220,  220,
      220,  220,  220,  220,  220,  220,  221,    0,    0,  221,
      221,  221,  221,  221,  221,    0,  221,  222,  222,  222,
      222,  222,  222,  222,  222,  222,  222,  222,  223,    0,
        0,  223,  223,  223,  223,  223,  223,    0,  223,  224,

      224,  224,  224,  224,  224,  224,  224,  224,  224,  224,
      226,    0,  226,  226,  226,    0,  226,  226,  226,  226,
      226,  227,    0,  227,  227,  227,  227,  227,  227,  227,
      227,  227,  228,    0,  228,    0,  228,  228,  228,    0,
      228,  228,  229,    0,  229,  229,  229,  229,  229,  229,
      229,  229,  229,  230,    0,  230,    0,    0,  230,  230,
        0,  230,  230,  230,  231,    0,  231,  231,  231,  231,
      231,  231,  231,  231,  231,  232,    0,  232,  232,  232,
      232,  232,  232,  232,  232,  232,  233,    0,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  234,    0,  234,

      234,  234,  234,  234,  234,  234,  234,  234,  235,    0,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  238,
        0,  238,  238,  238,  238,  238,  238,  238,  238,  238,
      241,    0,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  244,    0,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  245,    0,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,
      206,  206,  206,  206,  206,  206,  206,  206,  206,  206,

      206,  206,  206,  206,  206
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tools/wrc/parser.l"
#define INITIAL 0
/* -*-C-*-
 *
 * Copyright 1998-2000	Bertho A. Stultiens (BS)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * History:
 * 21-May-2000 BS	- Fixed the ident requirement of resource names
 *			  which can be keywords.
 * 30-Apr-2000 BS	- Reintegration into the wine-tree
 * 11-Jan-2000 BS	- Very drastic cleanup because we don't have a
 *			  preprocessor in here anymore.
 * 02-Jan-2000 BS	- Removed the preprocessor code
 * 23-Dec-1999 BS	- Removed the copyright for Martin von Loewis.
 *			  There is really nothing left of his code in
 *			  this parser.
 * 20-Jun-1998 BS	- Changed the filename conversion. Filenames are
 *			  case-sensitive inder *nix, but not under dos.
 *			  default behaviour is to convert to lower case.
 *			- All backslashes are converted to forward and
 *			  both single and double slash is recognized as
 *			  MS/Borland does.
 *			- Fixed a bug in 'yywf' case that prevented
 *			  double quoted names to be scanned propperly.
 *
 * 19-May-1998 BS	- Started to build a preprocessor.
 *			- Changed keyword processing completely to
 *			  table-lookups.
 *
 * 20-Apr-1998 BS	- Added ';' comment stripping
 *
 * 17-Apr-1998 BS	- Made the win32 keywords optional when compiling in
 *			  16bit mode
 *
 * 15-Apr-1998 BS	- Changed string handling to include escapes
 *			- Added unicode string handling (no codepage
 *			  translation though).
 *			- 'Borrowed' the main idea of string scanning from
 *			  the flex manual pages.
 *			- Added conditional handling of scanning depending
 *			  on the state of the parser. This was mainly required
 *			  to distinguish a file to load or raw data that
 *			  follows. MS's definition of filenames is rather
 *			  complex... It can be unquoted or double quoted. If
 *			  double quoted, then the '\\' char is not automatically
 *			  escaped according to Borland's rc compiler, but it
 *			  accepts both "\\path\\file.rc" and "\path\file.rc".
 *			  This makes life very hard! I go for the escaped
 *			  version, as this seems to be the documented way...
 *			- Single quoted strings are now parsed and converted
 *			  here.
 *			- Added comment stripping. The implementation is
 *			  'borrowed' from the flex manpages.
 *			- Rebuild string processing so that it may contain
 *			  escaped '\0'.
 */
/* Exclusive string handling */
#define yystr 1

/* Exclusive unicode string handling */
#define yylstr 2

/* Exclusive rcdata single quoted data handling */
#define yyrcd 3

/* Exclusive comment eating... */
#define comment 4

/* Set when stripping c-junk */
#define pp_stripe 5

#define pp_strips 6

#define pp_stripp 7

#define pp_stripp_final 8

/* Set when scanning #line style directives */
#define pp_line 9

/* Set when scanning #pragma */
#define pp_pragma 10

#define pp_code_page 11

#define YY_STACK_USED 1
#define YY_NO_UNPUT 1
#define YY_NO_TOP_STATE 1
#define YY_NEVER_INTERACTIVE 1
/* Some shortcut definitions */
#line 98 "tools/wrc/parser.l"

/*#define LEX_DEBUG*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <assert.h>

#include "wine/unicode.h"
#include "wrc.h"
#include "utils.h"
#include "parser.h"
#include "newstruc.h"

#include "parser.tab.h"

/* Always update the current character position within a line */
#define YY_USER_ACTION	char_number+=yyleng; wanted_id = want_id; want_id = 0;

static void addcchar(char c);
static void addwchar(WCHAR s);
static string_t *get_buffered_cstring(void);
static string_t *get_buffered_wstring(void);
static string_t *make_string(char *s);

static char *cbuffer;		/* Buffers for string collection */
static int cbufidx;
static int cbufalloc = 0;
static WCHAR *wbuffer;
static int wbufidx;
static int wbufalloc = 0;
static int stripslevel = 0;	/* Count {} during pp_strips/pp_stripe mode */
static int stripplevel = 0;	/* Count () during pp_strips mode */
static int cjunk_tagline;	/* Where did we start stripping (helps error tracking) */

static int current_codepage = -1;  /* use language default */

/*
 * This one is a bit tricky.
 * We set 'want_id' in the parser to get the first
 * identifier we get across in the scanner, but we
 * also want it to be reset at nearly any token we
 * see. Exceptions are:
 * - newlines
 * - comments
 * - whitespace
 *
 * The scanner will automatically reset 'want_id'
 * after *each* scanner reduction and puts is value
 * into the var below. In this way we can see the
 * state after the YY_RULE_SETUP (i.e. the user action;
 * see above) and don't have to worry too much when
 * it needs to be reset.
 */
static int wanted_id = 0;
static int save_wanted_id;	/* To save across comment reductions */

struct keyword {
	const char	*keyword;
	int		token;
	int		isextension;
	int		needcase;
	int		alwayskw;
};

static struct keyword keywords[] = {
	{ "ACCELERATORS",	tACCELERATORS,		0, 0, 0},
	{ "ALT",		tALT,			0, 0, 0},
	{ "ASCII",		tASCII,			0, 0, 0},
	{ "AUTO3STATE",		tAUTO3STATE,		1, 0, 0},
	{ "AUTOCHECKBOX",	tAUTOCHECKBOX,		1, 0, 0},
	{ "AUTORADIOBUTTON",	tAUTORADIOBUTTON,	1, 0, 0},
	{ "BEGIN",		tBEGIN,			0, 0, 0},
	{ "BITMAP",		tBITMAP,		0, 0, 0},
	{ "BLOCK",		tBLOCK,			0, 0, 0},
	{ "BUTTON",		tBUTTON,		1, 0, 0},
	{ "CAPTION",		tCAPTION,		0, 0, 0},
	{ "CHARACTERISTICS",	tCHARACTERISTICS,	1, 0, 0},
	{ "CHECKBOX",		tCHECKBOX,		0, 0, 0},
	{ "CHECKED",		tCHECKED,		0, 0, 0},
	{ "CLASS",		tCLASS,			0, 0, 0},
	{ "COMBOBOX",		tCOMBOBOX,		0, 0, 0},
	{ "CONTROL",		tCONTROL,		0, 0, 0},
	{ "CTEXT",		tCTEXT,			0, 0, 0},
	{ "CURSOR",		tCURSOR,		0, 0, 0},
	{ "DEFPUSHBUTTON",	tDEFPUSHBUTTON,		0, 0, 0},
	{ "DIALOG",		tDIALOG,		0, 0, 0},
	{ "DIALOGEX",		tDIALOGEX,		1, 0, 0},
	{ "DISCARDABLE",	tDISCARDABLE,		0, 0, 0},
	{ "DLGINIT",		tDLGINIT,		0, 0, 0},
	{ "EDITTEXT",		tEDITTEXT,		0, 0, 0},
	{ "END",		tEND,			0, 0, 0},
	{ "EXSTYLE",		tEXSTYLE,		0, 0, 0},
	{ "FILEFLAGS",		tFILEFLAGS,		0, 0, 0},
	{ "FILEFLAGSMASK",	tFILEFLAGSMASK,		0, 0, 0},
	{ "FILEOS",		tFILEOS,		0, 0, 0},
	{ "FILESUBTYPE",	tFILESUBTYPE,		0, 0, 0},
	{ "FILETYPE",		tFILETYPE,		0, 0, 0},
	{ "FILEVERSION",	tFILEVERSION,		0, 0, 0},
	{ "FIXED",		tFIXED,			0, 0, 0},
	{ "FONT",		tFONT,			0, 0, 0},
	{ "FONTDIR",		tFONTDIR,		0, 0, 0},	/* This is a Borland BRC extension */
	{ "GRAYED",		tGRAYED,		0, 0, 0},
	{ "GROUPBOX",		tGROUPBOX,		0, 0, 0},
	{ "HELP",		tHELP,			0, 0, 0},
	{ "HTML",		tHTML,			0, 0, 0},
	{ "ICON",		tICON,			0, 0, 0},
	{ "IMPURE",		tIMPURE,		0, 0, 0},
	{ "INACTIVE",		tINACTIVE,		0, 0, 0},
	{ "LANGUAGE",		tLANGUAGE,		1, 0, 1},
	{ "LISTBOX",		tLISTBOX,		0, 0, 0},
	{ "LOADONCALL",		tLOADONCALL,		0, 0, 0},
	{ "LTEXT",		tLTEXT,			0, 0, 0},
	{ "MENU",		tMENU,			0, 0, 0},
	{ "MENUBARBREAK",	tMENUBARBREAK,		0, 0, 0},
	{ "MENUBREAK",		tMENUBREAK,		0, 0, 0},
	{ "MENUEX",		tMENUEX,		1, 0, 0},
	{ "MENUITEM",		tMENUITEM,		0, 0, 0},
	{ "MESSAGETABLE",	tMESSAGETABLE,		1, 0, 0},
	{ "MOVEABLE",		tMOVEABLE,		0, 0, 0},
	{ "NOINVERT",		tNOINVERT,		0, 0, 0},
	{ "NOT",		tNOT,			0, 0, 0},
	{ "POPUP",		tPOPUP,			0, 0, 0},
	{ "PRELOAD",		tPRELOAD,		0, 0, 0},
	{ "PRODUCTVERSION",	tPRODUCTVERSION,	0, 0, 0},
	{ "PURE",		tPURE,			0, 0, 0},
	{ "PUSHBUTTON",		tPUSHBUTTON,		0, 0, 0},
	{ "RADIOBUTTON",	tRADIOBUTTON,		0, 0, 0},
	{ "RCDATA",		tRCDATA,		0, 0, 0},
	{ "RTEXT",		tRTEXT,			0, 0, 0},
	{ "SCROLLBAR",		tSCROLLBAR,		0, 0, 0},
	{ "SEPARATOR",		tSEPARATOR,		0, 0, 0},
	{ "SHIFT",		tSHIFT,			0, 0, 0},
	{ "STATE3",		tSTATE3,		1, 0, 0},
	{ "STRING",		tSTRING,		0, 0, 0},
	{ "STRINGTABLE",	tSTRINGTABLE,		0, 0, 1},
	{ "STYLE",		tSTYLE,			0, 0, 0},
	{ "TOOLBAR",		tTOOLBAR,		1, 0, 0},
	{ "VALUE",		tVALUE,			0, 0, 0},
	{ "VERSION",		tVERSION,		1, 0, 0},
	{ "VERSIONINFO",	tVERSIONINFO,		0, 0, 0},
	{ "VIRTKEY",		tVIRTKEY,		0, 0, 0}
};

#define NKEYWORDS	(sizeof(keywords)/sizeof(keywords[0]))
#define KWP(p)		((const struct keyword *)(p))
static int kw_cmp_func(const void *s1, const void *s2)
{
	int ret;
	ret = strcasecmp(KWP(s1)->keyword, KWP(s2)->keyword);
	if(!ret && (KWP(s1)->needcase || KWP(s2)->needcase))
		return strcmp(KWP(s1)->keyword, KWP(s2)->keyword);
	else
		return ret;
}

#define KW_BSEARCH
#define DO_SORT
static struct keyword *iskeyword(char *kw)
{
	struct keyword *kwp;
	struct keyword key;
	key.keyword = kw;
	key.needcase = 0;
#ifdef DO_SORT
	{
		/* Make sure that it is sorted for bsearsh */
		static int sorted = 0;
		if(!sorted)
		{
			qsort(keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
			sorted = 1;
		}
	}
#endif
#ifdef KW_BSEARCH
	kwp = bsearch(&key, keywords, NKEYWORDS, sizeof(keywords[0]), kw_cmp_func);
#else
	{
		int i;
		for(i = 0; i < NKEYWORDS; i++)
		{
			if(!kw_cmp_func(&key, &keywords[i]))
				break;
		}
		if(i < NKEYWORDS)
			kwp = &keywords[i];
		else
			kwp = NULL;
	}
#endif

	if(kwp == NULL || (kwp->isextension && !extensions))
		return NULL;
	else
		return kwp;
}

/*
 **************************************************************************
 * The flexer starts here
 **************************************************************************
 */
#line 925 "tools/wrc/lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 304 "tools/wrc/parser.l"

	/*
	 * Catch the GCC-style line statements here and parse them.
	 * This has the advantage that you can #include at any
	 * stage in the resource file.
	 * The preprocessor generates line directives in the format:
	 * # <linenum> "filename" <codes>
	 *
	 * Codes can be a sequence of:
	 * - 1 start of new file
	 * - 2 returning to previous
	 * - 3 system header
	 * - 4 interpret as C-code
	 *
	 * 4 is not used and 1 mutually excludes 2
	 * Anyhow, we are not really interested in these at all
	 * because we only want to know the linenumber and
	 * filename.
	 */
#line 1099 "tools/wrc/lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 207 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 764 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 323 "tools/wrc/parser.l"
yy_push_state(pp_pragma);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 324 "tools/wrc/parser.l"
yy_push_state(pp_line);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 325 "tools/wrc/parser.l"
{
		int lineno;
		char *cptr;
		char *fname;
		yy_pop_state();
		lineno = (int)strtol(yytext, &cptr, 10);
		if(!lineno)
			yyerror("Malformed '#...' line-directive; invalid linenumber");
		fname = strchr(cptr, '"');
		if(!fname)
			yyerror("Malformed '#...' line-directive; missing filename");
		fname++;
		cptr = strchr(fname, '"');
		if(!cptr)
			yyerror("Malformed '#...' line-directive; missing terminating \"");
		*cptr = '\0';
		line_number = lineno - 1;	/* We didn't read the newline */
		input_name = xstrdup(fname);
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 345 "tools/wrc/parser.l"
yyless(9); yy_pop_state(); yy_push_state(pp_code_page);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 346 "tools/wrc/parser.l"
yy_pop_state(); if (pedantic) yywarning("Unrecognized #pragma directive '%s'",yytext);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 348 "tools/wrc/parser.l"
current_codepage = -1; yy_pop_state();
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 349 "tools/wrc/parser.l"
{
        char *p = yytext;
        yy_pop_state();
        while (*p < '0' || *p > '9') p++;
        current_codepage = strtol( p, NULL, 10 );
        if (current_codepage && !wine_cp_get_table( current_codepage ))
        {
            yyerror("Codepage %d not supported", current_codepage);
            current_codepage = 0;
        }
    }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 360 "tools/wrc/parser.l"
yy_pop_state(); yyerror("Malformed #pragma code_page directive");
	YY_BREAK
/*
	 * Strip everything until a ';' taking
	 * into account braces {} for structures,
	 * classes and enums.
	 */
case 9:
YY_RULE_SETUP
#line 367 "tools/wrc/parser.l"
stripslevel++;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 368 "tools/wrc/parser.l"
stripslevel--;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 369 "tools/wrc/parser.l"
if(!stripslevel) yy_pop_state();
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 370 "tools/wrc/parser.l"
; /* To catch comments */
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 371 "tools/wrc/parser.l"
; /* Ignore rest */
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 372 "tools/wrc/parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 374 "tools/wrc/parser.l"
stripplevel++;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 375 "tools/wrc/parser.l"
{
					stripplevel--;
					if(!stripplevel)
					{
						yy_pop_state();
						yy_push_state(pp_stripp_final);
					}
				}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 383 "tools/wrc/parser.l"
; /* To catch comments */
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 384 "tools/wrc/parser.l"
; /* Ignore rest */
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 385 "tools/wrc/parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 387 "tools/wrc/parser.l"
; /* Ignore */
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 388 "tools/wrc/parser.l"
yy_pop_state(); /* Kill the semicolon */
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 389 "tools/wrc/parser.l"
line_number++; char_number = 1; yy_pop_state();
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 390 "tools/wrc/parser.l"
yyless(0); yy_pop_state();
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 392 "tools/wrc/parser.l"
return tBEGIN;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 393 "tools/wrc/parser.l"
return tEND;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 395 "tools/wrc/parser.l"
{ yylval.num = strtoul(yytext,  0, 10); return toupper(yytext[yyleng-1]) == 'L' ? tLNUMBER : tNUMBER; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 396 "tools/wrc/parser.l"
{ yylval.num = strtoul(yytext,  0, 16); return toupper(yytext[yyleng-1]) == 'L' ? tLNUMBER : tNUMBER; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 397 "tools/wrc/parser.l"
{ yylval.num = strtoul(yytext+2, 0, 8); return toupper(yytext[yyleng-1]) == 'L' ? tLNUMBER : tNUMBER; }
	YY_BREAK
/*
	 * The next two rules scan identifiers and filenames.
	 * This is achieved by using the priority ruling
	 * of the scanner where a '.' is valid in a filename
	 * and *only* in a filename. In this case, the second
	 * rule will be reduced because it is longer.
	 */
case 29:
YY_RULE_SETUP
#line 406 "tools/wrc/parser.l"
{
				struct keyword *tok = iskeyword(yytext);

				if(tok)
				{
					if(wanted_id && !tok->alwayskw)
					{
						yylval.str = make_string(yytext);
						return tIDENT;
					}
					else
						return tok->token;
				}
				else
				{
					yylval.str = make_string(yytext);
					return tIDENT;
				}
			}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 425 "tools/wrc/parser.l"
yylval.str = make_string(yytext); return tFILENAME;
	YY_BREAK
/*
	 * Wide string scanning
	 */
case 31:
YY_RULE_SETUP
#line 430 "tools/wrc/parser.l"
{
				yy_push_state(yylstr);
				wbufidx = 0;
				if(!win32)
					yywarning("16bit resource contains unicode strings\n");
			}
	YY_BREAK
case 32:
#line 437 "tools/wrc/parser.l"
case 33:
YY_RULE_SETUP
#line 437 "tools/wrc/parser.l"
{
				yy_pop_state();
				yylval.str = get_buffered_wstring();
				return tSTRING;
			}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 442 "tools/wrc/parser.l"
{ /* octal escape sequence */
				unsigned int result;
				result = strtoul(yytext+1, 0, 8);
				if ( result > 0xffff )
					yyerror("Character constant out of range");
				addwchar((WCHAR)result);
			}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 449 "tools/wrc/parser.l"
{  /* hex escape sequence */
				unsigned int result;
				result = strtoul(yytext+2, 0, 16);
				addwchar((WCHAR)result);
			}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 454 "tools/wrc/parser.l"
{  yyerror("Invalid hex escape sequence '%s'", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 456 "tools/wrc/parser.l"
yyerror("Bad escape sequence");
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 457 "tools/wrc/parser.l"
line_number++; char_number = 1; /* backslash at EOL continues string after leading whitespace on next line */
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 458 "tools/wrc/parser.l"
addwchar('\a');
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 459 "tools/wrc/parser.l"
addwchar('\b');
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 460 "tools/wrc/parser.l"
addwchar('\f');
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 461 "tools/wrc/parser.l"
addwchar('\n');
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 462 "tools/wrc/parser.l"
addwchar('\r');
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 463 "tools/wrc/parser.l"
addwchar('\t');
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 464 "tools/wrc/parser.l"
addwchar('\v');
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 465 "tools/wrc/parser.l"
addwchar(yytext[1]);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 466 "tools/wrc/parser.l"
addwchar(yytext[2]); line_number++; char_number = 1;
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 467 "tools/wrc/parser.l"
addwchar('\"');		/* "bla""bla"  -> "bla\"bla" */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 468 "tools/wrc/parser.l"
addwchar('\"');		/* "bla\""bla" -> "bla\"bla" */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 469 "tools/wrc/parser.l"
;			/* "bla" "bla" -> "blabla" */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 470 "tools/wrc/parser.l"
{
				char *yptr = yytext;
				while(*yptr)	/* FIXME: codepage translation */
					addwchar(*yptr++ & 0xff);
			}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 475 "tools/wrc/parser.l"
yyerror("Unterminated string");
	YY_BREAK
/*
	 * Normal string scanning
	 */
case 53:
YY_RULE_SETUP
#line 480 "tools/wrc/parser.l"
yy_push_state(yystr); cbufidx = 0;
	YY_BREAK
case 54:
#line 482 "tools/wrc/parser.l"
case 55:
YY_RULE_SETUP
#line 482 "tools/wrc/parser.l"
{
				yy_pop_state();
				yylval.str = get_buffered_cstring();
				return tSTRING;
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 487 "tools/wrc/parser.l"
{ /* octal escape sequence */
				int result;
				result = strtol(yytext+1, 0, 8);
				if ( result > 0xff )
					yyerror("Character constant out of range");
				addcchar((char)result);
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 494 "tools/wrc/parser.l"
{  /* hex escape sequence */
				int result;
				result = strtol(yytext+2, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 499 "tools/wrc/parser.l"
{  yyerror("Invalid hex escape sequence '%s'", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 501 "tools/wrc/parser.l"
yyerror("Bad escape sequence");
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 502 "tools/wrc/parser.l"
line_number++; char_number = 1; /* backslash at EOL continues string after leading whitespace on next line */
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 503 "tools/wrc/parser.l"
addcchar('\a');
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 504 "tools/wrc/parser.l"
addcchar('\b');
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 505 "tools/wrc/parser.l"
addcchar('\f');
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 506 "tools/wrc/parser.l"
addcchar('\n');
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 507 "tools/wrc/parser.l"
addcchar('\r');
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 508 "tools/wrc/parser.l"
addcchar('\t');
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 509 "tools/wrc/parser.l"
addcchar('\v');
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 510 "tools/wrc/parser.l"
addcchar(yytext[1]);
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 511 "tools/wrc/parser.l"
addcchar(yytext[2]); line_number++; char_number = 1;
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 512 "tools/wrc/parser.l"
{
				char *yptr = yytext;
				while(*yptr)
					addcchar(*yptr++);
			}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 517 "tools/wrc/parser.l"
addcchar('\"');		/* "bla""bla"   -> "bla\"bla" */
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 518 "tools/wrc/parser.l"
addcchar('\"');		/* "bla\""bla"  -> "bla\"bla" */
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 519 "tools/wrc/parser.l"
;			/* "bla" "bla"  -> "blabla" */
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 520 "tools/wrc/parser.l"
yyerror("Unterminated string");
	YY_BREAK
/*
	 * Raw data scanning
	 */
case 75:
YY_RULE_SETUP
#line 525 "tools/wrc/parser.l"
yy_push_state(yyrcd); cbufidx = 0;
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 526 "tools/wrc/parser.l"
{
				yy_pop_state();
				yylval.raw = new_raw_data();
				yylval.raw->size = cbufidx;
				yylval.raw->data = xmalloc(yylval.raw->size);
				memcpy(yylval.raw->data, cbuffer, yylval.raw->size);
				return tRAWDATA;
			}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 534 "tools/wrc/parser.l"
{
				int result;
				result = strtol(yytext, 0, 16);
				addcchar((char)result);
			}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 539 "tools/wrc/parser.l"
;	/* Ignore space */
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 540 "tools/wrc/parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 541 "tools/wrc/parser.l"
yyerror("Malformed data-line");
	YY_BREAK
/*
	 * Comment stripping
	 * Should never occur after preprocessing
	 */
case 81:
YY_RULE_SETUP
#line 547 "tools/wrc/parser.l"
{
				yy_push_state(comment);
				save_wanted_id = wanted_id;
				if(!no_preprocess)
					yywarning("Found comments after preprocessing, please report");
			}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 553 "tools/wrc/parser.l"
;
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 554 "tools/wrc/parser.l"
;
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 555 "tools/wrc/parser.l"
line_number++; char_number = 1;
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 556 "tools/wrc/parser.l"
yy_pop_state(); want_id = save_wanted_id;
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 558 "tools/wrc/parser.l"
want_id = wanted_id; /* not really comment, but left-over c-junk */
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 559 "tools/wrc/parser.l"
want_id = wanted_id; if(!no_preprocess) yywarning("Found comments after preprocessing, please report");
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 561 "tools/wrc/parser.l"
{
				want_id = wanted_id;
				line_number++;
				char_number = 1;
				if(want_nl)
				{
					want_nl = 0;
					return tNL;
				}
			}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 571 "tools/wrc/parser.l"
want_id = wanted_id;	/* Eat whitespace */
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 573 "tools/wrc/parser.l"
return yytext[0];
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(yystr):
case YY_STATE_EOF(yylstr):
case YY_STATE_EOF(yyrcd):
case YY_STATE_EOF(comment):
case YY_STATE_EOF(pp_stripe):
case YY_STATE_EOF(pp_strips):
case YY_STATE_EOF(pp_stripp):
case YY_STATE_EOF(pp_stripp_final):
case YY_STATE_EOF(pp_line):
case YY_STATE_EOF(pp_pragma):
case YY_STATE_EOF(pp_code_page):
#line 575 "tools/wrc/parser.l"
{
				if(YY_START == pp_strips || YY_START == pp_stripe || YY_START == pp_stripp || YY_START == pp_stripp_final)
					yyerror("Unexpected end of file during c-junk scanning (started at %d)", cjunk_tagline);
				else
					yyterminate();
			}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 582 "tools/wrc/parser.l"
{
				/* Catch all rule to find any unmatched text */
				if(*yytext == '\n')
				{
					line_number++;
					char_number = 1;
				}
				yywarning("Unmatched text '%c' (0x%02x) YY_START=%d stripslevel=%d",
					isprint(*yytext & 0xff) ? *yytext : '.', *yytext, YY_START,stripslevel);
			}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 593 "tools/wrc/parser.l"
ECHO;
	YY_BREAK
#line 1810 "tools/wrc/lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 207 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 207 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 206);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}
#endif /* YY_NO_INPUT */

#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}



#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 593 "tools/wrc/parser.l"


#ifndef yywrap
int yywrap(void)
{
#if 0
	if(bufferstackidx > 0)
	{
		return 0;
 	}
#endif
	return 1;
}
#endif

/* These dup functions copy the enclosed '\0' from
 * the resource string.
 */
static void addcchar(char c)
{
	if(cbufidx >= cbufalloc)
	{
		cbufalloc += 1024;
		cbuffer = xrealloc(cbuffer, cbufalloc * sizeof(cbuffer[0]));
		if(cbufalloc > 65536)
			yywarning("Reallocating string buffer larger than 64kB");
	}
	cbuffer[cbufidx++] = c;
}

static void addwchar(WCHAR s)
{
	if(wbufidx >= wbufalloc)
	{
		wbufalloc += 1024;
		wbuffer = xrealloc(wbuffer, wbufalloc * sizeof(wbuffer[0]));
		if(wbufalloc > 65536)
			yywarning("Reallocating wide string buffer larger than 64kB");
	}
	wbuffer[wbufidx++] = s;
}

static string_t *get_buffered_cstring(void)
{
    string_t *str = new_string();

    str->size = cbufidx;
    str->type = str_char;
    str->str.cstr = (char *)xmalloc(cbufidx+1);
    memcpy(str->str.cstr, cbuffer, cbufidx);
    str->str.cstr[cbufidx] = '\0';

    if (!current_codepage || current_codepage == -1 || !win32)  /* store as ANSI string */
    {
        if (!current_codepage) yyerror("Codepage set to Unicode only, cannot use ASCII string here");
        return str;
    }
    else  /* convert to Unicode before storing */
    {
        string_t *str_w = convert_string( str, str_unicode, current_codepage );
        if (!check_unicode_conversion( str, str_w, current_codepage ))
            yyerror("String %s does not convert identically to Unicode and back in codepage %d. "
                    "Try using a Unicode string instead.", str->str.cstr, current_codepage );
        free_string( str );
        return str_w;
    }
}

static string_t *get_buffered_wstring(void)
{
	string_t *str = new_string();
	str->size = wbufidx;
	str->type = str_unicode;
	str->str.wstr = xmalloc((wbufidx+1)*sizeof(WCHAR));
	memcpy(str->str.wstr, wbuffer, wbufidx*sizeof(WCHAR));
	str->str.wstr[wbufidx] = 0;
	return str;
}

static string_t *make_string(char *s)
{
	string_t *str = new_string();
	str->size = strlen(s);
	str->type = str_char;
	str->str.cstr = (char *)xmalloc(str->size+1);
	memcpy(str->str.cstr, s, str->size+1);
	return str;
}
