[
uuid(b574a080-aceb-11d3-95f9-aa43ded19f71),
version(1.0),
pointer_default(unique)
]
interface hello
{
  struct _hello_struct
  {
    int hello_member;
    int hello1_member;
    float hello3_member;
  };
  
  typedef struct _hello2_struct
  {
    int hello2_member;
  } __hello2_struct;
  
  typedef struct
  {
    int hello3_member;
  } hello3_typedef;

  typedef int hello_t;
  
  void Hello4Proc([in] hello3_typedef ii);
  void Hello3Proc([in] __hello2_struct h);
  void Hello2Proc([in] struct _hello_struct h);
  void HelloProc([in] hello_t pszString);
  void Shutdown(void);
  void RpcBenchmark(handle_t Server,
		    [out, size_is(32768)] unsigned char* pcOutBuffer);
}
