// no msg
#define ID_CDLDBG_NOMSG                              0

#define ID_CDLDBG_MISSING_DLLREGISTERSERVER          10000
#define ID_CDLDBG_INCOMPATIBLE_BINARY                10001
#define ID_CDLDBG_VERIFYTRUST_FAILED                 10002
#define ID_CDLDBG_ERR_PRIMARY_LANGUAGE               10003
#define ID_CDLDBG_ERR_NO_SECTION                     10004
#define ID_CDLDBG_SATELLITE_FOUND                    10005
#define ID_CDLDBG_PROCESSINF_FAILED                  10006
#define ID_CDLDBG_COMPLETEONE_IN                     10007
#define ID_CDLDBG_ONSTOPBINDING_CALLED               10008
#define ID_CDLDBG_FOUND_DUP                          10009
#define ID_CDLDBG_DOSETUP_FAILED                     10010
#define ID_CDLDBG_NO_IWINDOWFORBINDINGUI             10011
#define ID_CDLDBG_RUNSETUPHOOK_FAILED                10012
#define ID_CDLDBG_OBJ_TAG_MIXED_USAGE                10013
#define ID_CDLDBG_FAILED_OSD_OM                      10014
#define ID_CDLDBG_DU_REQUIRED_ATTRIB_MISSING         10015
#define ID_CDLDBG_NATIVECODE_SYNTAX                  10016
#define ID_CDLDBG_CODEBASE_SYNTAX                    10017
#define ID_CDLDBG_BAD_INF_FROM_OSD                   10018
#define ID_CDLDBG_JAVAPACKAGE_SYNTAX                 10019
#define ID_CDLDBG_DEPENDENCY_SYNTAX                  10020
#define ID_CDLDBG_DEPENDENCY_SOFTDIST_SYNTAX         10021
#define ID_CDLDBG_CDL_HANDLER_MISSING                10022

#define ID_CDLDBG_FILE_INUSE                         10023
#define ID_CDLDBG_SETUP_COMPLETE                     10024
#define ID_CDLDBG_HOOK_COMPLETE                      10025
#define ID_CDLDBG_DLL_REGISTERED                     10026
#define ID_CDLDBG_ITEM_PROCESSED                     10027
#define ID_CDLDBG_JAVA_PKG_SETUP                     10028
#define ID_CDLDBG_JAVA_PKG_FAILED                    10029
#define ID_CDLDBG_DL_REDUNDANT                       10030
#define ID_CDLDBG_DL_REDUNDANT_FAILED                10031
#define ID_CDLDBG_DL_ON_STOP_BINDING                 10032
#define ID_CDLDBG_DL_UPDATE_DU_NO_VERS               10033
#define ID_CDLDBG_DETAILS                            10034
#define ID_CDLDBG_FAILED_CONVERT_CLSID               10035
#define ID_CDLDBG_FAILED_STRING_FROM_CLSID           10036
#define ID_CDLDBG_ERROR_STRING                       10037
#define ID_CDLDBG_DETAILS_STRING                     10038
#define ID_CDLDBG_UNKNOWN_ERROR                      10039
#define ID_CDLDBG_UNKNOWN_SETUP_ERROR                10040

#define ID_CDLDBG_WX86_REQUIRE_PRIMARY_ARCH          10041
#define ID_CDLDBG_WX86_REQUIRE_ALTERNATE_ARCH        10042
#define ID_CDLDBG_CANNOT_REPLACE_SFP_FILE            10043

