#----------------------------------------------------------------------------
#
# Description:
#
#	makefile for the RSA 32 library
#
# History: 
#
#  raymondm 11/1/94 raymondm created
#
#----------------------------------------------------------------------------

#!include $(_NTDRIVE)$(_NTROOT)\private\security\makefile.sec

!INCLUDE $(NTMAKEENV)\makefile.def















