/*
 * COM Classes for dpvoice
 *
 * Copyright 2014 Alistair Leslie-Hughes
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    helpstring("DirectPlayVoice Client Object"),
    threading(both),
    progid("DirectPlayVoice.Client.1"),
    vi_progid("DirectPlayVoice.Client"),
    uuid(b9f3eb85-b781-4ac1-8d90-93a05ee37d7d)
]
coclass DirectPlayVoiceClient { interface IDirectPlayVoiceClient; }

[
    helpstring("DirectPlayVoice Server Object"),
    threading(both),
    progid("DirectPlayVoice.Server.1"),
    vi_progid("DirectPlayVoice.Server"),
    uuid(d3f5b8e6-9b78-4a4c-94ea-ca2397b663d3)
]
coclass DirectPlayVoiceServer { interface IDirectPlayVoiceServer; }

[
    helpstring("DirectPlayVoice Test Object"),
    threading(both),
    progid("DirectPlayVoice.Test.1"),
    vi_progid("DirectPlayVoice.Test"),
    uuid(0f0f094b-b01c-4091-a14d-dd0cd807711a)
]
coclass DirectPlayVoiceTest { interface IDirectPlayVoiceTest; }
