mkdir -p $1/reactos
mkdir -p $1/reactos/system32
mkdir -p $1/reactos/system32/drivers
mkdir -p $1/reactos/bin
#cp fdisk.exe $1
#cp format.exe $1
cp loaders/dos/loadros.com $1
cp ntoskrnl/ntoskrnl.exe $1
cp services/fs/vfat/vfatfs.sys $1
cp services/dd/ide/ide.sys $1
#cp services/dd/floppy/floppy.sys $1
#cp ntoskrnl/ntoskrnl.exe $1/reactos/system32/
#cp services/fs/vfat/vfatfs.sys $1/reactos/system32/drivers/
#cp services/dd/ide/ide.sys $1/reactos/system32/drivers/
