# $Id: makefile,v 1.10 2003/02/15 19:16:33 gvg Exp $

PATH_TO_TOP = ../../../..

TARGET_TYPE = driver

TARGET_NAME = vgamp

TARGET_DDKLIBS = videoprt.a

TARGET_OBJECTS = \
  initvga.o \
  vgamp.o \
  vgavideo.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
