//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by appmgr.rc
//
#define IDS_NAME                        1
#define IDS_INFO                        2
#define IDS_REMOVE1                     3
#define IDS_REMOVE2                     4
#define IDS_ADD1                        5
#define IDS_ADD2                        6
#define IDS_ADD3                        7
#define IDS_ADD4                        8
#define IDS_COLUMN_NAME                 9
#define IDS_COLUMN_VERSION              10
#define IDS_UNKNOWN_VERSION             11
#define IDS_ADD_START1                  12
#define IDS_ADD_START2                  13
#define IDS_MEDIASELECT1                14
#define IDS_MEDIASELECT2                15
#define IDS_INSTALL_NAMES               16
#define IDS_INSTALL_EXTENSIONS          17
#define IDS_MEDIA_FLOPPY                18
#define IDS_MEDIA_CDROM                 19
#define IDS_MEDIATEXT_CDROM             20
#define IDS_MEDIATEXT_FLOPPY            21
#define IDS_PLACEHOLDER                 22
#define IDS_MEDIA_TRYAGAIN              23
#define IDS_OPERATION_APPLIST           24
#define IDS_OPERATION_DS                25
#define IDS_NOT_IMPLEMENTED             26
#define IDS_BROWSE_INVALIDNAME          27
#define IDS_REPAIR_REPAIR               28
#define IDS_REPAIR_REINSTALL            29
#define IDS_BROWSE_STILLNOMEDIA         30
#define IDS_LARGEFONTNAME               31
#define IDS_LARGEFONTSIZE               32
#define IDS_MODIFYPROGRAM1              33
#define IDS_MODIFYPROGRAM2              34
#define IDS_ADDSOURCE1                  35
#define IDS_ADDSOURCE2                  36
#define IDS_ADDNOMEDIA1                 37
#define IDS_ADDNOMEDIA2                 38
#define IDS_INTERNETSITE1               39
#define IDS_INTERNETSITE2               40
#define IDS_REPAIRPROGRAM1              41
#define IDS_REPAIRPROGRAM2              42
#define IDS_ADDPROGRAM1                 43
#define IDS_ADDPROGRAM2                 44
#define IDS_ADDBROWSE1                  45
#define IDS_ADDBROWSE2                  46
#define IDS_INSTALLSUCCESS              47
#define IDS_INSTALLFAIL                 48
#define IDS_MEDIADETECT1                49
#define IDS_MEDIADETECT2                50
#define IDS_MEDIAERROR_CD               52
#define IDS_MEDIAERROR_FLOPPY           53
#define IDI_ICON                        102
#define IDB_PROGRAMS                    104
#define IDB_BITMAP1                     105
#define IDD_REMOVE_FINISH               105
#define IDD_REPAIR_FINISH               105
#define IDD_PROPPAGE_MEDIUM             106
#define IDD_WELCOME                     106
#define IDB_BITMAP2                     106
#define IDD_REMOVE_START                107
#define IDB_WATERMARK                   107
#define IDD_ADD_MEDIADETECT             107
#define IDD_ADD_SOURCE                  108
#define IDD_ADD_MEDIASELECT             109
#define IDD_ADD_FINISH                  110
#define IDD_WELCOME2                    111
#define IDD_REMOVE_PROGRAM              112
#define IDD_REPAIR_PROGRAM              112
#define IDD_MODIFY_FINISH               113
#define IDD_MODIFY_PROGRAM              114
#define IDD_ADD_PROGRAM                 115
#define IDB_CD                          119
#define IDB_FLOPPY                      120
#define IDD_UPGRADE_PROGRAM             121
#define IDD_ADD_BROWSE                  122
#define IDD_UPGRADE_FINISH              123
#define IDD_INTERNET_CHOOSE             124
#define IDD_FINISH_MEDIA_ERROR          126
#define IDD_FINISH_MEDIA                127
#define IDD_ADD_FINISH_CORP             128
#define IDD_REPAIR_DLG                  129
#define IDD_REPAIR_DLG2                 130
#define IDD_ADD_FINISH_BROWSE           131
#define IDD_INTERNETSITE                132
#define IDD_ADD_CANCEL                  133
#define IDD_ADD_NOMEDIA                 134
#define IDD_MODIFY_CANCEL               135
#define IDA_FINDFILE                    137
#define IDA_FINDCOMP                    138
#define IDD_ADD_CANCEL_CORPNET          139
#define IDD_REPAIRDLG1                  140
#define IDD_REPAIR_FINISH_CANCEL        141
#define IDB_WATERMARK_EXTERIOR          142
#define IDB_WATERMARK_INTERIOR          143
#define IDD_ADD_CANCEL_INTERNET         144
#define IDD_ADD_FINISH_INTERNET         145
#define IDD_UPGRADE_CANCEL              146
#define IDD_ADD_MEDIADETECT_ERROR       147
#define IDD_GENERAL_PROPERTIES          147
#define IDD_MEDIADETECT_FINISH          148
#define IDD_ADD_MEDIADETECT_FINISH      148
#define IDD_PROPPAGE_MEDIUM1            148
#define IDD_INSTALL_PROPERTIES          148
#define IDD_OFFLINE_PROPERTIES          149
#define IDC_ADDRADIO                    1001
#define IDC_REMOVERADIO                 1002
#define IDC_ADDRADIO2                   1002
#define IDC_RADIOOTHER                  1002
#define IDC_APPLICATION_LIST            1003
#define IDC_RADIO_LOCALMEDIA            1004
#define IDC_RADIO_CORPNET               1005
#define IDC_REMOVERADIO2                1005
#define IDC_RADIO_REPAIR                1005
#define IDC_RADIO_INTERNET              1006
#define IDC_REMOVERADIO3                1006
#define IDC_APPLICATION_NAME            1007
#define IDC_REMOVERADIO4                1007
#define IDC_RADIOUPGRADE                1007
#define IDC_BUTTON_CDROM                1008
#define IDC_BUTTON_FLOPPY               1009
#define IDC_TEXT_SOURCE                 1010
#define IDC_BUTTON1                     1012
#define IDC_BUTTON2                     1013
#define IDC_PROGRESS1                   1013
#define IDC_BUTTON3                     1014
#define IDC_EDIT1                       1014
#define IDC_EDIT_INTERNETADDRESS        1014
#define IDC_BUTTONUPGRADE               1014
#define IDC_MEDIA_TEXT                  1015
#define IDC_MEDIA_BROWSE                1016
#define IDC_MODIFY_REMOVE               1017
#define IDC_ANIMATE1                    1018
#define IDC_OPERATION_TEXT              1019
#define IDC_SETUPPATH                   1020
#define IDC_SETUPPATH_DISPLAY           1021
#define IDC_BUTTON_ADD                  1022
#define IDC_BUTTON_BROWSE               1023
#define IDC_BUTTON_MODIFY               1024
#define IDC_BUTTON_FIND                 1024
#define IDC_BUTTON_REPAIR               1025
#define IDC_RADIO_REINSTALL             1026
#define IDC_RADIOMICROSOFT              1028
#define IDC_TITLE_SMALL                 1029
#define IDC_TITLE_LARGE                 1030
#define IDC_ADDBROWSE_BROWSE            1031
#define IDC_PROPERTIES                  1032
#define IDC_BUTTON_PROPERTIES           1032
#define IDC_INSTALL_LOCATION            1033
#define IDC_INSTALL_SOURCE              1034
#define IDC_REQUIRED_POLICY             1035
#define IDC_ADMINISTRATIVE_CONTACT      1036
#define IDC_PRODUCT_NAME                1037
#define IDC_FOO                         1037
#define IDC_VERSION                     1038
#define IDC_PUBLISHER                   1039
#define IDC_PRODUCT_ID                  1040
#define IDC_REGISTERED_OWNER            1041
#define IDC_REGISTERED_COMPANY          1042
#define IDC_LANGUAGE                    1043
#define IDC_SUPPORT_URL                 1044
#define IDC_SUPPORT_TELEPHONE           1045
#define IDC_HELP_FILE                   1046
#define IDC_RADIO_ONLINE                1047
#define IDC_RADIO_OFFLINE               1048
#define IDC_NOMEDIA_TEXT                1049
#define IDC_STATIC                      -1
#define IDC_REPAIR_ACTION               65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1050
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
