# $Id: makefile,v 1.1 2003/05/02 18:08:39 ekohl Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = program

TARGET_APPTYPE = windows

TARGET_NAME = setup

TARGET_INSTALLDIR = system32

TARGET_SDKLIBS = kernel32.a

TARGET_CFLAGS = -DUNICODE

TARGET_LFLAGS =

TARGET_OBJECTS = $(TARGET_NAME).o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF