
PATH_TO_TOP=../../../reactos

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = niclist

TARGET_SDKLIBS =

TARGET_OBJECTS = $(TARGET_NAME).o

TARGET_GCCLIBS =

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
