# $Id: makefile,v 1.5 2001/08/21 20:13:11 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = sdisk

TARGET_OBJECTS = sdisk.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
