# $Id: Makefile,v 1.1 2003/07/11 18:13:57 chorns Exp $

PATH_TO_TOP = ../..

TARGET_NORC = yes

TARGET_TYPE = library

TARGET_NAME = rtshared

TARGET_OBJECTS = \
  regtests.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
