# $Id: makefile,v 1.15 2001/08/21 20:13:11 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = serial

TARGET_OBJECTS = serial.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
