@ stdcall getAF()
@ stdcall getAH()
@ stdcall getAL()
@ stdcall getAX()
@ stdcall getBH()
@ stdcall getBL()
@ stdcall getBP()
@ stdcall getBX()
@ stdcall getCF()
@ stdcall getCH()
@ stdcall getCL()
@ stdcall getCS()
@ stdcall getCX()
@ stdcall getDF()
@ stdcall getDH()
@ stdcall getDI()
@ stdcall getDL()
@ stdcall getDS()
@ stdcall getDX()
@ stdcall getEAX()
@ stdcall getEBP()
@ stdcall getEBX()
@ stdcall getECX()
@ stdcall getEDI()
@ stdcall getEDX()
@ stdcall getEFLAGS()
@ stdcall getEIP()
@ stdcall getES()
@ stdcall getESI()
@ stdcall getESP()
@ stdcall getFS()
@ stdcall getGS()
@ stdcall getIF()
; @ stdcall getIntelRegistersPointer()
@ stdcall getIP()
@ stdcall getMSW()
@ stdcall getOF()
@ stdcall getPF()
@ stdcall getSF()
@ stdcall getSI()
@ stdcall getSP()
@ stdcall getSS()
@ stdcall getZF()



@ stdcall setAF(long)
@ stdcall setAH(long)
@ stdcall setAL(long)
@ stdcall setAX(long)
@ stdcall setBH(long)
@ stdcall setBL(long)
@ stdcall setBP(long)
@ stdcall setBX(long)
@ stdcall setCF(long)
@ stdcall setCH(long)
@ stdcall setCL(long)
@ stdcall setCS(long)
@ stdcall setCX(long)
@ stdcall setDF(long)
@ stdcall setDH(long)
@ stdcall setDI(long)
@ stdcall setDL(long)
@ stdcall setDS(long)
@ stdcall setDX(long)
@ stdcall setEAX(long)
@ stdcall setEBP(long)
@ stdcall setEBX(long)
@ stdcall setECX(long)
@ stdcall setEDI(long)
@ stdcall setEDX(long)
@ stdcall setEFLAGS(long)
@ stdcall setEIP(long)
@ stdcall setES(long)
@ stdcall setESI(long)
@ stdcall setESP(long)
@ stdcall setFS(long)
@ stdcall setGS(long)
@ stdcall setIF(long)
@ stdcall setIP(long)
@ stdcall setMSW(long)
@ stdcall setOF(long)
@ stdcall setPF(long)
@ stdcall setSF(long)
@ stdcall setSI(long)
@ stdcall setSP(long)
@ stdcall setSS(long)
@ stdcall setZF(long)



@ stdcall MGetVdmPointer(long long long)
@ stdcall Sim32pGetVDMPointer(long long)
