//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by explorer_intres.rc
//
#define IDS_TITLE                       1
#define IDS_START                       2
#define IDS_LOGOFF                      3
#define IDS_SHUTDOWN                    4
#define IDS_LAUNCH                      5
#define IDS_START_HELP                  6
#define IDS_SEARCH_FILES                7
#define IDS_DOCUMENTS                   8
#define IDS_FAVORITES                   9
#define IDS_PROGRAMS                    10
#define IDS_SETTINGS                    11
#define IDS_EXPLORE                     12
#define IDS_EMPTY                       13
#define IDS_RECENT                      14
#define IDS_ADMIN                       15
#define IDS_NETWORK                     16
#define IDS_CONNECTIONS                 17
#define IDS_DRIVES                      18
#define IDS_SEARCH_COMPUTER             19
#define IDS_SETTINGS_MENU               20
#define IDS_CONTROL_PANEL               21
#define IDS_PRINTERS                    22
#define IDS_BROWSE                      23
#define IDS_SEARCH_PRG                  24
#define IDS_ALL_USERS                   25
#define IDS_SEARCH                      26
#define IDS_ABOUT_EXPLORER              27
#define IDS_LAUNCH_MANY_PROGRAMS        28
#define IDS_DESKTOPBAR_SETTINGS         29
#define IDS_DESKTOP                     30
#define IDS_TASKBAR                     31
#define IDS_STARTMENU                   32
#define IDS_MINIMIZE_ALL                33
#define IDI_REACTOS                     100
#define IDI_EXPLORER                    101
#define IDI_STARTMENU                   102
#define IDB_TOOLBAR                     103
#define IDA_EXPLORER                    104
#define ID_ACTIVATE                     105
#define IDD_SEARCH_PROGRAM              105
#define IDB_DRIVEBAR                    106
#define IDD_DESKBAR_DESKTOP             106
#define IDB_IMAGES                      107
#define IDD_EXECUTE                     108
#define IDR_MAINFRAME                   109
#define IDM_MAINFRAME                   110
#define ID_EXECUTE                      111
#define IDM_WINEFILE                    112
#define IDI_LOGOFF                      124
#define IDI_FOLDERARROW                 125
#define IDI_ARROW                       125
#define IDI_ARROW_SELECTED              126
#define IDB_LOGOV                       129
#define IDB_LOGOV256                    130
#define IDA_SEARCH_PROGRAM              133
#define IDI_APPICON                     134
#define IDI_FLOATING                    135
#define IDD_ABOUT_EXPLORER              135
#define IDI_REACTOS_BIG                 137
#define IDI_DOCUMENTS                   138
#define IDI_CONFIG                      139
#define IDI_FAVORITES                   140
#define IDI_INFO                        141
#define IDI_APPS                        142
#define IDI_SEARCH                      143
#define IDI_ACTION                      144
#define IDI_FOLDER                      145
#define IDI_SEARCH_DOC                  146
#define IDI_PRINTER                     147
#define IDI_NETWORK                     148
#define IDI_COMPUTER                    149
#define IDM_DESKTOPBAR                  150
#define IDD_DESKBAR_TASKBAR             153
#define IDB_ICON_ALIGN_0                153
#define IDD_DESKBAR_STARTMENU           154
#define IDB_ICON_ALIGN_1                154
#define IDB_ICON_ALIGN_2                155
#define IDB_ICON_ALIGN_3                156
#define IDB_ICON_ALIGN_4                157
#define IDB_ICON_ALIGN_5                158
#define IDB_ICON_ALIGN_6                159
#define IDB_ICON_ALIGN_7                160
#define IDB_ICON_ALIGN_8                161
#define IDB_ICON_ALIGN_9                162
#define IDB_ICON_ALIGN_10               163
#define IDB_LOGOV16                     164
#define ID_VIEW_NAME                    401
#define ID_VIEW_ALL_ATTRIBUTES          402
#define ID_VIEW_SELECTED_ATTRIBUTES     403
#define ID_VIEW_STATUSBAR               503
#define ID_VIEW_DRIVE_BAR               507
#define ID_VIEW_TOOL_BAR                508
#define IDC_ROS_EXPLORER                1000
#define IDC_ICON_ALIGN_0                1002
#define IDC_ICON_ALIGN_1                1003
#define IDC_ICON_ALIGN_2                1004
#define IDC_ICON_ALIGN_3                1005
#define IDC_ICON_ALIGN_4                1006
#define IDC_ICON_ALIGN_5                1007
#define IDC_ICON_ALIGN_6                1008
#define IDC_ICON_ALIGN_7                1009
#define IDC_ICON_ALIGN_8                1010
#define IDC_ICON_ALIGN_9                1011
#define IDC_ICON_ALIGN_10               1012
#define IDC_WWW                         1012
#define IDC_ICON_ALIGN_11               1013
#define IDC_TOPIC                       1017
#define IDC_MAILS_FOUND                 1018
#define ID_REFRESH                      1704
#define ID_ABOUT_WINEFILE               1705
#define IDC_FILETREE                    10001
#define ID_EXPLORER_FAQ                 10002
#define ID_WEB_WINDOW                   10003
#define ID_WINDOW_AUTOSORT              0x8003
#define ID_VIEW_FULLSCREEN              0x8004
#define ID_PREFERED_SIZES               0x8005
#define ID_DRIVE_DESKTOP                0x9000
#define ID_DRIVE_SHELL_NS               0x9001
#define ID_DRIVE_UNIX_FS                0x9002
#define ID_DRIVE_NTOBJ_NS               0x9003
#define ID_DRIVE_REGISTRY               0x9004
#define ID_DRIVE_FAT                    0x9005
#define ID_DRIVE_FIRST                  0x9006
#define ID_ABOUT_WINDOWS                40002
#define ID_ABOUT_EXPLORER               40003
#define ID_DESKTOPBAR_SETTINGS          40004
#define ID_BROWSE_BACK                  40005
#define ID_BROWSE_FORWARD               40006
#define ID_BROWSE_HOME                  40007
#define ID_BROWSE_SEARCH                40008
#define ID_STOP                         40009
#define ID_WINDOW_NEW                   0xE130
#define ID_WINDOW_ARRANGE               0xE131
#define ID_WINDOW_CASCADE               0xE132
#define ID_WINDOW_TILE_HORZ             0xE133
#define ID_WINDOW_TILE_VERT             0xE134
#define ID_WINDOW_SPLIT                 0xE135
#define ID_EDIT_PROPERTIES              57656
#define ID_FILE_EXIT                    0xE141
#define ID_HELP_USING                   0xE144
#define ID_HELP                         0xE146
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        161
#define _APS_NEXT_COMMAND_VALUE         40006
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
