
#define VER_MAJOR_PRODUCTVER        6
#define VER_MINOR_PRODUCTVER        0

#undef VER_PRODUCTBUILD
#define VER_PRODUCTBUILD            2900
#define VER_PRODUCTVERSION          VER_MAJOR_PRODUCTVER,VER_MINOR_PRODUCTVER,VER_PRODUCTBUILD,VER_PRODUCTBUILD_QFE
#define VER_PRODUCTVERSION_W        (0x0600)
#define VER_PRODUCTVERSION_DW       (0x06000000 | VER_PRODUCTBUILD)
#define VER_PRODUCTBETA_STR         ""
#define VER_PRODUCTVERSION_STRING   "6.00"

