# $Id: Makefile,v 1.1 2003/03/06 18:44:57 gvg Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = program

TARGET_APPTYPE = windows

TARGET_NAME = winemine

TARGET_SDKLIBS = kernel32.a gdi32.a

TARGET_OBJECTS = main.o dialog.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
