@ stdcall LpkInitialize(long)
@ stdcall LpkTabbedTextOut(long long long long long long long long long long long long)
@ stdcall LpkDllInitialize(ptr long ptr)
@ stdcall LpkDrawTextEx(long long long long long long long long long long)
@ extern LpkEditControl
@ stdcall LpkExtTextOut(long long long long long long long long long)
@ stdcall LpkGetCharacterPlacement(long long long long long long long)
@ stdcall LpkGetTextExtentExPoint(long long long long long long long long long)
@ stdcall LpkPSMTextOut(long long long long long long)
@ stdcall LpkUseGDIWidthCache(long long long long long)
@ stdcall ftsWordBreak(long long long long long)
