@ stub ClearEventData
@ stub CreateBlob
@ stub CreateNPPInterface
@ stub DestroyBlob
@ stub DestroyNPPBlobTable
@ stub DuplicateBlob
@ stub FilterNPPBlob
@ stub FindOneOf
@ stub FindUnknownBlobCategories
@ stub FindUnknownBlobTags
@ stub GetBoolFromBlob
@ stub GetClassIDFromBlob
@ stub GetDwordFromBlob
@ stub GetMacAddressFromBlob
@ stub GetNPPAddressFilterFromBlob
@ stub GetNPPBlobFromUI
@ stub GetNPPBlobTable
@ stub GetNPPEtypeSapFilter
@ stub GetNPPMacTypeAsNumber
@ stub GetNPPPatternFilterFromBlob
@ stub GetNPPTriggerFromBlob
@ stub GetNetworkInfoFromBlob
@ stub GetStringFromBlob
@ stub GetStringsFromBlob
@ stub IsRemoteNPP
@ stub LockBlob
@ stub MarshalBlob
@ stub MergeBlob
@ stub NmAddUsedEntry
@ stub NmHeapAllocate
@ stub NmHeapFree
@ stub NmHeapReallocate
@ stub NmHeapSetMaxSize
@ stub NmHeapSize
@ stub NmRemoveUsedEntry
@ stub RaiseNMEvent
@ stub ReadBlobFromFile
@ stub RegCreateBlobKey
@ stub RegOpenBlobKey
@ stub ReleaseEventSystem
@ stub RemoveFromBlob
@ stub SelectNPPBlobFromTable
@ stub SendEvent
@ stub SetBoolInBlob
@ stub SetClassIDInBlob
@ stub SetDwordInBlob
@ stub SetMacAddressInBlob
@ stub SetNPPAddressFilterInBlob
@ stub SetNPPEtypeSapFilter
@ stub SetNPPPatternFilterInBlob
@ stub SetNPPTriggerInBlob
@ stub SetNetworkInfoInBlob
@ stub SetStringInBlob
@ stub SubkeyExists
@ stub UnMarshalBlob
@ stub UnlockBlob
@ stub WriteBlobToFile
@ stub WriteCrackedBlobToFile
@ stub recursiveDeleteKey
@ stub setKeyAndValue
