tools : buildno.c depends.c mkconfig.c mkflpimg.c rcopy.c rdel.c regtests.c rline.c rmkdir.c rrmdir.c rsym.c rtouch.c
	cl buildno.c
	cl depends.c
	cl mkconfig.c
	cl mkflpimg.c
	cl rcopy.c
	cl rdel.c
	cl regtests.c
	cl rline.c
	cl rmkdir.c
	cl rrmdir.c
	cl rsym.c
	cl rtouch.c