# $Id: makefile,v 1.2 2001/08/21 20:13:04 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = program

TARGET_APPTYPE = native

TARGET_NAME = lsass

TARGET_INSTALLDIR = system32

TARGET_OBJECTS = $(TARGET_NAME).o init.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk

# EOF
