# $Id$

PATH_TO_TOP = ../..

TARGET_NORC = yes

TARGET_TYPE = library

TARGET_NAME = rtshared

TARGET_CFLAGS = -Wall -Werror

TARGET_OBJECTS = \
  regtests.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
