/************************************************************************/
/*                                                                      */
/* RCPP - Resource Compiler Pre-Processor for NT system                 */
/*                                                                      */
/* GRAMMAR.H - Grammar definitions for terminals                        */
/*                                                                      */
/* 27-Nov-90 w-BrianM  Update for NT from PM SDK RCPP                   */
/*                                                                      */
/************************************************************************/

#define L_NOTOKEN       1L
#define L_IDENT         2L
#define L_STRING        3L
#define L_CFLOAT        4L
#define L_CDOUBLE       5L
#define L_CLDOUBLE      6L
#define L_CINTEGER      7L
#define L_LONGINT       8L
#define L_CUNSIGNED     9L
#define L_LONGUNSIGNED  10L
#define L_AUTO          11L
#define L_STATIC        12L
#define L_EXTERN        13L
#define L_REGISTER      14L
#define L_TYPEDEF       15L
#define L_FORTRAN       16L
#define L_PASCAL        17L
#define L_C             18L
#define L_INTERRUPT     19L
#define L_SAVEREGS      20L
#define L_LOADDS        21L
#define L_EXPORT        22L
#define L_ASM           23L
#define L_NEAR          24L
#define L_FAR           25L
#define L_HUGE          26L
#define L_CONST         27L
#define L_VOLATILE      28L
#define L_CHAR          29L
#define L_INT           30L
#define L_FLOAT         31L
#define L_DOUBLE        32L
#define L_SHORT         33L
#define L_LONG          34L
#define L_VOID          35L
#define L_SIGNED        36L
#define L_UNSIGNED      37L
#define L_ENUM          38L
#define L_ENUM_TAG      39L
#define L_STRUCT        40L
#define L_STRUCT_TAG    41L
#define L_UNION         42L
#define L_UNION_TAG     43L
#define L_AND           44L
#define L_ANDAND        45L
#define L_ANDEQ         46L
#define L_ASSIGN        47L
#define L_BIT           48L
#define L_COLON         49L
#define L_COMMA         50L
#define L_DECR          51L
#define L_DIV           52L
#define L_DIVEQ         53L
#define L_EQUALS        54L
#define L_EXCLAIM       55L
#define L_EXTRACT       56L
#define L_GT            57L
#define L_GTEQ          58L
#define L_INCR          59L
#define L_LBRACK        60L
#define L_LSHFTEQ       61L
#define L_LSHIFT        62L
#define L_LT            63L
#define L_LTEQ          64L
#define L_MINUS         65L
#define L_MINUSEQ       66L
#define L_MOD           67L
#define L_MODEQ         68L
#define L_MULT          69L
#define L_MULTEQ        70L
#define L_NOTEQ         71L
#define L_OR            72L
#define L_OREQ          73L
#define L_OROR          74L
#define L_PERIOD        75L
#define L_PLUS          76L
#define L_PLUSEQ        77L
#define L_POINTSTO      78L
#define L_PREDECR       79L
#define L_PREINCR       80L
#define L_QUEST         81L
#define L_RSHFTEQ       82L
#define L_RSHIFT        83L
#define L_TILDE         84L
#define L_UMINUS        85L
#define L_XOR           86L
#define L_XOREQ         87L
#define L_ARG           88L
#define L_ASOP          89L
#define L_BREAK         90L
#define L_CASE          91L
#define L_CAST          92L
#define L_CLASS         93L
#define L_CONSTANT      94L
#define L_CONTINUE      95L
#define L_DEFAULT       96L
#define L_DIVOP         97L
#define L_DO            98L
#define L_ELLIPSIS      99L
#define L_ELSE          100L
#define L_ENTRY         101L
#define L_EOF           102L
#define L_EQUOP         103L
#define L_FILE          104L
#define L_FOR           105L
#define L_FUNCTION      106L
#define L_GOTO          107L
#define L_IF            108L
#define L_INCOP         109L
#define L_INIT          110L
#define L_LCURLY        111L
#define L_LINE          112L
#define L_LPAREN        113L
#define L_INTRINSIC     114L
#define L_MODIFIER      115L
#define L_MODULE        116L
#define L_RBRACK        117L
#define L_RCURLY        118L
#define L_RELOP         119L
#define L_RETURN        120L
#define L_RPAREN        121L
#define L_SELF          122L
#define L_SEMI          123L
#define L_SHIFTOP       124L
#define L_SIZEOF        125L
#define L_STUNOP        126L
#define L_SW            127L
#define L_SWEXP         128L
#define L_TYPE          129L
#define L_TYPENAME      130L
#define L_UPLUS         131L
#define L_WHILE         132L
