
if (MSVC)
    # Disable warning C4090: 'function': different 'const' qualifiers
    # Disable warning C4146: unary minus operator applied to unsigned type, result still unsigned
    add_compile_options(/wd4090 /wd4146)
endif()

set(VKD3D_INCLUDE_DIRS
    ${REACTOS_SOURCE_DIR}/sdk/lib/vkd3d/include
    ${REACTOS_SOURCE_DIR}/sdk/lib/vkd3d/include/private)

add_subdirectory(amstream)
add_subdirectory(d3d8)
add_subdirectory(d3d9)
add_subdirectory(d3dcompiler_33)
add_subdirectory(d3dcompiler_34)
add_subdirectory(d3dcompiler_35)
add_subdirectory(d3dcompiler_36)
add_subdirectory(d3dcompiler_37)
add_subdirectory(d3dcompiler_38)
add_subdirectory(d3dcompiler_39)
add_subdirectory(d3dcompiler_40)
add_subdirectory(d3dcompiler_41)
add_subdirectory(d3dcompiler_42)
add_subdirectory(d3dcompiler_43)
add_subdirectory(d3dcompiler_46)
add_subdirectory(d3dcompiler_47)
add_subdirectory(d3drm)
add_subdirectory(d3dx9_24)
add_subdirectory(d3dx9_25)
add_subdirectory(d3dx9_26)
add_subdirectory(d3dx9_27)
add_subdirectory(d3dx9_28)
add_subdirectory(d3dx9_29)
add_subdirectory(d3dx9_30)
add_subdirectory(d3dx9_31)
add_subdirectory(d3dx9_32)
add_subdirectory(d3dx9_33)
add_subdirectory(d3dx9_34)
add_subdirectory(d3dx9_35)
add_subdirectory(d3dx9_36)
add_subdirectory(d3dx9_37)
add_subdirectory(d3dx9_38)
add_subdirectory(d3dx9_39)
add_subdirectory(d3dx9_40)
add_subdirectory(d3dx9_41)
add_subdirectory(d3dx9_42)
add_subdirectory(d3dx9_43)
add_subdirectory(d3dx11_42)
add_subdirectory(d3dx11_43)
add_subdirectory(d3dx10_33)
add_subdirectory(d3dx10_34)
add_subdirectory(d3dx10_35)
add_subdirectory(d3dx10_36)
add_subdirectory(d3dx10_37)
add_subdirectory(d3dx10_38)
add_subdirectory(d3dx10_39)
add_subdirectory(d3dx10_40)
add_subdirectory(d3dx10_41)
add_subdirectory(d3dx10_42)
add_subdirectory(d3dx10_43)
add_subdirectory(d3dxof)
add_subdirectory(ddraw)
add_subdirectory(ddrawex)
add_subdirectory(dxcore)
add_subdirectory(dxva2)
add_subdirectory(d3d12)
add_subdirectory(d3d12core)
add_subdirectory(devenum)
add_subdirectory(dinput)
add_subdirectory(dinput8)
add_subdirectory(dmband)
add_subdirectory(dmcompos)
add_subdirectory(dmime)
add_subdirectory(dmloader)
add_subdirectory(dmscript)
add_subdirectory(dmstyle)
#add_subdirectory(dmsynth) # Requires fluidsynth, which we don't have yet
add_subdirectory(dmusic)
#add_subdirectory(dplay)
add_subdirectory(dplayx)
add_subdirectory(dpnaddr)
add_subdirectory(dpnet)
#add_subdirectory(dpnhpast)
add_subdirectory(dpnhupnp)
add_subdirectory(dpnlobby)
add_subdirectory(dpvoice)
add_subdirectory(dpwsockx)
add_subdirectory(dsound)
add_subdirectory(d3d10)
add_subdirectory(d3d10_1)
add_subdirectory(d3d10core)
add_subdirectory(d3d11)
add_subdirectory(dxgi)
add_subdirectory(dxdiagn)
add_subdirectory(msdmo)
add_subdirectory(qcap)
add_subdirectory(qedit)
add_subdirectory(quartz)
add_subdirectory(wined3d)
