#ifndef __RESOURCE_H
#define __RESOURCE_H

#define IDC_STATIC -1

#define IDI_START   101

#define IDS_START   101
#define IDS_PROPERTIES  102
#define IDS_OPEN_ALL_USERS  103
#define IDS_EXPLORE_ALL_USERS   104

#define IDC_STARTBTN    304

#define IDM_TRAYWND 101
#define IDM_STARTMENU 102

#define IDB_STARTMENU 101

#define ID_SHELL_CMD_FIRST  0xF
#define ID_SHELL_CMD_LAST   0x7FEF
#define ID_SHELL_CMD_PROPERTIES (ID_SHELL_CMD_LAST + 1)
#define ID_SHELL_CMD_OPEN_ALL_USERS (ID_SHELL_CMD_LAST + 2)
#define ID_SHELL_CMD_EXPLORE_ALL_USERS  (ID_SHELL_CMD_LAST + 3)
#define ID_LOCKTASKBAR  (ID_SHELL_CMD_LAST + 4)
#define ID_SHELL_CMD_OPEN_TASKMGR (ID_SHELL_CMD_LAST + 5)

/* NOTE: The following constants may *NOT* be changed because
         they're hardcoded and need to be the exact values
         in order to get the start menu to work! */
#define IDM_PROGRAMS 504
#define IDM_FAVORITES 507
#define IDM_DOCUMENTS 501
#define IDM_SETTINGS 508
#define IDM_CONTROLPANEL 505
#define IDM_SECURITY 5001
#define IDM_NETWORKCONNECTIONS 557
#define IDM_PRINTERSANDFAXES 510
#define IDM_TASKBARANDSTARTMENU 413
#define IDM_SEARCH 520
#define IDM_HELPANDSUPPORT 503
#define IDM_RUN 401
#define IDM_SYNCHRONIZE 553
#define IDM_LOGOFF 402
#define IDM_DISCONNECT 5000
#define IDM_UNDOCKCOMPUTER 410
#define IDM_SHUTDOWN 506
#define IDM_LASTSTARTMENU_SEPARATOR 450

/* Taskbar resources */
#define IDD_TASKBARPAGE 2000
#define IDC_TASKBAR_BITMAP 2001
#define IDD_STARTMENUPAGE 2001
#define IDD_NOTIFICATIONPAGE 2002
#define IDD_TOOLBARSPAGE 2003

#define IDD_TASKBARPROP_TASKBAR 2000
#define IDC_TASKBARPROP_TASKBARBITMAP 2001
#define IDC_TASKBARPROP_LOCK 2002
#define IDC_TASKBARPROP_HIDE 2003
#define IDC_TASKBARPROP_ONTOP 2004
#define IDC_TASKBARPROP_GROUP 2005
#define IDC_TASKBARPROP_SHOWQL 2006
#define IDC_TASKBARPROP_WNDPREV 2007

#define IDD_TASKBARPROP_STARTMENU 2100
#define IDC_TASKBARPROP_STARTMENU 2101
#define IDC_TASKBARPROP_STARTMENUCUST 2102
#define IDC_TASKBARPROP_STARTMENUCLASSIC 2103
#define IDC_TASKBARPROP_STARTMENUCLASSICCUST 2104
#define IDC_TASKBARPROP_RECENTFILES 2105
#define IDC_TASKBARPROP_RECENTFOLDERS 2106

#define IDD_TASKBARPROP_NOTIFICATION 2200
#define IDC_TASKBARPROP_TASKBARBITMAP 2201
#define IDC_TASKBARPROP_HIDEICONS 2202
#define IDC_TASKBARPROP_ICONCUST 2203
#define IDC_TASKBARPROP_CLOCK 2204
#define IDC_TASKBARPROP_VOLUME 2205
#define IDC_TASKBARPROP_NETWORK 2206
#define IDC_TASKBARPROP_POWER 2207

#define IDD_TASKBARPROP_TOOLBARS 2300
#define IDC_TASKBARPROP_DESKBANDLIST 2301

#define IDS_TASKBAR_STARTMENU_PROP_CAPTION 2200

#endif /* __RESOURCE_H */
