//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
#define IDB_DOMAIN                      201
#define IDB_MACHINE                     202
#define IDB_NETWORK                     203
#define IDR_POPUPMENU_LISTCTRL          204
#define IDR_POPUPMENU_HEADERCTRL        205
#define IDI_CHECKMARK                   206
#define IDB_MENUCHK                     207
#define IDR_POPUPMENU_DRAGDROP          208
#define IDR_POPUPMENU_TREE_FOLDER       209
#define IDB_COLDTOOLBAR                 210
#define IDB_HOTTOOLBAR                  211
#define IDI_FOLDER_CLOSED               212
#define IDC_NODROP                      213
#define IDB_REPORT                      214
#define IDC_COLUMNLIST                  215
#define ID_VIEW_FIELDCHOOSER            216
#define CG_IDC_PROGDLG_PROGRESS1        217
#define CG_IDC_PROGDLG_PROGRESS2        218
#define CG_IDC_PROGDLG_PERCENT1         219
#define CG_IDC_PROGDLG_PERCENT2         220
#define CG_IDC_PROGDLG_STATUS           221
#define IDC_FOP_LIST_ICONS              222
#define IDC_NETWORK                     223
#define IDC_EDIT_NEW_CATEGORY           224
#define IDD_NEW_CATEGORY                225
#define IDC_UIOD_HAND                   226
#define IDC_LIST_SEARCH                 227
#define IDC_TREE_SHELL                  228
#define IDC_LIST_SHELL                  229
#define IDC_CB_IE_ADDRESS               230
#define CG_IDD_PROGRESS                 1001
#define IDD_FILEOPENPREVIEW_ICON        1002
#define IDD_MACHINES                    1003
#define IDD_FIELDCHOOSER                1004
#define IDC_IMAGE                       1005
#define IDD_FILEOPENPREVIEW_IMAGE       1006
#define IDC_BUTT_SEARCH                 1010
#define IDC_STATIC_STATUS               1011
#define IDC_BUTT_OPEN                   1012
#define IDD_FILEOPENPREVIEW_SEARCH      1013
#define ID_SHELL_POPUP_FIRST            42500
#define ID_SHELL_POPUP_LAST             42600
#define ID_POPUP_DD_MOVE                42768
#define ID_POPUP_DD_COPY                42769
#define ID_POPUP_DD_CANCEL              42770
#define ID_UI_VIEW_LARGE_ICONS          42771
#define ID_UI_VIEW_SMALL_ICONS          42772
#define ID_UI_VIEW_DETAILS              42773
#define ID_UI_VIEW_LIST                 42774
#define ID_UI_VIEW_GRIDLINES            42775
#define ID_UI_VIEW_FULL_SELECTION       42776
#define ID_UI_VIEW_CHECKBOXES           42777
#define ID_UI_VIEW_COLUMN_ORDERING      42778
#define ID_UI_VIEW_FULL_ROW_SELECTION   42779
#define ID_UI_VIEW_TRACK_SELECT         42780
#define ID_UI_VIEW_COLUMN_SIZING        42781
#define ID_HEADER_REMOVE_COL            42782
#define ID_HEADER_EDIT_TEXT             42783
#define ID_HEADER_RESET                 42784
#define ID_UI_VIEW_EDIT_COLUMN          42786
#define ID_BROWSER_GO_BACK              42787
#define ID_BROWSER_GO_FORWARD           42788
#define ID_BROWSER_GO_HOME              42789
#define ID_BROWSER_REFRESH              42790
#define ID_BROWSER_STOP                 42791
#define ID_BROWSER_SEARCH               42792
#define ID_BROWSER_FAVORITES            42793
#define IDS_BROWSER_GO_BACK             42794
#define IDS_BROWSER_GO_FORWARD          42795
#define IDS_BROWSER_GO_HOME             42796
#define IDS_BROWSER_REFRESH             42797
#define IDS_BROWSER_STOP                42798
#define IDS_BROWSER_SEARCH              42799
#define IDS_BROWSER_FAVORITES           42800
#define ID_POPUP_TF_NEW_FOLDER          42801
#define CG_IDS_PROGRESS_CAPTION         42801
#define ID_POPUP_TF_DELETE_FOLDER       42802
#define IDS_ICON_FILTER                 42802
#define ID_POPUP_TF_REFRESH             42803
#define IDS_ICON_CAPTION                42803
#define IDS_SEARCH_CAPTION              42804
#define IDS_SEARCH_FILTER               42805
#define IDS_FILE_SELECT_APP             42806
#define IDS_FILE_SELECT_ICON            42807
#define IDS_FILE_SELECT_EXEC            42808
#define IDS_FILE_SELECT_HTML            42809
#define IDS_FILE_SELECT_COM             42810
#define IDS_FILE_SELECT_SCRIPT          42811
#define IDS_FILE_SELECT_APP_EXT         42812
#define IDS_FILE_SELECT_IMAGES          42813
#define IDS_FILE_SELECT_AUDIO           42814
#define IDS_IMAGE_CAPTION               42815
#define IDS_NO_ITEMS_MESS               42816
