#define UNIATA_VER_STR         "45a3"
#define UNIATA_VER_DOT         0.45.1.3
#define UNIATA_VER_MJ          0
#define UNIATA_VER_MN          45
#define UNIATA_VER_SUB_MJ      1
#define UNIATA_VER_SUB_MN      3
#define UNIATA_VER_DOT_COMMA   0,45,1,3
#define UNIATA_VER_DOT_STR     "0.45.1.3"
#define UNIATA_VER_YEAR        2014
#define UNIATA_VER_YEAR_STR    "2014"
