@ stdcall -private DllCanUnloadNow()
@ stdcall -private DllGetClassObject(ptr ptr ptr)
@ stdcall -private DllRegisterServer()
@ stdcall -private DllUnregisterServer()
@ stdcall WinHttpAddRequestHeaders(ptr wstr long long)
@ stdcall WinHttpCheckPlatform()
@ stdcall WinHttpCloseHandle(ptr)
@ stdcall WinHttpConnect(ptr wstr long long)
@ stdcall WinHttpCrackUrl(wstr long long ptr)
@ stdcall WinHttpCreateProxyResolver(ptr ptr)
@ stdcall WinHttpCreateUrl(ptr long ptr ptr)
@ stdcall WinHttpDetectAutoProxyConfigUrl(long ptr)
@ stdcall WinHttpFreeProxyResult(ptr)
@ stdcall WinHttpFreeProxyResultEx(ptr)
@ stdcall WinHttpFreeProxySettings(ptr)
@ stdcall WinHttpGetDefaultProxyConfiguration(ptr)
@ stdcall WinHttpGetIEProxyConfigForCurrentUser(ptr)
@ stdcall WinHttpGetProxyForUrl(ptr wstr ptr ptr)
@ stdcall WinHttpGetProxyForUrlEx(ptr wstr ptr ptr)
@ stdcall WinHttpGetProxyForUrlEx2(ptr wstr ptr long ptr ptr)
@ stdcall WinHttpGetProxyResult(ptr ptr)
@ stdcall WinHttpGetProxyResultEx(ptr ptr)
@ stdcall WinHttpGetProxySettingsVersion(ptr ptr)
@ stdcall WinHttpOpen(wstr long wstr wstr long)
@ stdcall WinHttpOpenRequest(ptr wstr wstr wstr wstr ptr long)
@ stdcall WinHttpQueryAuthSchemes(ptr ptr ptr ptr)
@ stdcall WinHttpQueryDataAvailable(ptr ptr)
@ stdcall WinHttpQueryHeaders(ptr long wstr ptr ptr ptr)
@ stdcall WinHttpQueryOption(ptr long ptr ptr)
@ stdcall WinHttpReadData(ptr ptr long ptr)
@ stdcall WinHttpReadProxySettings(ptr wstr long long ptr ptr ptr)
@ stdcall WinHttpReceiveResponse(ptr ptr)
@ stdcall WinHttpResetAutoProxy(ptr long)
@ stdcall WinHttpSendRequest(ptr wstr long ptr long long long)
@ stdcall WinHttpSetCredentials(ptr long long wstr ptr ptr)
@ stdcall WinHttpSetDefaultProxyConfiguration(ptr)
@ stdcall WinHttpSetOption(ptr long ptr long)
@ stdcall WinHttpSetStatusCallback(ptr ptr long long)
@ stdcall WinHttpSetTimeouts(ptr long long long long)
@ stdcall WinHttpTimeFromSystemTime(ptr ptr)
@ stdcall WinHttpTimeToSystemTime(wstr ptr)
@ stdcall WinHttpWebSocketClose(ptr long ptr long)
@ stdcall WinHttpWebSocketCompleteUpgrade(ptr ptr)
@ stdcall WinHttpWebSocketQueryCloseStatus(ptr ptr ptr long ptr)
@ stdcall WinHttpWebSocketReceive(ptr ptr long ptr ptr)
@ stdcall WinHttpWebSocketSend(ptr long ptr long)
@ stdcall WinHttpWebSocketShutdown(ptr long ptr long)
@ stdcall WinHttpWriteData(ptr ptr long ptr)
@ stdcall WinHttpWriteProxySettings(ptr long ptr)
