PATH_TO_TOP = ../../../..

TARGET_TYPE = program

TARGET_APPTYPE = console

TARGET_NAME = ftp

TARGET_INSTALLDIR = system32

TARGET_SDKLIBS = ws2_32.a iphlpapi.a ntdll.a

TARGET_OBJECTS = \
	cmds.o \
	cmdtab.o \
	domacro.o \
	fake.o \
	ftp.o \
	main.o \
	ruserpass.o

TARGET_GCCLIBS = 

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
