

BOOL (*PGD_ENABLEDRIVER)(ULONG, ULONG, PDRVENABLEDATA); 

typedef struct _DRIVER_FUNCTIONS
{
  PGD_ENABLEDRIVER  EnableDriver;
  PGD_ENABLEPDEV  EnablePDev;
  PGD_COMPLETEPDEV  CompletePDev;
  PGD_DISABLEPDEV  DisablePDev;
  PGD_ENABLESURFACE  EnableSurface;
  PGD_DISABLESURFACE  DisableSurface;
  PGD_ASSERTMODE  AssertMode;
  PGD_RESETPDEV  ResetPDev;
#if 0
  PGD_CREATEDEVICEBITMAP,
  PGD_DELETEDEVICEBITMAP,
  PGD_REALIZEBRUSH,
  PGD_DITHERCOLOR,
  PGD_STROKEPATH,
  PGD_FILLPATH,
  PGD_STROKEANDFILLPATH,
  PGD_PAINT
  PGD_BITBLT,
  PGD_COPYBITS,
  PGD_STRETCHBLT,
  PGD_SETPALETTE,
  PGD_TEXTOUT,
  PGD_ESCAPE,
  PGD_DRAWESCAPE,
  PGD_QUERYFONT,
  PGD_QUERYFONTTREE,
  PGD_QUERYFONTDATA,
  PGD_SETPOINTERSHAPE,
  PGD_MOVEPOINTER,
  PGD_LINETO,
  PGD_SENDPAGE,
  PGD_STARTPAGE,
  PGD_ENDDOC,
  PGD_STARTDOC,
  PGD_GETGLYPHMODE,
  PGD_SYNCHRONIZE,
  PGD_SAVESCREENBITS,
  PGD_GETMODES,
  PGD_FREE,
  PGD_DESTROYFONT,
  PGD_QUERYFONTCAPS,
  PGD_LOADFONTFILE,
  PGD_UNLOADFONTFILE,
  PGD_FONTMANAGEMENT,
  PGD_QUERYTRUETYPETABLE,
  PGD_QUERYTRUETYPEOUTLINE,
  PGD_GETTRUETYPEFILE,
  PGD_QUERYFONTFILE,
  PGD_QUERYADVANCEWIDTHS,
  PGD_SETPIXELFORMAT,
  PGD_DESCRIBEPIXELFORMAT,
  PGD_SWAPBUFFERS,
  PGD_STARTBANDING,
  PGD_NEXTBAND,
  PGD_GETDIRECTDRAWINFO,
  PGD_ENABLEDIRECTDRAW,
  PGD_DISABLEDIRECTDRAW,
  PGD_QUERYSPOOLTYPE,
#endif
} DRIVER_FUNCTIONS, *PDRIVER_FUNCTIONS;

BOOL  DRIVER_RegisterDriver(PWSTR  Name, GD_ENABLEDRIVER  EnableDriver);
PDRIVER_FUNCTIONS  DRIVER_FindDriver(PWSTR  Name);
BOOL  DRIVER_BuildFunctions(PWSTR  Name, PDRVENABLEDATA  DED);
BOOL  DRIVER_UnregisterDriver(PWSTR  Name);

