# $Id: Makefile.ros-template,v 1.3.16.1 2004/12/08 21:57:21 hyperion Exp $

TARGET_NAME = rpcrt4

TARGET_OBJECTS = @C_SRCS@

TARGET_CFLAGS = @EXTRADEFS@ -D__REACTOS__ -Wall

TARGET_SDKLIBS = @IMPORTS@ winmm.a wine.a wine_uuid.a ntdll.a

TARGET_BASE = $(TARGET_BASE_LIB_RPCRT4)

TARGET_RC_BINSRC = @RC_BINSRC@
TARGET_RC_BINARIES = @RC_BINARIES@

TARGET_NORC = yes

default: all

DEP_OBJECTS = $(TARGET_OBJECTS)

include $(TOOLS_PATH)/depend.mk
