 @ stdcall CTEAllocateString(long long)
 @ stdcall CTEBlock(long)
 @ stdcall CTEInitEvent(long)
 @ stdcall CTEInitString(long long)
 @ stdcall CTEInitTimer(long)
 @ stdcall CTEInitialize()
 @ stdcall CTELogEvent(long long long long long long long)
 @ stdcall CTEScheduleEvent(long long)
 @ stdcall CTESignal(long long)
 @ stdcall CTEStartTimer(long long long long)
 @ stdcall CTESystemUpTime()
 @ stdcall TdiBuildNetbiosAddress(str long)
 @ stdcall TdiBuildNetbiosAddressEa(str long str)
 @ stdcall TdiCopyBufferToMdl(ptr long long ptr long ptr)
 @ stdcall TdiCopyMdlToBuffer(ptr long long ptr long ptr)
 @ stdcall TdiDefaultChainedRcvDatagramHandler(ptr long ptr long ptr long long long ptr ptr)
 @ stdcall TdiDefaultChainedRcvExpeditedHandler(ptr ptr long long long ptr ptr)
 @ stdcall TdiDefaultChainedReceiveHandler(ptr ptr long long long ptr ptr)
 @ stdcall TdiDefaultConnectHandler(ptr long ptr long ptr long ptr ptr ptr)
 @ stdcall TdiDefaultDisconnectHandler(ptr ptr long ptr long ptr long)
 @ stdcall TdiDefaultErrorHandler(ptr long)
 @ stdcall TdiDefaultRcvDatagramHandler(ptr long ptr long ptr long long long ptr ptr ptr)
 @ stdcall TdiDefaultRcvExpeditedHandler(ptr ptr long long long ptr ptr ptr)
 @ stdcall TdiDefaultReceiveHandler(ptr ptr long long long ptr ptr ptr)
 @ stdcall TdiDefaultSendPossibleHandler(ptr ptr long)
 @ stdcall TdiDeregisterAddressChangeHandler(ptr)
 @ stdcall TdiDeregisterDeviceObject(ptr)
 @ stdcall TdiDeregisterNetAddress(ptr)
 @ stdcall TdiDeregisterNotificationHandler(ptr)
 @ stdcall TdiInitialize(ptr)
 @ stdcall TdiMapBuffer(ptr)
 @ stdcall TdiMapUserRequest(ptr ptr ptr)
 @ stdcall TdiOpenNetbiosAddress(long long long long)
 @ stdcall TdiRegisterAddressChangeHandler(long long long)
 @ stdcall TdiRegisterDeviceObject(long long)
 @ stdcall TdiRegisterNetAddress(long long)
 @ stdcall TdiRegisterNotificationHandler(long long long)
 @ stdcall TdiReturnChainedReceives(ptr long)
 @ stdcall TdiUnmapBuffer(ptr)
