// Defines for resources

#ifndef _RESOURCE_H
#define _RESOURCE_H

#define IDS_THUMBNAILVIEW_DESC      1000
#define IDS_RENAME_TITLE            1001
#define IDS_CREATETHUMBNAIL         1002
#define IDS_CREATETHUMBNAILHELP     1003
#define IDS_HTMLTHUMBEXTRACT_DESC   1004
#define IDS_BMPTHUMBEXTRACT_DESC    1005
#define IDS_OFCTHUMBEXTRACT_DESC    1006
#define IDS_DOCTHUMBEXTRACT_DESC    1007
#define IDS_TASKSCHEDULER_DESC      1008
#define IDS_LNKTHUMBEXTRACT_DESC    1009
#define IDS_EXTRACTING              1010
#define IDS_THUMBNAILGEN_DESC       1011

#define IDS_ERR_OUTOFMEM            2000
#define IDS_ERR_SHELLTITLE          2001
#define IDS_ERR_CONTEXTMENUFAILED   2003

#define IDM_COMMDLG_POPUPMERGE      4000

#endif
