# $Id: Makefile,v 1.10 2001/08/21 20:13:10 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = driver

TARGET_NAME = floppy

TARGET_OBJECTS = \
  dpc.o \
  floppy.o \
  isr.o

include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
