#pragma once

#define IDS_SERVICE_START    100
#define IDS_SERVICE_STOP     101
#define IDS_SERVICE_PAUSE    102
#define IDS_SERVICE_RESUME   103
#define IDS_SERVICE_RUNNING  104
#define IDS_SERVICE_STOPPED  105
#define IDS_SERVICE_PAUSED   106
