# $Id: Makefile,v 1.1 2003/04/05 19:40:41 chorns Exp $

PATH_TO_TOP = ../../..

TARGET_TYPE = library

TARGET_NAME = vfatlib

TARGET_OBJECTS = \
 vfatlib.o
 
include $(PATH_TO_TOP)/rules.mak

include $(TOOLS_PATH)/helper.mk
