[FREELOADER]
DefaultOS=LiveImg_Debug
TimeOut=10

[Display]
TitleText=ReactOS CD-ROM Boot
MinimalUI=Yes

[Operating Systems]
Setup="ReactOS Setup (Text Mode)"
LiveImg="ReactOS Live Environment (Graphics Mode)"
==
;; The entries below are for testing and development:
Setup_Debug="Setup (Debug)"
Setup_Screen="Setup (Screen Debug)"
LiveImg_Debug="Live (Debug)"
LiveImg_Screen="Live (Screen Debug)"
;; The following entry is an example template:
;LiveImg_LogFile="Live (Log file)"

[Setup]
BootType=ReactOSSetup
SystemPath=multi(0)disk(0)cdrom(0)\
Options=/HAL=halpc98.dll

[Setup_Debug]
BootType=ReactOSSetup
SystemPath=multi(0)disk(0)cdrom(0)\
Options=/HAL=halpc98.dll /DEBUG /DEBUGPORT=COM1 /BAUDRATE=9600 /NOGUIBOOT /SIFOPTIONSOVERRIDE

[Setup_Screen]
BootType=ReactOSSetup
SystemPath=multi(0)disk(0)cdrom(0)\
Options=/HAL=halpc98.dll /DEBUG /DEBUGPORT=SCREEN /SIFOPTIONSOVERRIDE

[LiveImg]
BootType=Windows2003
SystemPath=multi(0)disk(0)cdrom(0)\reactos
Options=/HAL=halpc98.dll /MININT

[LiveImg_Debug]
BootType=Windows2003
SystemPath=multi(0)disk(0)cdrom(0)\reactos
Options=/HAL=halpc98.dll /DEBUG /DEBUGPORT=COM1 /BAUDRATE=9600 /SOS /MININT

[LiveImg_Screen]
BootType=Windows2003
SystemPath=multi(0)disk(0)cdrom(0)\reactos
Options=/HAL=halpc98.dll /DEBUG /DEBUGPORT=SCREEN /SOS /MININT

;[LiveImg_LogFile]
;BootType=Windows2003
;SystemPath=multi(0)disk(0)cdrom(0)\reactos
;Options=/HAL=halpc98.dll /DEBUG /DEBUGPORT=FILE:\Device\HarddiskX\PartitionY\debug.log /SOS /MININT
