/*
 * COM Classes for dmusic
 *
 * Copyright 2010 Alexandre Julliard
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 */

#pragma makedep register

[
    threading(both),
    progid("Microsoft.DirectMusic.1"),
    vi_progid("Microsoft.DirectMusic"),
    uuid(636b9f10-0c7d-11d1-95b2-0020afdc7421)
]
coclass DirectMusic { interface IDirectMusic; }

[
    threading(both),
    progid("Microsoft.DirectMusicCollection.1"),
    vi_progid("Microsoft.DirectMusicCollection"),
    uuid(480ff4b0-28b2-11d1-bef7-00c04fbf8fef)
]
coclass DirectMusicCollection { interface IDirectMusicCollection; }
